official-antistasi-community/A3-Antistasi

A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf, A3-Antistasi/Templates/Invaders3CBAFRFT.sqf, A3-Antistasi/Templates/Invaders3CBTKM.sqf, A3-Antistasi/Templates/Occupants3CBBAF.sqf, A3-Antistasi/Templates/Occupants3CBBAFT.sqf, A3-Antistasi/Templates/teamPlayer3CBCCM.sqf, A3-Antistasi/Templates/teamPlayer3CBCCMT.sqf, A3-Antistasi/initVar.sqf
Integrates 3CB as template options, as well as into initVar.sqf
(cherry picked from commit 0a8ded5da7189f8447435121569213e0858eec18)
(cherry picked from commit 86d7058fc1e8519fa7af2b4f97cf2559369fbcc7)
=> 3CB Integration

A3-Antistasi/initPetros.sqf
=> Changed Petros timeout to Spawn process

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_init.sqf, A3-Antistasi/init.sqf, A3-Antistasi/initFuncs.sqf, A3-Antistasi/initGarrisons.sqf, A3-Antistasi/initGetMissionPath.sqf, A3-Antistasi/initPetros.sqf, A3-Antistasi/initPlayerLocal.sqf, A3-Antistasi/initServer.sqf, A3-Antistasi/initVar.sqf, A3-Antistasi/initZones.sqf
A first pass to standardise the logging throughout Antistasi and hopefully provide some more useful information when stuff actually breaks.
Directly for issue #87.
=> Enhanced logging

A3-Antistasi/Stringtable.xml, A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/description.ext, A3-Antistasi/Templates/A3-AATemplate.Altis/description.ext, A3-Antistasi/Templates/A3-ArmiaKrajowaTemplate.chernarus_summer/description.ext, A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/description.ext, A3-Antistasi/description.ext, A3-Antistasi/dialogs.hpp
This PR will contain the start of localisation to the StringTable
Now with a rebased / fetched Upstream..
=> Starting localisation

.travis.yml, Tools/sqf_validate.py
Adds travis config file and working SQF validation script.
Validation script requires Python3.
=> Travis implementation

A3-Antistasi/initServer.sqf, A3-Antistasi/initVar.sqf
ARMA Doesn't like localizing in SQF apparently?
=> Fixes the Localization for Version number

A3-Antistasi/CREATE/removeVehFromPool.sqf
`isNil _cant` generate ERROR:
> 23:16:03 Error in expression <{
> _cant = timer getVariable _this;
> if !(isNil _cant) then
> {
> if !(_cant isEqualTy>
> 23:16:03   Error position: <isNil _cant) then
> {
> if !(_cant isEqualTy>
> 23:16:03   Error isnil: Тип Число, ожидался Строка,code
EXAMPLE: [https://community.bistudio.com/wiki/isNil](url)
=> FIX removeVehFromPool.sqf

A3-Antistasi/functions.hpp, A3-Antistasi/functions/init/fn_getArrayMrks.sqf, A3-Antistasi/initVar.sqf, A3-Antistasi/initZones.sqf
As this function use not only in initZones, i put it to function library of the mission
=> Move mrkrs function to function lib and apply it to roadsMrk variable

A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/mission.sqm, A3-Antistasi/Templates/A3-AATemplate.Altis/description.ext, A3-Antistasi/Templates/A3-AATemplate.Altis/mission.sqm, A3-Antistasi/Templates/A3-ArmiaKrajowaTemplate.chernarus_summer/mission.sqm, A3-Antistasi/Templates/A3-Livonia-Template.Enoch/mission.sqm, A3-Antistasi/Templates/A3-Malden-Template.Malden/mission.sqm, A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/mission.sqm
=> Changed the mission.sqm to use localized data.

A3-Antistasi/undercover.sqf
=> fix invalid _baseSide variable check in undercover.sqf

A3-Antistasi/Stringtable.xml
everything according to plan, as agreed
=> Russian language for multilaguage system

A3-Antistasi/initGarrisons.sqf, A3-Antistasi/initServer.sqf, A3-Antistasi/initZones.sqf
Added some nice debugging in the two init files to help identify why initial startup can be slow.
Also commented out the `wait` sections to allow servers with `-autoinit` to complete server load without requiring a player join.
=> Add debugging for init Garrisons / Zones and Remove dedicated startup wait

A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/mission.sqm, A3-Antistasi/Templates/A3-AATemplate.Altis/mission.sqm, A3-Antistasi/Templates/A3-Livonia-Template.Enoch/mission.sqm, A3-Antistasi/Templates/A3-Malden-Template.Malden/mission.sqm, A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/mission.sqm
https://github.com/official-antistasi-community/A3-Antistasi/issues/184#issue-484909912
i fixed this error on all templates exept armiaKrajowa - I'm too lazy to figure out what mods are needed there
=> FIX _leader error

A3-Antistasi/initVar.sqf
PBP forgot GPS's when he made his initVar changes. Without this players get no GPS or Terminal at start.
=> Re-Add GPS

A3-Antistasi/initGarrisons.sqf
=> Pulling the initGarrison rework to start the rework

A3-Antistasi/Stringtable.xml
BOB was commit to stringtable.xml (Kunduz),  and commit old stringtable with old data. I fixed that.
=> FIX wrong commit to Stringtable.xml

.github/pull_request_template.md
This needs additional configuration in the Git settings tab to enable it's use.
https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository
=> Add a PR Template for Git

A3-Antistasi/Ammunition/getRadio.sqf
Reverts official-antistasi-community/A3-Antistasi#326
=> Revert "Fix for acre2 radios not being recognized as a units radio"

A3-Antistasi/functions/Base/fn_economicsAI.sqf
=> proper treatment of array/string

A3-Antistasi/Templates/A3-AA-BLUFORTemplate.Altis/description.ext, A3-Antistasi/Templates/A3-AATemplate.Altis/description.ext, A3-Antistasi/Templates/A3-ArmiaKrajowaTemplate.chernarus_summer/description.ext, A3-Antistasi/Templates/A3-Kunduz-Template.kunduz/description.ext, A3-Antistasi/Templates/A3-Livonia-Template.Enoch/description.ext, A3-Antistasi/Templates/A3-Malden-Template.Malden/description.ext, A3-Antistasi/Templates/A3-Tembelan.Tembelan/description.ext, A3-Antistasi/Templates/A3-WotPTemplate.Tanoa/description.ext, A3-Antistasi/functions/Base/fn_distance.sqf, A3-Antistasi/functions/Base/fn_powerReorg.sqf, A3-Antistasi/functions/Base/fn_rebelAttack.sqf, A3-Antistasi/functions/Base/fn_rebuildAssets.sqf, A3-Antistasi/functions/CREATE/fn_createAICities.sqf, A3-Antistasi/functions/CREATE/fn_createAIResources.sqf, A3-Antistasi/functions/CREATE/fn_createCIV.sqf, A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf, A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf, A3-Antistasi/functions/Missions/fn_missionRequest.sqf, A3-Antistasi/functions/Save/fn_loadServer.sqf, A3-Antistasi/functions/init/fn_cityinfo.sqf, A3-Antistasi/functions/init/fn_resourcecheck.sqf, A3-Antistasi/initZones.sqf, A3-Antistasi/statSave/saveFuncs.sqf, A3-Antistasi/statSave/saveLoop.sqf
=> Replaced destroyedCities => destroyedSites, fixes #157

A3-Antistasi/Templates/Loadouts/rhs_afrf_AT.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_AT2.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_machineGunner.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_medic.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_grenadier.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
Class name for harries bipod on marksman fixed 
Added the medical equipment for the Russian medic
=> AFRF and USAF fixed 

A3-Antistasi/functions/CREATE/fn_WPCreate.sqf, A3-Antistasi/functions/Convoy/fn_convoyDebug.sqf, A3-Antistasi/functions/Convoy/fn_convoyMovement.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf, A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf, A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
Fixed a few errors regarding convoys, mostly #392
=> Convoy fix

A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
Fixed the heli mission, it is now won if you either tow the truck carrying the vehicle or enter this truck
=> Fixed heli mission bug

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/init/fn_initSpawnPlaces.sqf
As title states. On Bobs wish I unlocked at least one AA for every airfield
=> Unlocked at least one AA vehicle per airfield

A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
Changed 'Roadblock' to 'Installation' so that it applies to all cases.
resloves #401
=> Changed a notification line that only referenced Roadblocks

A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf, A3-Antistasi/functions/Save/fn_loadServer.sqf, A3-Antistasi/statSave/saveFuncs.sqf, A3-Antistasi/statSave/saveLoop.sqf
First step for #344
Contains only format and spacing changes so far, so Spoffy's head doesn't explode.
=> INV punish mission save fix part 1

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_WPCreate.sqf, A3-Antistasi/functions/Missions/fn_convoy.sqf, A3-Antistasi/functions/init/fn_getArrayMrks.sqf, A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf, A3-Antistasi/initVar.sqf, A3-Antistasi/initZones.sqf
This PR will fix the #247 and #348 issues from 2.2
Descriptions are in the commits
=> PR to fix multiple smaller issues

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
Planes are getting selected based on the availability, if none is available selectRandom would return nil, which then crashes the code.
=> Fixed a undefined case when spawning planes

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
I ignored the spacing just for you Spoffy!
=> Fixes error thrown because Ammo Trucks never got updated with new types

A3-Antistasi/functions/Ammunition/fn_configSort.sqf
This PR fixes the allX arrays to not duplicate items.
=> changed `pushBack` to `pushBackUnique` in configSort

A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
=> Remove Deadman Switch from ACE items

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/Base/fn_mrkWIN.sqf
I added a isGettingCaptured variable to the flag, which is getting set to true once someone is capturing the flag. Every further call of the call will abort and hint the player about it.
=> Fixed flag exploit by adding safety check

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/functions/Ammunition/fn_dress.sqf, A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf, A3-Antistasi/functions/CREATE/fn_FIAinitBASES.sqf, A3-Antistasi/functions/REINF/fn_FIAinit.sqf
FIAinit - converted the big "if" to a switch
FIAinitBASES - just a spacing update to match
randomRifle - Spacing and local variable 
dress - took 'teamPlayerDefaultLoadout' out of templates and put it directly in dress, randomized choice
=> FIAinit Fixes round 1

A3-Antistasi/functions/Templates/fn_getLoadout.sqf
Adds splints to PvP basic medical supplies, in case ADV splint is loaded.
Increases number of splints PvP medics have.
=> Adds splints to PvP basic medical supplies

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Utility/fn_log.sqf, A3-Antistasi/initServer.sqf, A3-Antistasi/initVar.sqf, A3-Antistasi/log.sqf
1. [X] Enhancement
Information:
Adds a logging function for unified log messages throughout the project.
closes #336 
1. [X] Have you loaded the Mission in a Dedicated Server?
1. [x] No
Notes:
Example Commands to use with this:
```SQF
loglevel = 3;
"Default Error" execvm "log.sqf";
[1,"Error Logging","log.sqf"] execvm "log.sqf";
[2,"Info Logging"] execvm "log.sqf";
[3,"Debug Logging","log.sqf"] execvm "log.sqf";
```
Gives this output:
```
"358.729: [Antistasi] | ERROR | No File Specified | Default Error"
"358.729: [Antistasi] | ERROR | log.sqf | Error Logging"
"358.729: [Antistasi] | INFO | Info Logging"
"358.729: [Antistasi] | DEBUG | log.sqf | DebugLogging"
```
=> Creation of Logging Function

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
Added limits to vehicle spawn on airfields (and outpost but thats not a problem)
Fixes #447
=> Reduce vehicle count

Map-Templates/Antistasi-ArmiaKrajowa.chernarus_summer/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi.Malden/mission.sqm
1. [x] Bug
Information: changed the classname of author attribute reference in Maldens mission sqm
dont think it is one
1. [x] No
Notes: this doesn't cause an issue in DS anyways, perhaps each environment looks for this data somewhere different?
=> Fixes warning about author class error when LAN hosting

A3-Antistasi/functions/init/fn_initGarrisons.sqf, A3-Antistasi/initPlayerLocal.sqf
1. [X] Bug
Information: SP was broken due to parameters not set in SP. Fixed it by adding additional checks to prevent not defined errors
None opened for it
2. [X] Have you loaded the Mission in local Multiplayer? (This option is missing in the template)
3. [ ] Have you loaded the Mission in a Dedicated Server?
1. [ ] No
Notes:
Can someone please double check if I have missed some case.
**This PR is important, as SP is completely broken till this is merged!**
=> Singleplayer fixes

README.md
The new tools changes the process of how to prepare the missions for a pbo manager.
I added the new instructions to fix #412
=> Added instruction for the new packing tool

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf, A3-Antistasi/initZones.sqf
Fixes three of the issues Bob found today, all minor fixes for edge cases
=> Fix bobs issues

A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf, A3-Antistasi/functions/Ammunition/fn_crateLootParams.sqf
1. [ ] Bug
Information:
I've changed the weighted function to use the built in one provided by the engine. There is also additional debugging for weapons and random magazine unlocks per weapon.
closes #485 
1. [ ] No
Notes:
Review and please let me know what you think.
=> Set Weighted changes to the ammo crates for weapons

A3-Antistasi/functions/Base/fn_citySupportChange.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf, A3-Antistasi/functions/Convoy/fn_createAIAction.sqf, A3-Antistasi/functions/Convoy/fn_onConvoyArrival.sqf, A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
1. [X] Bug
Information:
Fixes all me related errors from Bobs test rpts from 12.11.19
The exact fixes are stated in the commits
None opened for them yet
1. [X] No
Notes: Only started, not playtested, but should be fine
=> 191112 fix

A3-Antistasi/changelog_2_2.txt
1. [ ] Bug
Information:
Added localisation changes and groundwork for NATOCrate changes.
None yet. 
NOT REQUIRED.
1. [X] No
Notes:
=> Added changelog updates

Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi.Kunduz/mission.sqm, Map-Templates/Antistasi.Malden/mission.sqm, Map-Templates/Antistasi.Tembelan/mission.sqm
1. [ ] Bug
Information:
Bob's mission updates for Tembelan, Kunduz, Malden and Livonia
closes #495 
1. [ ] No
Notes:
@Bob-Murphy, please can you provide detail on what you've done and what, if any, testing is now required.
=> Map overhauls for 2.2

A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/Convoy/fn_createAIAction.sqf
1. [X] Bug
Information: Fixes the bugs found by Bob in the tests from 15.11.19
1. [X] No
Notes:
=> 191115 fixes

A3-Antistasi/functions/CREATE/fn_AAFroadPatrol.sqf, A3-Antistasi/functions/CREATE/fn_patrolCA.sqf, A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf, A3-Antistasi/functions/Missions/fn_convoy.sqf, A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf
1. [X] Bug
Information: Linkes spawnPoints markers to airports based on distance
closes #499 
1. [ ] No
Notes: There are 6 scripts using this to spawn in vehicles, I haven't tested them all. There is a chance I fucked up the copy paste
=> Spawn marker fix

A3-Antistasi/functions/REINF/fn_FIAinit.sqf
1. [X] Bug
FIA squad leaders and AT guys weren't being equipped with primary weapons. Now they are.
1. [X] No
=> Give AT guys and squad leaders a rifle

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf
1. [X] Bug
Information: I have updated the code in CSATCrate to match the NATOCrate script and all its new fanciness. I know we could probably just remove one and only use a single script, but for now I would like it to stay until I settle out all my plans for loot and am sure I wont need it.
closes #504 
1. [X] No
=> matched CSAT loot crate script with NATO

A3-Antistasi/functions/OrgPlayers/fn_assigntheBoss.sqf, A3-Antistasi/functions/OrgPlayers/fn_theBossInit.sqf, A3-Antistasi/initPlayerLocal.sqf
1. [X] Bug
Information:
Added debug logging for the Boss generation, hopefully it can shed some light on why the boss fails to assign.
closes #XXXX
1. [ ] No
Notes:
This needs testing on the Official servers to determine what's going wrong with #512 .
=> Add debug logging for Boss assignment

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_milBuildings.sqf, A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf, A3-Antistasi/functions/Garrison/fn_updateReinfState.sqf
1. [X] Bug
Information: Fixed airplanes spawning worng in hangars (I cannot stop them from moving! Hangars have to be placed on even ground!). Added missing conditions to stop bases from sending reinforcements convoys (Under attack, player near, wrong side)
closes #525 
closes #528
closes #529
1. [ ] No
Notes: Completely untested, need someone to confirm the code is working as it should
=> Convoy and plane fix

A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf
1. [X] Bug
Information: Added a default grpNull variable
closes #548 
1. [X] No
Notes: Not tested, but the change is minimal
=> Fixes an issue with cargoGroup not set

Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm
1. [x] Bug
Information:
- cleaned up the bridge
- removed rocks next to a road because AI flipped itself
- disabled simulation for containers in mid-south outpost
- placed new roadblocks
closes #549  
1. [x] No
Notes:
=> Kunduz map overhaul

A3-Antistasi/functions/AI/fn_inmuneConvoy.sqf
small translation of _puentes  --> _bridges
=> Translate _puentes into _bridges

A3-Antistasi/initVar.sqf
1. [X] Bug
Information: Readded an array for the breach script to work.
solves #570 codewise, check the issue for further details
1. [X] No
Notes:
=> Fixed breaching script

A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
1. [X] Bug
I'm not sure if this mission ever worked, but it had a critical typo that prevented the helicopter being created, causing autocompletion. I've fixed that along with an error that prevented the mission terminating correctly. It does now appear to work to some degree.
closes #558 
partial resolution of #551 
1. [X] No
...but the mission probably needs some work. Currently it sends an unarmed light vehicle with a couple of soldiers, which isn't much of a threat. The flatbed truck has some AI issues with getting anywhere near the helicopter, possibly because it's scared of me. Rewards aren't great unless you can convince the flatbed truck to show up and then steal an attack helicopter.
I don't feel like this is …
=> Basic fixes to make helicopter destruction mission work

Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
=> ESSENTIAL Tembelan overhaul

A3-Antistasi/functions/Garrison/fn_createGarrisonLine.sqf, A3-Antistasi/functions/Garrison/fn_logArray.sqf, A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf, A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
1. [X] Bug
Information:
Adds more logs to selectReinfUnits and improves its code
1. [ ] No
Notes: Due to time issues untested
=> Added more logs to find the quad bug, also improved code a bit

A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf
1. [X] Bug
Information:
Fixes spamming once and for all, even if the vehicle is named wrong, unavailable or else.
Also changes code style to use four spaces for each tab 
1. [X] No
Notes:
=> Fix spamming of vehicles in convoys

A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
=> removes missing forms of priest outfit I missed

A3-Antistasi/Stringtable.xml, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/briefing.sqf, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_createBreachChargeText.sqf, A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf, A3-Antistasi/initVarServer.sqf
1. [X] Bug
Information: Reworked the charge selection for vehicle breaching. The charges are now set in the FIA templates as follows:
```
breachingExplosivesAPC = [["NameOfExplosive", AmountNeeded], ["NameOfExplosive2", AmountNeeded]];
breachingExplosivesTank = [["NameOfExplosive", AmountNeeded], ["NameOfExplosive2", AmountNeeded]];
```
The choosen explosives are shown in the briefing under Feature Details >> Breaching charges.
A general description can be found at Feature Details >> Breaching Vehicles.
Adding @SonorousMeerkat to add correct charges for all templates. When this is finished, breaching should work for all mods.
closes #570 
1. [X] No
2. [ ] Yes …
=> Breaching templates

Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
1. [ ] Bug
Information:
Moved the position of the CSAT carrier to the corner of the CSAT airport    
closes #596 
1. [x] No
Notes:
=> Tembelan carrier position update

A3-Antistasi/functions/Revive/fn_actionRevive.sqf
1. [X] Bug
Information: Enabled the medikit for vanilla revives, so vanilla medics with a medikit are no longer getting the "You need a First Aid Kit to revive someone", which is annoying and really frustrating at some points.
closes #615 
1. [ ] No
Notes:
Haven't tested it as I am on a laptop, but Travis said it worked, needs a bit of testing
=> Enable vanilla revive with Medikits

A3-Antistasi/functions/Base/fn_sellVehicle.sqf
1. [X] Bug
Information: Reduced the credits granted by transport helicopters to 500, replaced vehicle check with isKindOf
closes #588 
1. [ ] No
Notes: A single startup should be fine, the change is minimal
=> Reducing price of helicopters to 500, replaced vehPlanes by isKindOf

A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [ ] Bug
Information:
Added map markers which should be CSAT at the start of the mission.   
closes #594 
1. [ ] No
Notes:
=> Updated CSAT locations for new maps

A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
Information: Added Ace spare barrel so the overheat function can be used ingame
closes #647 
1. [x] No
Notes:
=> Add ACE spare barrel

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Fixes one variable in every mission.sqm to fix the gamemaster module not loading every mod stuff in Zeus
1. [x] Bug
Information:
Fixes that shit    
closes #659 
1. [x] No
Notes:
=> mission.sqm overhaul

Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [x] Bug
Information:
Everybody should have my D!!   
closes #665 
1. [x] No
Notes:
=> D-insertion

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Changes all officer units besides Petros to teamleaders  for unitTraits compatibility
1. [ ] Bug
3. [x] Change
Information:
closes #667 
1. [x] No
Notes:
=> mission.sqm update

A3-Antistasi/orgPlayers/unitTraits.sqf
1. [ ] Bug
Information:
closes #661 
1. [ ] No
Notes:
The changes have to be tested properly in a multiplayer environment where we directly can compare units and see, if the traits are working
=> Enables unit traits

A3-Antistasi/orgPlayers/unitTraits.sqf, Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm
1. [ ] Bug
Information:
Changes one PvP green unit from SL to TL
Enables unitTraits for PvP units as well    
closes #661
1. [x] No
Notes:
Meerkat has long hair growing out of his ears :)
=> 2.2.1 unit traits

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
changes 2 TL to rifleman
1. [ ] Bug
Information:
Changes 2 TL to riflemen    
closes #681 
1. [x] No
Notes:
=> Unit update

A3-Antistasi/functions/init/fn_initSnowFall.sqf
1. [x] Bug
Information:
closes #687 
1. [x] No
Notes:
=> deactivate _ambient_sound_al

A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
1. [ ] Bug
Information:
Fixes the evil typo    
closes #691 
1. [x] No
Notes:
=> Fices damn evil typo that breaks nato crates

A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf, A3-Antistasi/functions/CREATE/fn_patrolCA.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf, A3-Antistasi/functions/Convoy/fn_createAIAction.sqf, A3-Antistasi/functions/Convoy/fn_roadblockFight.sqf, A3-Antistasi/functions/Garrison/fn_updateGarrison.sqf, A3-Antistasi/functions/Missions/fn_convoy.sqf, A3-Antistasi/functions/REINF/fn_garrisonAdd.sqf, A3-Antistasi/functions/init/fn_cityinfo.sqf
1. [X] Bug
Information: Fixed null errors caused by garrison data not set
closes #683 
1. [ ] No
Notes: A single startup should be fine, I haven't changed any logic
=> Added default variables for all getVariable to avoid null errors

Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [ ] Bug
3. [x] Change
Information:
Marker placement
closes #699 
1. [x] No
Notes:
=> Tanoa mission update

Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
1. [ ] Bug
3. [x] Change
Information:
Fixes positioning of some objects
closes #701 
1. [x] No
Notes:
=> Livonia mission update

A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm
1. [ ] Bug
Information:
@SEBArma Have your flag, Sir!    
closes #400 
1. [x] No
Notes:
=> Flag exchange to FIA

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm
1. [ ] Bug
Information:
closes #708 
1. [x] No
Notes:
=> Altis Airfield Flag adjustment

Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
finally adds tover, barriers and shit
1. [ ] Bug
Information:
Finally adds buildings and shit    
closes #715 
1. [x] No
Notes:
=> Updates mission.sqm of chernarus winter

Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm
1. [x] Bug
Information:
adds missing variables to playable pvp units on the maps:
Anizay
Malden
Livonia    
closes #733 
1. [x] No
Notes:
=> PVP Loadout assignment fix

A3-Antistasi/Stringtable.xml, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm
Altis asset update
Chernarus Winter asset update
Chernarus Summer asset update closes #717 
Anizay asset update
Version number update to 2.2.2
=> Map updates and version number change

A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
1. [ ] Bug
3. [X] Balance change
NV goggles with a thermal mode are ignored when unlocking. NV goggles with the highest count in the arsenal are unlocked first when you have >minWeaps total NVs.
Previously there was a high chance of unlocking ENVGs when you only had a few of them.
closes #765
1. [X] No
=> Ignore ENVGs when unlocking, unlock NV with the most units first

A3-Antistasi/functions/Ammunition/fn_checkRadiosUnlocked.sqf
1. [X] Bug
Information:
Minor fix, added in check for hasACRE to set haveRadio to true.
closes #811
1. [X] No
Notes:
=> [checkRadiosUnlocked] Fixed issue with haveRadio not returning True with ACRE

A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT2_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_AT_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_marksman_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_medic_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_teamLeader_tanoa.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf
1. [ ] Bug
Information:
Added Calls in Templates for Loadouts.
Added Loadouts for Alits,Tanoa,Enoch.
Keept them similar to Nato Loadouts.
closes #XXXX
1. [X] Have you loaded the Mission in Local Host?
1. [X] No
Notes:
=> Vanilla Csat Loadouts

A3-Antistasi/Templates/Loadouts/rhs_afrf_AT.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_AT2.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_machineGunner.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_medic.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf
1. [X] Bug
Information:
Fixed Bad Classname in AT Loadouts.
Overhauled AFRF Loadouts.
closes #XXXX
1. [x] No
Notes:
Tried to stay similar to balancing of USAF Templates.
Gave AT2 Ammo for AT1 to enforce Teamplay.
All exept Marksman and Machine gunner received Zentico AKs
Changes can be made from Feedback :)
=> AFRF Loadout Overhaul

A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_enoch.sqf, A3-Antistasi/Templates/Loadouts/vanilla_opfor_machineGunner_tanoa.sqf
1. [X] Bug
Information: Removed a not needed comma to fix Machinegunner Loadouts.
closes #XXXX
1. [X] No
Notes:
=> Fixes Vanilla Csat Machinegunners

A3-Antistasi/JeroenArsenal/JND/fn_debugv2.sqf, A3-Antistasi/JeroenArsenal/functions.hpp
This commit adds the first version of the "Ultra Wide Extended Debug Console With Extra Save Buttons!", developed by Jeroen Not.
What needs testing/is missing is to make sure that still only an Admin has the debug console once this is enabled.
Also, currently this code REQUIRES CBA but it's automatically disabled if CBA is not loaded.
Co-Authored-By: Jeroen-Notenbomer <jeroen-notenbomer@users.noreply.github.com>
1. [ ] Bug
Information:
Read above   
closes #854 
1. [x] No
Notes:
=> Jeroen Nots Debug-stuff

A3-Antistasi/functions/Utility/fn_log.sqf
1. [ ] Bug
Information:
Added a verbose level to the Log function. This is for our testing purposes to get every detail out that they can.
None
1. [X] No
Notes:
I'll be making a follow up PR for the following functions so they will use this level from now on and clear up the debug spam.
- fn_equipRebel
- fn_NATOCrate
- fn_CSATCrate
@wurzel0701 (You requested this stuff, please make sure your projects make use of it 👍 )
=> Added verb log level for those that need it

Tools/sqf_validate.py
1. [X] Bug
Information:
Removes the Array selection validation which was preventing the Jereon code from being merged.
closes #873 
1. [ ] No
Notes:
=> Removed `#` Validation which is used for array selection

A3-Antistasi/JeroenArsenal/JND/fn_debugv2.sqf, A3-Antistasi/JeroenArsenal/functions.hpp
Co-Authored-By: Jeroen-Notenbomer <jeroen-notenbomer@users.noreply.github.com>
1. [ ] Bug
Information:
closes #854 
1. [x] No
Notes:
=> JND implementation the second

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf, A3-Antistasi/functions/Base/fn_logPerformance.sqf, A3-Antistasi/functions/REINF/fn_equipRebel.sqf, A3-Antistasi/functions/Utility/fn_log.sqf
1. [ ] Bug
Information:
I've updated `fn_log` with a some examples in the header of the file on how to use the actual function as someone on the team requested.
Further #895, I have changed the following to make use of the Verbosity log level now that it's implemented. Logs attached to show them working.
- fn_equipRebel
- fn_NATOCrate
- fn_CSATCrate
[CrateAndRebel.log](https://github.com/official-antistasi-community/A3-Antistasi/files/4394319/CrateAndRebel.log)
I have also closed #864 as part of this since it was just a log change ~this needs one additional change first.~
[864-LogExample.log](https://github.com/official-antistasi-community/A3-Antistasi/files/4394301/864-LogExample.log)
closes #864 
2. [X] Have you …
=> Updated Logging for Verbose layer

A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
1. [ ] Bug
Information: Changed Flag Texture and Flagpost in:
IFA_Reb ---------> FIA Flag + Texture
INV_AFRF -------> Russianflag in MrkCsatflag
OCC_USAF ------> USA Flag + Texture
Removed HIDF Teamleaders from Lowtier (FIA) AFRF and replaced with AFRF "rhs_msv_emr_sergeant".
closes #882
1. [x] No
Notes: 
Due to Markers also being Colored in Opfor/Blufor/Independant Colors seeing them gets a bit harder.
#901
=> Flags + Textures, Small fixes

A3-Antistasi/Stringtable.xml
* Fixed fallback to English/Original strings if current language isn't supported (removed empty string tags)
* Added German localization
None
=> [2.2.2] German localization

A3-Antistasi/Templates/Loadouts/Vanilla_AAF_AT1_Altis.sqf, A3-Antistasi/Templates/Loadouts/Vanilla_AAF_AT2_Altis.sqf, A3-Antistasi/Templates/Loadouts/Vanilla_AAF_MachineGunner_Altis.sqf, A3-Antistasi/Templates/Loadouts/Vanilla_AAF_Marksman_Altis.sqf, A3-Antistasi/Templates/Loadouts/Vanilla_AAF_Medic_Altis.sqf, A3-Antistasi/Templates/Loadouts/Vanilla_AAF_TeamLeader_Altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_blufor_machineGunner_WDL.sqf, A3-Antistasi/Templates/Loadouts/vanilla_blufor_machineGunner_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_blufor_machineGunner_tanoa.sqf, A3-Antistasi/Templates/Loadouts/vanilla_blufor_marksman_altis.sqf, A3-Antistasi/Templates/Loadouts/vanilla_blufor_marksman_tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf
1. [ ] Bug
Information:
Added AAF Loadouts
And gave Nato Machinegunner Loadouts Binos and GPSs
Removed Silencers from Vanilla Marksmans.
closes #XXXX
1. [x] No
Notes:
=> AAF Loadouts

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
1. [x] Bug
Information:
Some Mines had wrong Magazine Classnames defined those were corrected.
Corrected mixed TNT charges Classnames.
closes #951 
1. [X] No
Notes:
=> RHS Mines and Breaching Charges fixes

A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf
1. [X] Bug
Information: Due to the Restriction Script being Case sensitive it didnt see the Plane and it wasnt stoping it from being Ungaraged from HQ.
closes #949 
1. [X] No
Notes: I looked through RHS USAF, CDF, Rebell Templates (NOT 3CB Yet) and it seems that so far this is the only Case where that kind of Error apeared.
Might need a better name for the PR.
=> Csatplane AFRF Fix

A3-Antistasi/functions/init/fn_initSnowFall.sqf
1. [x] Bug
Information:
disabled script from running
closes #933 
1. [x] No
Notes:temp fix til a proper fix can be made that fixes the performance issues this script creates
=> disabled snow Script

A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
Information:
I added comment that will explain what `countCA` is.
closes #944
I do not think this is needed.
1. [x] No
=> Documented countCA

A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
1. [X] Bug
- Physics objects (eg vehicle crate) could injure a player who dropped it while running
- On a dedicated server, the setVelocity tent fix didn't work due to locality
- Fixed up object attachment position for better clearance and visibility
Both setVelocities were required: The first (local) one is necessary to avoid physics objects causing immediate injuries, possibly because the remoteExec is too slow. The second one is necessary because non-physics objects like the tent regain velocity shortly after dropping on a DS. 
Spacing out objects with the bounding box also helped with the tent, possibly because otherwise the tent is spawned within the player object. I also improved the vertical positioning for carried objects, although that wasn't strictly related. …
=> Fix various cases where repositioning HQ objects could injure players:

A3-Antistasi/MissionDescription/params.hpp
1. [ ] Bug
3. [x]Change
Information:
Changed comment
closes #973 
1. [x] No
Notes:
=> Change descriptive text for mRadius parameter

A3-Antistasi/functions/Utility/fn_log.sqf
1. [ ] Bug
Added a player/HC name tag to remotely logged lines as requested. Used a postfix as it's usually unimportant information and the code would have been horrible otherwise.
closes #977
1. [X] No
=> Tag remote logs with player/HC name

A3-Antistasi/functions/init/fn_initVarCommon.sqf
1. [X] Bug
Information:
Deactivated th IFA mod from passing the detection. Once detected the rpt will log an error and the game will end with the "modUnauthorized" endscreen
closes #1000 
1. [ ] No
Notes: Someone should test if that actually works, I dont have IFA downloaded
=> Wurzel deactivate ifa

A3-Antistasi/MissionDescription/endMission.hpp, Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext, Map-Templates/Antistasi-Altis.Altis/description.ext, Map-Templates/Antistasi-Anizay.tem_anizay/description.ext, Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext, Map-Templates/Antistasi-Kunduz.Kunduz/description.ext, Map-Templates/Antistasi-Livonia.Enoch/description.ext, Map-Templates/Antistasi-Malden.Malden/description.ext, Map-Templates/Antistasi-Stratis.Stratis/description.ext, Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext, Map-Templates/Antistasi-WotP.Tanoa/description.ext
1. [X] Bug
- Separated the duplicated standard messages into a single file in MissionDescription
- Rewrote PvP noJIP message so that newbies will (hopefully) know what they did wrong
- Fixed misnamed reserved member slots issue and improved the text
closes #1002
1. [X] No
=> EndMission messages refactor and fixes

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Stratis.Stratis/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-Virolahti.vt7/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [ ] Bug
Information:
Every map is overhauled in terms of helipads, control  markers and known issues.
closes #1066 
1. [x] No
Notes:
=> Overhaul of every map

A3-Antistasi/Stringtable.xml
1. [ ] Bug
3. [x] Change
Information:
closes #1064
1. [x] No
Notes:
=> Implemented proper Virolahti blurp text.

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_singlePlayerBlackScreenWarning.sqf, A3-Antistasi/functions/init/fn_initClient.sqf
1. [ ] Bug
Information: Added a warning for SP modus, displayed on start of the mission
closes #991 
1. [X] No
Notes:
=> Added a warning for SP modus

A3-Antistasi/Stringtable.xml
1. [ ] Bug
Information: The question asked is misleading - therefore changed.
closes #990 
1. [x] No
Notes:
=> updated dialog_load_previous_session

A3-Antistasi/functions/Garrison/fn_addGarrison.sqf
1. [X] Bug
addGarrison stomped on local vars. Now it doesn't. This was causing an error in #1043's version of ConvoyTravel.fsm, but that may not be the only related error.
closes #1071 
1. [X] No
=> Fix non-private vars in addGarrison

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
1. [X] Bug
Information: Due to Change of _veh to _ammobox in #1043 flyGear doesent apply anymore
closes #1077 
1. [x] No
Notes:
=> Fixed Variable Name

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm
1. [ ] Bug
3. [x] Change
Information:
Overhauled a few map markers and added 2 missing flags at Altis Blufor    
closes #1064 
Notes:
=> Map overhaul 2

A3-Antistasi/functions/Punishment/fn_punishment.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf, A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf, A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf, A3-Antistasi/functions/Punishment/fn_punishment_dataGet.sqf, A3-Antistasi/functions/Punishment/fn_punishment_dataRem.sqf, A3-Antistasi/functions/Punishment/fn_punishment_dataSet.sqf, A3-Antistasi/functions/Punishment/fn_punishment_notifyAdmin.sqf, A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf, A3-Antistasi/functions/Punishment/fn_punishment_release.sqf, A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf, A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf, A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
* Bug
Information: Basic checks in `Punishment FF` no longer spam RPT.
Some doc headers have had minor fixes.
Converted Punishment_FF tabs to spaces.
closes [#1081](https://github.com/official-antistasi-community/A3-Antistasi/issues/1081)
1. ~Have you loaded the Mission in Singleplayer?~
Notes:
=> Caleb s punish rpt spam

A3-Antistasi/Stringtable.xml
1. [ ] Bug
Information: Adds Czech translation to the stringtable
closes #1104 
closes #1080 
1. [x] No
Notes:
=> Adds Czech translation and fixes small typos

A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
The Elcan was the wrong sight for this.
1. [ ] Bug
Information:
Swapped the ELCAN MG Optic to a proper alternative
closes #1064 
1. [ ] No
Notes:
=> Remove MG optic from USAF PvP TL

A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_AT.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_machineGunner.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_medic.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_rifleman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
1. [ ] Bug
Information:
Swapped RHS flashbangs for the less cancerous ACE ones. Also swapped AP ammo to normal for anyone that had it.
closes #1064 
1. [ ] No
Notes:
=> Remove rhs bangs

A3-Antistasi/Stringtable.xml
1. [ ] Bug
Information: Completed the French translation.
closes #1064 
1. [x] No
=> French translation

A3-Antistasi/functions/AI/fn_airbomb.sqf
1. [x] Bug
Information:
_plane is actually the pilot and therefore typeOf _plane would never == vehSDKPlane
closes #XXXX in to sec
1. [x] No
Notes:
=> Fix broken halfing for rebel case of airbomb

A3-Antistasi/FSMs/DriveAlongPath.fsm, A3-Antistasi/functions/AI/fn_vehicleMarkers.sqf, A3-Antistasi/functions/Missions/fn_convoy.sqf
1. [X] Bug
Some turd-polishing on the convoy mission code. Vehicles flying 500m into the sea on spawn were getting a bit ridiculous:
- Replaced the spawning mechanics, should be mostly non-lethal.
- Rewrote the crew spawning to work better with the FSM.
- Pulled out a lot of duplicated code.
- Fixed the despawn mechanics for FSM crew splitting.
- Fixed a bug with getVehiclePoolForQRFs and selectRandom.
- Fixed some termination bugs, probably added a few too.
- Fixed a CfgMarkers lookup bug with mission box vans.
It's still not good. Convoy vehicles don't follow each other except by timing and accident. The convoy escorts aren't going to make any effort to defend the objective. But it spawns, rarely explodes, drives towards the objective reasonably reliably and …
=> Refactor and fixes to get the convoy mission approximately working:

A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
1. [x] Bug
Information:
this is to check if SalvageRope action in use with salvage mission is being executed on jip clients is actually being run. respawn eh in addplayerWinchActions was fixed for a possible BI bugg/bad behavior with respawn eh, now only set the variable SalvageRopeAction to false and lets the spawned loop handle it. spawned loop is now also set with _missionComplete as initially false and only updates to actual status after at least running once
closes #1139 
1. [x] No
Notes:
=> added a log for JIP, fixed bad respawn eh and spawn loop

A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_WDL.sqf
1. [ ] Bug
3. [x] change
Information:
Removed the VTOLs from attack helicopters as per the latest meeting.
closes #unnecessary explosions
1. [ ] No
Notes:
=> Sonorous meerkat remove vtol

A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [X] Bug
Information:
Added missing lines for updating the HUD on server load, to avoid getting the message shortly after the load
closes #1146 
1. [ ] No
Notes: Havent loaded it yet, but it should be no problem
=> Fixed HUD not getting updated on mission load with aggression

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm
1. [x] Bug
Information:
- fixed the 50 cals at kavala castle and seaport for altis green and blu
- added 50 cals for the stadium for altis green and blu
closes #1066  
3. [x] Have you loaded the Mission in local MP?
1. [x] No
Notes:
@Lazejun This time I tested it
=> Altis map updates

Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Virolahti.vt7/mission.sqm
1. [x] Bug
Information:
fixed issues
closes #1066 
1. [x] No
Notes:
=> Map updates

A3-Antistasi/functions/init/fn_initSpawnPlaces.sqf
Added CUP Hangars.
Added CUP Hangars to array that turns the Plane 180 degrees.
Removed Contact DLC Service Hangar
1. [x] Bug
Information: Added 3 CUP Hangars to Hangar array "Land_Mil_hangar_EP1", "Land_Ss_hangar", "Land_Ss_hangard".
Since they spawn the wrong way around i had to add them to the Case where the Plane gets turned 180 Degrees.
Removed the Contact DLC Service Hangar since its a Bad spawn due to the Plane being unrecoverable.
closes #1166 
1. [x] No
Notes:
=> Hangar Update/Enhancement

A3-Antistasi/functions/CREATE/fn_patrolCA.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
Information:
Added fallbacks for the vehicle selection, so the script has some vehicle to choose from in any case. Might have not caused problems yet, but it wont in the future
closes #1154 
1. [ ] No
Notes: Havent started it, worked from my laptop, but Travis should figure out if it is ok
=> Fix edge cases for attacks

README.md
* Bug
Information:
ADDed build with ADD to README.md
Notes:
=> Added how to build with ADD

A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf
1. [x] Bug
2. [ ] Change
Information: rhsusf_M1117_W changed to rhsusf_M1117_D, due to Camo.
closes #1192 
1. [x] No
Steps: 
Notes:
=> Correct Vehicle Camo

A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
GL soldier swapped with marksman after complaints about difficulty.
1. [ ] Bug
3. [x] Change
Information:
Swapped the GL soldier in TKA sentry squad with a marksman after complaints about difficulty.
closes #1064 
1. [ ] No
Notes:
=> Replace GL in TKA sentry patrols

A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions/Garage/fn_garageVehicle.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [X] Change
Information:
Added limit to personal garage with parameter.
Texts: Unlimited, 2, 5, 10
Values: 0, 2, 5, 10
Default: 2
closes #1210
1. [x] No
Steps: 
start the game with wanted params, start garaging
Notes:
=> added limit to personal garage with param for count/off

A3-Antistasi/functions/Ammunition/fn_itemSort.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Save/fn_varNameToSaveName.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
=> Testing of PR #1234 

A3-Antistasi/functions/Base/fn_logPerformance.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds faction cash and HR to the performance log.
closes #XXXX
1. [ ] No
Steps: 
Run on a server, check log.
Notes:
=> Faction cash and HR added to perf log.

A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
1. [ ] Bug
2. [X] Change
Information:
per request of bob, a block to garaging for players when they are more than 25m away from the vehicle
closes #1064 
1. [ ] No
Steps: 
Notes:
=> added block if players are more than 25m away from the vehicle

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Stratis.Stratis/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-Virolahti.vt7/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
- check every vehicle marker for road availability
- added seaSpawn as well as seaPatrol markers to cherno summer and cherno winter
- includes Lazejuns adaptation of the slot order
- Adapted island markers on Tanoa 
closes #1303 
closes #1233 
closes #1048 
1. [x] No
Steps: 
Load the missions and look around - there is nothing directly to test.
Notes:
=> map overhaul

A3-Antistasi/FSMs/ConvoyTravel.fsm
1. [X] Bug
2. [ ] Change
Fixed a bug where a variable wasn't passed into a spawn, causing RPT errors when a reinf convoy vehicle despawned after arriving, and possibly failing to delete the vehicle.
Also threw in a couple of setWaypointStatements fixes in the same file from #1229 because merge conflicts in FSM code are likely to be a pain.
closes #1324 
1. [x] No
=> Fix reinf convoy vehicle deletion bug

A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
Someone reported FF in the AI, all are now different and safe.
1. [x] Bug
2. [x] Change
Information:
All units in 3CB Reb TPGM Arid replaced from UN to TPGM
closes #1319 
1. [ ] No
Steps: 
load mission, spawn one of each rebel unit + vic
Notes:
=> Replace possibly faulty UN units with TPGM

A3-Antistasi/JeroenArsenal/JNL/fn_logistics_load.sqf, A3-Antistasi/JeroenArsenal/JNL/fn_logistics_unLoad.sqf, A3-Antistasi/functions/AI/fn_surrenderAction.sqf, A3-Antistasi/functions/Base/fn_garbageCleaner.sqf, A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> update 31.07 fix ace actions and despawning crates

A3-Antistasi/Templates/3CB_Occ_BAF_Arid.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Temp.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Temp.sqf
These actually break stuff. Get them removed for 2.3.1
1. [x] Bug
2. [ ] Change
Information:
closes #1358
1. [ ] No
Steps: 
Notes:
=> Remove FFAA checks from templates

A3-Antistasi/functions/Punishment/fn_punishment_addActionForgive.sqf, A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf, A3-Antistasi/functions/Punishment/fn_punishment_removeActionForgive.sqf, A3-Antistasi/functions/Punishment/fn_punishment_sentence_client.sqf, A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf
* Bug
* Change
Information:
When teleporting in and out of the Ocean Gulag:
The animation is cleared (For free fall it take the game while to register: so the player returns to the fall position).
The velocity is reset with 1m*s^-1 vertical velocity.
Detainees are checked for vehicle incase they jumped into a boat while in the Ocean Gulag.    
closes [#1374](https://github.com/official-antistasi-community/A3-Antistasi/issues/1374)
* Yes (Needs testing)
Vehicle Steps: 
1. Drive over many people (or Petros with AllowDamage).
2. Get pulled out of the vehicle and sent to the ocean over the above surfboard with reset animation.
3. Upon return, you are pulled out of any sort of speed boat, placed with reset animation, small upward velocity, on a safe location within 50m of …
=> CS 1374 Punishment teleport dangerous

A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
1. [X] Bug
2. [ ] Change
Information: Corrected a Typo in a Modelpath.
closes #1378 
1. [ ] No
Steps:  Try loading a Box in a Ural-4320 (Closed)
Those are the ones with the cover in the back.
Notes:
=> Fix JNL Modelpath Typo

A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
1. [x] Bug
2. [ ] Change
Information: added a helper object to salvage rope (winch action) and adjusted its offset to avoid some arma fuckery that could launch/damage players using the action
closes #1380
1. [x] No
Steps: spawn in call A3A_fnc_salvageRope to add the action, and go deploy and stow the winch.
Notes:
=> added a helper and adjusted the attachment point

.github/ISSUE_TEMPLATE/bug_report.md
Check boxes now work and disay correctly
=> Fixed the check boxes on bug template

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_placementselection.sqf, A3-Antistasi/functions/Punishment/fn_outOfBounds.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/onPlayerRespawn.sqf
1. [x] Bug
2. [x] Change
Information:
added a kill zone to prevent players using moving outside the map to avoid having to deal with the ei between them and their objective.
closes #1322
1. [x] No
Steps: take a stroll or ride or flight outside the map
Notes: Jets have a 3k increased traversal area, and hq has a 1k exception distance.
=> added out of bounds kill zone

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_HIDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_HIDF_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Temp.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
=> PR #1357 to Bugfix

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
**airport_2**
Turned Helipads facing downhill, Moved Vehicle Marker away from Hangar, added 1 Mortar marker and moved the existing one away, added Sandbag Cover Circle for each Mortar Marker.
**BEFORE**
**AFTER**
**Control Markers**
Moved all Control markers that could possibly spawn bad further away from Crossings to ensure no bad spawns.
Example:
**Before:**
**After**
(I am aware its the Vehicle Roadblock but its not alligned with the Road that spawned it turned)
**HQ**
Moved HQ to Gori Factory area.
**Kavala Castle Outpost**
Turned Helipad facing downhill to Prevent this:
closes #1454 
3. [ ] Have you loaded the mission on a …
=> Map Update: Move HQ, Helipads, Small changes

A3-Antistasi/Stringtable.xml
This adds Korean translation to the existing stringtable.
Thank you very much to cucumber2, weed, astral and unit_normal from the DCinside's Arma Community.
1. [ ] Bug
2. [ ] Change
Information:
Added Korean translation    
closes #1423 
1. [ ] No - Translation was already checked by others outside of the community
=> Added Korean Translation

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/Missions/fn_missionRequest.sqf, A3-Antistasi/functions/Missions/fn_missionRequestAUTO.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [x] Bug
2. [ ] Change
Information:
missionRequest can be called by functions at init, and the boss is not defined yet, this holds those untill theBoss is defined. in addition auto mission requests when all missions exists it exits out now
closes #1455
1. [x] No
Steps: 
Notes:
=> fixed two errors with mission request

A3-Antistasi/functions/Save/fn_deleteSave.sqf
1. [X] Bug
2. [ ] Change
Fix typo in deleteSave that probably slipped through due to excessive debug console testing. Also added the new saved variables for deletion.
closes #1474
1. [X] No
=> Fix typo in deleteSave, add new saved vars

A3-Antistasi/Stringtable.xml
Changes the 2 tabs in front of the korean translation into 8 spaces
=> Tab to space conversion

A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf, A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3-Antistasi/functions/Dialogs/fn_mineDialog.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf
* Bug
* Change
Information:
* The Join message has been simplified and shortened.
* The Persistent Save message only contains the HR, Money and direction on how to get more information from Persistent Save Diary Entry.
* Minefield English gramma has been corrected.
closes [#1468](https://github.com/official-antistasi-community/A3-Antistasi/issues/1468)
1. [ ] No
2. [x] Yes (May need further critique about style and content.)
Steps: 
Load in mission, have a look at the Join message.
Persistent save, have a look at the message.
Images for assistance:
=> CS-1468-Chop-Long-Hints

A3-Antistasi/functions/Missions/fn_missionRequest.sqf
1. [x] Bug
2. [ ] Change
Information:
self explanatory
closes #1545
1. [x] No
Steps: 
Notes: [] call A3A_fnc_missionRequest; a bunch of times, no assassination missions should spawn
=> assassination missions removed from auto request

A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf, A3-Antistasi/functions/Revive/fn_handleDamage.sqf
* Change
* Removed, The EH used is not close to a catch-all solution.
* `Petros was injured by FrostsBite (UID: 01234567890123456), 5.81221m from HQ`
* Removed, Bug caused this log to not go to server
* `21:10:00 "578.751: [Antistasi] | INFO | fn_punishment_FF_checkNearHQ.sqf | EXPLOSIVE DISCHARGE HQ | FrostsBite [01234567890123456] distance from Petros: 4.80029"`
* Added 
* `20:35:18 "1438.55: [Antistasi] | INFO | fn_punishment_FF.sqf | DAMAGE | FrostsBite [01234567890123456] (grid: 026006; 6m from HQ; customMessage:'You cannot throw grenades or place explosives within 75m of base.')"`
OR
* `20:35:48 "1468.45: [Antistasi] | INFO | fn_punishment_FF.sqf | DAMAGE | FrostsBite [01234567890123456] (grid: 026006; 6m from HQ; customMessage:'') damaged Petros [AI] (grid: 026006; 8m from HQ; 3m …
=> CS-1536-AllDamageLog

A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Copying data, nothing to see here
=> Making CSAT more aggressive

A3-Antistasi/functions/AI/fn_chooseSupport.sqf, A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf, A3-Antistasi/functions/Supports/fn_SUP_CASRun.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrike.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrikeAvailable.sqf, A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineCSAT.sqf, A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineNATO.sqf, A3-Antistasi/functions/Supports/fn_createSupport.sqf, A3-Antistasi/functions/Supports/fn_initSupportCooldowns.sqf, A3-Antistasi/functions/Supports/fn_sendSupport.sqf, A3-Antistasi/functions/Supports/fn_supportAvailable.sqf, A3-Antistasi/functions/Supports/gunshipTest.sqf
=> Wurzel hardcore supports

A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf, README.md
1. [x] Bug
2. [ ] Change
Information: same as #1570, but to unstble
closes #XXXX
1. [ ] No
Steps: 
Notes: wait for john to review and approve #1570 then you can merge
=> Salvage rope fix

A3-Antistasi/functions/UI/fn_customHintInit.sqf
* Bug
* Change
Added commented list of global variables and processes to customHintInt.
Closes [#1599](https://github.com/official-antistasi-community/A3-Antistasi/issues/1599)
1. [x] No (I don't think this should cause issues. If it does, give me a call.)
Load game, make sure unit tests pass.
=> Added list of global UI vars and UI processes.

A3-Antistasi/functions/Base/fn_flagaction.sqf
1. [ ] Bug
2. [x] Change
Information: Added SetRain to FireX, should cause no issues cause its completly the same way as the other actions.
closes #1597 
1. [x] No
Steps: Setrain to whatever, slap the Option on the Tent
Notes:
=> Add Remove Rain to "Tent"

A3-Antistasi/Stringtable.xml, A3-Antistasi/changelog.txt, A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf, README.md
This merges the bugfixed and tested version to the master branch so version 2.3.2 can be published.
=> Merge bugfix branch into master to release 2.3.2

A3-Antistasi/Stringtable.xml
**What type of PR is this.**
**What have you changed and why?**
Add Russian localization
**Please specify which Issue this PR Resolves.**
NONE
**Please verify the following and ensure all checks are completed.**
**Is further testing or are further changes required?**
=> Added Russian translation

A3-Antistasi/Stringtable.xml, A3-Antistasi/dialogs.hpp
1. [ ] Bug
2. [ ] Change
Information:
Multilanguage support in Dialog Menu and translation into Russian
1. [x] No
=> Multilanguage support in Dialog Menu

A3-Antistasi/functions/Base/fn_AILoadInfo.sqf
* Change
* Enhancement
AILoadInfo now has a title.
closes #1624 
1. [x] No
* Yes
Steps: 
1. open game option
2. open map info
3. AI load
4. trigger persistent save
=> AILoadInfo now has a title.

A3-Antistasi/functions/Base/fn_rebelAttack.sqf
Copying data over after deleting my local repository...
=> Revert aggro improvements

README.md
1. [x] Bug
2. [ ] Change
Updated discord link as the old one was deleted.
1. [ ] No
Steps: 
Run Antistasi, confirm that PC does not ignite.
=> Updated discord link as old one was deleted.

A3-Antistasi/functions/LTC/fn_canLoot.sqf, A3-Antistasi/functions/LTC/fn_canTransfer.sqf, A3-Antistasi/functions/LTC/fn_carryCrate.sqf, A3-Antistasi/functions/LTC/fn_initLootToCrate.sqf, A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf, A3-Antistasi/functions/LTC/fn_lootToCrate.sqf, A3-Antistasi/functions/LTC/fn_spawnCrate.sqf
1. [x] Bug
2. [ ] Change
Information:
Missed dupe prevention on leftovers in previous fix. also changed tabs to spaces and added headers to the files. dupe prevention change is on line 182
closes #1582
1. [ ] No
Steps: 
Notes:
=> Fix dupe with LTC leftovers

A3-Antistasi/functions/AI/fn_canConquer.sqf, A3-Antistasi/functions/AI/fn_canFight.sqf
1. [x] Bug
2. [ ] Change
Information:
problem describes in #97
this PR make roadblock destroy normal, like it must be 
closes #97
1. [x] No
Steps: 
1. find roadblock
2. kill car gunner
3. wait
4. no more problem
Notes:
=> Bug-fix #97

A3-Antistasi/functions/Base/fn_distance.sqf
1. [x] Bug
2. [ ] Change
Information:
accidentally, I tried to figure out how it works to find the reason for the other issue and 
i refactor the file  fn_distance.sqf  and find some wrong code
closes #1644
1. [x] No
Steps:  
Notes:
=> distance refactoring and fix

A3-Antistasi/functions/AI/fn_typeOfSoldier.sqf
1. [x] Bug
2. [ ] Change
Information: fix typo
closes #1656
=> Bug-fix #1656 Update fn_typeOfSoldier.sqf

A3-Antistasi/REINF/dismissPlayerGroup.sqf, A3-Antistasi/REINF/dismissSquad.sqf
1. [x] Bug
2. [ ] Change
Information:
I adding check for petros in dismiss scripts
to fix the issue
closes #1567
1. [ ] No
check pls in dedicate server
Steps: 
1. select in menu move HQ
2. try dismiss Petros
Notes:
=> Bug-fix Issue #1567 HQ can sell Petros

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_cargoToArsenal.sqf, A3-Antistasi/functions/Ammunition/fn_ammunitionTransfer.sqf
1. [x] Bug
* Change
* Enhancement
* Fixed `Transfer Vehicle Cargo to Ammobox` dupe.
* Fixed `To Crate` dupe.
* Added busy checks to `fn_ammunitionTransfer.sqf` and `fn_arsenal_cargoToArsenal.sqf`.
* Get & clear inventory moved from `fn_arsenal.sqf` (client-side) to `fn_arsenal_cargoToArsenal.sqf` (server-side)
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1665
###Is further testing or are further changes required?
1. [ ] No
* Yes
1. Create crate
```sqf
_crate ="B_supplyCrate_F" createVehicle getPos Player; 
clearMagazineCargoGlobal _crate; 
clearWeaponCargoGlobal _crate; 
clearItemCargoGlobal _crate; 
clearBackpackCargoGlobal _crate; 
_crate call …
```
=> Fixed multiple Arsenal duplication exploits

A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
1. [x] Bug
2. [ ] Change
1679 What have you changed and why?
Information:  
closes #1679 
1. [x ] No
Steps: kill tank, clean turret.
Notes: First PR, Blame Laze if everything breaks.
=> Added ACE turret wrecks to garbage clean

A3-Antistasi/Stringtable.xml, A3-Antistasi/dialogs.hpp
1. [ ] Bug
2. [ ] Change
Information: corrected typos in stringtable.xml and dialogs.hpp changed donation message to read "Faction" instead of "Fraction
closes #1635 
1. [x] No
Steps: Check to see that the UI changes have correctly been implemented. 
Notes:
=> Fixed typos in Stringtables & dialogs

A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
1. [X] Bug
2. [ ] Change
Information: 
Yoinked the Tow Rope check from Fast Travel and applied it to Garage
closes #1654 
1. [x] No
Steps: Have a Tow Rope out on the Vehicle you are Garaging,
Try to Garage while Towing a Vehicle.
Notes:
=> Add Towing check for Garaging Vehicles

A3-Antistasi/Templates/AddonVics/rds_Civ.sqf, A3-Antistasi/Templates/AddonVics/rds_Logi_Nodes.sqf, A3-Antistasi/Templates/detector.sqf, A3-Antistasi/Templates/selector.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds additive civ template, logi nodes, detection and selection for RDS Civilian Pack
closes #1024 
1. [x] No
Steps: 
Load into the mission with RDS Civilian pack and observe the new civilian vehicle spawns, Civilian Skoda is capable of loading 1 crate.
Notes:
While it could fit 2 small crates, the skoda cannot fit the full size ammo box.
=> RDS Integration

A3-Antistasi/Templates/RHS/RHS_Logistics_Nodes.sqf, A3-Antistasi/Templates/Vanilla/Vanilla_Logistics_Nodes.sqf
1. [x] Bug
2. [ ] Change
Information: halfed the recoil of all static weapons in the logistics system, this will likely prevent the issue from recurring 
closes #1696 
1. [x] No
Steps: 
Notes:
=> halfed recoil force for all static mounts

A3-Antistasi/Templates/NewTemplates/#Examples/CivilianExample.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Tropical.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Civ.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_HIDF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_HIDF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Civ.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf
@Spoffy
Additional things added to the templates:
- REB-Template
-- "vehicleAA"-variable
- Only added the assets up to the marker put in by you
- CIV-Template
-- "vehiclesCivRepair"-variable
-- "vehiclesCivMedical"-variable
-- "vehiclesCivFuel"-variable
-- every vehicle has a variable after the classname determining the chance to spawn
- CIV uniforms and headgear are missing
=> Adds temporary REB and CIV templates for Vanilla, RHS and 3CB

A3-Antistasi/functions/AI/fn_napalm.sqf, A3-Antistasi/functions/AI/fn_napalmDamage.sqf
See https://github.com/official-antistasi-community/A3-Antistasi/pull/1725
=> Cs 1724 napalm player no UI d

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_crewTypeForVehicle.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf, A3-Antistasi/functions/init/fn_initVehClassToCrew.sqf
* Bug
* Change
Information:
* The lookup table is a hashmap initialised in fn_initVarServer.
* It allows quickly getting the crew type from a vehicle classname.
* Lets the developer know when the template array was incorrectly strctured.
1. [ ] No
Steps: 
1. Next open debug console and local exec this script:
```sqf
[getPos player vectorAdd [0,0,1000],0,selectRandom vehFixedWing,west,false] call A3A_fnc_spawnVehicle params ["_vehicle", "_crew", "_group"]; 
{moveOut _x} forEach _crew; 
{_x setVelocity [0,0,0]} forEach _crew; 
{_x setPos (getPos player getPos [2,getDir player])} forEach _crew; 
deleteVehicle _vehicle; 
{_x …
```
=> CrewTypes are now pulled from a lookup table.

.github/pull_request_template.md
as we dont support SP anymore we should not have testing for it as a part of our PRs
1. [ ] Bug
2. [x] Change
Information: We dont support SP anymore our PR template should therefor not have a check for tested in SP, especially since SP behaves differently to LH/DS
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Removed SP test checkbox from PR template

A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
1. [x] Bug
2. [ ] Change
Information: if we cant find a position to create the guard vehicle, treat the heli as the guard vehicle.
guards are likely not going to be able to get in and have to walk,
but no errors
closes #1739 
1. [x] No
Steps: 
Notes:
=> fix #1739 - default guard to treating the heli as there vehicle

A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
for cases where it cant find the node.
added log line to gather more information about the issue
1. [x] Bug
2. [ ] Change
Information: added an exit case should the node index be -1. in addition it will now log an error as to gather more info about why this happened.
closes #1742 
1. [x] No
Steps: 
Notes:
=> fix - #1742 - added exit case for updateList

A3-Antistasi/functions/Logistics/functions/fn_logistics_addOrRemoveObjectMass.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
1. [x] Bug
2. [ ] Change
Information: reset vehicle mass on last cargo unloaded.
closes #1756 
1. [ ] No
Steps: 
Notes:
=> fix accumulating mass with deleted cargo

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Dialogs/fn_HQGameOptions.sqf
* Bug
* Change
* All button changes to Civ Limit, AI Limit, Spawn Distance create a log entry.
* Put blame on server people who raise it. (Allow them to be educated).
* Know its effect on performance.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1772
1. [x] No
Steps: 
1. Load Antistasi
2. Click each of the limit buttons at the Map Object > Game Options.
3. Check RPT.
Notes:
```sqf
0:05:27 "3383.11: [Antistasi] | INFO | dialogs.hpp | FrostsBite[12345678901234567] changed the Spawn distance from 1000 to 900"
0:05:27 "3383.41: [Antistasi] | INFO | …
```
=> CS-1772-log-AI-limit-spawn-distance

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Dialogs/fn_HQGameOptions.sqf, A3-Antistasi/functions/init/fn_initClient.sqf
* Bug
* Change
* All button changes to Civ Limit, AI Limit, Spawn Distance create a log entry.
* Allow commanders and admins to edit game options.
* Slow min and max to user.
* Put blame on server people who raise it. (Allow them to be educated).
* Know its effect on performance.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1772
1. [x] No
Steps: 
1. Load Antistasi
2. Click each of the limit buttons at the Map Object > Game Options.
3. Check RPT.
Notes:
```sqf
191.156: [Antistasi] | INFO | fn_HQSpawnOptions.sqf | SET | FrostsBite [12345678901234567] [4] …
```
=> Allow commanders and admins to edit game options.

A3-Antistasi/Includes/LogMacros.inc, A3-Antistasi/Includes/common.inc, A3-Antistasi/Includes/includesBasics.txt, A3-Antistasi/init.sqf
1. [ ] Bug
2. [x] Change
Information:
Log macros made to replace ``A3A_fnc_Log``
closes #XXXX
1. [x] No
Steps: 
Notes:
Changing away from ``A3A_fnc_Log`` would be a gradual move for when we touch files with logging in them
=> Log macros

A3-Antistasi/functions/AI/fn_napalmDamage.sqf
1. [ ] Bug
2. [ ] Change
* Reduced overkill from 5 to 3
* Reduced ticks from 12 to 3.
* Total damge ticks per object reduced from 60 to 9.
* Increases performance.
1. [x] No
Steps:
=> CS-NapalmReduceDetail

A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf, A3-Antistasi/functions/Base/fn_logPerformance.sqf
1. [ ] Bug
2. [X] Change
Information: Integrated the aggression log line from its file into the main log line.
closes #1573 
1. [X] No
Steps: Start the game and look in the logfile
Notes:
=> Reordered logs to main function

A3-Antistasi/functions/Supports/fn_SUP_mortar.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Wurzel template support fixes - side dependency

A3-Antistasi/functions/Supports/fn_SUP_QRFAvailable.sqf
1. [x] Bug
2. [ ] Change
Information: check should exitWith if it found a suitable outpost
closes #1844 
1. [ ] No
Steps: 
Notes:
=> should exitWith if it found an outpost

A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
1. [X] Bug
2. [ ] Change
Information:
Prevents HQ assets from getting destroyed by orbital strikes.
None opened
1. [X] No
Steps: 
Notes:
=> Fixed orbital strikes deleting HQ assets

A3-Antistasi/functions/init/fn_initClient.sqf
1. [x] Bug
2. [ ] Change
Information:
Used Ace_Claim to disable all Ace Interaction on BoxX
Also changed one accidental miss case on Vehiclebox
closes #1873 
1. [x] No
Steps: 
Start the Game with Ace,
Try to Ace load the Arsenal,
There should be no interaction.
Notes:
=> Remove Ace interaction from Arsenal (BoxX)

A3-Antistasi/MissionDescription/gameSettings.hpp, A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions/init/fn_initParams.sqf, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Sahrani.sara/mission.sqm, Map-Templates/Antistasi-Stratis.Stratis/mission.sqm, Map-Templates/Antistasi-Takistan.takistan/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-Virolahti.vt7/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
- deleted all PvP relevant assets in all missions (marker, flags, playable units)
- set "allowPvP" to false in fn_initParams
- adapted max player number in gameSettings.hpp (includes HCs)
- deleted obsolete parameters (allowPvP and teamSwitchDelay) from params.hpp    
closes #####
1. [x] No
Steps: 
Simply load it and check that nothing is breaking
Notes:
=> Getting rid of / deactivating PvP

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/EventHandler/addArtilleryTrailEH.sqf, A3-Antistasi/functions/Supports/fn_SUP_mortar.sqf, A3-Antistasi/functions/Supports/fn_addSupportTarget.sqf
1. [ ] Bug
2. [X] Change
Information:
Added smoke trail for flying artillery shells to give the fire direction away.
Also make the mortar support less spammy when attacking the same position.
None opened
1. [ ] No
Steps: Buy mortar/get under mortar fire. Watch trails
Notes:
=> Added arty trails and make the mortar less spammy on the same position

A3-Antistasi/MissionDescription/CfgRemoteExec.hpp, A3-Antistasi/MissionDescription/master.hpp
* Bug
* Change
Information:
* All commands and functions have been allowed for BE. This will allow the use of BE's RCON tools and scripts build on Battleye. 
* More detailed whitelisting may be made in the future if nessary.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1838
* Have you loaded the mission in LAN host?
Steps: 
Create dedicatied server with Battleye enabled. Join game. Changes map settings, the UI slider should appear and work correctly.
=> CfgRemoteExec Allow All for BE.

A3-Antistasi/MissionDescription/gameSettings.hpp, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initParams.sqf
Fixes issues which were not caught when merging
- fixed JIP issue
- updated the gamemode-tag
=> remove leftover from merge conflict

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
1. [X] Bug
2. [ ] Change
Fixed references to FlagCarrier that were either not working with VN (should have been FlagCarrierCore) or redundant (FlagCarrierCore is a building anyway).
closes #1912 
1. [X] No
=> Fix references to FlagCarrier so that they work for VN flagpoles

A3-Antistasi/functions/AI/fn_askHelp.sqf, A3-Antistasi/functions/AI/fn_chargeWithSmoke.sqf, A3-Antistasi/functions/AI/fn_help.sqf, A3-Antistasi/functions/REINF/fn_equipRebel.sqf
1. [X] Bug
2. [ ] Change
Fixed a bunch of stuff while dealing with #1915:
- Include VN first aid kits in askHelp checks.
- Refactor askHelp for performance and sanity.
- Fix precedence bug that could prevent AIs from reviving players.
- Fix local variable overwrite in chargeWithSmoke.
- Fix case where medic stops at >3m from target and then waits for 60 seconds.
- Equip rebel medics with appropriate medical gear (they had nothing since new templates).
closes #1915
1. [X] No
The rest of the vanilla medical system is no worse than it was.
Get a medic and two riflemen. Enable AI autoheal:
1. Shoot the medic in the legs …
=> Vanilla medical fixes + VN AI compatibility

A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added the Flare Launcher with 1 Magazine, might be useful at Night, but thats about it.
I already checked if Ai uses the Flarelauncher as "AT", they dont so we are good there.
Added 3 more Uniforms to RebellUniforms/CivilianUniforms
Added a Machete and an Axe as Starting Melee weapons,
Added Bayonets that are already visible on the Weapons but need the Item to work.
Added all Camo Wraps, these are only cosmetic, but as you could make such very easily its fair to give them at the start.
Added one Punji Traps "mine", will probably do very little, but people can play around with it and walk into their own mines.
closes #XXXX
1. [x] …
=> Vn Expand Starting Gear

A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
1. [ ] Bug
2. [ ] Change
Information:
For whatever Reason some Weapons are in the weirdest Categories:
The ones with Comments were overwriten to fit in their respective Categories
```sqf
//AllRifles, these should only be Rifles + Assault Rifles
["vn_m1897", //Shotgun
"vn_izh54", //Shotgun 
"vn_izh54_shorty", //Shotgun
"vn_pps52", //SMG
"vn_pps43", //SMG
"vn_mc10", //SMG 
"vn_ppsh41", //SMG
"vn_k50m", //SMG 
"vn_mat49", //SMG
"vn_mat49_f", //SMG
"vn_mat49_vc", //SMG
"vn_m3a1", //SMG
"vn_sten", //SMG
"vn_m16",
"vn_m16_camo",
"vn_m16_xm148",
"vn_xm177",
"vn_xm177_camo",
"vn_xm177_xm148",
"vn_xm177_xm148_camo",
"vn_xm177_fg",
"vn_xm177_short",
"vn_xm177_stock",
"vn_xm177_stock_camo",
"vn_m63a",
"vn_m79" //GrenadeLauncher ]
```
```sqf
//AllRocketLaunchers
["vn_rpg2", …
```
=> VN Weapon Category Filtering

A3-Antistasi/functions/init/fn_initZones.sqf, Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/mission.sqm
- adds a few new roadblocks
- blacklisted 2 villages
Does not really has to be completely reviewed.
Currently is being tested on Test 1.
closes #1907 
closes #1909
=> Vn map update

A3-Antistasi/Stringtable.xml
Information:
To be honest, previous Simplified Chinese translation is a really really ugly work.
Although it made the mission finally readable for some Chinese-only people, there are almost misunderstandings and incorrectness everywhere.
This time. I've **totally refactored all the Simplified Chinese translation, making it finally readable and as accurate as I can do**.
Thanks for player xiduola in my clan, he helped translate the UI part.
However, I still see **many strings are not added to stringtable so we cannot provide multilingual support**. I hope developers can help with that.
closes #XXXX
1. [x] No
Steps: Change the game into Simplified Chinese, restart the …
=> Multilingual Support: Completely refactored previous Simplified Chinese translation for vn-development branch

A3-Antistasi/functions/Supports/fn_SUP_ASFRoutine.sqf, A3-Antistasi/functions/Supports/fn_SUP_gunshipSpawn.sqf
1. [x] Bug
2. [ ] Change
Follow up to #1948. Same changes made in the HandleDamage EH in fn_SUP_ASFRoutine.sqf and fn_SUP_gunshipSpawn.sqf.
closes #1938
1. [x] No
Steps: 
Notes:
=> Fix Other Support HandleDamage EHs

A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Templates/fn_compatibilityLoadFaction.sqf
1. [x] Bug
2. [ ] Change
I renamed the file fn_compatabilityLoadFaction.sqf to fn_compatibilityLoadFaction.sqf, then used VS Code's find and replace function to replace every instance of the string "compatability" with "compatibility" across all files in the mission.
closes #1946
1. [x] No
Just see if the scenario loads correctly
Notes:
=> rename fn_compatabilityLoadFaction.sqf and update all references

A3-Antistasi/functions/Base/fn_sellVehicle.sqf
1. [x] Bug
* Change
* Enhancement
Information:
* Moved the vehicle sell checks lower, bellow the basic sale checks.
* Removed a vehicle sell check reset line.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1941
1. [ ] No
Steps: 
You will need two vehicles.
* Sell a vehicle within 50m of HQ.
* Try to sell a vehicle further than 50m from HQ. nothing happens and take that vehicle back.
* Sell the same vehicle within 50 of HQ.
Notes:
Has not been tested.
=> ↕ Moved the sale block checks lower.

A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
1. [X] Bug
2. [ ] Change
Fixed a logic bug in the offroading conditional caused during the undercover refactor (#1818).
closes #1952 
1. [X] No
Get in civilian car, drive slightly offroad (tolerance is ~50m) within 350m of enemy troops.
=> Fix refactor bug that caused vehicles to incorrectly lose undercover

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/Logistics/fn_logistics_isLoadable.sqf
1. [x] Bug
2. [ ] Change
Information: added a isLoadable function to logistiscs, mad AIVehInit add load action to all objects its run on that "isLoadable"
closes #XXXX
1. [x] No
Steps: 
Notes:
=> added a isLoadable check and implemented it in AIVehInit

A3-Antistasi/functions/Base/fn_resourcesFIA.sqf
1. [x] Bug
2. [ ] Change
Information: set the lockout flag to false when bailing. this fixes the lockout on bad input
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fix perma lockout in resourceFIA

A3-Antistasi/Garage/Core/fn_getCatIndex.sqf, A3-Antistasi/Garage/Core/fn_onUnload.sqf, A3-Antistasi/Garage/config.inc, A3-Antistasi/Garage/fn_addVehicle.sqf, A3-Antistasi/functions/init/fn_initParams.sqf
1. [x] Bug
2. [ ] Change
Information:
- old param not removed from initParams
- old log used (and incorrectly)
- wrong param passed to `execForGarageUsers`
closes #XXXX
1. [x] No
Steps: 
Notes:
=> 🩹fix a few errors that slipped in during garage review changes.

A3-Antistasi/functions/Revive/fn_unconscious.sqf
1. [x] Bug
2. [] Change
Information:
Removed the random chance to get your Voice Muted,
Turned it around so your Voice is always muted, cause you are Unconsious/in revive state,
Lowered the Global Volume to 0,7 to have it behave a bit similar to Ace's Revive State
closes #1993
1. [] Have you loaded the mission in LAN host?
1. [x] No
Steps: 
Notes:
=> Vanilla Revive TFAR Mute Fix

A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
1. [x] Bug
2. [ ] Change
Information: Fixed error about nil/null cargo/vehicle by adding a couple more null checks and adding defaults to _cargo
closes #XXXX
1. [x] No
Steps: 
Notes:
=> added null checks for logi unload

A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
1. [x] Bug
2. [] Change
3. [] Enhancement
Information:
Wrong Ammo given to Nato Military MGs,
Changed to the correct Ammo
closes nothing
1. [x] No
Steps: 
Notes:
=> Fix Typo in MG Array (Nato_Temperate)

A3-Antistasi/Garage/fn_addVehicle.sqf, A3-Antistasi/Garage/fn_initGarage.sqf, A3-Antistasi/Stringtable.xml
1. [x] Bug
2. [ ] Change
Information: fixed being able to manage garage while in a vehicle
- Open garage & garaging a vehicle
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> block garage access while in vehicle

A3-Antistasi/Garage/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
Information:
saftey!!!
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added extra safety checks to prevent dupe

A3-Antistasi/functions/Save/fn_saveLoop.sqf
unify persistent save hint title
1. [ ] Bug
2. [x] Change
Information:
Unified persistent save hint title    
closes #2021 
1. [x] No
Steps: 
Notes:
=> unify persistent save hint title

A3-Antistasi/functions/Ammunition/fn_configSort.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3-Antistasi/functions/Ammunition/fn_launcherInfo.sqf
1. [x] Bug
2. [ ] Change
Information:
fixed a return possibility of `nil` to the default `[false,false,[],[],[]]`
closes #1439 
1. [ ] No
Steps: 
Notes:
=> fixed a return case with nil

A3-Antistasi/Templates/NewTemplates/3CB/3CBFactions_Logistics_Nodes.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_AAF.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_ADA.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_ANA.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_HIDF.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_MDF.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Arid.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Logistics_Nodes.sqf, A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions/Base/fn_setPlaneLoadout.sqf
1. [ ] Bug
2. [x] Change
Information:
Added Malden Defense Force Template, used as OCC on Malden,
Added Afgan National Army Template, used as OCC on Kunduz,
Added African Desert Army Template, currently unused,
Added Brians HIDF Template with a few changes, used as OCC on Tanoa,
Added [Masai's](https://github.com/Masaigu1) AAF Template with a few changes, used as OCC on Altis.
Added Planes to SetPlaneloadout so they will be used with CASroutine etc.
Corrected a Typo in TKA East Template causing Police sometimes without a Primary Weapon.
Changed CDF's AN2 to a C130 due to Problems with the AN2.
Added RBS 70 as a Size 2 Static, it fits most vehicles and doesen't clip that badly.
Added High M240 as a Size 4 Static,
Added a new Pickup Truck from 3CB Factions with 2 Nodes, …
=> 3CB Factions, Add more Templates, New Vehicles, Nodes.

Tools/StreetArtist/LICENSE.txt
* Bug
2. [x] Change
* Enhancement
* Street Artist relicensed under ARMA PUBLIC LICENSE NO DERIVATIVES (APL-ND)
1. [x] No
No testing.
=> Updated StreetArtist LICENSE.txt

A3-Antistasi/functions/init/fn_initZones.sqf, Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/mission.sqm
1. [x] Bug
2. [ ] Change
Information:
- lowered the amount of civs in Hanoi North (hanoi2) as it was too high
- changed position of vehicle marker and hide terrain module on factory_1 due to issues with floating water
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Cln updates (hanoi2 civ count & factory_1 placements)

LICENSE, changelog.txt
1. [x] Changelog update
Notes:
=> 2.5.0 preliminary changelog & main license update

A3-Antistasi/Stringtable.xml, A3-Antistasi/functions/Base/fn_vehicleBoxHeal.sqf
1. [x] Bug
2. [ ] Change
Information:
added the feedback to stringtable and updated it to be correct and clearer
closes #2050 
1. [x] No
Steps: 
Notes:
=> updated feedback for vehicleBoxHeal

A3-Antistasi/functions/Base/fn_zoneCheck.sqf
1. [ ] Bug
2. [x] Change
Information:
as per meeting, rebel autocap is now disabled
closes #1480 
1. [x] No
Steps: 
Notes:
=> blocked rebel auto capture

A3-Antistasi/functions/Punishment/fn_punishment_sentence_server.sqf, changelog.txt
1. [x] Bug
2. [ ] Change
Information:
added a param
and added the right passing in spawn.
closes #2046
1. [ ] No
Steps: 
Notes:
simple param added
=> Punishment bug fix

A3-Antistasi/functions.hpp
1. [ ] Bug
2. [x] Change
Information:
changed tabs to spaces
closes #1867 
1. [x] No
Steps: 
Notes:
=> functions.hpp tabs to spaces

A3-Antistasi/Includes/LogMacros.inc, A3-Antistasi/functions/AI/fn_vehicleConvoyTravel.sqf, A3-Antistasi/functions/CREATE/fn_cycleSpawn.sqf, A3-Antistasi/functions/CREATE/fn_freeSpawnPositions.sqf, A3-Antistasi/functions/CREATE/fn_milBuildings.sqf, A3-Antistasi/functions/Convoy/fn_createAIAction.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf, A3-Antistasi/functions/Garrison/fn_createGarrison.sqf, A3-Antistasi/functions/Intel/fn_placeIntel.sqf, A3-Antistasi/functions/Utility/fn_localLog.sqf, A3-Antistasi/functions/init/fn_prepareMarkerArrays.sqf
1. [x] Bug
2. [x] Change
Information: 
The old log macros implementation lack overflow handling of the log message char limit.
this PR fixes this as well as introduces a new line indicator `>>> ` and eol termination to the log macros.
in addition the logArray calls that was left in previously due to the overflow issue has now been made into log array macro calls.
closes #XXXX
1. [ ] No
Steps: 
Notes: The overflow handling adds to the logging time as it has to do heavier processing of the log line, but for most shorter logging it will have a negligent impact.
=> Log improvements

A3-Antistasi/Garage/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
`[cursorObject, clientOwner, call HR_GRG_dLock, player] remoteExecCall ['HR_GRG_fnc_addVehicle',2]` call on listen server leads to 
inability to put vehicles into garage if host sits inside the vehicle. It is caused by seems to be forgotten usage of vanilla `player` function/property, so when we're executing it on listen server (`remoteExecCall ['HR_GRG_fnc_addVehicle',**2**]`) it checks host player instead of `_player`.
Also, this fix fixes vehicle checks on dedicated server too.
Original reports about the problem for reference and more explanation:
```
My friend and I have an issue where we cannot garage a vehicle while the other person is driving. For example I could be driving an offroad miles away but he cannot garage a vehicle unless I get …
```
=> Fixed inability to put vehicles into garage when player host of listen server is inside vehicle

A3-Antistasi/Garage/Core/fn_confirm.sqf, A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf, A3-Antistasi/Garage/fn_callbackHandler.sqf, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Dialogs/fn_squadRecruit.sqf, A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf, A3-Antistasi/functions/REINF/fn_addFIAveh.sqf, A3-Antistasi/functions/REINF/fn_build.sqf, A3-Antistasi/functions/REINF/fn_spawnHCGroup.sqf
1. [ ] Bug
2. [x] Change
Information:
- Reworked confirmPlacement to be easier to use externaly;
also removed some unnecessary statements.
- altered confirmPlacement and callbackHandler to accept external arguments.
- added a new case for addFIAsquadHC to callbackHandler
- made addFIAsquadHC use garage placement.
closes #2073 
1. [x] No
Steps: 
Notes:
=> Made HC squads vehicle placement use the garage placement

A3-Antistasi/functions/Base/fn_initPetros.sqf
1. [] Bug
2. [x] Change
3. [] Enhancement
Information:
Added the same Behaivior for Vests from Equip Rebell
https://github.com/official-antistasi-community/A3-Antistasi/blob/14d1505a278e0b198fa79962436c400f50766796/A3-Antistasi/functions/REINF/fn_equipRebel.sqf#L25-L28
closes #2070 
1. [x] No
Steps: 
Load into the Mission, check Petros Equipment, he should have a Vest and enough Space to fit Magazines
Notes:
=> Give Petros a Vest

A3-Antistasi/functions/Base/fn_distance.sqf, A3-Antistasi/functions/Base/fn_mrkUpdate.sqf, A3-Antistasi/functions/Base/fn_rebelAttack.sqf, A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf, A3-Antistasi/functions/Save/fn_loadServer.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf, A3-Antistasi/functions/init/fn_resourcecheck.sqf
1. [X] Bug
2. [X] Change
Ended up rewriting most of the punishment function:
- Punishment attacks no longer sent against occupant-controlled towns.
- Player scaling added to delay time and attacker vehicle count.
- Improved vehicle choice and maxUnits control, ensure 2+ transports.
- Defender ("civilian") count non-linearised, splits to groups of 4.
- Removed civInit from defenders, so that they shoot and don't affect aggro.
- Use combat landing in preference to fastrope, remove slow landing.
- Simplified termination conditions.
- Results only adjust support of nearby cities.
Plus some fixes to how destroyed cities are handled:
- Destroyed cities are now coloured black on the map.
- Destroyed cities are now invader-side, to prevent some weird spawning.
- Destroyed …
=> Quick rework of punishment attacks

A3-Antistasi/MissionDescription/params.hpp
1. [ ] Bug
2. [X] Change
A lot of users don't understand the limitations of the parameters page and don't read the text at the top properly. This PR adds some extra explanation in an attempt to reduce support overhead.
Tested in some plausible sub-1080p resolutions, parameter text mostly fits.
closes #XXXX
1. [X] No
=> More parameters explanation

A3-Antistasi/Stringtable.xml, A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/Missions/fn_missionRequest.sqf
- Changes "Assasination" to "Assassination" where available
- few punctuation things
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Assassination spelling overhaul

A3-Antistasi/functions/Base/fn_aggressionUpdateLoop.sqf, A3-Antistasi/functions/Base/fn_rebelAttack.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
2. [X] Change
After a real or simulated attack, the countdown of the attacking side was incremented. This conflicted with the counter-attack system where the final attacker was not always the one whose countdown had reached zero. This frequently caused degenerate results, commonly rebels being spammed with government attacks in the early game, followed by invaders not attacking for several hours in the midgame.
Some extra stuff that I fixed while I was in there:
- Reduced attack wave timeout to 15 mins after the wave completes spawning.
- Cleaned up the remUnitCount stuff that got moved into a function previously.
- Fixed copypaste error where invader countdown wasn't broadcast.
closes #1918
2. [ ] Have you …
=> Fix incorrect attack countdown incrementing + extras

A3-Antistasi/Includes/LogMacros.inc
1. [ ] Bug
2. [ ] Change
Information:
fixed array processing for large log lines, should now display them with each element on a new line 
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fixed white space issue with log processing

A3-Antistasi/Templates/Templates/#Examples/Example_Logistics_Nodes.sqf, A3-Antistasi/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf, A3-Antistasi/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf
1. [x] Bug
2. [ ] Change
Information: Fixed scripting errors in templates:
- Templates/Templates/#Examples/Example_Logistics_Nodes.sqf:25 missing delimiter , in array literal
- Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf:47 missing closing ] in array literal
- Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf:47 missing closing ] in array literal
n/a
1. [x] No
Steps: n/a
Notes:
=> Fixed script errors in 3CB and #Example templates

A3-Antistasi/Templates/Templates/VN/VN_MACV.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf
1. [X] Bug
2. [ ] Change
So far:
- Fixed trailing comma in MACV template causing init failures.
- Fixed array/string mismatch on staticAT causing airfield spawn failures.
closes #XXXX
1. [ ] No
=> Fix leftover bugs from #2047

Tools/StreetArtist/NG_importGUI.hpp, Tools/StreetArtist/Please Read Me.md, Tools/StreetArtist/functions.hpp, Tools/StreetArtist/functions/Model/fn_NG_navRoadHM_assert.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoadHM_remove.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoad_assert.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoad_connect.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoad_disconnect.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoad_getPeers.sqf, Tools/StreetArtist/functions/Model/fn_NG_navRoad_isConnected.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_convert_navGridHM_navGridDB.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_convert_navRoadHM_navGridHM.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_fix_oneWays.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_init.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_main.sqf, Tools/StreetArtist/functions/NavGridGen/fn_NG_simplify_junc.sqf, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_import.sqf, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_main.sqf, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_mainDialog.sqf, Tools/StreetArtist/init.sqf
* Change
* ☣ FIlters unknown connections from DB output.
* ☣ Filter unknown roads in navRoadHM to navGridHM. 
* ‼ Assertions for navRoad that achieve 100% coverage
* 🧲 Extracted methods for navRoad Model.
* 👷‍♂️ Refactored simplify junction to model methods
* ♻ Option for brute-forcing the simplify loop.
* 🏜 Can open the Street Artist editor empty.
* 🔲 Menu replaces opening the debug console. 
Forced Connections need to be added to when connecting two roads that are not normally connected.
0.  Run Arma 3.
1.  Make an empty mp-mission on any map (community or official) with just one player.
2.  Save and close the editor.
3.  Locate the folder `A3-Antistasi\Tools\StreetArtist\`.
4.  Copy Everything …
=> Tools - 👷‍♂️ Fixed data corruption caused by simplifyJunctions.

Map-Templates/Antistasi-Kunduz.Kunduz/Map/kunduzInfo.sqf, Map-Templates/Antistasi-Malden.Malden/Map/maldenInfo.sqf, Map-Templates/Antistasi-Takistan.takistan/Map/takistanInfo.sqf
1. [x] Bug
2. [x] Change
Information:
undefined variable returned in takistanInfo removed.
1. [x] No
Steps: 
Notes:
=> Removed bad return value in takistanInfo

A3-Antistasi/Garage/CfgDefines.inc, A3-Antistasi/Garage/Core/fn_confirmPlacement.sqf, A3-Antistasi/Garage/Core/fn_onLoad.sqf, A3-Antistasi/Garage/Core/fn_reloadCategory.sqf, A3-Antistasi/Garage/Core/fn_removeFromPool.sqf, A3-Antistasi/Garage/Core/fn_updateVehicleCount.sqf, A3-Antistasi/Garage/Dialogs.hpp, A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf, A3-Antistasi/Garage/Refuel/defines.inc, A3-Antistasi/Garage/Refuel/fn_broadcastStateUpdate.sqf, A3-Antistasi/Garage/Refuel/fn_getTotalFuelCargo.sqf, A3-Antistasi/Garage/Refuel/fn_prefix.sqf, A3-Antistasi/Garage/Refuel/fn_reciveStateUpdate.sqf, A3-Antistasi/Garage/Refuel/fn_refuelVehicleFromSources.sqf, A3-Antistasi/Garage/StatePreservation/fn_getFuel.sqf, A3-Antistasi/Garage/StatePreservation/fn_setFuel.sqf, A3-Antistasi/Garage/config.inc, A3-Antistasi/Garage/fn_addVehicle.sqf, A3-Antistasi/Garage/fn_addVehiclesByClass.sqf, A3-Antistasi/Garage/functions.hpp, A3-Antistasi/Stringtable.xml, Map-Templates/Antistasi-Altis.Altis/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
- Added synergy with fuel scarcity with actual fuel consumption on un-garage (vanilla still practically still has unlimited fuel due to vanilla fuel truck configs).
- Added long time requested QOL changes #2138 #2006 
- Added alphabetical sorting to the vehicle lists
- Fixed a type causing an error in capacity check code
- Added a wrapper around the info panel to aid with extending text OOB
closes #2138 #2006 
1. [x] No
Steps: 
Notes:
=> Projects - Garage improvements

A3A/addons/Garage/Core/fn_addUser.sqf, A3A/addons/Garage/Refuel/fn_broadcastStateUpdate.sqf, A3A/addons/Garage/Refuel/fn_refuelVehicleFromSources.sqf
1. [x] Bug
2. [ ] Change
Information:
Fixed incorrect state index being passed in refuelVehicleFromSources to broadcastStateUpdate
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fixed wrong state index being passed to update state

.github/workflows/workshopUpdate_Dev.yml
builds and updates unstable on commit
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added workflow for unstable publishing

.github/workflows/workshopUpdate_Dev.yml
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fix error in checkout action

A3A/addons/Garage/config.cpp, A3A/addons/JeroenArsenal/config.cpp, A3A/addons/core/Includes/LogMacros.inc, A3A/addons/core/config.cpp, A3A/addons/maps/config.cpp
1. [x] Bug
2. [ ] Change
Information:
hemtt tool dosnt like preprocessor commands from arma version 2.02 and above 😠 
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> removed __A3_Debug__ as it breaks hemtt

A3A/addons/maps/MissionDescription/params.hpp, Tools/Builder/buildAddons.ps1
- fixed: missing semicolon in params.hpp
1. [x] Bug
2. [ ] Change
Information:
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fixed hemtt build script

Tools/incrementVersion.js
1. [ ] Bug
2. [ ] Change
Information:
automation script for version bumping with workflows
closes #XXXX
1. [ ] No
Steps: 
Notes: workflow needs to be added in git manually
workflow:
```yml
name: "Update the version"
on:
push:
branches:
- unstable
jobs:
scripts:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- run: chmod +x ./Tools/incrementVersion.js
- run: ./Tools/incrementVersion.js -b ${{GITHUB_SHA}}
- uses: stefanzweifel/git-auto-commit-action@v4
with:
commit_message: "Automated version bump"
```
=> Version updater

.github/workflows/workshopUpdate_Dev.yml, Tools/incrementVersion.js
1. [ ] Bug
2. [ ] Change
Information:
after local testing on own repository this resulted in a working auto updating build number
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fixed version updater for git, breaks for client

Tools/StreetArtist/functions.hpp, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_import.sqf, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_importV2.sqf, Tools/StreetArtist/functions/StreetArtist/fn_NGSA_main.sqf
* Bug
* Change
* Added support for versioned and organised metadata for StreetArtist navGrid files.
* Less likely to break unexpectedly.
* Provides useful feedback when an issue was encountered.
* Validates schema of emitted data.
* Fully backwards compatible with current navGrid DB format.
* Detects forwards non-compatibility.
* Loads old metadata comments if available. (Assuming they are not stripped out)
* Legal JSON structure that's limited to only arrays and no JSON objects.
* Better metadata support.
* Integrity validation.
* After this merge, another PR will go up to replace Antistasi's navGrid parser with this version.
* Have you loaded the mission on a dedicated server?
1. Load up StreetArtist and import an old navGridDB.
2. Load up …
=> ℹ NavGrid Meta Supports Structued Schema.

.github/workflows/workshopUpdate_Dev.yml
Added github Sha to workflow commit
=> Added github Sha to workflow commit

A3A/addons/core/dialogs.hpp
1. [X] Bug
2. [ ] Change
AI/HC dismiss, garrison and remote control commands got broken recently, looks like a find/replace screwup. This fixes them.
closes #2256
1. [X] No
=> Fix AI/HC dismiss, remote control and garrison commands

A3A/addons/Garage/Stringtable.xml
1. [ ] Bug
2. [x] Change
Information:
Fixed Typos
Added `English` lines for uniformity
Steps: 
Read.
=> Garage System - Small stringtable overhaul

A3A/addons/Garage/CfgFunctions.hpp, A3A/addons/core/functions/init/fn_initPreJIP.sqf
1. [x] Bug
2. [ ] Change
Information:
missionConfigFile is not available at preInit, this blocked cba setting from being added as it would think it was not an a3a mission
closes #XXXX
1. [x] No
Steps: 
Notes:
=> moved garage initServer to postInit

A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [X] Bug
2. [ ] Change
Worked around an issue where RHS had the wrong casing for some magazine and magazineWell lists.
Refactored related code from two pass to single pass while attempting to find the problem.
closes #XXXX
1. [ ] No
Was a relatively major change due to the refactor, so play around with the vehicle arsenal and check if I broke anything new.
=> Refactor vehicle arsenal magazine selection, fix case sensitivity issue

A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf, A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds functionality to shift and Ctrl Keys in the Vehicle Arsenal.
Shift takes 5,
Ctrl takes 10,
Shift ctrl takes 25.
closes nothing
1. [x] No
Steps: 
As it only works in the Vehicle Arsenal you can only use it there.
Take items, put items back nothing should duplicate or increase in amount.
Notes:
=> Vehicle Arsenal - Ability to take more at once

A3A/addons/core/Templates/Templates.hpp
Change selector for Testing
For Cherno Winter
CDF as OCC,
AFRF as INV.
=> Change selector for Testing

A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
1. [ ] Bug
2. [x ] Change
3. [x ] Enhancement
Information:
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fix flag texture on AI resources and factories

A3A/addons/Garage/Core/fn_confirmPlacement.sqf
1. [x] Bug
2. [ ] Change
Information:
Added a block to prevent multiple event handlers being added and therefore not be able to remove them all on cleanup
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Added a block in confimPlacement if already placing

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/AI/fn_staticAutoT.sqf, A3A/addons/core/functions/Artillery/fn_artilleryAdd.sqf, A3A/addons/core/functions/Artillery/fn_artilleryDangerClose.sqf, A3A/addons/core/functions/Artillery/fn_artilleryFireMission.sqf, A3A/addons/core/functions/Artillery/fn_artilleryGetBattery.sqf, A3A/addons/core/functions/Artillery/fn_artilleryGetRounds.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf, A3A/addons/core/functions/CREATE/fn_createSDKgarrisonsTemp.sqf, A3A/addons/core/functions/Civilian/fn_createAmbientCiv.sqf, A3A/addons/core/functions/Patrol/fn_patrolAttack.sqf, A3A/addons/core/functions/Patrol/fn_patrolCanSee.sqf, A3A/addons/core/functions/Patrol/fn_patrolCommander.sqf, A3A/addons/core/functions/Patrol/fn_patrolGroupVariables.sqf, A3A/addons/core/functions/Patrol/fn_patrolInit.sqf, A3A/addons/core/functions/Patrol/fn_patrolLoop.sqf, A3A/addons/core/vcomai/FSMS/fn_SQUADBEH.fsm, A3A/addons/core/vcomai/Functions/VCM_Functions/fn_HearingAids.sqf, A3A/addons/core/vcomai/Functions/VCM_Functions/fn_RStatics.sqf, A3A/addons/core/vcomai/Functions/VCM_Functions/fn_ResetAnimation.sqf, A3A/addons/core/vcomai/Functions/VCM_Functions/fn_VcomInit.sqf, A3A/addons/core/vcomai/Functions/VcomAI_DefaultSettings.sqf, A3A/addons/core/vcomai/cfgFunctions.hpp, A3A/addons/maps/MissionDescription/debug.hpp
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Upsmon removal - Test Branch

A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createAICities.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf, A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf, A3A/addons/core/functions/CREATE/fn_createSDKgarrisons.sqf, A3A/addons/core/functions/CREATE/fn_cycleSpawn.sqf, A3A/addons/core/functions/Patrol/fn_patrolGroupGarrison.sqf
1. [x] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Attempted fix for garrison errors locking parent script

A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initZones.sqf
1. [ ] Bug
2. [x] Change
Information:
Changed color of the fuel marker and made the small fuel containers purchasable for non-commanders.
closes nothing
1. [x] No
Steps: 
Notes:
=> 2262 Part 1 🍕 Fuel changes

README.md
1. [x] Bug
2. [ ] Change
Information:
Fixes the suggested modlists in the readme 404ing
None since I just fixed it instead of making an issue.
1. [x] No
Steps: 
Notes:
=> Fix suggested Modlists

A3A/addons/core/functions/Base/fn_logPerformance.sqf, A3A/addons/core/functions/Base/fn_resourcesFIA.sqf, A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/Save/fn_savePlayer.sqf
1. [ ] Bug
2. [x] Change
Information:
Same treatment as #2321 for consistency, in theory its not needed as its probably very Rare to reach that much Personal Money/HR.
And Killed one Singleplayer Line in the process.
closes nothing
1. [x] No
Steps: 
Give yourself an Insane amount of Money, there should be no E+0006 etc. anymore
```sqf
//HR Money 
[830000,420000000] remoteExec ["A3A_fnc_resourcesFIA",2]; 
[1500000] call A3A_fnc_resourcesPlayer;  
```
Notes:
=> Add ToFixed to the rest of Numbers being Displayed for Consistency

A3A/addons/GUI/CfgFunctions.hpp, A3A/addons/GUI/functions/controlsHelpers/fn_directChildCtrls.sqf, A3A/addons/GUI/functions/controlsHelpers/fn_emplaceControl.sqf, A3A/addons/GUI/functions/controlsHelpers/fn_sortCGList.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added helper functions for GUI work with controls groups
closes #XXXX
1. [x] No
Steps: 
Notes:
=> added gui helper functions

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
1. [x] Bug
2. [ ] Change
Information:
Undid a Typo for Chineese CSAT
closes nothing
1. [x] No
Steps: 
Notes:
=> Correct a Typo in CSAT Voices

A3A/addons/Garage/Core/fn_confirmPlacement.sqf
1. [ ] Bug
2. [X] Change
Change garage placement from 1 degree per key repeat to 120 degrees per second by adding a keyUp handler. Was aiming for "not making me rage each time I have to place a static" but it worked surprisingly well. Smooth.
closes #2391
1. [X] No
=> Rework garage placement rotation

A3A/addons/maps/Antistasi_sara.sara/description.ext, A3A/addons/maps/Stringtable.xml
1. [x] Bug
2. [ ] Change
fixed 2 typos    
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fixed typo for sara mapname_short

A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf, A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf, A3A/addons/core/functions/Missions/fn_DES_Heli.sqf, A3A/addons/core/functions/REINF/fn_addBombRun.sqf, A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf, A3A/addons/core/functions/Supports/fn_requestArtillery.sqf
Punishment bugfixes for attack/support test.
=> Test PR #7 for attack/support rework

A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf, A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf, A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_equipmentSort.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [ ] Bug
2. [ ] Change
Information:
The VN Part of #2404 
Should be pretty similar.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Vn update for Unstable

A3A/addons/JeroenArsenal/JND/fn_debugv2.sqf, A3A/addons/core/functions/init/fn_initParams.sqf, A3A/addons/maps/MissionDescription/params.hpp
1. [ ] Bug
2. [ ] Change
Information:
Now logs debug console executions with the users in game name and UID, this includes logging the target: local, server, global, this allows server owners to track what code has been run on their servers to help track hackers, but also keeps a record of debug code run that may have caused a bug etc.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> added logging of debug code execution with name and UID

A3A/addons/core/functions/Base/fn_buildHQ.sqf, A3A/addons/core/functions/Base/fn_vehicleBoxHeal.sqf, A3A/addons/core/functions/CREATE/fn_civVEHinit.sqf
1. [x] Bug
2. [ ] Change
Information:
missing includes caused errors as it couldn't decipher the macros for the function call, i have double checked the other calls and the same issue is not present anywhere else.
closes #2422 
1. [ ] No
Steps: 
Notes:
=> corrected errors with event triggers

A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
Reverts official-antistasi-community/A3-Antistasi#2426 based on Johns request
=> Revert "Stop god carry"

A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
1. [x] Bug
2. [ ] Change
Information:
_isSpawner could be nil, this errored out the event trigger
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> solved possible null variable issue with triggerEvent call

A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
1. [ ] Bug
2. [ ] Change
Information:
Check if game is started in debug mode, if so then template verification happens. Verification is about 2 seconds, so start up can receive an upper bound of 2 seconds speed up. 
closes #2433
1. [x] No
Steps: 
Notes:
=> Template verification

A3A/addons/core/functions/Base/fn_distance.sqf
1. [ ] Bug
2. [X] Change
1. Excluded additional units in the same vehicle from spawning. Perf difference isn't large in most cases, but it doesn't hurt either.
2. Excluded rebels in fast-moving fixed wing aircraft from spawning. This is to prevent CAS/CAP rebels from repeatedly spawning and despawning locations that they overfly. If they're playing solo and need a location spawned then they can simply move an HC squad within range.
3. Included rebel UAVs in spawn list. This prevents an exploit where you could park UAVs with attached explosives near a flag and then spawn it in.
4. Excluded airborne+moving rebels from spawning civilian vehicles in towns and rebel garrisons. You don't care about those when airborne so they're just a performance cost.
closes #XXXX
1. [X] …
=> Change spawning rules for airborne players and rebel UAVs

A3-Antistasi/Stringtable.xml, A3-Antistasi/Templates/selector.sqf, README.md
1. [x] Bug
2. [ ] Change
Information:
Fixed the Typo,
Updated the Readme from 2.4 to 2.5.5,
Updated the Version number in Stringtables to 2.5.5 too
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fix Filepath Typo

A3A/mod.cpp
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added safeguard to mod.cpp fancies

A3A/addons/Events/Stringtable.xml, A3A/addons/GUI/Stringtable.xml, A3A/addons/Garage/Stringtable.xml, A3A/addons/core/Stringtable.xml, A3A/addons/maps/Stringtable.xml
1. [ ] Bug
2. [ ] Change
4. [x] Preparations
Information:
This PR changes the current stringtables to the 4-space standard so the following changes will be properly visible and not hidden under all the whitespace changes. In addition this cleans up small typos.
Tested and working.
=> whitespace changes and small error corrections

A3A/addons/Garage/Public/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
Information:
replaces the + with a comma. refunding fuel now returns the amount used.
1. [x] No
Steps: 
Notes:
=> Fix refuel refunding

A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
1. [x] Bug
2. [x] Change
Information:
changes to the right casing. Removes optics that were removed in cup. fixes weird rpg 18 mag in m72 law.
1. [x] No
Steps: 
Notes:
=> Cup template nit pick fixes

A3A/addons/core/functions/Base/fn_distanceUnits.sqf, A3A/addons/core/functions/Dialogs/fn_skiptime.sqf
1. [ ] Bug
2. [x] Change
Information:
distance unit now checks for behavior and can fight. Helps skip time easier.
1. [x] No
Steps: 
Notes:
=> Skip time behavior check

.github/workflows/publishBranchToSteamDev.yml
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added dirty cd fix for options

.github/workflows/publishBranchToSteamDev.yml
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added new wf to unstable for use with current mod branches

A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf, A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [ ] Bug
2. [ ] Change
Information:
Make JNA USE COMMANDS AGAIN. Makes the arsenal mag search use the compatibleMagazines command.
1. [x] No
Steps: 
Notes:
=> Compatible magazines in jna

A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf
1. [X] Bug
2. [ ] Change
The template verification patch apparently wasn't updated for recent additions to template verification, so it spams errors when verification is run. Simple fix.
closes #XXXX
1. [X] No
=> Fix missing _fnc prefixes created during merges

A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/AI/fn_fleeToSide.sqf, A3A/addons/core/functions/Base/fn_addHC.sqf, A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_initZones.sqf
1. [X] Bug
2. [ ] Change
- Fixed fillLootCrate bugging out on HCs due to lack of player count broadcast.
- Re-enabled blackListDest. Convoy request still using it.
- Blank out defunct AI limit UI button.
- Remove dead/broken waitUntil in addHC.
- Remove dead respawnOccupants reference.
As far as I know the loot crates one was the only bug with serious effects, although blackListDest may have broken convoy mission requests.
closes #XXXX
1. [X] No
=> Fixes from testing

A3A/addons/core/functions/Base/fn_markerChange.sqf, changelog.rst
1. [ ] Bug
2. [x] Change
Information:
- fixed "looser" typos in every file beside the stringtable
- stringtable got fixed in commit 67c0a7e482e05c0c572726134743e54b0ad325ca and will be merged with other stringtable changes
closes #2484 
1. [x] No
=> fixed "looser" typo

A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
switched "edit terrain object" modules for "hide terrain" modules    
closes #2504 
1. [x] No
Steps: 
- load map and check for incorrect spawns at the 2 proper airfields
Notes:
=> Virolahti - removed "edit terrain object" modules

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf, A3A/addons/core/functions/init/fn_initVarCommon.sqf
1. [ ] Bug
2. [x] Change
4. [x] Update
Information:
Update for [Kat  - Advanced Medical REWRITE](https://steamcommunity.com/sharedfiles/filedetails/?id=2020940806)
- overhauled the detection to not also detect the [deprecated version](https://steamcommunity.com/sharedfiles/filedetails/?id=1626728054) by using an asset that's new
- added new assets
closes #XXXX
1. [x] No
Steps: 
- load it
Notes:
[Classnames](https://github.com/Tomcat-SG/KAM/wiki/Classnames)
[KAT - Advanced Medical REWRITE OFFICIAL GUIDE](https://docs.google.com/document/d/1YlY00qoL2gdrbOJJzi5aW19 …
=> KAT Med update

A3A/addons/core/functions/init/fn_setupMonitor.sqf
1. [X] Bug
2. [ ] Change
Autoload didn't check faction/addonVics/DLC availability, and so could attempt to load a game with missing mods. This PR fixes that by checking all three for validity.
closes #XXXX
1. [X] No
=> Check autoload factions/addonVics/DLC

A3A/addons/core/functions/OrgPlayers/fn_isMember.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [x] Change
Information:
admins were not considered members for some reason so i
made the isMember check add admins as members if they are not already one
closes #2530 
1. [ ] No
Steps: 
Notes:
=> add admins as member on check

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf, A3A/addons/core/functions/CREATE/fn_VEHdespawner.sqf
1. [X] Bug
2. [X] Change
- Fixed bug where captured vehicles could be added to the despawner. Code accounted correctly for capture after vehicles were added to the despawner but not before.
- Fixed broken "disabled" option in idleTimeout. No point making the code more complex given that Arma servers are lucky to stay up for a week.
- Fixed tiny Test text in old dialogs.
- Removed RHS HIMARS launchers for the moment. The only classname has a full load of clusters, which each wreck an area the size of a football field. We'd need pylon configuration to give them a more balanced option.
closes #2533
1. [X] No
=> More minor-ish fixes from testing

A3A/addons/Logistics/Nodes/CUP.hpp
1. [ ] Bug
2. [x] Change
Information:
Bob asked for them, Bob gets them.
1. [x] No
Steps: 
Notes:
=> CUP Range Rover nodes

A3A/addons/GUI/functions/SetupGUI/fn_setupDialog.sqf, A3A/addons/GUI/functions/SetupGUI/fn_setupLoadgameTab.sqf
1. [X] Bug
2. [ ] Change
Minor fixes to game selector UI
- Fix empty row selection bug (see #2550)
- Fixed game selector showing full version including build number (was unintentional).
closes #XXXX
1. [X] No
=> Minor fixes to game selector UI

A3A/addons/core/Params.hpp, A3A/addons/core/functions/Save/fn_loadPlayer.sqf, A3A/addons/core/functions/Save/fn_resetPlayer.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Information:
Along with initial player and faction money, HR could be allowed to be tuned via startup menu too. 
closes #XXXX
1. [x] No
=> Initial HR Parameter

A3A/addons/core/Includes/script_version.hpp, changelog.rst
1. [ ] Bug
2. [x] Change
formatting, typos and order of current changelogs
=> changelog overhaul up to 2.5.3

A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug in several CUP factions where they attempted to use non-existent shotgun lists for equipping police units.
closes #2572
1. [X] No
=> Fix CUP police weapons

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Dialogs/fn_buyVehicle.sqf, A3A/addons/core/functions/Dialogs/fn_buyVehicleCiv.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [x] Change
as stated in title    
1. [ ] No
Steps: 
Notes:
=> Move buy GUI out of dev state

A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
- Fixed a TODO where new campaign IDs weren't checked for collisions.
- Added info logging for campaign IDs used when loading & creating.
closes #2579
1. [X] No
=> Campaign ID check and logging

A3A/addons/core/Includes/script_version.hpp, A3A/addons/core/Params.hpp, changelog.rst
- Changed version and added preliminary changelog for 3.0.0 release
- added 2.5.4 changelog which was prior only merged onto master
- added 2.5.5 changelog which was prior only merged onto master   
- Check and complete the additional information of the Major changes
- Check for completion
- Check for typos
- Check for unnecessary information
=> version update and preliminary changelog for 3.0.0

A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
1. [x] Bug
2. [ ] Change
Information:
Fixes count attached objects each frame. 
N/A
1. [x] No
Steps: 
Notes:
=> lazy evaluation for LTC

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [x] Change
Information:
adds new KAT item because https://steamcommunity.com/sharedfiles/filedetails/changelog/2020940806
=> KAT medical update

A3A/addons/core/Includes/cba_settings.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
Push the commits of #2591 and #2592 to Unstable as it was accidentally PRd into Master
=> #2592 and #2591 to Unstable

A3A/addons/core/Includes/cba_settings.sqf
1. [ ] Bug
2. [x] Change
Information:
force disabled  acex_headless
closes #2607
1. [ ] No
Steps: 
Notes:
=> force disable acex_headless

A3A/addons/maps/Stringtable.xml
1. [ ] Bug
2. [ ] Change
Information:
typo fix
=> typo fix leafes-leaves

A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
1. [X] Bug
2. [ ] Change
Fixed some artillery classnames that I broke in the patch where I disabled the HIMARS. Kinda bad because it's mismatched with the magazine table so they throw RPT errors and don't fire.
closes #XXXX
1. [X] No
=> Fix RHS USAF non-arid artillery copypaste bugs

A3A/addons/core/functions/init/fn_initClient.sqf
1. [x] Bug
2. [ ] Change
Information:
Since Bob Removed the check for the preview gui instead of setting it to be true. Lights and fuel containerss are still on the vehicle box.
1. [ ] No
Steps: 
Notes:
=> remove old addactions

Tools/Builder/buildAddons.ps1
1. [x] Bug
2. [ ] Change
Information:
fix casing for host bisingn replacement
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> lowercase key name

Tools/Builder/buildAddons.ps1
1. [x] Bug
2. [ ] Change
Information:
striped version number from key name, added 3 unique keys for official builds, main, dev 1, dev 2, added 4th for unnoficial use `a3a`
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> update key names

A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
1. [x] Bug
2. [ ] Change
Information:
block adding entries to the buy vehicle gui if the entries does not exist in cfgVehicles
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> skip vehicles that are not in cfgVehicles BuyVehicle GUI

changelog.rst
Information:
Preliminary changelog
=> 3.1.0 preliminary changelog

A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf, changelog.rst
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Unstable into Master for 3.1.0 release

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf, A3A/addons/core/functions/init/fn_setupMonitor.sqf, A3A/addons/core/functions/init/fn_startGame.sqf, changelog.rst
* Make the setup process feedback hints clearer and more persistent
* Update changelog for setup feedback improvement
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Improved setup process feedback hints (#2640)

A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf
1. [x] Bug
2. [ ] Change
Information:
This PR fixes finite items duping exploit. 
-
1. [x] No
Steps: 
-
=> Vehicle Arsenal dupe fix

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Base/fn_garbageCleanerTracker.sqf, A3A/addons/core/functions/init/fn_initServer.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Information:
Implements a system by tracking last gc time, to run a gc if the threshold is passed.
1. [x] No
Steps: 
Notes:
=> Automatic GC

A3A/addons/logistics/CfgLogistics.hpp
1. [x] Bug
2. [ ] Change
Information:
Cargo and node configurations for Western Sahara existed, but where not loaded in CfgLogistics.hpp.
None
1. [x] No
Steps:
- Start a game with WS CDLC enabled
- Spawn Zamak flatbed or Zamak cargo variant
- Buy/Spawn ZU-23
- Check that ZU-23 can be loaded onto Zamak variants
Notes:
=> Include WS config in logistics config

A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_Reb_NAPA.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_Reb_TKM.sqf, A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf, A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf, A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [x] Change
Information:
adds chemlights the starting equipment arrays. Adds ace specific chemlights too.
N/A
1. [x] No
Steps: 
Notes:
=> Add Chemlights to the starting equipment

A3A/addons/core/functions/Dialogs/fn_mineDialog.sqf
1. [x] Bug
2. [ ] Change
Information:
checks that the count is not equal to -1 before exit
closes #2540
1. [ ] No
Steps: 
Notes:
=> Fix edge case in minefields mine count

A3A/addons/core/Stringtable.xml
1. [ ] Bug
2. [ ] Change
Added translations from #2652 and German ones
1. [x] No
Steps: 
Notes:
=> 2652 - Czech and German translations

A3A/addons/Logistics/Packable/Vanilla.hpp
removing dublicate
1. [x] Bug
2. [ ] Change
removed dublicate which accidentally got introduced
=> Delete A3A/addons/Logistics/Packable directory

A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf, A3A/addons/logistics/Private/fn_unpackObject.sqf
1. [x] Bug
2. [ ] Change
Information:
I flip the logic for a few of these. This fixes that.
1. [ ] No
Steps: 
Notes:
=> Temp fix for buyItems 

A3A/addons/core/functions/EventHandler/fn_vehicleDeletedEH.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Missed some stuff in the spawn places rework:
- Broken code in SUP_mortar. Improved it.
- Deleted EH wasn't installed for mortars because they're free. Gave them a small price as a workaround.
- Deleted EH freeSpawnPositions syntax was incorrect.
closes #XXXX
1. [X] No
=> Fix support mortar spawn places

A3A/addons/patcom/functions/Civilian/fn_createAmbientCiv.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Another One!

A3A/addons/core/functions/UtilityItems/fn_initMovableObject.sqf
1. [x] Bug
2. [ ] Change
Information:
rotating objects addaction was broken. This fixes it. Adds a check to see if the object is not being carried.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Rotate Item Fix

A3A/addons/patcom/functions/Civilian/fn_createAmbientCiv.sqf, A3A/addons/patcom/functions/Civilian/fn_createResourceCiv.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Additional Error Handling

A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
1. [X] Bug
2. [ ] Change
Fixed stupid bug in previous bugfix caused by sleep deprivation.
closes #XXXX
1. [X] No
=> Fix support mortars not entering active info correctly

A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [x] Bug
2. [ ] Change
Information:
forgot to add civilian planes to undercover vehicles. Now they are.
1. [x] No
Steps: 
Notes:
=> Fix undercover for civ planes

A3A/addons/logistics/CfgFunctions.hpp, A3A/addons/logistics/Private/fn_packObject.sqf, A3A/addons/logistics/Private/fn_unpackObjectAction.sqf
1. [x] Bug
2. [ ] Change
Information:
Fixes the case of unpack object not showing up for player. Makes the addAction a function, and remote execs it.
1. [x] No
Steps: 
Notes:
=> Remote exec packing

A3A/addons/core/functions/AI/fn_airbomb.sqf
1. [X] Bug
2. [ ] Change
Under some circumstances (plane crashing while dropping?), it's possible for a napalm bomb dropped by airbomb to detonate before spawn loop records a position for it. This PR fixes that problem by passing in the initial position.
Also cleaned up a very bad parameter name, some bad getPos and possibly allowed enemy bombs to kill petros (not the napalm though). The setShotParents line seems to work anyway.
Petros being immune to napalm should probably be fixed but I'm not sure about the best method yet.
closes #2718
1. [X] No
=> Fix case where napalm bomb lands before spawn runs

A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Arid.sqf, A3A/addons/core/Templates/Templates/BWA3/BWA3_AI_BW_Temperate.sqf
1. [x] Bug
2. [x] Change
Information:
Assumed the Fliegerfaust to work like CUP/CBA disposables but they work like normal AA Launchers in Arma, they are reloadable and need the Magazine.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Add lost Fliegerfaust magazine

A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Remove dead statics

A3A/addons/core/functions/init/fn_initSpawnPlaces.sqf
1. [x] Bug
2. [ ] Change
Changes one line from Error to Info which triggered me for being for way too long.
=> change vehiclemarker error to info

A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm, A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm, A3A/addons/maps/Antistasi_Takistan.takistan/mission.sqm, A3A/addons/maps/Antistasi_Tanoa.Tanoa/mission.sqm, A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mission.sqm
1. [x] Bugfix
2. [ ] Change
Fixed reasons for the errors and adjusted some minor things like naming or separating one large vehicle marker into 2 smaller ones.
closes #2743 
1. [x] No
=> map error fixes

A3A/addons/patcom/functions/Artillery/fn_artilleryFireMission.sqf, A3A/addons/patcom/functions/Civilian/fn_civilianFiredNearEH.sqf, A3A/addons/patcom/functions/Civilian/fn_createAmbientCivTraffic.sqf, A3A/addons/patcom/functions/Civilian/fn_createRoomLight.sqf, A3A/addons/patcom/functions/Patcom/fn_getSafePos.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolAttack.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolSearchBuilding.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolWater.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Convert getPos -> getPosATL

A3A/addons/patcom/functions/Patcom/fn_getSafePos.sqf
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Added back power lines for poles.

A3A/addons/maps/Antistasi_Malden.Malden/mission.sqm
Malden had VR debug marker at the airfield. This PR removes them.
=> Remove debug marker

A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf, A3A/addons/core/Templates/Templates/GM/GM_AI_BW_arctic.sqf, A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf, A3A/addons/core/Templates/Templates/GM/GM_AI_NVA_arctic.sqf, A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf, A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf, A3A/addons/logistics/Nodes/GM.hpp
1. [ ] Bug
2. [ ] Change
Information:
Updated templates with new GM stuff from GM release 1.5
- weapons
- vehicles
closes Bob's request to implement the new assets
1. [ ] No
Steps: 
Throw on server and play
Notes:
=> updated GM templates with new assets

changelog.rst
=> 3.2 preliminary changelog

A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf, A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
1. [X] Bug
2. [ ] Change
Turns out that the dive bomber routine only worked for aircraft with "airplane" simulation, not "airplanex". Apparently setting the velocity for airplanex just makes them hang in mid-air. Thanks Arma. Fixed it without breaking the other simulation, I think.
Also fixed an issue where CAS aircraft with only one of rockets or missiles wouldn't use them.
closes #XXXX
1. [X] No
=> Dive bombing & CAS fixes

A3A/addons/logistics/CfgFunctions.hpp
1. [X] Bug
2. [ ] Change
Forgot to clean up the logistics CfgFunctions in #2773. Apparently servers don't like this.
closes #XXXX
1. [X] No
=> Remove deleted files from logistics CfgFunctions

A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [x] Change
Information:
Using Johns work on jamming, Acre Jamming is added. All we needed to do is have a custom signal power calculated and set. This pr does that.
closes #1645
1. [ ] No
Steps: 
Notes:
=> ACRE Jamming

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Reverts official-antistasi-community/A3-Antistasi#2769
=> Revert "Fix trailing comma and missing AA plane in ION Temperate"

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
Retarget of #2769 for unstable.
=> Fix trailing comma and missing AA plane in ION Temperate

A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf, A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_Vehicle_Attributes.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds most of the sog 1.3 update to the templates. Australian stuff was not added nor touched. 
N/A
1. [x] No
Steps: 
Notes:
=> Rudimentary Sog 1.3 Update

A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
1. [x] Bug
2. [x] Change
Information:
Replaced ChDZK tanks with russian flags to side step the issue of too persistent flags.
Updates the crew loadout to set them apart from russian tank crews.
closes #XXXX
1. [ ] No
Steps: 
Notes:
I'd prefer to solve the issue with the tanks with something like a config patch of the tanks, but I do not have the confidence/knowledge to throw that together quickly in an acceptable form.
=> Chdzk tank-flag  quick-fix, crew update

A3A/addons/core/Includes/script_version.hpp, changelog.rst
Changelog and version update for 3.3.1 hotfix release
=> changelog and version update

A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/mission.sqm
1. [ ] Bug
2. [x] Change
Turned a few hundred objects into simple objects and to improve map performance
1. [x] No
=> Simplifying map placed objects - Normandy

A3A/addons/core/Includes/script_version.hpp, changelog.rst
Updates changelog and version number for 3.3.2
=> changelog and version update for 3.3.2

A3A/addons/core/Includes/script_version.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/REINF/fn_addFIAveh.sqf, A3A/addons/core/functions/Save/fn_loadStat.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/init/fn_initVarCommon.sqf, changelog.rst
Reverts official-antistasi-community/A3-Antistasi#2882
=> Revert "3.3.3 version and changelog change"

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
=> Fix trailing comma and missing AA plane in ION Temperate (master repair attempt)

changelog.rst
Changelog update for version 3.3.3
=> 3.3.3 changelog update

A3A/addons/core/functions/Save/fn_saveLoop.sqf
1. [X] Bug
2. [ ] Change
What ended up in the static fixes commit wasn't what I tested. Which is worrying. Oh well. Re-tested, should be correct now.
closes #XXXX
1. [X] No
=> Fix static saving mis-commit

A3A/addons/core/functions/Save/fn_saveLoop.sqf, changelog.rst
Fixes a static saving mis-commit
=> another 3.3.3 push

A3A/addons/core/functions/SalvageRope/fn_salvageRope.sqf, A3A/addons/logistics/Dev/fn_generateCargoOffset.sqf, A3A/addons/logistics/Private/fn_addAction.sqf, A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf, A3A/addons/logistics/Private/fn_addWeaponAction.sqf, A3A/addons/logistics/Private/fn_load.sqf, A3A/addons/logistics/Private/fn_tryLoad.sqf, A3A/addons/logistics/Private/fn_unload.sqf, A3A/addons/logistics/Stringtable.xml
1. [ ] Bug
2. [ ] Change
localized logistics
1. [ ] No
- needs adaptation to implement the ones in `fn_addOrRemoveObjectMass` as commented in the file
- needs proper testing
Dev Team: Feel free to commit changes directly to this branch rather than asking me.
=> logistics_localization

A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_handleAction.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf, A3A/addons/jeroen_arsenal/JNA/fn_vehicleArsenal.sqf, A3A/addons/jeroen_arsenal/JND/fn_debugv2.sqf, A3A/addons/jeroen_arsenal/Stringtable.xml
1. [ ] Bug
2. [ ] Change
localized jeroen_arsenal    
1. [x] No
- Have not checked functionality at all. I have no fucking clue where there have to be brackets and where not. Somebody please take over.
Dev Team: Feel free to commit changes directly to this branch rather than asking me to change anything.
=> jeroen_arsenal_localization

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/init/fn_initACE.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [x] Change
Information:
Moves the ACE initialization code to it's own function. Adds some more logging of specific actions that players can do with medical items.
N/A
1. [x] No
=> Moving Ace Init

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
1. [ ] Bug
2. [x] Change
Information:
*I redone this PR because I messed up last time and guys from discord told me how to do PR properly
Adding attack UAV's to CSAT and NATO from APEX and JETS dlc's 
closes 
1. [x] No
Steps: 
Notes:
*Since attack UAV's are not currently used ,these changes are for the future IF UAV support will be added back
**There is no need for testing since no function currently call's for attack UAV
=> Apex and jets uavs

A3A/addons/core/functions/AI/fn_fastrope.sqf, A3A/addons/core/functions/AI/fn_landThreatEval.sqf, A3A/addons/core/functions/AI/fn_rearmCall.sqf, A3A/addons/core/functions/Base/fn_placementselection.sqf, A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf, A3A/addons/core/functions/CREATE/fn_milBuildings.sqf, A3A/addons/core/functions/Garrison/fn_updateGarrison.sqf, A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf, A3A/addons/core/functions/REINF/fn_buildMinefield.sqf, A3A/addons/core/functions/init/fn_initUtilityItems.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf, A3A/addons/events/functions/fn_validateEventArguments.sqf
1. [x] Bug
2. [ ] Change
Information: multiple issues regarding the incorrect precedence of operations, resulting in different behavior than what is intended.
These issues were identified by [sqf-analyzer](https://marketplace.visualstudio.com/items?itemName=SQF-analyzer.sqf-analyzer).
Not yet, I can but would like to ensure this PR is acceptable before running manual tests.
1. [ ] No
This may have changed behavior in ways that were not intended, since the code was tested with the previously (likely incorrect) behavior.
=> Multiple bug fixes

A3A/addons/config_fixes/Stringtable.xml, A3A/addons/core/Stringtable.xml, A3A/addons/events/Stringtable.xml, A3A/addons/garage/Stringtable.xml, A3A/addons/gear/Stringtable.xml, A3A/addons/gui/Stringtable.xml, A3A/addons/jeroen_arsenal/Stringtable.xml, A3A/addons/logistics/Stringtable.xml, A3A/addons/maps/Stringtable.xml
1. [ ] Bug
2. [ ] Change
Changes currently useless package names which are part of the stringtables to be used as identifiers for Tolgee Automation
=> package name change

A3A/addons/core/Templates/Templates.hpp
1. [x] Bug
2. [ ] Change
Fixes two template display names
=> " rebells"-fix

A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
1. [ ] Bug
2. [x] Change
Adds jungle version to spawn AAs
=> Land_Cargo_HQ_V4_F addition

A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf, A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf, A3A/addons/core/functions/Base/fn_sellVehicle.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf, A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Added a light tanks category for vehicles with similar firepower to an IFV but no passenger space. Most templates won't need it but SPE-IFA does for the M18 Hellcat, and some others would benefit (most of the VN tanks are probably overvalued, for example).
closes #XXXX
1. [ ] No
I didn't actually use the new category yet. Some stuff won't really be tested until then.
=> Add vehiclesLightTanks template category

A3A/addons/logistics/Nodes/WS.hpp
1. [ ] Bug
2. [x] Change
Information:
Adds logistics nodes to the offroad (desert) and offroad (UP)
closes #XXXX
1. [x] No
Steps: 
Notes:
Required as PR #2931 makes these vehicles accessible to the rebels
=> Adds logistics nodes for WS offroads

A3A/addons/core/Stringtable.xml, A3A/addons/logistics/Stringtable.xml
1. [ ] Bug
2. [x] Change
just some typo and punctuation fixes
=> Stringtable fixes

A3A/addons/config_fixes/CUP/config.cpp, A3A/addons/config_fixes/CfgMagazines.hpp, A3A/addons/config_fixes/CfgVehicles.hpp, A3A/addons/config_fixes/CfgWeapons.hpp, A3A/addons/config_fixes/RHS/CfgVehicles.hpp, A3A/addons/config_fixes/RHS/chdkz_rhs.hpp, A3A/addons/config_fixes/RHS/config.cpp, A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp, A3A/addons/config_fixes/Vanilla/air.hpp, A3A/addons/config_fixes/Vanilla/armor.hpp, A3A/addons/config_fixes/Vanilla/config.cpp, A3A/addons/config_fixes/Vanilla/sea.hpp, A3A/addons/config_fixes/Vanilla/soft.hpp, A3A/addons/config_fixes/WS/CfgMarkers.hpp, A3A/addons/config_fixes/WS/CfgVehicles.hpp, A3A/addons/config_fixes/WS/config.cpp, A3A/addons/config_fixes/WS/ws_ion.hpp, A3A/addons/config_fixes/bomb_weapons.hpp, A3A/addons/config_fixes/config.cpp, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
1. [ ] Bug
2. [x] Change
Shit wasn't ordered - now it is
=> config_fixes-cleanup

A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf
1. [x] Bug
2. [x] Change
Information:
Replaces a Mk200 entry with an correct XMS SW entry.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fixed loadout validation in WS_AI_ION.sqf

A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf, A3A/addons/core/functions/Builder/fn_initBuilderMonitors.sqf, A3A/addons/core/functions/Builder/fn_placeBuilderObjects.sqf
1. [x] Bug
2. [x] Change
Information:
Fixes the text not being red on certain key selections. Fixes weird edge case where in unsafe placement objects will be inside builds that players can not enter. Adds a bobble effect to icons, they no longer are just static icons. Decreases the distance to show Icons from 300 to 150 meters. The farther away you are to the icon the lower the alpha channel is set for icons.
1. [x] No
Steps: 
Notes:
=> playtesting fixes

A3A/addons/core/functions/Builder/fn_placeBuilderObjects.sqf
1. [X] Bug
2. [ ] Change
Fixed a missing semicolon added in the review process for #2988
closes #XXXX
1. [X] No
=> Fix missing semicolon in placeBuilderObjects

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Base/fn_garbageCleaner.sqf, A3A/addons/core/functions/Base/fn_startBreachVehicle.sqf, A3A/addons/core/functions/Builder/fn_addBuildingActions.sqf, A3A/addons/core/functions/Builder/fn_buildingPlacerStart.sqf, A3A/addons/core/functions/Builder/fn_initBuilderMonitors.sqf, A3A/addons/core/functions/Intel/fn_placeIntel.sqf, A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf, A3A/addons/core/functions/Utility/fn_isEngineer.sqf, A3A/addons/garage/Extras/fn_isRepairSource.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
1. [ ] Bug
2. [x] Change
PR to collect changes based on the ACE 3.16.0 update
This won't be immediately merged so we can collect whatever comes up.
=> ACE 3.16.0 stuff

A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initZeusLogging.sqf
1. [X] Bug
2. [X] Change
- Prevent zeus logging being multiplied by client count. There was a bogus remoteExec 0 in initClient.
- Stop logging selection-only events.
closes #2992
1. [X] No
=> Zeus logging spam fixes

A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf
1. [ ] Bug
2. [ ] Change
Arma was really bad at snapping building placer objects to the terrain surface in some cases. This PR appears to fix it. Was much simpler than expected, so I have no idea how Arma is fucking it up that much.
closes #XXXX
1. [X] No
The slopes at the Takistan default start are a good test.
=> Manually force building placement to nearby composite surface normal

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/maps/MissionDescription/params.hpp, A3A/addons/maps/Stringtable.xml
1. [ ] Bug
2. [ ] Change
Localizes the parameters in available through the unit selection screen as well as the ones in the StartupGUI.
In total adds 142 new stringtable entries.
=> Localized parameters

A3A/addons/config_fixes/Vanilla/CfgWeapons.hpp, A3A/addons/config_fixes/Vanilla/config.cpp
1. [x] Bug
2. [ ] Change
Information:
Changes baseWeapon of arifle_AK12_GL_lush_F to correctly point it at an existing class
closes #XXXX
1. [x] No
Steps: 
Notes:
=> arifle_AK12_GL_lush_F

A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf, A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
1. [ ] Bug
2. [x] Change
Information:
Changes to vehicle lineups to differentiate between regular and militia vehicles.
Adjusted ADF and CSAT NA templates to use ever so slightly more vanilla weapons.
Removed a uniform from Tura rebels.
1. [x] No
Steps: 
Notes:
=> Western sahara template update

A3A/addons/core/functions/Ammunition/fn_ammunitionTransfer.sqf, A3A/addons/core/functions/Base/fn_AILoadInfo.sqf, A3A/addons/core/functions/Base/fn_NATOFT.sqf, A3A/addons/core/functions/Base/fn_garrisonInfo.sqf, A3A/addons/core/functions/Base/fn_localizar.sqf, A3A/addons/core/functions/Base/fn_markerChange.sqf, A3A/addons/core/functions/Base/fn_resourcesFIA.sqf, A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/CREATE/fn_attackHQ.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf, A3A/addons/core/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf, A3A/addons/core/functions/Dialogs/fn_squadOptions.sqf, A3A/addons/core/functions/Dialogs/fn_squadRecruit.sqf, A3A/addons/core/functions/Dialogs/fn_unit_recruit.sqf, A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf, A3A/addons/core/functions/OrgPlayers/fn_theBossTransfer.sqf, A3A/addons/core/functions/Punishment/fn_punishment.sqf, A3A/addons/core/functions/REINF/fn_buildMinefield.sqf, A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf, A3A/addons/core/functions/Supports/fn_showInterceptedSetupCall.sqf, A3A/addons/core/functions/Supports/fn_showInterceptedSupportCall.sqf, A3A/addons/core/functions/init/fn_credits.sqf, A3A/addons/garage/Public/config.inc, A3A/addons/gui/functions/GUI/fn_aiManagementTab.sqf, A3A/addons/gui/functions/GUI/fn_hqDialog.sqf, A3A/addons/gui/functions/SetupGUI/fn_setupLoadgameTab.sqf
Adds `TODO` comments for future stuff, mostly localization.
=> todo comments

A3A/addons/core/functions/Supports/fn_createSupport.sqf
1. [ ] Bug
2. [X] Change
Info-level logging wasn't showing anything about supports created, and that's definitely info-level. Rejigged it to do so, and provide more useful data.
closes #XXXX
1. [X] No
=> Improve createSupport logging

A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf
1. [X] Bug
2. [ ] Change
Fixed the build placer UI code that prevents mouse wheel scrolling over the selection dialog from zooming the camera.
closes #3029
1. [X] No
=> Fix mouse scrolling in building placer

changelog.rst
Contains 3.4 changelog for update release
=> 3.4 changelog

A3A/addons/config_fixes/WS/CfgMarkers.hpp, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
1. [ ] Bug
2. [x] Change
Information:
Typo in faction name in a couple places
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> SIFA -> SFIA typo fix

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
1. [x] Bug
2. [ ] Change
Information:
CSAT enoch was missing conditional check for marksmen DLC weapons
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Csat enoch marksmens dlc for 3.4.1

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
1. [x] Bug
2. [x] Change
Information:
Changes or substitutes attachments for weapons that did not pass loadout validation.
exchanged a couple SMG optics for SMG appropriate equivalent.s
closes #XXXX
1. [x] No
Steps: 
Notes:
Non critical/minimal impact issue.
=> Vanilla templates adjusted to pass loadout validation.

A3A/addons/core/functions/Base/fn_startBreachVehicle.sqf
1. [X] Bug
2. [ ] Change
Information:
1. Fixed a minor bug where you would attempt to breach a vehicle while undercover and nothing would happen. You now get kicked off undercover if you attempt to breach and all other checks pass.
2. Fixed another exploit (?) where you could breach vehicles for free if the charges were removed mid-animation, E.G. a friend pulls the breaching charges out of your backpack after the animation starts, and at the end the script attempts to pull a non-existent charge out of your bag and fails, and no charges are consumed. You now will get the "no explosives" hint if the charges are absent when it tries to remove them, assuming my baby's first SQF venture actually works.
closes #XXXX
3. [ ] Have …
=> Minor fixes for breaching vehicles

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [x] Change
Information:
This PR is to fix issue submitted to KAT Advanced Medical (KAM). https://github.com/KAT-Advanced-Medical/KAM/issues/423
And this PR will apply item compatibility updates to Antistasi that correspond to the latest version of KAM (2.13.3).
This issue has been reported to KAM, see https://github.com/KAT-Advanced-Medical/KAM/issues/423
1. [x] No
Steps: 
N/A
Notes:
N/A
=> Add and Update KAM Support for KAM 2.13.3

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [ ] Change
Information:
This change adds Banana, Sunflower Seeds, Humanitarian Ration for compatibility list.
I don't know why they are missing, but they are also available as ACE food item, I will add them.
N/A
1. [x] No
Steps: 
N/A
Notes:
N/A
=> Update ACE Food Item (Add bananas)

A3A/addons/core/functions/CREATE/fn_AAFroadPatrol.sqf
1. [x] Bug
2. [ ] Change
Information:
AND was used instead of an OR in #3031
1. [x] No
Steps: 
Notes:
=> Bugfix: broke patrol max distance check in #3031

A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm, A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mapInfo.hpp, A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm, A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mapInfo.hpp, A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm
Fixes from map testing.
Colombia:
- new initial HQ location
Weferlingen:
- removed trees from roads
- fixed climate of winter map
- added definition for buildable objects
=> Weferlingen & Colombia fixes

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Desert.sqf
1. [ ] Bug
2. [X] Change
Information:
Adds template for CUP AFRF, utilizing the Russian Pink Desert camo uniforms, vests and helmets.
1. [X] No
Steps: Load the mod and use the CUP AFRF Desert template
Notes: Picture from Warlevel 1 resource site, militia utilizes some of the older helmets.
=> Add CUP AFRF Desert Template

A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
1. [ ] Bug
2. [x] Change
Information:
Removes the debug dependent scope of the fixed chdkz T-72 tanks
1. [x] No
Steps: 
Notes:
=> Removed debug scope from a3a rhs t-72

A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp, A3A/addons/config_fixes/Vanilla/armor.hpp, A3A/addons/config_fixes/Vanilla/ifv.hpp
1. [ ] Bug
2. [x] Change
Information:
re-alphabetized the includes list
Moved the blufor Gorgon to its pal in the ifv.hpp file, allowing the alphabetizing of the include list
1. [x] No
Steps: 
Notes:
=> Cleaned up vanilla/ifv.hpp & armour.hpp

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Debug/fn_debugSpawnVics.sqf, A3A/addons/core/functions/Debug/fn_spawnSelectedTemplateAI.sqf
1. [ ] Bug
2. [ ] Change
Information:
#3130 
1. [x] Have you loaded the mission in LAN host? (in the last version i added it)
1. [ ] No
Steps: 
details can be found in #3130 
Notes:
Please never squash commits if there is a branch based on them
1. [ ] Bug
2. [ ] Change
Information:
Adds ability so spawn units of current selected template as well as fitting vehicles
1. [x] No
Steps: 
1. Load into Antistasi
2. Start game with selected …
=> readded debug functions second time

changelog.rst
Adds preliminary changelog for 3.5.0 update
version number in code as well as readme is already adjusted
=> preliminary 3.5.0 changelog

A3A/addons/core/functions/Revive/fn_actionRevive.sqf
1. [X] Bug
2. [ ] Change
Fixed missing localize command in actionRevive.    
closes #XXXX
1. [X] No
=> Fix missing localize in actionRevive

A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
1. [x] Bug
2. [ ] Change
Fixed the issues    
closes #3119
=> 3119 - kujari map fixes

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
Updates version and changelog for 3.5.1 release
=> 3.5.1 version and changelog

A3A/addons/config_fixes/RF/CfgVehicles.hpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf, A3A/addons/core/Templates/Templates/WS/WS_Reb_Vehicle_Attributes.sqf, A3A/addons/logistics/Nodes/RF.hpp
1. [ ] Bug
2. [ ] Change
Information:
Pushing changes to the correct branch now, will be closed shortly.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> RF Compat - Commit because I can't use GitHub properly

A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
1. [x] Bug
2. [ ] Change
Information:
Minor fixes and adjustments
Fixes ION pilot loadout setting the crew loadout SMG
Add a few vanilla armoured vests to the NATO template - it was the only one without vanilla armour
Moved SFIA's dlc guns to the appropiate location
Notes:
Does not include the fix to ADF as it is fixed in #3162 and i don't know if fixing it twice would cause issues
=> WS minuscule patch

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds arid and green templates built from APEX that feature what the armaverse british forces would look like in 2035
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Vanilla UK/NATO faction

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds the closest approximate to an ION services PMC faction using the vanilla and DLC assets available.
They feature a mis-mash of independently sourced equipment both when it comes to personal equipment and vehicles.
1. [x] No
Steps: 
Notes:
=> Vanilla ION pmc faction

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
=> 3.5.2 changelog and version

A3A/addons/logistics/Private/fn_addOrRemoveObjectMass.sqf
1. [x] Bug
2. [x] Change
Information:
Changing the mass calculation for attached objects on logistic vehicles. This prevents mass from being too heavy and clipping the wheel into the ground.
N/A
1. [x] No
Steps: 
Notes:
=> Added: New mass calculations based on wheel springs

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_KRG.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf
1. [x] Bug
2. [ ] Change
Information:
Replaces incompatible magazines with compatible ones
closes #3218
1. [x] No
Steps: 
Notes:
=> 3CB Factions Wrong Magazines Fix

changelog.rst
=> 3.5.3 changelog

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
changelog and version udpate for 3.5.4
=> changelog + version for 3.5.4

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_KRG.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf, changelog.rst
merge into master for 3.5.4
see changelog
=> merge to master for 3.5.4

A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf, A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf, A3A/addons/core/functions/Base/fn_sellVehicle.sqf, A3A/addons/core/functions/Base/fn_startBreachVehicle.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf, A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf, A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf, A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [x] Change
Information:
adds a vehicle category for heavy tanks
I need this for the IFA AIO templates im working on, surely useful for other things too.
1. [ ] No
Steps: 
Notes:
RFC on cost and threat i set in initVarServer
Need feedback on the weights set in getVehicleGroundSupport
=> Adds vehiclesHeavyTanks template category 

A3A/addons/core/Templates/Templates/RHS/RHS_Reb_NAPA.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_Reb_Vehicle_Attributes.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds the Poseidon II as a purchasable boat
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Adds Poseidon II to RHS NAPA

A3A/addons/core/functions/Base/fn_citySupportChange.sqf, A3A/addons/core/functions/Base/fn_resourcesFIA.sqf, A3A/addons/core/functions/OrgPlayers/fn_resourcesPlayer.sqf
1. [ ] Bug
2. [X] Change
Information:
This PR adds error messages for when a parameter in an easily breakable function is found to be outside bounds.
I'm not available to test it right now, but it's 18 lines regardless.
closes #3224 
1. [ ] No
Steps: 
Notes:
=> Parameter fencing for debug commands

A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp
1. [x] Bug
2. [ ] Change
Information:
A piece of code for testing the plane loadout changes was unintentionally left behind, this PR removes it.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Removed testing code

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_VDV_Temperate.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds the VDV as a faction to RHS, ~~only a temperate template exists for now~~
arid and temperate templates
closes #XXXX
1. [x] No
Steps: 
*******************************************
*************
Notes:
Made by skilless802 on the discord, PR made for him
=> RHS VDV Templates

A3A/addons/config_fixes/3CB/CfgWeapons.hpp, A3A/addons/config_fixes/3CB/config.cpp
1. [x] Bug
2. [ ] Change
Information:
resolved baseWeapon error of
UK3CB_MG3_KWS_T
UK3CB_M21_Bipod_Railed
uk3cb_auga2_sr_carb_tan
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> 3CB Factions baseWeapon config fix

A3A/addons/core/functions/Missions/fn_DES_Vehicle.sqf
1. [X] Bug
2. [ ] Change
Fixed a typo that was apparently added to the destroy vehicle mission when it was being stringtabled.
closes #XXXX
1. [X] No
=> Fix mistype in DES_Vehicle

A3A/addons/maps/Antistasi_Enoch.Enoch/mission.sqm
1. [ ] Bug
2. [ ] Change
Information:
Adds a handful of SF spawn spots around Livonia, on spots that are semi obviously "SF spots" so to speak - ie the middle of the map is still lacking but there's not an awful lot of places to put them down.
Moved the default HQ south west into an area that is hopefully more beneficial to start out in. ie not under mortar cover of an nearby airbase.
closes #3181
1. [x] No
Steps: 
Notes:
=> Livonia SF update

A3A/addons/config_fixes/CUP/sfp_air.hpp
1. [x] Bug
2. [ ] Change
Information:
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Update sfp_air.hpp with eventHandler inheritance 

A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_Vehicle_Attributes.sqf
1. [ ] Bug
2. [x] Change
Information:
Change, refactor.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Standardized IFA attribute location

A3A/addons/maps/Antistasi_pulau.pulau/mission.sqm
1. [x] Bug
2. [ ] Change
Information:
Because this has to be done for every map port and i forgot this time
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Update Pulau mission.sqm, make blufor & indfor hostile

A3A/addons/core/functions/OrgPlayers/fn_sendMoney.sqf, A3A/addons/gui/functions/GUI/fn_donateTab.sqf
1. [X] Bug
2. [ ] Change
- Fixed misplaced default statement in switch causing syntax errors.
- Removed headless clients from new-UI player donation list.
- Cleared up a `typename` because it was annoying me.
closes #XXXX
1. [X] No
=> Donate money fixes

A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_REB_FFI.sqf
1. [ ] Bug
2. [x] Change
Information:
Gives AK rebel a probability to wear themed helmet.
Replaces default long range radio backpack with IFA radio backpack
Adds IFA parachutes flyGear
closes #XXXX
1. [x] No
Steps: 
Notes:
=> updated IFA radio backpacks, AK headwear, Parachutes

A3A/addons/core/Stringtable.xml, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/AI/fn_artySupport.sqf, A3A/addons/garage/Core/fn_sellVehGRG.sqf, A3A/addons/garage/Dialogs.hpp, A3A/addons/gui/functions/SetupGUI/fn_setupFactionsTab.sqf
1. [X] Bug
2. [X] Change
Information: 
Added faction information to the SFP and IFA factions
Corrected a misspelling in "arctic"
Corrected typos in the hint if the new battle menu is disabled
Artillery markers will now delete globally when the interface is exited
Garage hints should execute onto the actual player now
The garage should now also remove the vehicle from the pool server side as well, fixing a duping exploit
Added additional logging to the sale of vehicles.
Slightly restructured the garage UI to fix an edge case if ACE was loaded
Added SFP hardcoding to the factions tab data
The factions tab addons will now fall back on the internal name of the dependency if none is found
2. [ ] Have you loaded the mission on a …
=> 3.6 Testing Fixes 1

A3A/addons/garage/Core/fn_removeFromPool.sqf, A3A/addons/garage/Core/fn_sellVehGRG.sqf
1. [X] Bug
2. [ ] Change
Information: Fixes a bug where the garage sell would remove everyone's vehicle section on a dedicated server
1. [X] No
Steps: 
Notes:
=> Fix for vehicle sell DS

A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf
1. [ ] Bug
2. [x] Change
Information:
replaces the civilian Gaz M1's with jeeps or camouflaged cars in the allies, us, uk, and soviet templates.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> IFA Replaced police vehicle with something less civilian

A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf
1. [x] Bug
2. [x] Change
Information:
For whatever reason the TLA get binocular NVGs on their military even though they're not supposed to, those NVGs are not present in the templates.
This should fix that
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Update RHS_AI_TLA military NVGs

A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp
1. [x] Bug
2. [x] Change
Information:
Adds loadouts for two variants of T50 used in the new VDV template.
Experiments with adding a CAS loadout to T50
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Update RHS T50 loadouts

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_CIV.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Vehicle_Attributes.sqf, A3A/addons/logistics/Nodes/SPE.hpp
1. [ ] Bug
2. [X] Change
Information:
Added 1.1 content to the SPE_IFA templates. The SPE templates themselves have not been updated, support for SPEX will have to be made at some point.
1. [ ] No
Notes:
Templates are still rough around the edges and could use some more work in terms of balancing vehicle prices, for both enemies and rebels. Transferring to @ante185 for polishing.
=> SPE_IFA 1.1 Template Updates

A3A/addons/core/Templates/Templates.hpp
1. [x] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Missing semi colon in IFA_SOV lore line.

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/garage/Public/fn_initGarage.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_init.sqf
1. [x] Bug
2. [ ] Change
Arsenal, Garage and Vehicle arsenal actions are now unavailable for UAVs.
This prevents players from accessing them through UAVs.
closes #3161
1. [ ] No
Steps: see issue. Vehicle arsenal action resulted in the same behaviour as arsenal.
Notes:
=> Fix HQ actions being available through remote controls

A3A/addons/core/Includes/script_version.hpp, A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf, README.md, changelog.rst
Hotfix to push changes from #3409 directly to master for publishing.
=> 3409 master

A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
1. [X] Bug
2. [ ] Change
Apparently made a last-minute change that broke the logic in the mortar routine. Whoops.
Re-tested both code paths, seems fine.
closes #XXXX
1. [X] No
=> Fix precedence error in mortar/arty support routine

A3A/addons/config_fixes/RF/CfgVehicles.hpp, A3A/addons/core/Templates/AircraftLoadouts/RF/config.cpp, A3A/addons/core/functions/AI/fn_attackHeli.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [ ] Bug
2. [X] Change
Information:
Helicopters can now have config-defined loadouts. Cougar has moved to configs
Refactor on setPlaneLoadout to have a bit less reused code
1. [X] No
Notes: No other helicopters have been changed. Others can be adjusted though
=> Helicopter Config Loadouts

A3A/addons/config_fixes/WS/CfgVehicles.hpp, A3A/addons/config_fixes/WS/ws_ion.hpp
1. [ ] Bug
2. [ ] Change
Information:
Fixes the textures of a number of custom kamaz truck classes
closes #XXXX
1. [x] No
Steps: 
Notes:
Not sure when or how this happened, it was fine when i left it im pretty sure
=> WS Kamaz Texture Fix

A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [x] Bug
2. [ ] Change
Information:
Tiny fix
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fix debug line in fn_setPlaneLoadout.sqf

A3A/addons/core/Templates/Templates/CWR/CWR_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CWR/CWR_Reb_FIA.sqf
1. [ ] Bug
2. [x] Change
Information:
Replaced Jawa motorbike with regular quadbike, behaviour was too erratic - CUP motorbike alternative was slightly better but still bad.
Gave the US police additional ammo when they get issued shotguns.
Supplemented rebel vehicle selection
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Cwr3 post-test adjustments

A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_TLA.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf
1. [ ] Bug
2. [x] Change
Information:
added a case that adds a couple appropriate weapons in the case that an pure RHS faction is used while 3CB Factions is loaded.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> 3CBF weapon integration into RHS factions

A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_SOV.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf
1. [X] Bug
2. [X] Change
Information:
Replaced the large intel item because the previous one had unintended interactions.
Adds the howitzer and AVRE churchill to the UK ARMY IFV lineup
Moved the M4A3E8 HVSS into heavy tank
Increased the probability for M2 carbines among western SF
closes #XXXX
1. [X] No
Steps: 
Notes:
=> Ifa update

A3A/addons/maps/Antistasi_isladuala3.isladuala3/initServer.sqf, A3A/addons/maps/Antistasi_isladuala3.isladuala3/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
Removed a number objective locations to provide more breathing room and less server congestion.
Did a pass looking for outposts and objectives with insufficient ingress points and addressed them.
Switched the numerous hide terrain objects modules to local.
added fort_rampart to the initial object hiding.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Isla duala enemy location cull

A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf
1. [x] Bug
2. [ ] Change
Information:
added missing comma.
replaced nonexisting mlrs class with existing mlrs class
closes #XXXX
1. [x] No
Steps: 
Notes:
=> CUP template fixes in BAF, ION

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/RHS/RHS_AI_HIDF.sqf
1. [x] Bug
2. [ ] Change
Information:
Removes blank entry from HIDF (It was giving them vanilla NVGs)
Flagged HIDF and TLA as lowTech
closes #XXXX
1. [x] No
Steps: 
Notes:
=> RHS HIDF, TLA, NVG fix

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
Updates changelog and version for 3.8.0 update
Also added 3.7.1 changelog here as it was only direcly added to Master branch in the past
=> 3.8.0 changelog and version

A3A/addons/gui/Stringtable.xml
Removes duplicate `setup_dialog` entry breaking the localization pipeline
=> removes dublicate container entry

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
1. [X] Bug
2. [ ] Change
Information:
Fixed bug that let players search multiple SL bodies at the same tim\e
closes #XXXX
1. [X] No
Steps: 
Notes:
=> Fixed double Intel search Bug

A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf, A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf, A3A/addons/core/Templates/Templates/VN/VN_CIV.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf
1. [X] Bug
2. [X] Change
Information:
Added names to SOG factions, as they used to have greek names.
closes #3465 
1. [ ] No
Steps: 
Load the factions up and check for errors
Notes:
No testing done at all yet
=> Added appropriate names to SOG factions

A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
1. [X] Bug
2. [ ] Change
Information: (ACE) Trying to repair your car because you cant drive and hit a rock wont break your undercover. Nothing wrong with a bit of field repair.
1. [X] No
Steps: Go undercover and try to remove and replace wheels on a car with ACE loaded
=> Fix ACE Veh Repair breaking undercover

A3A/addons/core/functions/Intel/fn_searchIntelOnLaptop.sqf
1. [X] Bug
2. [ ] Change
Information: commsMP is kind of unintuitive in how it works, and when the strings here were serialized an oversight included a different than intended string.
1. [X] No
=> Fix wrong laptop hack string

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [ ] Change
Information: Start with ACE Plotting Board in arsenal
1. [X] No
Steps: Load the game with ACE enabled
=> Start with ACE plotting board

A3A/addons/core/Stringtable.xml, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/3CB/3CB_Civ_ADC.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Civ_MEC.sqf
1. [ ] Bug
2. [ ] Change
Information:
Felt the current CIV selection is quite lacking, so added these two.
1. [ ] No
Steps: Load up new mission with 3cb factions 
Notes:
=> Add 3CB Civilan Factions African Desert Civilians and Middle Eastern Civilians

A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added scaling of TFAR receiving/sending distance multipliers. Every captured and alive antenna boosts the signal by ~10%.
-
1. [ ] No
Steps: 
Notes:
All of the commands run individually, math maths, but I don't have a TS3 server ~or friends~ to check whether this works.
=> TFAR Signal distance scaling off Radio towers.

A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/initServer.sqf, A3A/addons/maps/Antistasi_SPE_Normandy.SPE_Normandy/initServer.sqf
1. [x] Bug
2. [x] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
tested by loading the missions, and zeus lighting and calling artillery supports on a couple of bridges.
May need a sanity check with a DS but I've been assured that it works.
Notes:
=> Made SPE bridges indestructible 

A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf
1. [ ] Bug
2. [ ] Change
Information:
Sets CAS to fly at a maximum of either 80% or 450 km/h
closes #XXXX
1. [ ] No
Steps: 
Notes:
keep it simple stupid works.
An alternative would be setting different speed limits for the various stages/phases the CAS plane switches between
=> CAS speed limit imposed to minimise lawn darting

A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/3CB/3CB_AI_GAF.sqf
1. [ ] Bug
2. [ ] Change
Information: Added a 3CB faction for the Grozovia Armed Forces.
They use a fair amount of SAF stuff which is interesting to play with.
Thanks Skill for allowing us to port his extender.
1. [ ] No
Steps: Needs to be reviewed and played
=> 3CB Grozovia Armed Forces

A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
1. [ ] Bug
2. [ ] Change
At admin request, all explosive placement will now be logged to server.
1. [X] No
Steps: Load, grab IED, place IED
=> Explosive placement logging

A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
1. [ ] Bug
2. [X] Change
Cleaned up dive bomb run test logging spam that was accidentally left enabled.
closes #3520
1. [X] No
=> Disable dive bomb test debug spam

A3A/addons/gui/functions/GUI/fn_playerTab.sqf
1. [X] Bug
2. [ ] Change
Information: Context menu only worked with air and land vics. This has been corrected to anything garageable. Needs minimal testing
Steps: Try to garage a loot box, repair station, or boat
=> New UI: Context menu fix

A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Information:
All helicopters large enough to in transportHelicopter category are probably fine to use for fast roping
closes #XXXX
1. [ ] No
Steps: 
Notes:
TODO: find a command and a method to test this
=> Update fn_initVarServer.sqf with more helicopters to fast rope from

A3A/addons/maps/Antistasi_Altis.Altis/mission.sqm
1. [X] Bug
2. [ ] Change
Fix busted control count in altis SQM.
closes #XXXX
1. [X] No
=> Fix altis SQM control count

A3A/addons/maps/Antistasi_SPE_Mortain.SPE_Mortain/mission.sqm, A3A/addons/maps/Antistasi_UMB_Colombia.UMB_Colombia/mission.sqm, A3A/addons/maps/Antistasi_cup_chernarus_A3.cup_chernarus_A3/mission.sqm, A3A/addons/maps/Antistasi_gm_weferlingen_summer.gm_weferlingen_summer/mission.sqm, A3A/addons/maps/Antistasi_gm_weferlingen_winter.gm_weferlingen_winter/mission.sqm, A3A/addons/maps/Antistasi_regero.regero/mission.sqm, A3A/addons/maps/Antistasi_tem_kujari.tem_kujari/mission.sqm
1. [x] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Update garage box to not use vehicle ammo boxes

A3A/addons/core/functions/Dialogs/fn_canFastTravel.sqf, A3A/addons/core/functions/OrgPlayers/fn_theBossToggleEligibility.sqf, A3A/addons/core/keybinds/fn_keyActions.sqf, A3A/addons/gui/dialogues/mainDialog.hpp, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf, A3A/addons/gui/functions/GUI/fn_mainDialog.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf, A3A/addons/gui/functions/GUI/fn_playerTab.sqf, A3A/addons/gui/functions/GUI/fn_requestMissionDialog.sqf
1. [X] Bug
2. [ ] Change
Information: Fixed a few UI bugs that came up in testing
1. [X] No
=> Playtesting UI fixes 1

A3A/addons/maps/Antistasi_regero.regero/mission.sqm
1. [X] Bug
2. [ ] Change
- Fix airport_2 sending land vehicles up north due to bad spawn point.
May add further fixes to this PR.
closes #3548
1. [X] No
=> Regero testing fixes

A3A/addons/core/Templates/Templates/3CB/3CB_AI_GAF.sqf
1. [x] Bug
2. [ ] Change
Information:
Error missed in review
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Update 3CB_AI_GAF.sqf with militia marksmen rifle fix

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf, A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
1. [X] Bug
2. [X] Change
Information: Tent can now be used to skip 8 hours, was bugged before.
Stopped every client from logging explosive placement. There's a deeper bug that I'm not working out now
Killed auto-switch to mortar team, pressing Y with an HC squad now always opens single group. Open to more feedback.
1. [X] No
=> Playtesting UI fixes 2

A3A/addons/config_fixes/3CB/CfgWeapons.hpp, A3A/addons/config_fixes/Aegis/CfgWeapons.hpp, A3A/addons/config_fixes/Vanilla/CfgWeapons.hpp, A3A/addons/config_fixes/WS/CfgWeapons.hpp, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_addItem.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
1. [x] Bug
2. [ ] Change
Information:
Made the arsenal not accept erroneous base weapons (These would formerly appear as blank entries). 
Removed the obsoleted config fixes.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Final baseWeapon fix

A3A/addons/core/keybinds/fn_keyActions.sqf, A3A/addons/gui/Stringtable.xml, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf, A3A/addons/gui/functions/GUI/fn_hqDialog.sqf, A3A/addons/gui/functions/GUI/fn_mainDialog.sqf
1. [X] Bug
2. [X] Change
Mortar routine now checks if the target pos is within range before allowing fire
Marker and HC squad draw EHs now added to garrison and fast travel maps
Clicking on the commander map no longer closes the UI in many cases
Changed many stringtabled breaks to be \n instead
1. [ ] No
Steps: 
Notes:
=> Playtesting UI Fixes 3

A3A/addons/garage/Core/fn_getCatIndex.sqf, A3A/addons/garage/Public/fn_loadSaveData.sqf
1. [X] Bug
2. [ ] Change
Fix shit    
closes #XXXX
1. [X] No
=> Fix bug with garage category defaulting to helicopter

A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
1. [ ] Bug
2. [X] Change
Rebalanced airbase heli spawns from the previous worst possible implementation
1. [X] No
Steps: Go to an airbase with multiple helipads
=> Airbase heli balancing

A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
1. [X] Bug
2. [ ] Change
Information:
Garrison counts are now displayed on maps
Fixed a bug where you could garrison enemy cities
1. [X] No
Steps:
=> Minor garrison fixes

A3A/addons/core/Templates/Templates.hpp
1. [ ] Bug
2. [ ] Change
Information:
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> 3.9.0 Unstable -> Master Hotfixes

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ_LIV.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Civ_TNA.sqf
1. [ ] Bug
2. [x] Change
Information:
Renamed A3 Civilian to A3 Altian Civilians.
Added Tanoan and Livonian civilian factions.
Rebalanced vehicle weights to try and make them be different from each other.
Changed uniforms to make Altian, Tanoan, and Livonian civilians distinct from each other. 
Changes the LDF from using the Enoch flag to the EAF flag so the Enoch flag could be used for Livonian civilians
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> [Templates] Vanilla Civilians Upgrade?

A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
1. [ ] Bug
2. [X] Change
Rebalanced probabilities on the des heli
closes #3270 
1. [ ] No
Steps: 
Notes:
=> DES Heli mission probability fixes

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Dialogs/fn_canSkipTime.sqf, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf, A3A/addons/gui/functions/GUI/fn_fastTravelTab.sqf, A3A/addons/gui/functions/GUI/fn_playerTab.sqf, A3A/addons/gui/functions/GUI/fn_recruitDialog.sqf
1. [X] Bug
2. [ ] Change
Fixed unit recruit action on captured flags using only old UI
Fixed error cases for time skip
Fixed line breaks in several UI cases
Added outpostsFIA as valid fast travel targets
Commander unit recruit now properly checks faction instead of personal cash    
closes #3629 
closes #3627 
1. [X] No
Steps: 
Notes:
=> Playtesting UI Fixes 4

A3A/addons/core/functions/Ammunition/fn_ammunitionTransfer.sqf, A3A/addons/core/functions/UtilityItems/fn_remainingAmmo.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug where commsMP would trigger every time something was garaged
Fixed some bad comments in remainingAmmo
Fixed a bug where bombRuns would be maxed constantly
Fixed a bug where ammo boxes and loot boxes would not be deleted when transferring to arsenal
Fixed a bug where loot boxes wouldnt be refunded
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Ammo transfer + Airsupport fixes
