official-antistasi-community/A3-Antistasi

A3-Antistasi/Templates/teamPlayerRHSGREF.sqf
Replaces Gendame troops with american UCP units to remove vanilla weapons from the RHS version.
Also replaces the Gendarmerie offroad as it no longer matches the units that spawn.
=> Replace Gendarmerie

A3-Antistasi/Ammunition/getRadio.sqf
`{_x find "Acre" > -1}` allows for finding the acre ItemRadio replacement ("ItemRadioAcreFlagged"),
`{_x find "ACRE_" > -1}` allows for finding the acre radio classes if acre is not flagging the unit correctly ("ACRE_PRC343")
Fixes #324
=> Fix for acre2 radios not being recognized as a units radio

A3-Antistasi/onPlayerRespawn.sqf
we only add these items back to player when unlocked here for their convenience. But they need to go to the arsenal anways to get guns and whatnot, so really it just makes our lives difficult for no gain.
=> Stops messing with items in onPlayerRespawn

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
assigned max type values to local variables inside the crates script so that they are not artificially inflated each ammo truck mission.
=> Protects maxTypes parameter value in loot crates scripts

A3-Antistasi/functions/init/fn_initDisabledMods.sqf
The parameter existed but initDisabledMods never did anything with it.
=> added missing check for globmob DLC

A3-Antistasi/Templates/Loadouts/rhs_afrf_AT2.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_machineGunner.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_medic.sqf, A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_grenadier.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_machineGunner.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_marksman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_medic.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_rifleman.sqf, A3-Antistasi/Templates/Loadouts/rhs_usaf_teamLeader.sqf
Recent loadout changes have broken some implicit rules regarding how strong PvP loadouts should be. This reverts the recent changes in their entirety (except for changes to AT), so that the changes can be re-reviewed, adjusted and re-implemented.
=> Rolls back recent changes to loadouts

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Arct.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Arid.sqf, A3-Antistasi/Templates/IFA_Reb_POL_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/functions/AI/fn_autoRearm.sqf, A3-Antistasi/initVar.sqf
resolves #347 
**Changes**
- removed 'initialWeapons' array from all templates and initVar
- replaced 'initialWeapons' check with 'intialRebelEquipment'
- converted all `and/or/not` to `&&/||/!`
- cleaned up bracketing format
- unified whitespace
- replaced use of 'private' array for use as keyword
- removed unnecessary re-define of _maxDistance within each loop
- expanded weapons search to include new stored types
**Variables Changed**
- _Pweapon to _primaryWeapon
- _Sweapon to _secondaryWeapon
- _hasBox to _foundItem
- _distanceX to _maxDistance
- _objectsX to _nearbyContainers
- _objectX to _potentialContainer
- _target to _selectedContainer
- _potential to _potentialWeapon
- _weaponsX to _containerWeapons
- _weaponX to _selectedWeapon
- _basePossible to _baseWeapon
- _magazines to …
=> Auto rearm fix

Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
Signed-off-by: Tad <tdaykin@live.co.uk>
1. [X] Bug
Information:
This seems to have been created when the Tanoa map was updated to include a Min player cap. It duplicated the `ScenarioData` class which was then throwing errors.
closes #449 
1. [X] Have you loaded the Mission in a Dedicated Server?
1. [X] Yes (Please provide further detail below.)
Notes:
Needs additional load check as the map loaded on my server.
=> Removed duplicated Class preventing Tanoa load.

A3-Antistasi/functions/init/fn_initGarrisons.sqf, A3-Antistasi/initServer.sqf
The garrison will now be loaded after the check if there is a old save to load, if thats so, the system will not create new garrison.
However, this system will be replaced by the new (already in the background working) system for the new garrisons, so it is only a temporary fix and does not have to be absolutely solid
=> Fixed the bug with the garrison spawning in wrong

A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
just adds a simple check in the fast travel script for any rope cargo, if it detects anything it will fail. This does mean that an empty tow rope will also prevent fast traveling. If anyone has any tips to fix that please let me know.
resloves #420
=> Fast travel towing fix

A3-Antistasi/functions/init/fn_initSpawnPlaces.sqf
Warning about markers being to far away from the main marker shows only in debug mode
=> Added debug check

A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [X] Bug
The marker flips to government after loading a game problem mentioned in #454 persists. This version switches all spawns in initGarrisons to calls to make sure the markers are initialised in the right order, and avoids the unnecessary garrison init calls when loading a game.
Mentioned as a secondary problem in #453 and #454.
Singleplayer only calls initGarrisons when starting a new game. Seems to work fine in that case.
Yes, and hosted.
1. [X] No
Well, the init order is nasty, initGarrisons contains critical functionality that isn't related to garrisons and the roadblock creation is horribly slow, but as a bugfix this should be fine.
2. [ ] Yes …
=> Fix marker init order on game load

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/statSave/saveFuncs.sqf, A3-Antistasi/statSave/saveLoop.sqf
1. [X] Bug
Also arguably an enhancement, as players can now retain some above-ground statics.
At some point, markerChange gained a feature to add local statics to the save list when a marker was captured by the rebels. There are two issues related to this:
1. Enemy statics are usually placed on building surfaces rather than terrain, and the load/save code didn't support that, so the statics moved to the ground after a save/load cycle. This was fixed by using getPosATL and setPosATL rather than getPos and setPos. Apparently getPos returns the distance from the nearest surface, so it loses information. Old saves will work as before, as setPosATL and setPos have the same effect over land.
2. markerChange didn't clear the local statics from the save list when a marker was recaptured by an …
=> Fix static save

A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf
1. [X] Bug
RHS rifles (both with and without GL) have an additional muzzle called "SAFE", so the simple `muzzles == 2` check doesn't work. This instead checks `cursorAim` in the muzzle config for the second muzzle. Looks like a dirty hack, but it's the same dirty hack that BIS_fnc_itemType uses internally.
A slightly simpler test would be be to check if muzzle 2 has the name "SAFE", but that would include other non-GL underbarrels, like that weird CSAT gun in Apex with the underbarrel 50cal.
Tested with vanilla and RHS. Will also work with CUP weapons.
1. [ ] No
Should ideally be checked with 3CB, although it should work unless 3CB is even weirder than RHS. I don't have 3CB installed at the moment.
=> Fix RHS rifle underbarrel GL categorisation

A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
1. [X] Bug
On unstable, missile launcher ammo currently unlocks at minWeaps, regardless of whether missile launcher unlocking is allowed. This code prevents missile ammunition unlocking unless `allowGuidedLaunchers` is true.
I retained the style of declaring the private variables outside the loop, but the performance gain is very small (checked with diag_codeperformance) even for trivial loops, so I wouldn't recommend it here.
One oddity is that this code blocks PCML ammunition from unlocking, because the PCML is classified as a rocket launcher by BIS_fnc_itemType, but the ammunition is a missile. As it's probably a BIS bug, it could be worked around with a `_type == "NLAW_F"` check if necessary, rather than grinding through all the launchers and categorising their ammo …
=> Prevent missile launcher ammo unlocking without allowGuidedLaunchers

A3-Antistasi/functions/Base/fn_rebuildAssets.sqf, A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf, A3-Antistasi/initZones.sqf
1. [x] Bug
Information:
Fixed a bug where a radio tower marker would not show after a radio tower is rebuilt. It was because the marker name was already in use.
I changed it to use map grid position in the name of the marker, so they should be unique now, as long as we don't have multiple antennas in the same grid.
closes #XXXX
1. [x] No
Notes:
=> Fix radio tower marker not showing after rebuild

A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf
1. [X] Bug
Rebel recruits now get the correct type of GL round for the weapon used, instead of assuming that it's 40mm. Fixed a typo (addMagazine vs addMagazines) that limited troops to one round. Also fenced off some currently-unused code that assumed the target unit already had a primary weapon.
Small part of #406.
1. [X] No
=> Fix rebel recruit GL ammo type & quantity

Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-ArmiaKrajowa.chernarus_summer/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [X] Bug
Information:
Reverted some changes made in #474 as they removed identifiable information from the Server browser for the Antistasi map names, and from the in-game menu where you would see the Mission name.
None
1. [X] No
Notes:
=> Restored map name function in Server browser

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/Base/fn_mrkWIN.sqf, A3-Antistasi/functions/Utility/fn_log.sqf
1. [ ] Bug
Added logging to mrkWIN and markerChange to track the effects of take-the-flag actions. Because that process is split between client and server, I added some functionality to log to the server RPT instead of the client. Also moved the logging code to utilities/fn_log for sanity. 
log.sqf now appears to be unused and can probably be deleted, but I haven't checked.
closes #527 
1. [ ] No
log.sqf could be deleted if unused. Log-to-server param should probably default to true, as I can't think of many cases where you'd want to log to the client separately, but I retained the previous behaviour.
=> Marker change logging

Map-Templates/Antistasi-Malden.Malden/mission.sqm
This fixed the island detection which was not functional on Malden as reported by Spoffy.
1. [x] Bug
Information:
Island markers fixed on Malden for island detection    
closes #560 
1. [x] No
Notes:
=> Malden - Island marker overhaul

A3-Antistasi/initZones.sqf
1. [x] Bug
Information:
I fixed an issue with radio towers that I introduced in pull request #534.
The tower class that I previously used to replace the bad ones comes from CUP mod, so it wasn't available when playing Altis without CUP. I had previously tested it on chernarus_summer. I now replace it with a vanilla model but I don't like it much because that tower is really big. But at least it's functional now.
While debugging it I also discovered that the check on map name doesn't work in https://github.com/rurku/A3-Antistasi/blob/9d4234ca70a36aba48306c00eca9e635799b176d/A3-Antistasi/initZones.sqf#L201 becasue switch - case is case sensitive.
This means that the radio towers present on altis are not what was intended. But I don't dare to touch that.
closes #XXXX
1. [ …
=> Fix bad radio tower substitution on Altis

A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug (ish)
Roadblocks currently don't spawn any troops (but they do spawn everything else, including the vehicles) if the unit limit is near max. This causes the "roadblock destroyed" mission to complete and gives players free stuff. This is probably undesirable.
Partial resolution of #551
=> Force roadblock groups to always spawn

A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
Changes the Panzerfaust to the RPG-75 as the panzerfaust has no weight until equipped by a soldier. This is due to RHS not assigning a weight to the tube and it not having a warhead until equipped by a soldier.
=> Rhs launcher change

A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
Closes #556 
Had some CDF officers to make the traitor missions look like a meeting between US and Local forces. Because CDF is GREF their uniforms can be picked up by rebels. They are now 101st and 1st cavalry troops.
=> Cdf traitors

A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
1. [X] Bug
One-letter vehicle classname typo in two RHS templates that actually caused the quadbike spam (since #544, larger vehicle spam) by a slightly bizarre chain, which I will document because some other steps may need cleaning up:
1. A couple of the USAF templates have "rhsusf_CGRAT1A2_Mk19_usmc_wd" in them, which is missing a C.
2. These sometimes get passed as requested garrison vehicles, and end up hitting selectReinfUnits.
3. The BIS seat count functions on non-existent vehicles return 0, which causes selectReinfUnits to fail the _allSeats > _seatCount check.
4. These vehicles are therefore ignored, but remain in the requested array. 
5. If there are no other vehicles or units remaining in the requested array (which is inevitable, as the rest are eventually …
=> Fix CGRCAT vehicle typo in USAF templates

A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Wdl.sqf
No one accounted for the duplicate listings in the templates when initialRebelEquipment was made. this let the panzerfaust through.
Now it doesn't have any more panzerfausts, and i fixed a misplaced m1garand.
=> Sonorous meerkat patch 1

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
1. [x] Bug
Information:
This fixes a bug in arsenal loading saved loadout.
If the player has NVGs or binoculars equipped and loads a saved loadout then the binos and nvgs are added to arsenal twice. It's because nvgs and binos are returned by `assignedItems` but the code was also adding them to the list explicitly.
It can be used as an exploit to unlock equipment.
closes #XXXX
1. [x] No
Notes:
=> Fix arsenal duplicating equipped nvgs and binoculars

A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
Changed the blufor version's startLR to make it the same size as the other versions. This was brought up in the community meeting in so far as several squad leaders refusing to take an LR at all because, and i quote, "It has no carry capacity."
To be fair, startLR could be disabled for 2.2 since the radios now appear in loot, which is what startLR was, partially, a temporary fix for.
=> Upgrade AltisB start LR

A3-Antistasi/functions/Ammunition/fn_ammunitionTransfer.sqf
1. [x] Bug
Information:
If a weapon has a magazine/grenade/missile loaded then the ammo gets lost and is not transferred to arsenal. Because of this bug I now have 3 Javelin launchers and no rockets.
I looked in git history and found that this code had been there at some point but was commented out and subsequently removed. I wonder why. It works fine for me.
https://github.com/official-antistasi-community/A3-Antistasi/commit/1cde46509a0b11e5bae4a32ebf7667fa7a38d684#diff-fff9ca636b2f6c7b1d986d4b3b111bfeL45-L57
closes #XXXX
1. [x] No
Notes:
=> Fix magazines loaded to weapons getting lost when transferring to arsenal

A3-Antistasi/FSMs/ConvoyTravel.fsm, A3-Antistasi/FSMs/ConvoyTravelAir.fsm, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/Convoy/fn_convoyMovement.sqf, A3-Antistasi/functions/Convoy/fn_despawnConvoy.sqf, A3-Antistasi/functions/Convoy/fn_onSpawnedArrival.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoyLine.sqf
1. [X] Bug
A ton of reinforcement convoy spawning and spawned-management code. See below.
1. [X] No, but you can't have too much testing for this stuff.
Initial bugs fixed, relatively easy stuff:
1. Convoys with multiple ground vehicles annihilating on spawn, caused by moving vehicles being teleported backwards with findEmptyPosition.
2. At least three different bugs where a spawned convoy could initially drive backwards, often causing explosions and/or stuck vehicles.
3. Pure air convoys flying to [0,0,0].
4. Various arrival glitches with troops refusing to disembark.
5. Vehicle gunner/commander not using the vehicle's weapons.
Reorganisation
Then it gets ugly. Frustrated with trying to add functioning despawn code to …
=> Spawned convoy fixes and reorganisation

A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf, A3-Antistasi/functions/Base/fn_createPetros.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
1. [x] Bug
(Mod) fn_unlockEquipment.sqf
(Mod) fn_createPetros.sqf
(Mod) fn_initServer.sqf 
`//ya estamos todos` removed from `fn_initServer.sqf` It is obvious that playerUnits contains "all of us". Therefore, it is a violation of comment rules.
Changed `spawn A3A_fnc_initPetros` to `call A3A_fnc_createPetros` in fn_initServer.sqf.
Changed `spawn A3A_fnc_initPetros` to `call A3A_fnc_initPetros` in fn_createPetros.sqf.
Moved call `A3A_fnc_createPetros` to a position after `_x call A3A_fnc_unlockEquipment` in fn_initServer.sqf.
comment `You can also find unlockedRifles and other variables constructed here. - FrostsBite.` added to `fn_unlockEquipment.sqf` to make it easier to find in the future.
This allows Petros to init with the correct gear and classname without having …
=> Petros gear init

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_createAISite.sqf, A3-Antistasi/functions/Missions/fn_LOG_Ammo.sqf
1. [X] Bug
Fixed one common and two unlikely cases where the crate loot generation code would error out due to accessing nil variables, blocking some crate items and possibly breaking the marker spawning.
Also switched the crate loot generation calls to spawn, as they're not time- or order-critical, and it protects the marker spawning code from other potential errors.
1. [X] No
=> Fix error cases in crate generation, change from call to spawn

A3-Antistasi/functions/REINF/fn_NATObomb.sqf
1. [X] Bug
NATObomb is missing the type input parameter for the HE case. NATObomb is the function used for rebel airstrikes. The name probably dates back from NATO-supported Antistasi versions.
closes #633 
1. [ ] No
Could do with changing the filename.
=> Fix missing bomb type param in HE case

A3-Antistasi/functions/Garrison/fn_getVehicleCrew.sqf, A3-Antistasi/functions/Garrison/fn_selectVehicleType.sqf, A3-Antistasi/functions/Garrison/fn_updatePreference.sqf
1. [X] Bug
Information:
Read title
If the selectVehicleType does not have any results it will drop an error and returns "Empty". The following functions will return [] when given an "Empty" parameter
closes #626 
1. [ ] No
Notes: Laptop again, someone better start it once
=> Fixed a bad parameter name and made the system a bit more failsafe

A3-Antistasi/functions/Base/fn_rebelAttack.sqf
1. [X] Bug
As far as I can tell, the only way #625 can happen is as follows:
1. You're either playing reb vs (gov+inv) or at war tier 1, which reduces the range of attack targets.
2. Enemy launches a few counterattacks, adding player-taken locations to killZones.
3. When calculating the possible targets for an attack, killZones reduce all target weights below 0.5, which are then rounded down to zero.
4. selectRandomWeighted is called with an array only containing zeros, returning nil.
As a caveat, it'd take a lot more time to figure how killZones work in detail, so I can't be sure that this is possible. Maybe I missed another way for this code to break.    
Fixed by removing the rounding, as there's no reason not to use fractional inputs to selectRandomWeighted. I'm …
=> Fix rounding bug that could potentially prevent finding an attack target

A3-Antistasi/functions/Garrison/fn_selectReinfUnits.sqf
1. [X] Bug
- Fixed the vehicle selection loop so that the crew count from the selected vehicle was preserved.
- Changed the behaviour of the function to ignore input crew, as the rest of the code was auto-filling vehicle crew anyway. If extra crew were desired for some reason, you could still add them to the cargo lists.
- Moved the variable declarations to their appropriate scopes, as bugs were really hard to spot when so many variables had unclear scopes. This may be fractionally slower, but it's worth it if anyone needs to read the code again.
closes #629 
1. [X] No
=> Fix crew-handling bugs in fn_selectReinfUnits

A3-Antistasi/functions/Missions/fn_missionRequest.sqf
1. [X] Bug
Prevented DES_heli (destroy helicopter) missions from being created by mission requests, as the RHS templates lack the flatbed truck data for it, causing errors on launch. Fixing it would require too much work at this stage.
closes #636 
1. [ ] No
Ideally fix up the mission at some stage, or something like it. Currently it's attempting to load helicopters onto flatbed trucks, which might be a bit unreasonable unless we can make use of JNL.
=> Disable DES_heli mission as RHS templates lack data for it

A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf
1. [X] Bug
Information: Vehicles are not longer breachable if they have no crew or are crewed by someone from the teamPlayer faction. This includes PvP players. They are no longer able to breach vehicles of the rebels.
1. [ ] No
Notes: Needs testing (laptop again), but as it is only minor, there should be no problems
=> Add a check to prevent breaching an empty or teamPlayer vehicle

A3-Antistasi/functions/Templates/fn_aceModCompat.sqf, Map-Templates/Antistasi-Altis-BLUFOR.Altis/mission.sqm, Map-Templates/Antistasi-Altis.Altis/mission.sqm, Map-Templates/Antistasi-Anizay.tem_anizay/mission.sqm, Map-Templates/Antistasi-Chernarus.chernarus_summer/mission.sqm, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/mission.sqm, Map-Templates/Antistasi-Kunduz.Kunduz/mission.sqm, Map-Templates/Antistasi-Livonia.Enoch/mission.sqm, Map-Templates/Antistasi-Malden.Malden/mission.sqm, Map-Templates/Antistasi-Tembelan-Island.Tembelan/mission.sqm, Map-Templates/Antistasi-WotP.Tanoa/mission.sqm
1. [ ] Bug
Information:
All maps got overhauled in terms of:
- changed playable rebel slots to:
- 8 officers
- 6 riflemen
- 6 autoriflemen
- 6 grenadiers
- 6 combat life savers
- 6 engineers    
- Disabled simulation for helipads
Some maps got overhauled in terms of:
- Disabled simulation for Portable Helipad Lights and turned into simple objects
- Disabled simulation for H-barriers
- Disabled simulation for containers and turned into simple objects
- removed the large tents
closes #643 
closes #645 
1. [ ] No
Notes:
This needs to be merged BEFORE #648
=> 2.2.1 map overhauls

A3-Antistasi/functions/init/fn_playerMarkers.sqf
Also show markers for vehicles if the driver is not a player (otherwise no markers will show)
1. [x] Bug
closes #663 
closes #664 
- Injured player marker condition is extended to check the `ACE_isUnconscious` variable
- Vehicle markers check if the driver is a player, this is needed as having an AI driver causes your marker to become invisible
1. [x] No
Notes:
=> Show injured marker for ACE Unconsciousness & AI Driver bug fix

A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
They have now been fucked
1. [ ] Bug
Information:
Removed IEDs from rebel starting equipment on vanilla
closes #676 
1. [x] No
Notes:
=> IEDs removed from vanilla starting gear.

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_rebuildAssets.sqf, A3-Antistasi/functions/Base/fn_rebuildRadioTower.sqf, A3-Antistasi/functions/Base/fn_repairRuinedBuilding.sqf, A3-Antistasi/functions/Missions/fn_REP_Antenna.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
1. [X] Bug
Three bugs related to radio tower rebuilding:
1. A3A_fnc_repairRuinedBuilding only works when run on the server, because it accesses non-public variables, so neither the repair mission or the boss rebuild option actually rebuilt the tower object. One option was to make those variables public, but given what the function does I chose to move radio tower rebuilding onto the server, rather than clients and HCs mangling several different public arrays and setVariables.
2. Markers for dead radio towers were being deleted, but not removed from mrkAntennas. Minor issue that may have caused some missing-object RPT spam.
3. Radio towers were being added to destroyedBuildings, when they're specifically excluded from that mechanic. Probably minor.
closes #673
1. [X] No …
=> Move radio tower repair to server side, fix bugs

A3-Antistasi/functions/init/fn_initZones.sqf
1. [X] Bug
Fixed clear typo added in 2e2d7f7c34652280dc708f1eab9dfb51a9b8faf8.  
closes #695
1. [X] No
=> Fix typo in initZones

Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/AL_snowstorm/al_trembling.sqf
1. [X] Bug
Prevented the snowstorm code in al_trembling from running when executed on servers and HCs. It's not supposed to, but the syntax is botched in the if...exitwith statement.
Caveat: I have little idea what this code does.
closes #689 
1. [ ] No
Untested. It won't work any worse at least. Travis will probably fail to due to hash-select syntax.
=> Make al_trembling quit silently when run on server/HC

A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_RESPAWN.sqf, A3-Antistasi/Scripts/UPSMON/MODULES/UPSMON_spawn.sqf, A3-Antistasi/functions/Base/fn_garbageCleaner.sqf, A3-Antistasi/functions/Base/fn_outpostDialog.sqf, A3-Antistasi/functions/CREATE/fn_createFIAOutposts2.sqf, A3-Antistasi/functions/Dialogs/fn_skiptime.sqf, A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf, A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf, A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf, A3-Antistasi/functions/REINF/fn_buildMinefield.sqf, A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/statSave/saveLoop.sqf
1. [X] Bug
Changed a lot of remoteExecCalls to remoteExec, mostly introduced erroneously by #620. None of the BIS_fnc_MP calls replaced there were unscheduled, and in some cases they call code that needs to be scheduled due to use of sleep or waituntil. Some detail:
1. UPSMON_fnc_setVehicleInit: Most of these were set to remoteExec anyway. I didn't check what it does, but it was scheduled before so it stays scheduled.
2. A3A_fnc_commsMP: Needs to be scheduled due to sleeps & waituntil. Not critical as it only spams text, but still a bug.
3. A3A_fnc_createOutpostsFIA: Needs to be scheduled due to sleeps. If not, FIA roadblocks break (see #710).
4. A3A_fnc_resourcesFIA: Uses waituntil to synchronize updates. Broken because other calls are scheduled, so they may overlap …
=> Change bogus remoteExecCalls to remoteExec

A3-Antistasi/Scripts/fn_advancedTowingInit.sqf
1. [X] Bug
When ropes are detached from a towed vehicle, the helper object wasn't detached from the vehicle before deleting it. This causes the vehicle to be left with null objects in its attachedObjects array. As the vehicle save code doesn't save anything with an attached object, these vehicles would not be saved if left near the HQ.
This fix simply detaches the helper object before it's deleted. I'm fairly sure that there are no side effects.
At least a partial fix for #692.
1. [X] No, but...
Could consider making the vehicle save code less restrictive. We'd need a reliable way to determine which objects should and shouldn't be saved, which requires a lot more testing than this bugfix.
=> Fix towed vehicles left with null attached objects

A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf, A3-Antistasi/functions/Garage/fn_garageVehicle.sqf, A3-Antistasi/functions/init/fn_initClient.sqf
1. [X] Bug
Fixed some trivial SP bugs:
1. Main UI garage button now redirects to the faction garage rather than blackholing.
2. SP difficulty setup code now waits for its server init dependencies.
3. SP player now gets the medic and engineer traits, as before.
closes #658 and #669 
1. [X] No
=> Fix some SP bugs

A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3-Antistasi/functions/REINF/fn_equipRebel.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
unlockedBackpacks includes static weapon, UAV and parachute backpacks. This is not suitable for the rebel AI backpack list, as they need to put gear in backpacks. I created a new subcategory (backpacksCargo) which generates allBackpacksCargo and unlockedBackpacksCargo lists.
`fn_equipmentSort` has some backpack sorting, but it doesn't use categories and so doesn't generate unlockedXXX lists. The method used also doesn't pick out small-cap backpacks or parachutes, so I used a maximumLoad threshold instead. I left the equipmentSort code unmodified, so there won't be any side effects.
Checked the new code against all RHS and vanilla backpacks, works as intended.
closes #722
1. [ ] No
`fn_equipRebel` may have line …
=> Create new category for cargo backpacks, use it for rebel AIs

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_init.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
1. [X] Bug
Several arsenal bugs, mostly related to loading loadouts:
1. Fixed a bug where the arsenal used 24 rather than Antistasi's minWeaps param as the guest limit.
2. Fixed a bug where weapon accessories bypassed the guest limit.
3. Fixed some potential bugs with negative bullet counts and off-by-ones.
4. Fixed a bug where grenades wouldn't be throwable after loading a loadout.
5. Fixed a bug where the magazine guest limit was counting in mags rather than bullets.
4 is arguably an Arma bug. `(vestContainer player) addItemCargo "HandGrenade"` demonstrates the problem, at least in vanilla. Not difficult to work around, but rather spoiled the attempt at code reduction.
closes #721, maybe others
1. [X] No, but:
I reckon …
=> Fix arsenal loadouts

A3-Antistasi/functions/AI/fn_airstrike.sqf
1. [X] Bug
When fn_airstrike is called with an airport marker as the target, it adjusts the target position based on the runway. As some airports on smaller maps (eg Malden airport_2) do not have runways, this breaks. I added a check for whether the airport has a runway, in which case the adjustment is bypassed.
closes #704 
1. [X] No, but
The runway detection functionality should really be moved into init code, and the data stored. Doesn't much matter for any current uses though.
=> Fix case where an airstrike targets an airport with no runway

A3-Antistasi/functions/AI/fn_captureX.sqf, A3-Antistasi/functions/AI/fn_interrogate.sqf, A3-Antistasi/functions/AI/fn_surrenderAction.sqf, A3-Antistasi/functions/Base/fn_flagaction.sqf
1. [X] Bug
Releasing a surrendered enemy used to work as described in #739. Non-militia occupants would reduce occupant aggro by 0.5 points each, while militia occupants and invaders would instead be given an offer to join the rebels, causing +1/+1 aggro and +1 HR.
This PR instead splits the release and recruit actions in the action menu, so either can be used on any surrendered enemy. Aggro reduction from releasing varies by faction (militia cause less than non-militia, invaders have little effect, as it's supposed to be very difficult to reduce invader aggro). Recruit chance also varies by faction (militia much easier than regular troops) while the aggro penalty is reduced to make it a more attractive early-game option.
I also made releasing or recruiting possible …
=> Separate release & recruit actions on surrendered enemies

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
1. [X] Bug
Fixed a bug introduced in #726 which caused some items to placed in the wrong uniform/vest/backpack container when loading a saved loadout.
closes #748 
1. [X] No
=> Fix loadout item scrambling

A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
Fuel trucks are no longer blocked from being automatically added to the civilian vehicles list.
closes #768 
1. [X] No
=> Re-enable spawning fuel trucks as civilian vehicles

A3-Antistasi/functions/Garage/fn_vehPlacementBegin.sqf, A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf
1. [X] Bug
- Both purchased and ungaraged boats can now be placed up to 150m from the marker.
- Boats no longer placed underwater or at non-upright angles.
closes #766
1. [X] No
=> Allow boats to be placed further from flags, place upright on surface

A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
1. [X] Bug
NATOcrate/CSATcrate function calls on ammo trucks removed from AIVEHInit. These functions are already called in the ammo truck mission, so the AIVEHInit calls only cause an exploit.
closes #784
1. [X] No
=> Fix loot exploit when ungaraging ammo trucks away from HQ

A3-Antistasi/statSave/saveLoop.sqf
1. [X] Bug
Ammo boxes left near the HQ were being saved. Because AIVEHInit doesn't touch ammo boxes (as it's also used for the full ones), they were not being cleared of default cargo on load, so were an easy way to unlock some items.
The poor code quality and spaghetti design remain unchanged. This is just a quick fix.
closes #754 
1. [X] No
=> Add ammo boxes to list of objects that shouldn't be saved near the HQ

A3-Antistasi/functions/Intel/fn_searchIntelOnLaptop.sqf
1. [X] Bug
Fixes a bug where the timeDiff calculation was reversed in the laptop search loop, causing the completion percentage to count backwards.
Also ensured that the diff value is at least 1 second, just in case `time` doesn't behave nicely in some situations. Documentation is insufficient to know whether it's necessary, but it won't hurt.
Quick fix for testing bug report.
1. [X] No
=> Fix negative laptop search time diff

A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
1. Replaced references to non-existent RHS M2A3 classnames.
2. Replaced reference to non-existent 3CB fuel truck classname.
3. Removed container from light unarmed vehicles. Assumed unintentional.
4. Added some sanity checking code to make this easier to debug in future.
The sanity checking is probably not complete, but it should be testing the vast majority of vehicle classnames.
closes #771, #772
1. [X] No
=> Fix bad classnames in 3CB templates

A3-Antistasi/functions/Intel/fn_searchIntelOnLaptop.sqf
1. [X] Bug
Information:
- Fixed the ending of pictures from .jpg to .paa
- Fixed a typo in the path of the complete.paa picture
- Reset the texture to the default one, if the players fail to download it
1. [X] No
Notes:
=> Fix picture endings for intel laptops

A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf
1. [X] Bug
- Fixed a group leak bug in rebel garrisons (first infantry group not deleted).
- Fixed a group leak bug in enemy outpost garrisons (mortar group not deleted).
- Made rebel garrisons only create groups as required, rather than 3 minimum.
- Cleaned up rebel garrison function a bit.
- Fixed a bug where all rebel garrison infantry were placed in one group.
- Accidentally fixed a bug where rebel garrisons weren't sent to UPSMON, causing them to stand around the flag like idiots. Now they patrol the area and/or snipe from buildings.
closes #793, plus maybe some old garrison patrol feature requests
1. [X] No
There are probably still group leak bugs though. There's one known with A3A_fnc_postmortem that's fixed in …
=> Fix rebel & outpost groups

A3-Antistasi/statSave/saveFuncs.sqf, A3-Antistasi/statSave/saveLoop.sqf
1. [x] Bug
Information: 
Vehicles now take into account its direction and rotation. This will help make sure vehicles don't explode if parked on another object.
closes #804
1. [ ] No
Notes:
Park vehicle on a brick wall or in a weird position. 
Save and reload.
Vehicle should spawn back in position without exploding. (should...)
=> [Save/Load] Changed how vehicle re-spawn orientation is handled to avoid clipping

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Convoy/fn_cleanConvoyMarker.sqf, A3-Antistasi/functions/Intel/fn_searchIntelOnLeader.sqf, A3-Antistasi/functions/Intel/fn_selectIntel.sqf, A3-Antistasi/functions/init/fn_resourcecheck.sqf
1. [X] Bug
Information:
Fixed multiple bugs in and around the intel system.
1) Added a function to clean the convoy marker array every tick or before a intel convoy reward is issued. The A3A_fnc_cleanConvoyMarker function checks all markers by checking if `getMarkerColor` returns anything besides "". The still existing markers are then saved again. This fixes an issue with a single convoy reward, which selected a marker that isn't there anymore and therefor doesn't show anything on the map. Furthermore it should stop the array from growing the whole time.
2) Fixed a missing call to add the "Search for Intel" action on squadleaders if the action has been aborted by the player. If the players abort the search now, the action is getting readded correctly.
3) Fixed the …
=> Fixed multiple bugs in intel rework

A3-Antistasi/functions/Base/fn_fogCheck.sqf
1. [X] Bug
With extreme inputs from fogParams, _fogViewDistance can have a value of zero due to floating-point underflow. This may cause a zero divisor error. This PR skips the final calculation in this case.
closes #810 
1. [X] No
=> Fix potential zero-divisor error in fogCheck

A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
1. [X] Bug
Removed AA planes from the random-aircraft pool in patrolCA. They'll still be used in the case where the rebels are using air vehicles.
I think the inclusion of AA planes here was a bug in the first place, as ground aircraft are already removed from the random pool. The AA planes often just circle at high altitude, unnecessarily spawning in rebel garrisons (at high perf cost) and confusing your AIs.   
closes #774
1. [X] No
=> Remove AA planes from random pool in patrolCA

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
This is an example method of adding manual overrides for items that are mis-categorized by mods. From a design perspective it may be preferable to put the table somewhere more obviously editable, or split it into chunks. It may be partially or wholly obsoleted depending on how the template system is implemented.
Table should currently include almost all miscategorized ACE, RHS and 3CB gear. IFA needs to be done. Some debatable decisions:
1. LSWs classified as MGs. Maybe a bit weedy.
2. Marksman rifles (eg M14 DMR) classified as sniper rifles, but battle rifles (eg M14) classified as rifles. Enfield & Kar98 classified as sniper rifles, because you wouldn't want your AI riflemen using them by choice.
3. Missile launchers classified by their primary purpose. …
=> Equipment category manual overrides

A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
1. [X] Bug
Apparently non-PhysX objects retain their current velocity forever when detached from another object, becoming lethal on contact. This could happen by dropping some HQ assets (tent, flag) while moving.
closes #834 
1. [X] No
=> Fix HQ objects becoming lethal if dropped while moving

A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf, A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_AT2_MTP.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_AT_MTP.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_MachineGunner_MTP.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_Marksman_MTP.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_Medic_MTP.sqf, A3-Antistasi/Templates/Loadouts/3CB_BAF_Teamleader_MTP.sqf
1. [x] Bug
Information:
Added 3CB MTP Loadouts:
AT/AT2/Teamleader get a L85A3, Holosights for AT, LDS x4 Scope for TL.
Marksman gets a weirdly named British DMR chambered in 7.62 and a x4 Scope.
Medics gets a weirdly British M4 with Holosight.
Machinegunner gets a British M249.
Added Calls for Loadouts in Both Templates.
Fixes 3CB BAF PVP for Tanoa:
Changed PVP vehicles to avoid Vanilla vehicles, they are the same as in Arid Template just in Green.
closes #XXXX
1. [x] Have you loaded the Mission in Local host?
1. [x] No
Notes:
=> 3CB Loadouts + small PVP Fixes.

A3-Antistasi/onPlayerRespawn.sqf
1. [X] Bug
There's a bug in BIS's curator script related to the #adminlogged mode where a link is retained to the player's old corpse, and when that's deleted, the (real) curator is unassigned. Only applies to hosted MP.
This patch works around the problem with a fairly direct route: Reassigning the curator to the hosting player shortly after the corpse is deleted. It can be removed if BIS fix their bug, or if we switch to creating and/or assigning the curator by script rather than relying on #adminlogged. The latter option would probably require a fair amount of work, including a UI.
closes #835
1. [X] No
=> Workaround for Zeus link lost when old corpse is deleted

A3-Antistasi/Templates/3CB_Inv_TKM_Arid.sqf, A3-Antistasi/Templates/3CB_Inv_UKN_Temp.sqf, A3-Antistasi/Templates/3CB_Inv_UKN_Trop.sqf
1. [X] Bug
3CB invader factions had a bogus classname for the flagpole, which caused it not to spawn, often preventing capture of locations.
closes #846
1. [X] No
Although these templates clearly haven't had much testing, so they may benefit from a second look.
=> Fix bogus classname for 3CB invader flagpole

A3-Antistasi/functions/init/fn_initServer.sqf
1. [X] Bug
Information: Added a default value for startWithLongRangeRadio for SP games Assumed to true due to two reasons
1) Default value in params.hpp is true
2) LR radios in SP are kinda useless anyways, so no need to block them
closes #799 
1. [X] No
Notes:
=> Fixed missing startWithLongRangeRadio parameter

A3-Antistasi/functions/Base/fn_healAndRepair.sqf
1. [X] Bug, probably
The vehicle box would repair occupied enemy vehicles, which is weird and probably unintentional. This PR restricts it to unoccupied vehicles and those currently controlled by the player team.
This depends on `side group _vehicle` working in a reasonable manner, which it seems to.
closes #824
1. [X] No
=> Restrict vehicle box repair to unoccupied and rebel vehicles

A3-Antistasi/functions/Base/fn_markerChange.sqf
1. [X] Bug
Winner/loser params passed to updateReinfState were backwards, causing cross-faction reinforcement convoys, including from rebel airports.    
closes #858
1. [X] No
=> Fix reversed winner/loser params in markerChange

.gitignore, A3-Antistasi/functions/Base/fn_mrkWIN.sqf
1. [X] Bug
Information:
- First I've updated `.gitignore` with the changes to ignore the Mission subfolders in the pictures subfolders.
- Second, i've moved some / changed some of the logic for `fn_mrkWIN` and it's logging.
No PR, this is in response to an RPT crash report from the Official server.
1. [ ] No
Notes:
I have run this on a dedicated MP server and without error captured an enemy Resource point. However with the additional tweaked logic some further testing will be required to ensure it is not miss-behaving.
```
0:28:44 "953.911: [Antistasi] | …
```
=> Quick fixes

A3-Antistasi/MissionDescription/params.hpp
1. [ ] Bug
3. [X] Something
Changed the fast travel and unlock count parameter descriptions as they confused a lot of people.
"Anywhere" isn't really ideal as it's actually "any rebel-held location", but the latter is a bit long for a parameter value. Couldn't think of a better way to phrase this. Someone else might.
closes #869 
1. [X] No
Params could do with a reorganisation, but now is not the time.
=> Fix misleading descriptions of fast travel and unlock count params

A3-Antistasi/functions/Revive/fn_handleDamage.sqf
1. [ ] Bug
3. [X] Feature removal
The TK check had a check for whether the player was wearing an enemy uniform. However, none of the current data is sufficient for an accurate test:
- allRebelUniforms does not always contain uniforms of the player units or rebel AIs.
- Blufor guerrilla uniforms are currently used for greenfor, so uniform side is not a valid check.
This PR removes the uniform check so that all rebel TK incidents are now considered a TK, regardless of uniform worn.
Alternative solutions that don't remove the uniform check are possible, but would require feedback:
1. Fix allRebelUniforms so that it includes all valid rebel uniforms for each case, preferably without using both greenfor and blufor guerrilla uniforms (to avoid arsenal dupes). Ensure that all …
=> Remove TK uniform check due to uniform inconsistency

A3-Antistasi/Stringtable.xml, A3-Antistasi/functions.hpp, A3-Antistasi/functions/AI/fn_surrenderAction.sqf, A3-Antistasi/functions/REINF/fn_postmortem.sqf
1. [X] Bug
Information:
Added Debug logging and some null catches to determine if bad UNIT's are being passed to the script.
closes #589 
1. [ ] No
Notes:
In my testing something did pass through a null unit value to the Postmortem script, however it was caught by the new `exitwith` I have added early on. Finding out what is causing this would be ideal.
=> Add debug for PostMortem and SurrenderAction Call

A3-Antistasi/dialogs.hpp
1. [X] Bug
Spawn distance reduction button was broken in the customHint patch by misplaced quotes. Fixed that, and removed some redundant checks to make it slightly less unreadable.
closes #884
1. [X] No
=> Fix bug in spawn distance reduction button

A3-Antistasi/functions/Intel/fn_selectIntel.sqf
1. [X] Bug
The TIME_LEFT intel option attempted to use the non-public time-until-next-tick value (nextTick). This PR changes it to return an approximated version of the time until the next attack (countCA) instead, which is already public and is a bit more useful. The ticks are always 10 minutes apart but the attack timer has much more variation.
Note that the attacking side currently isn't determined until the attack is launched, so the side parameter isn't used.
closes #874
1. [X] No
=> Change TIME_LEFT intel option to return approx time until next attack

A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf
1. [X] Bug
randomRifle assumed that all grenade launchers were also rifles, and so have multiple muzzles, which is no longer true since the category override patch where weapons like the M79 and M320 are not classed as grenade launchers. This PR handles the case where the grenade launcher is just a grenade launcher.
closes #913
1. [X] No
Should really add some better handling for how much ammunition to add though. Five grenades is going to be a bit miserable for a non-rifle GL. Best method is probably weight-based, so it'd take some work.
=> Fix error when rebels equip a grenade launcher that's not a rifle

A3-Antistasi/functions/Save/fn_savePlayer.sqf
1. [X] Bug
The savePlayer code attempts to determine the monetary value of each unit in the player's group, but doesn't correctly handle the nil case where a unit has no value. This could be caused by abusing ACE group join, or possibly by other methods.
closes #908 
1. [ ] No
This functionality appears to be a giant exploit. Players gain the monetary value of any non-player units and vehicles in their group, regardless of who purchased them. This might make some sense if the player saves were simultaneous and the group leader received the resources, but currently players are only saved on disconnection or when personally using the map board.
=> Fix savePlayer error caused by group member without a value

A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf
1. [X] Bug
Removed the patrol heli from the attack heli array in the blufor 3CB TKA template. Antistasi makes assumptions in several places that the attack heli array doesn't contain the patrol heli. 
I can't prove that this fixes #905, but it's the only possibility I can find. The theoretical problem is that attack helis are a limited resource, so it was possible for patrolCA to build a _vehPool that contained no air transport vehicles. Normally the patrol heli is guaranteed to be in _vehPool.
closes #905
1. [X] No
=> Remove patrol heli from attack heli array in 3CB TKA template

A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf
1. [X] Bug
1. Fixed a bug where the traitor could only surrender when dead.
2. Fixed a group-leak bug in the surrender path (join grpNull creates a group).
3. Fixed a syntax error in the traitor group despawn.
I decided to leave the traitor to the surrender despawn logic, as it's cheaper than running one of those sleep 1 distance-check things forever. He'll disappear into the void after an hour.
closes #904 
1. [X] No
=> Fix traitor mission despawn and surrender bugs

A3-Antistasi/functions/Ammunition/fn_CSATCrate.sqf, A3-Antistasi/functions/Ammunition/fn_NATOCrate.sqf
1. [ ] Bug
Information:added optional arguments for NATO- CSATcrate
new NATO- CSATcrate arguments
[object, //required
WeapTypes, WeapNum, //opt
ItemTypes, ItemNum, //opt
AmmoTypes, AmmoNum, //opt
ExplosiveTypes, ExplosiveNum, //opt
AttachmentTypes, AttachmentNum, //opt
BackpackTypes, BackpackNum, //opt
HelmetTypes, HelmetNum, //opt
VestTypes, VestNum, //opt
DeviceTypes, DeviceNum //opt
] call A3A_fnc_NATOcrate;
example:
[cursorTarget,
1, 100,
0, 0,
0, 0,
0, 0,
0, 0,
0, 0,
0, 0,
0, 0,
0, 0
] call A3A_fnc_NATOcrate;
would spawn up to 100 of 1 type of weapon, and coresponding ammo
[cursorTarget] call A3A_fnc_NATOcrate; //would spawn default ammocrate
Why?
i needed this to specify what loot to add to crate in Salvage mission.
This change allows me to specify which type of …
=> NATO/CSATcrate added optional arguments v2.0

A3-Antistasi/functions/init/fn_initClient.sqf
1. [X] Bug
Apparently someone had a brain glitch and set the remoteExec for "AI Load Info" to target 4 instead of 2. Fixed. Tested with two HCs, seems to work correctly.
closes #735
1. [X] No
=> Fix AI Load Info remoteExec targeted on wrong machine

A3-Antistasi/functions/Missions/fn_underAttack.sqf, A3-Antistasi/functions/Revive/fn_handleDamage.sqf, A3-Antistasi/functions/Revive/fn_handleDamageAAF.sqf, A3-Antistasi/functions/Revive/fn_unconscious.sqf, A3-Antistasi/functions/Revive/fn_unconsciousAAF.sqf
1. [X] Bug
Contact report tasks for locations were triggered by the unconscious handlers, which are no longer called when ACE medical is running. This PR moves them to the damage handlers instead, and adds a timeout so that they no longer stick around on the map until the location is despawned.    
Because the damage handler and task update are often running on different machines, the synchronization is not perfect and the occasional shooting incident will be missed. There are more accurate methods than I used here, but as alert accuracy isn't important or even realistic, I prioritized complexity and performance.
closes #882
1. [X] No
=> Reimplement contact reports with timeout

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/AI/fn_airbomb.sqf, A3-Antistasi/functions/REINF/fn_NATObomb.sqf
1. [ ] Bug
3. [x] Change
Information:
Halved the bomb count, now 4 for AI and 2 for rebel.
Rework bomb type detection, it is now modular if we get more ideas.
Removed redundant drop inaccuracy, was only used because the plane was dropping the 
sub-munitions directly.
Removed 2 unused variables, _carpet and _cluster.
Adds comment explaining the point of _bomba
closes:
#524 
#546 
1. [ ] No
Notes:
=> Airstrike sanity

A3-Antistasi/functions/OrgPlayers/fn_tierCheck.sqf, A3-Antistasi/functions/Save/fn_loadServer.sqf
1. [ ] Bug
The old war level calculation is purely dependent on the count of locations captured, with no adjustment for map size. This PR changes the calculation. Features:
1. Hits war level 10 with 70% of the island captured.
2. Calculation is non-linear so that lower war levels are still triggered early.
3. War level contribution of cities reduced to make the mass flips less punishing.
4. Factories now included. Probably an old bug that they weren't.
The non-linearity is currently critical, because until war level 2, reb vs gov vs inv acts like reb vs gov, where every attack will be launched against rebels. Makes it very difficult to hold territory at war level 1. I could disable major attacks at war level 1, but then you'd have people thinking it's a great idea to …
=> New war level calculation

A3-Antistasi/Templates/3CB_Occ_TKA_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf
1. [x] Bug
Information:
vehSDKLightUnarmed to an existing classname , fitting to the rest of the UN Vehicles.
Fixed the Typo in SDKMortar
changed Flag texture to be the same as on the Flag.
Changed Civcar from Bus to Open Hilux.
Changed SDKbike from Golf to Quadbike.
Changed Civcar from Bus to Open Hilux.
Changed SDKbike from Golf to Quadbike.
Swaped Blue UAVs for Greenfor onces.
Changed Bluefors Tropical Quadbike to an Independant one.
closes #XXXX
1. [x] No
Notes:
Fixes this report from 2.2.2 Bugs report channel
=> 3CB Classname Fixes/Civcar changes

A3-Antistasi/functions/Base/fn_mrkUpdate.sqf, A3-Antistasi/functions/init/fn_initGarrisons.sqf
Updated airbase markers to be deafult color, this is done to improve "readability" of the markers
1. [ ] Bug
Information:Updated airbase markers to be deafult color, this is done to improve "readability" of the markers
https://drive.google.com/open?id=1XxQFud57tw4hQiBgZyNY_BNA6J5eD8u2
closes #901
1. [x] No
Notes:
=> Updated airbase markers to be default colour

A3-Antistasi/Templates/Loadouts/rhs_afrf_teamLeader.sqf
No other RHS loadout has the TL with LAT, nor on 3CB.
1. [ ] Bug
3. [x] Balance tweak
Information:
Removed RPG-26 from AFRF TL Loadout
closes none
1. [x] No
Notes:
=> Remove LAT from RHS AFRF TL

A3-Antistasi/functions/Base/fn_mrkUpdate.sqf
1. [X] Bug
Fixed typo in #925 that throws RPT errors and prevents some invader markers from having their colours set correctly.
Possibly related to #954. Not clear.
1. [X] No
=> Fix marker colour-setting typo in mrkUpdate

A3-Antistasi/functions/REINF/fn_addBombRun.sqf
1. [X] Bug
It was possible to farm infinite airstrike points by unlocking a UAV backpack and then converting the assembled UAVs. This PR adds a check for whether an aircraft can be disassembled.    
closes #958
1. [X] No
=> Prevent backpack drones from being used to farm airstrike points

A3-Antistasi/functions/AI/fn_surrenderAction.sqf
1. [X] Bug
On creation, JNL load actions are currently added to surrender crates. These crates aren't supported by JNL and so using the action generates errors. This PR removes the JNL load action from these crates.
While JNL can be easily adapted to support this crate type, surrender crates are currently automatically deleted after an hour, so using them with JNL could cause serious problems.
closes #910 
1. [X] No
=> Prevent bogus JNL load action being added to surrender crates

A3-Antistasi/functions/Utility/fn_log.sqf
1. [ ] Bug
3. [X] Whatever
Implemented design specified in #891. It doesn't actually do much yet because most of the HC functions currently use direct diag_log calls rather than A3A_fnc_log.
closes #757, #891.
1. [X] No
=> Change logging function to default to logging to server

A3-Antistasi/functions/CREATE/fn_patrolCA.sqf, A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf
1. [ ] Bug
Port the logging code in patrolReinf and patrolCA from diag_log to A3A_fnc_log, so that they can be logged to server in combination with #966.
Also added lines to log the vehicle types sent, when log level is set to debug or higher.
In combination with #966, closes #740
1. [X] No
=> Port patrolReinf and patrolCA logging to A3A_fnc_log

A3-Antistasi/functions/AI/fn_mortyAI.sqf
1. [X] Bug
In some cases, the non-gunner of a mortar team will attempt to board the mortar, causing the Antistasi mortar loop to think the squad has been given a move order. How to reproduce:
- Buy a two-man mortar team with no quadbike in RHS greenfor. Might also happen with other cases where the mortar has two seats.
- Using high command, order them to move to a position at least 300m away (minimum not known, probably closer to 200m, but short distances do not work).
- Once they arrive, the mortar team will now continually unpack and repack the mortar (they're actually creating a new mortar vehicle each time, but that's what it looks like). Once in this state, they'll never set up the mortar correctly regardless of future move distances or waypoint clearance.
Removing …
=> Work around probable Arma bug causing mortar unpack/repack loop

A3-Antistasi/JeroenArsenal/JNL/Actions/fn_logistics_addActionLoad.sqf
1. [X] Bug
Loot crates could be loaded into vehicles without breaking undercover, so it was straightforward to farm them in the early game by driving in with civvie clothes and an offroad/truck. This PR breaks undercover when a JNL crate is loaded.
The local setCaptive should be fine here, as the player is always local to an addAction.
closes #971
1. [X] No
=> Fix exploit where crates could be loaded into a vehicle while undercover

A3-Antistasi/functions/Base/fn_buildHQ.sqf, A3-Antistasi/functions/Base/fn_createPetros.sqf, A3-Antistasi/functions/Base/fn_moveHQ.sqf, A3-Antistasi/functions/Dialogs/fn_moveHQObject.sqf
1. [X] Bug
- Enabled placing HQ objects on nearest surface.
- Fixed an issue where Petros remained local to player after building HQ.
- Fixed an issue where attached Petros could disappear if move HQ option was used.
- Fixed an issue where Petros wouldn't move when moving HQ the second time.
- Cleaned up some unnecessary JIPs.
closes #976, plus possibly some reported cases where Petros disappears if the commander disconnects.
1. [X] No
=> Various Petros & moveHQObject fixes

A3-Antistasi/functions/OrgPlayers/fn_assignBossIfNone.sqf, A3-Antistasi/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf, A3-Antistasi/functions/OrgPlayers/fn_theBossTransfer.sqf, A3-Antistasi/onPlayerRespawn.sqf
1. [X] Bug
- Fixed bug where theBossTransfer wasn't being remoteExec'd in onPlayerRespawn, causing the commander role to end up on a corpse after a respawn.
- Added silent mode to theBossTransfer so that corpse transfers aren't broadcast.
- Improved logging output of commander transfer functions.
closes #995
1. [X] No
=> Fix boss loss on respawn and clean up logging

A3-Antistasi/functions/init/fn_initClient.sqf
1. [ ] Bug
Information: Added "ace_common_fnc_claim" to VehicleBox in Fn_InitClient, since its only Important to disable Ace actions on Clients since noone else can Interact with the Box it should work on All Players.
--------> Adding it in the Init of VehicleBox in the Missions could also work but thats pretty annoying to edit and 1 times per Map instead of once in Initclient.
Ignore Line 345,353,390,500 that seems to be Atom fighting random Spaces.
closes #948 
1. [ ] No
I havent had any Errors during my testing and it disabled Ace Interactions completly as intended, in Theory it should work on all Clients …
=> Remove Ace Interaction on VehicleBox

A3-Antistasi/functions/init/fn_initClient.sqf
Changes the start money from 100 to 95 to prevent endless money exploit.
1. [x] Bug
Information:
Changes start money value from 100 to 95 to avoid the money exploid. Now people have to go kill first before they have enough money to give it away.   
closes #1021 
1. [ ] No
Notes:
=> Update start money

A3-Antistasi/MissionDescription/endMission.hpp
1. [ ] Bug
Information:
Added IFA to the text shown to the players when the load an incompatible mod.
None, it is linked to #1000
1. [X] No
Notes: Just a change in a string, it literally can't break anything
=> Add ifa to mod not allowed description

A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [X] Bug
Bad algorithm in initGarrisons (overwriting of input params) caused some outpost and airport markers to have the wrong side name on initialization. This PR fixes it. There were no side effects, so this wouldn't have been causing any of the mixed-side bugs.
closes #756
1. [X] No
=> Fix outpost and airport markers initializing with wrong side name

A3-Antistasi/Templates/RHS_Reb_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_CDF_Wdl.sqf
1. [x] Bug
Information: Changed SDKMortarSmokeMag from HE to a Smoke Mortar Round
The 8 Rounds are the highest amount possible in that Mortar, there is no RHS Variant it uses Vanilla
closes #1005 
1. [x] No
Notes:
It only has Happend in Reb_CDF Templates.
=> "SDKMortarSmokeMag" Fix for Reb_CDF

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_repairRuinedBuilding.sqf, A3-Antistasi/functions/Base/fn_requestDataFromServer.sqf, A3-Antistasi/functions/Base/fn_setDataOnClient.sqf, A3-Antistasi/functions/Save/fn_loadServer.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
3. [X] Armaaaaa
A speculative workaround for a potential Arma bug with the synchronization of destroyed buildings. Currently we JIP-remoteExec hideObject for each building that was destroyed at server start, and we have an additional fix (`fn_installSchrodingersBuildingFix`) for the case where a building is destroyed while a client is connected but not correctly updated on all clients.
This PR covers a third case where a building is destroyed after server load but before a specific client joins. The current destroyedBuildings list is sent to each client on connection, and the client then hides those buildings. The list is sent using a request/send system to avoid unnecessary publicVariable spam on building destruction. As the remoteExec count is much lower, …
=> Speculative workaround for remaining schrodinger's buildings

A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf, A3-Antistasi/functions/OrgPlayers/fn_donateMoney.sqf, A3-Antistasi/functions/OrgPlayers/fn_playerScoreAdd.sqf, A3-Antistasi/functions/OrgPlayers/fn_resourcesPlayer.sqf, A3-Antistasi/functions/OrgPlayers/fn_theBossSteal.sqf, A3-Antistasi/functions/REINF/fn_buildCreateVehicleCallback.sqf, A3-Antistasi/functions/REINF/fn_reinfPlayer.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Save/fn_savePlayer.sqf, A3-Antistasi/functions/Save/fn_setStatVariable.sqf, A3-Antistasi/onPlayerRespawn.sqf
1. [X] Bug
Fix various player money exploits involving saving with AIs and vehicles. Players used to have their squad-owned vehicles and AIs refunded whenever they disconnected or saved, but these vehicles were not deleted so you could simply disconnect and reconnect to farm money.
Players are now saved during a global save (they weren't before), and their owned units are refunded during that save, but not if they disconnect or save manually. I think it's still a bit generous to players (you get full purchase value for vehicles, not sale value), but it'll be lightly used and it'll do for now. There's a fair argument for simply removing the refund code entirely.
As it'll be saving some extra data, I sorted out the saveProfileNamespace usage in the first commit. This was …
=> Fix savegame player money exploits and profilenamespace spam

A3-Antistasi/cba_settings.sqf
Got rid of "force TF_default_radioVolume = 8.5;" as it's blowing peoples ears out.
1. [ ] Bug
3. [x] Change
Information:
closes #1057 
1. [x] No
Notes:
=> Get rid of forced default TFAR radio volume

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/REINF/fn_FIAinit.sqf
1. [X] Bug
Some old code that I missed was preventing #1015 from working correctly on a dedicated server:
- Players were already being saved by the server->client->server route, now removed.
- FIAinit wasn't setting the unit ownership globally for player squad recruits.    
closes #1055 
1. [X] No
=> Fix double player save and DS refund bugs

A3-Antistasi/Templates/BAF_Occ_BAF_Arid.sqf, A3-Antistasi/Templates/BAF_Occ_BAF_Trop.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
Information:
**Both Templates:**
Changed PVP Vehicle on BAF from the HMG Landrover to GPMG Husky.
------> More Armor less Penetration power. AND Most importantly No Javelin in the Inventory.
Added Husky Mraps in GPMG, HMG and GMG Sand/Green.
Added FV510 Warriors in all Variantions in Sand/Green.
Added 2 Merlins (DDPM_RM and Tropcial_RM) to VehFastrope
**Tropcial Template:**
Added Call for Woodland Maps, those will use the Tropical Template since we dont have actual Woodland now, it does fit pretty well tho.
Changed M109 SPA to Woodland Variant.
**Arid Template:**
Changed the Spotter L129 to L85 due to L129 getting a wrong Rifle and wrong Magazines by Classname.
Changed Hercules C3 to DDPM Variant. To Prevent Vanilla Nato Units
Changed Merlin HC3 to DDPM …
=> 3CB BAF Additions

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/functions/Templates/fn_aceModCompat.sqf, A3-Antistasi/functions/Templates/fn_getLoadout.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
1. [ ] Bug
Information: 
**Added**
Handthrown Flares to Acecompat file ------> Added to Starting Gear.
Added a White Flashlight to Starting Gear Items Aswell (Inventory Flashlight)
Added 2 Flashlights for Vanilla, Pistol Flashlight and SMG Flashlight so they would be availble for the current starting Gear.
Added "UK3CB_BAF_Flashlight_L105A1" to 3CB Reb Templates.
**Changed**
"UK3CB_BAF_L107A1" to "UK3CB_BAF_L117A2" The A2 does Support a Flashlight, the other one didnt.
**Removed**
ADV Detection
ADV Items that would have been given.
closes #1033 
closes #635 
1. [X] No …
=> Starting Gear for Night/Removed ADV

A3-Antistasi/functions/Base/fn_garbageCleaner.sqf
1. [ ] Bug
Garbage cleaner left a lot of junk untouched. This should remove most of it. Stuff now removed:
- Surrender boxes
- Drone drop leaflets
- Ejection seats (vanilla and RHS at least)
- ACE bodybags and spraycan tags
- ACE and GRAD trenches, if no rebel spawners are within 200m
closes #850 
1. [X] No
=> Remove more junk in the garbage cleaner

A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
1. [ ] Bug
Information: 
Due to the Great Autodetection if X DLC are enabled/Gmob is loaded the Following Uniforms will be worn by Civilians and are Availible in the Starting Arsenal:
(List of AllCivilianUniforms with all DLCs enabled)
["U_C_Poloshirt_blue",
"U_C_Poloshirt_burgundy",
"U_C_Poloshirt_stripped",
"U_C_Poloshirt_tricolour",
"U_C_Poloshirt_salmon",
"U_C_Poloshirt_redwhite",
"U_OrestesBody",
"U_C_Poor_1",
"U_C_WorkerCoveralls",
"U_C_HunterBody_grn",
"U_C_Journalist",
"U_C_Scientist",
"U_C_Driver_1",
"U_C_Driver_2",
"U_C_Driver_3",
"U_C_Driver_4",
"U_Marshal",
"U_C_Driver_1_black",
"U_C_Driver_1_blue",
"U_C_Driver_1_green",
"U_C_Driver_1_red",
"U_C_Driver_1_white",
"U_C_Driver_1_yellow",
"U_C_Driver_1_orange",
"U_C_man_sport_1_F",
"U_C_man_sport_2_F", …
=> Civilian Uniform removal

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_itemType.sqf
1. [ ] Bug
3. [X] 3CB misfeature workaround
3CB vehicles expose their ammunition to the inventory system, which means that the arsenal ammunition transfer action will strip it all, throwing away the vehicle-specific ammo because it doesn't have a proper magazine type.
Tried to fix this in #1059 by not moving the vehicle ammo, but because all inventory is cleared from vehicle when they're pulled from the garage, and the vehicle box rearm doesn't work on inventory ammunition, the problem vehicles would be impossible to rearm once garaged.
This PR instead changes JNA to accept all magazine types, not just a fixed list, so that you can at least use the vehicle arsenal to rearm 3CB vehicles. I can't think of any negative side effects.
closes #959
1. [X] No
2. [ ] Yes (Please …
=> Change JNA to accept all magazine types

A3-Antistasi/functions/Ammunition/fn_ammunitionTransfer.sqf, A3-Antistasi/functions/Ammunition/fn_empty.sqf
1. [ ] Bug
The cargo-to-arsenal transfer action only works on ammoboxes and land vehicles. This PR extends the check to planes and helicopters.
I removed UAVs from the check, to prevent trolling by hiding small UAVs near the arsenal and blocking arsenal transfers.
Also added some feedback about which vehicle has been selected for the transfer.
closes #1063
1. [X] No
=> Enable cargo-to-arsenal transfer for planes and helis

A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf
- Enhancement
Information:
Outpost trucks no longer require a road in proximity to permit spawning. Note: Before this change, there was no use of road position.
closes [#1051](https://github.com/official-antistasi-community/A3-Antistasi/issues/1051#issue-623669534)
- Have you loaded the Mission in Singleplayer?
- Yes (Please provide further detail below.)
Notes:
I have not noticed any side effects as of yet.
=> Road requirement removed from outpost trucks.

A3-Antistasi/functions/Ammunition/fn_itemSort.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
Information:
This will add Flight Suits (Pilot Coveralls [AAF]/Pilot Coveralls [NATO]) to Airport crates.
They are useful to withstand higher G-Forces with Ace.
With the Help of Hakon i added "flyGear" to InitVarserver, fn_itemSort and to fn_createAIAirplane.
Added the same Check as diveGear has for Side.
Made the Amount of Uniforms random, minimum is 5, Maximum is 15.
closes #1027 
1. [ ] No
---------> Tweaking of the Amount of Pilot suits.
Notes:
=> Add Flight Suit to Airport Crates

A3-Antistasi/functions/Missions/fn_convoy.sqf
1. [ X ] Bug
- Fixed convoys _always_ immediately departing. There was a line (maybe left over from debugging?) setting the timer to 0 every time.
- The chance of immediately departing was also seemingly double the intended one - the base chance calculated from the war level, on top of the 0-10 minute rnd. I modified that to 5-10 minutes, but of course that can be omitted if it was actually intentional!
closes #1064 
1. [ X ] Have you loaded the Mission in Singleplayer?
2. [ X ] Have you loaded the Mission in a Dedicated Server?
1. [ X ] No
=> Convoy depart timer fix

A3-Antistasi/functions/Punishment/fn_punishment_checkStatus.sqf
* Enhancement
Information:
fn_punishment)checkStatus uses correct logging format.
No longer logs when checking AI.
closes [#1084](https://github.com/official-antistasi-community/A3-Antistasi/issues/1084)
* ~ Have you loaded the Mission in Singleplayer?~
Notes:
=> No longer logs when checkStatus on AI.

A3-Antistasi/functions/AI/fn_artySupport.sqf
##What type of PR is this.
1. [x] Bug
Information:
Fixed a spelling error in the artillery support function.
Atry ---> Artillery
Arty ---> Artillery (I know, not a spelling error, but still)
closes #1064 
1. [x] No
Notes:
=> fn_artySupport spelling error

A3-Antistasi/Templates/RHS_Occ_USAF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_USAF_Wdl.sqf
1. [x] Bug
Information:
Since we had this mixed Mess of Template for Multiple versions and 2.2.2 being pretty close to be Done we could Finally have Full Camo Templates, thats why this PR exists.
**Arid Template:**
Call for Woodland Maps.
**PVP Vehicles**
Changed the MRZR4 to the Mud Variant
Added M124A1 with M240 (M-ATV/Hunter) ------> Less fire Power more Armor, similar to 3CB BAF Husky.
**Both Templates**
Changed Vehicles to be Tan/Woodland for their Specific Template.
**Infantry Units**
Changed SARC Medical to a Normal one since that Array is not part of any kind of Special Forces.
**vehNATOLightArmed**
Added M1240 as M240, Mk19 and M2 Variant.
**vehNATOLightUnarmed**
Added M1240 Unarmed Variant.
**vehNATOTrucks**
Matched Cases for all Classnames.
**vehNATOAPC** …
=> RHS-USAF-Template Update Full Camo.

A3-Antistasi/functions/Base/fn_getVehiclePoolForAttacks.sqf, A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf
If thats not the case, something strange is happening and more information are needed to solve that
1. [X] Bug
Information:
Fixed an edge case when a vehicle array is defined but empty for a modset, resulting in the vehicle pool selection code crashing. 
I added a check if the amount of vehicles is equal zero and if so, the code will log it. Added further logs to find out the array in question.
If that is not the reason for the issue, the new logs should improve debugging abilities.
closes #1126 (hopefully)
1. [X] No
Notes:
=> Fixed edge case when vehicle array is empty

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
1. [X] Bug
JNA assumes that removing and then adding identical magazines will cause loadBackpack to return the same value as before. Depending on the exact items in the backpack, this is not always true.
This causes an exploit where a player can indefinitely increase the number of magazines in the arsenal.
closes #1142
1. [X] No
=> Fix arsenal item removal exploit

A3-Antistasi/functions/Ammunition/fn_itemSort.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_createAISite.sqf
1. [x] Bug
Information:
**Removed**
Rebreathers and Diving Googles from **fn_createAIOutposts.sqf** line 331-337 and from
**fn_createAISite.sqf** line 87-91
**Added**
A Sleep to ensure that diveGear applies, it did improve spawning during my Tests.
**Added**
A bit of Randomisation lowest is 2 Middle is roughly 6 Max is 8.
Seaports are usually more Common than Airbases on some Maps and they tend to be captured multiple times so thats why i set the Amount is a bit lower than flyGear.
closes #1151 
1. [x] No
Notes: If you have any Ideas how to do it better …
=> Improve diveGear spawning.

A3-Antistasi/functions/Convoy/fn_createConvoy.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf
1. [ ] Bug
Information: Changed the text shown for the reinforcements convoys once the GPS data is found as intel reward. It now shows like
[GPS-645] NATO reinforcement convoy
The number is the same as the one used in the logs and only for debug purposes (looks cool tho), the remaining information are for the players to know what they are fighting
closes #1064 
1. [ ] No
Notes: Needs to be started once, working from my laptop
=> Improved the text for reinforcements convoys, so they are less confusing

A3-Antistasi/functions/Pathfinding/fn_loadNavGrid.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/functions/init/fn_initZones.sqf
1. [X] Bug
The navGrid and other generated data used by A3A_fnc_findPath was only loaded on the server, but the convoy missions use findPath and run on HCs. The main use was new reinforcement convoys, which are only executed on the server for some reason.
This PR loads and generates the navGrid data on HCs as well. Also cleaned up the code and disabled the section that was spamming 400 invisible markers to all clients.
One thing I didn't change is that the function expects the navGrid file to have the first letter of the world name uppercased, but some of the navgrid files have all-lowercase world names. This works fine on Windows but may be an issue on Linux servers.
closes #1121
1. [X] No
=> navGrid loading fixes and cleanup

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_milBuildings.sqf
1. [X] Bug
- Fixed statics being placed in destroyed buildings.
- Fixed misplaced statics where building is placed on rough terrain.
- Refactored milBuildings to reduce code duplication.
- Fixed case where NATOinit was called twice on airport static crew.
closes #1123
1. [X] No
Positions 11 and 13 in the large towers are pretty shaky though, as the flat floor area isn't large enough for the statics and they often end up hanging at an angle. Tempted to switch them to other positions.
=> Various fixes for building-placed static weapons

A3-Antistasi/functions/Base/fn_addActionBreachVehicle.sqf, A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf
1. [X] Bug
AA vehicles look a lot like APCs but weren't breachable. This was confusing and probably unintentional. This patch makes them breachable like APCs. Also fixed a couple of issues with the breach results:
- Aggro was being added twice, once for the breach and once for the capture.
- SurrenderAction on crew wasn't being called locally to the targets.
closes #1128 
1. [X] No
=> Make AA vehicles breachable plus fixes

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf, A3-Antistasi/functions/Ammunition/fn_randomRifle.sqf, A3-Antistasi/functions/Base/fn_startBreachVehicle.sqf, A3-Antistasi/functions/CREATE/fn_NATOinit.sqf
1. [X] Bug
Some functions (mostly in the arsenal code) were using local-only inventory modification functions, causing a class of exploits where the player's loadout as saved on the server could contain several times as many magazines as expected. This PR fixes most of them.
I marked a couple of minor cases rather than fixing them, as they have very limited effects due to AI-only use, and will be obsoleted by the template overhaul.
closes #1169 
1. [X] No
=> Fix incorrect uses of local-only inventory modification functions

A3-Antistasi/REINF/addToGarrison.sqf
1. [x] Bug
Information:
added a block to prevent re adding units that are already assigned to a garrison
closes #1177
1. [x] No
Notes:
=> added block if units are already in a garrison

A3-Antistasi/functions/AI/fn_airstrike.sqf
1. [X] Bug
Rewritten the airstrike despawn code, because it was completely broken. The waypoint statements were deleting the pilot but not the aircraft, which caused the current waypoint to stick at 3 and so the rest of the termination code was never executed if the plane survived the impact with the ground.
Also added the airstrike aircraft to AIVEHInit, to make it worth shooting them down. Previously it had no effect on the vehicle pool or aggro.
closes #1181
1. [X] No
=> Make airstrikes despawn correctly after reaching their final waypoint

A3-Antistasi/functions.hpp, A3-Antistasi/functions/AI/fn_AIreactOnKill.sqf, A3-Antistasi/functions/AI/fn_attackDrillAI.sqf, A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/CREATE/fn_cargoSeats.sqf, A3-Antistasi/functions/CREATE/fn_createQRF.sqf, A3-Antistasi/functions/CREATE/fn_patrolCA.sqf, A3-Antistasi/functions/CREATE/fn_updateCAMark.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [X] Bug
2. [X] Change
A synchronization bug in patrolCA was causing multiple patrolCAs to be sent to the same location. It's an old bug but was far more obvious with six vehicles per patrolCA.
This was resolved by splitting patrolCA into decision and execution functions. The decision part (still called patrolCA) is server-only and strictly fenced, so it won't start examining a second patrolCA request until the previous one has been decided. This function calls createQRF to handle the actual spawning and management of the QRFs, or launches airstrikes itself.
The underlying logic is mostly unchanged, except for some bugs discovered although the way and some mostly-uncontroversial balance changes:
- Halved the vehicle count of position-target patrolCAs (they're now 1-3 …
=> Split patrolCA into decision & execution functions

A3-Antistasi/REINF/controlHCsquad.sqf, A3-Antistasi/REINF/controlunit.sqf, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf, A3-Antistasi/functions/Punishment/fn_punishment_notPlayer.sqf, A3-Antistasi/functions/REINF/fn_build.sqf
* Change
* Enhancement
Information:
> some moments EH's return objNull
> and other moments return random numbers
> it all depends on the moon and the stars
> for the universe does not define TRACE
fn_punishment_addEH:<br/>
Player checks at EH level now check `typeName` before `isPlayer` to ensure that no unexpected errors will be thrown.
added fn_punishment_notPlauyr;
closes [#1201](https://github.com/official-antistasi-community/A3-Antistasi/issues/1201)
closes [#1204](https://github.com/official-antistasi-community/A3-Antistasi/issues/1204)
Needs dedicated server test.
Steps: 
1. Run game
2. Shoot friendly x3
3. Should be in the ocean.
4. Admin should be notified
5. Should be released automatically.
6. Repeat above for a bit and see if the …
=> punishment_notPlayer does EH-lvl obj checks.

A3-Antistasi/functions/init/fn_initClient.sqf
1. [X] Bug
2. [ ] Change
The code in initClient to acquire the destroyedBuildings array on startup doesn't wait for serverInitDone, so it's likely to acquire an empty (incorrect) array for early-connecting clients (including HCs) because the server won't have loaded the saved game yet. This PR fixes it.
closes #1214 
3. [X] Have you loaded the mission on a dedicated server?
4. [X] Have you loaded the mission on a dedicated server with HCs?
1. [X] No
=> DestroyedBuildings non-JIP fix

A3-Antistasi/functions/init/fn_initClient.sqf
1. [X] Bug?
2. [ ] Change
Version of #1190 that works on clients other than the server host. Removes ACE group join action from all rebel unit types to prevent players joining HC and garrison groups. 
I forgot exactly why we're doing this, although there are several related exploits and breakages that can result from joining HC groups or garrisons. There should be an issue but I can't find one.
I'm assuming that all playable rebel unit types are always present in the rebel templates. If not, some player units may be missed and be able to leave groups using ACE. I don't think this causes any serious problems though.
Where is the issue for this? huh.
Closes #1064 
3. [X] …
=> Remove ACE group join action from all rebel unit types

A3-Antistasi/functions/Base/fn_initPetros.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_AddEH.sqf
* Change
* Enhancement
Information:
Adding an EH to AI now requires explicit permission through the param `_addToAI`
closes [#1219](https://github.com/official-antistasi-community/A3-Antistasi/issues/1219)
Needs testing on a dedicated server.
Steps: 
1. `Petros allowDamage true` and shoot him => Get warning.
2. Hire friendly AI and shoot it => No warning.
3. Go to friendly garrison and shoot them => No warning.
4. Find enemy AI and shoot them => No warning.
Notes:
There maybe another cause of the referenced bug.
=> AddEH Param to avoid unintentional EH's for FIA AI

A3-Antistasi/functions/AI/fn_airbomb.sqf, A3-Antistasi/functions/AI/fn_airstrike.sqf, A3-Antistasi/functions/REINF/fn_NATObomb.sqf
1. [x] Bug
2. [ ] Change
Information:
airbomb was executed on hc as well when it spawned duplication the effect, now it will execute on either the firs hc or server
closes #1223
1. [x] No
Steps: 
call in an airstrike and watch, it also logs the airstrike heavely
Notes:
=> Fix double airbomb spawn

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_onPlayerDisconnect.sqf, A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3-Antistasi/functions/Dialogs/fn_loadPreviousSession.sqf, A3-Antistasi/functions/Dialogs/fn_persistentSave.sqf, A3-Antistasi/functions/Save/fn_loadPlayer.sqf, A3-Antistasi/functions/Save/fn_loadPreviousSession.sqf, A3-Antistasi/functions/Save/fn_resetPlayer.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Save/fn_savePlayer.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf, A3-Antistasi/functions/init/fn_resourcecheck.sqf
1. [X] Bug
2. [X] Change
- Fixes bug where player saves wouldn't load correctly due to multiple global setVariables.
- Fixes bug where player saving could be enabled slightly before their stats were loaded.
- Fixes bug where autosave would spam additional player saves.
- Fixes minor exploit where players could gain money by not loading their previous game.
- Fixes issue where autosave wouldn't trigger unless there was a commander on the server.
- Fixes bug where player loadout wasn't loaded in SP.
- Works around unknown-cause issue where player unit lacked variables on disconnection.
- Adds some save/load logging to diagnose future broken player saves.
The first bug needed a substantial reorganisation so that the global variables related to the player save are always …
=> Overhaul save consistency, especially player saves

A3-Antistasi/functions/Punishment/fn_punishment.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf, A3-Antistasi/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf
* Bug
* Change
Information:
Reason can be passed to punishment function to display to the instigator.
Explosive delete and warn distance unified to 75m
closes [#1236](https://github.com/official-antistasi-community/A3-Antistasi/issues/1236)
closes [#1239](https://github.com/official-antistasi-community/A3-Antistasi/issues/1239)
(Please see one section above)
Steps: 
1. Shoot player and confirm basic FF detection works
**Repeat below for Ace and without Ace**
**Test with throwing grenade as well**
1. Place explosive >75m away from Petros => {No explosive  deleted and no warning issued};
2. Place explosive <75m away from Petros => {explosive deleted and warning issued};
=> CS-1236-punish-pass-reason

A3-Antistasi/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [X] Change
Information:
Removed M152 Firing Device from Starting Arsenal due to people requesting it.
--------> It should be gathered instead of being given at the Start.
closes #1248 
1. [X] Have you loaded the mission in singleplayer?
1. [X] No
Steps: 
Notes:
=> (ACE) Remove M152 Remote Detonator from Starting Arsenal

A3-Antistasi/functions/AI/fn_undercoverAI.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Added rebel civilian car & truck to undercover vehicles, in case they're not identical classes to the civilian template. Currently happens with 3CB because it has a ton of identical vehicles with different classnames.
Also added the boxer truck from the bank job, as it's not currently defined in the rebel template and may not be in the civilian
template either. The definition for this truck should be moved to the rebel template at some point.
Also fixed an inconsistency with undercover AIs that may have caused them to break undercover in civilian helicopters and boats.    
closes #1237
1. [X] No
=> Add rebel civilian car & truck to undercover vehicles

A3-Antistasi/functions/Ammunition/fn_itemSort.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/Save/fn_varNameToSaveName.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
1. [x] Bug
2. [ ] Change
Information:
Attempted to change `side petros` and `side (group petros)` in all checks for player side. Bug was caused by dead petros on check.
closes #282 
3. [x] Have you loaded the mission on a dedicated server? *by @CalebSerafin*
1. [ ] No
Steps: 
Not tested, needs further testing
Notes:
Untested change, found six instances where `side petros` was checked and removed
=> Removed `side petros` #282 again but hopefully no conflicts

A3-Antistasi/functions/CREATE/fn_WPCreate.sqf, A3-Antistasi/functions/CREATE/fn_createQRF.sqf, A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
2. [X] Change
The primary change is to limit the proportion of air supports used for an attack so that there's always a reasonable quantity of infantry for the termination conditions to work. Ground vehicle selection also takes greater care to maintain a balance of vehicle firepower vs infantry cargo.
Additional changes:
- Fixed a recent bug where land vehicles didn't reduce the number of air vehicles.
- Fixed a bug with WPCreate where an additional 0,0 waypoint was often added.
- Boosted the first wave vehicle count relative to later waves.
- A single available vehicle can no longer be used multiple times per wave.
- Force aircraft to return after termination, as with createQRF/patrolCA.
- Improved unit limit handling, will not longer drop single unit …
=> WavedCA vehicle selection overhaul

A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
1. [ ] Bug
2. [ ] Change
Information:
blocks players from garaging when they are being engaged by enemies within 500m of the player
closes #1242
1. [x] No
Steps: 
go and try to garage while in combat
Notes:
=> block players from garraging while being engaged by hostiles within 500m

A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
1. [X] Bug
2. [ ] Change
- Override the assembled 3CB Javelin's categories from nothing to AT + MissileLaunchers.
- Override the vanilla PDW2000's categories from Rifles to SMGs.
closes #1257
closes #1258
1. [X] No
=> Add 3CB Javelin and vanilla PDW2000 to category overrides

A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
1. [X] Bug
2. [ ] Change
Moved teamPlayer definition to the top of initServer so that it's available for the loadgame selection code.
Short term fix. We can argue about the organisational options later.
closes #1271
3. [X] Have you loaded the mission on a dedicated server?
1. [X] No
Load a game.
=> Fix loadgame functionality broken by #1234

A3-Antistasi/functions/CREATE/fn_createSDKgarrisonsTemp.sqf
1. [X] Bug
2. [ ] Change
When adding troops to a spawned garrison, Antistasi searches for nearby groups from the same marker to add them to, but doesn't check the side, so enemy groups from the previous garrison may be used, causing friendly fire incidents.
This PR fixes the problem by checking that the group has the correct side.
closes #1195
1. [X] No
1. Buy an AI or two. You'll need them later.
2. Capture an isolated enemy marker. Leave a couple of surrendered garrison troops nearby.
3. Defeat the QRF.
4. Leave your AIs near the marker to keep it spawned. Drive back to HQ.
5. Add a few garrison troops from the HQ management menu.
6. Check that they're not exchanging fire with your AIs.
=> Fix bug where new rebel garrison troops could be added to enemy group

A3-Antistasi/functions/AI/fn_surrenderAction.sqf, A3-Antistasi/functions/Revive/fn_handleDamageAAF.sqf, A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
1. [X] Bug
2. [X] Change
Information:
The squad leader is important for AI groups as he does most of the calculations and is also the one calculating the path and the waypoints. When he dies, the engine passes command to the second unit. However Antistasi has to cases in which the leader does not die, but still get incapable of executing commands, these being surrendering or going uncon.
In that two cases, the group stops to move and gets more or less useless until the SL dies. To avoid that behaviour, the squad lead is now passed onto the next active unit in the group, keeping the group active until no AI left in fighting state.
For the support rework: If the SL calls for help and dies, then passing command to the next one, the call for support is aborted, as the new …
=> Group leader now gets passed when the SL is not longer capable

A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Expanded the template sanity check to include almost all template vars, and include mis-cased class values, which break `_vehicle in _typeArray` tests.
closes #1265
1. [X] No
=> Expand template sanity check

A3-Antistasi/Templates/3CB_Inv_Sov_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Arid.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Temp.sqf, A3-Antistasi/Templates/RHS_Inv_AFRF_Trop.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Temp.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_B_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf
1. [X] Bug
2. [ ] Change
Fixed a lot of template errors discovered by #1273:
- Fixed broken boats array in 3CB_Inv_Sov_Temp.
- Fixed wrong classname of rhsgref_cdf_reg_uaz_spg9.
- Fixed wrong classname of AT launcher in Vanilla_Inv_CSAT_Tanoa.
- Fixed wrong classname for militia car in Vanilla_Occ_AAF_Altis.
- Fixed wrong classname for rebel AT car in Vanilla_Reb_SDK_Tanoa.
- Fixed a ton of mis-cased classes, mostly in vanilla.
1. [X] No
Could do with actually identifying an amphibious APC for use in the boats array of 3CB_Inv_Sov_Temp, but it'll do as-is.
=> Various template fixes

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3-Antistasi/functions/Dialogs/fn_loadPreviousSession.sqf
1. [X] Bug
2. [ ] Change
I completely forgot that it was possible to close dialogs without clicking on a button, which leaves players with zero money and blocks them from saving. Not critical because they could re-log to retrieve their save, but not good either.
I used loading as the default, because it's reversible and most escape-exits will be accidental.
closes #1284
3. [X] Have you loaded the mission on a dedicated server?
1. [X] No
Press escape when the load previous session dialog comes up.
=> Make the load personal save dialog default to loading

A3-Antistasi/functions/AI/fn_airstrike.sqf, A3-Antistasi/functions/Base/fn_rebelAttack.sqf, A3-Antistasi/functions/CREATE/fn_AAFroadPatrol.sqf, A3-Antistasi/functions/CREATE/fn_NATOinit.sqf, A3-Antistasi/functions/CREATE/fn_createAICities.sqf, A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
1. [ ] Bug
2. [X] Change
Removed spawner variable from units where it was unintentional or had a poor simulation/performance tradeoff:
- Added optional isSpawner parameter to NATOinit for forcing special cases.
- Fixed bug where cargo units were spawners while still cargo.
- Fixed bug where simulation disabling could be permanently applied to static crew.
- Switched airstrikes to use NATOinit. Should be fine.
- Removed spawner status by default for fixed-wing aircraft pilots.
- Removed spawner status from roadblock garrisons.
- Removed spawner status from road patrols (vehicle).
- Removed spawner status from city patrols.
Also disabled the 4x patrolCA option for major attacks in the Gov vs Inv case, restoring
the former behaviour. This was a massive performance hog for …
=> Performance and bugfix adjustments to spawning enemies

A3-Antistasi/functions/AI/fn_vehicleMarkers.sqf
1. [X] Bug
2. [ ] Change
Supply and money convoys generate civilian objective vehicles with civilian crew, and vehicleMarkers doesn't know what to do with civilian vehicles. This patch uses the occupant markers for civilian groups as a temporary fix.
At some point we should have our own vehicle/crew spawning functions to prevent bad-faction crew issues (for example FIA AT/AA vehicles with the wrong uniforms), but not before 2.3.
closes #1299 
1. [X] No
Create a supply convoy with:
`[destMrk, originMrk, "Supplies"] remoteExec ["A3A_fnc_convoy", 2]`
=> Hack-fix for civilian convoy objective markers

A3-Antistasi/functions/CREATE/fn_cargoSeats.sqf
1. [X] Bug
2. [ ] Change
Rewrote the cargoSeats function which takes vehicle input and spits out an array of cargo units:
- Now generates appropriate squads for militia and police vehicles.
- Now generates 8(-1) man squads for Warriors (7-seat problem).
- Fix case where it incorrectly errored out with two cargo seats.
- Rewrote no-cargo error message in english.
Currently the militia vehicle functionality is unused but it's easy to test.
closes #1295 
closes #1205
1. [X] No
Debug console abuse:
`[vehPoliceCar, Occupants] call A3A_fnc_cargoSeats`
Returns array with squad members suitable for police car, whatever that is.
`[vehFIACar, Occupants] call A3A_fnc_cargoSeats`
Returns array with squad members suitable for militia …
=> CargoSeats rewrite

A3-Antistasi/cba_settings.sqf
1. [X] Bug
2. [ ] Change
TFAR settings were set to convert radios differently for squad leaders and everyone else. This was apparently not the intended behaviour.
closes #1238 
1. [X] No
=> Enable 5km TFAR radio conversion for everyone, not just squad leaders

A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf, A3-Antistasi/functions/CREATE/fn_createQRF.sqf, A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
1. [ ] Bug
2. [X] Change
Various issues related to QRF balance:
Prevented QRF spawning closer than half spawn distance from rebels. Outposts and airports beyond spawn distance are preferred. Note that the check applies to the the marker, not the spawn point, so airports may be a bit weird.
Increased the delay between QRFs to/near the same marker to 20-30 mins from 10-20 as requested.
I thought this was over-adjusted given that QRFs are also being multiplied by AOs, and the constant one-vehicle QRFs in SP are pitiful. Replaced some aggro adjustment with a bit of randomness.  The range is now more like 1.25 to 5 vehicles rather than 0-6 min 1.
Should be re-examined if we stop multiplying QRFs by AOs, but it's not a strong change anyway.
- Advanced vehicles are available …
=> Tweak QRF balance

A3-Antistasi/Templates/selector.sqf
1. [X] Bug
2. [ ] Change
Information: Worldname of Chernarus_Winter was incorrect since its Case-Sensitive
Move Tembelan to Temperate Maps due to being way to Green for an Arid map.
closes #1312 
1. [x] No
Steps: 
Load Chernarus Winter with RHS/3CB Modset, Units were supposed to be in TEMP Camo ---> Woodland etc.
Not in Arid.
Notes:
=> Template Selector fix

A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
2. [ ] Change
The sea attack code in wavedCA assumes that at least one marker is present in the seaAttackSpawn array. This PR early-outs if this isn't true.
closes #1326
1. [X] No
=> Fix RPT error in wavedCA caused by empty seaAttackSpawn array

A3-Antistasi/functions/Base/fn_getVehiclePoolForQRFs.sqf
1. [X] Bug
2. [ ] Change
War levels 7-10 of getVehiclePoolForQRFs used vehNATOTruck and vehCSATTruck. The correct variable names are vehNATOTrucks and vehCSATTrucks.
closes #1329 
1. [X] No
Functionality can mostly be tested from the debug console by changing the war tier on each execution:
```
warTier = 7;
[Occupants, ["Air"]] call A3A_fnc_getVehiclePoolForQRFs
```
=> Fix QRF vehicle selection typos from war level 7-10

A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added 2 lines to initGarrisons that replace the NATO/CSAT markers to the one defined in template.
closes #1335 
1. [x] No
Steps: 
Load into the mission on a modset other than vanilla, check the markers on map.
Notes:
Previously tested in initZones, lines are the exact same.
=> Add Carrier re-flagging to initGarrisons.

A3-Antistasi/functions/init/fn_initZones.sqf
1. [x] Bug
2. [x] Change
Information:
-Fixed Case detection for Radiotowers. #1332 
-Updated Radiotower Positions
-Updated Radiotower Blacklist
-Added Hardcoded Civ Pop for Livonia and Virolahti.
-Tried to make Civ-Pop list more readable.
-Fixed a Typo in Chernos Civ Pop.
-Updated Townblacklist: #680 , Doesent get fully Closed but most of it, Tembelan and Making it Map-Specific is still on the Table.
Removed:
Malden Main Airbase as a Town.
Airport-Road on Kunduz (Twice).
2 Villages on Virolahti: toipela and hirvela.
FobNauzad and FobObeh on Anizay.
closes #1332 
1. [X] No
2. [ ] Yes (Please provide further detail …
=> Fix Radiotower Blacklist/Add Hardcoded Civ-Pop/Remove Towns

A3-Antistasi/Templates/AddonVics/tcgm_Civ.sqf, A3-Antistasi/Templates/detector.sqf, A3-Antistasi/Templates/selector.sqf
1. [ ] Bug
2. [ ] Change
Information:
- added all bikes to civ vehicle array so you can be undercover in any bike
- disabled spawning of military variants (the once that actually fold into backpacks) for civs
- added military variants to the light vehicle arrays of nato and csat
closes #XXXX
1. [ ] No
Steps: 
- look for spawned bikes :)
Notes:
I actually only checked civ spawning and undercover yet. Didn't have a look for NATO or CSAT spawning with bikes.
=> added folding bikes from tcgm_bikebackpack

A3-Antistasi/functions.hpp, A3-Antistasi/functions/AI/fn_airdrop.sqf, A3-Antistasi/functions/AI/fn_fastrope.sqf, A3-Antistasi/functions/Base/fn_remUnitCount.sqf, A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
patrolReinf overhaul, mostly to the termination logic:
- Fixed a lot of related setWaypointStatements locality bugs.
- Added timeout so that reinforcements can't get stuck & spawned forever.
- Fixed issue where reinforcements remained spawners after adding to garrison.
- Fixed issue where arrived reinforcements weren't removed from the garrison on death.
- Removed possibility of single-unit reinforcements.
- Stopped trucks trying to drive right into the middle of outposts.
- Fixed killZones update code.
- Added 'Spawn Performed' logging string.
Most of this code will be stripped out for 2.4, but the setWaypointStatements bugs are so bad that I think it's worth sorting it  out for 2.3.1.
closes #907 
partial fix for #1229
1. [X] No
2. [ ] Yes …
=> patrolReinf termination overhaul

A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Sanity-checker crashed out on Arma versions below 1.95 due to use of `substring in string`. I don't think we care much about supporting older Arma versions but this was an unnecessary incompatibility.
closes #1344 
1. [X] No
=> Fix unintentional use of Arma 1.95+ SQF feature

A3-Antistasi/functions/AI/fn_airbomb.sqf
1. [X] Bug
2. [ ] Change
Rebel airstrikes stopped spawning bombs when the commander wasn't the host, because they're executed on the commander's client, setWaypointStatements in NATObomb was constrained to only execute locally (to prevent multiplied bomb drops), but airbomb only executes on HC or server.
There were various ways to fix this. I chose to allow NATObomb to execute on clients because otherwise the drop point could get badly desynced if passed off to another machine. The more centralized fix would be to execute rebel airstrikes on the server or HC, but that was fairly complex due to how the airstrike function manages the markers.
Also removed some redundant debugging code from airbomb and made the remainder log to server, as the default for clients is to log …
=> Fix non-hosted rebel airstrikes

A3-Antistasi/functions/init/fn_initClient.sqf
1. [X] Bug
2. [ ] Change
initClient wasn't intended to run most of its code on headless clients, but it was due to bad exitWith scope. Oddly enough it doesn't seem to matter much, but as changes there won't usually be tested on HCs, it's a bad idea. This patch breaks out where it's supposed to.
I think this bug was introduced in 2.3, and the new initClient code that needs to run on HCs (navgrid, destroyed buildings) is above the break, so everything should be fine. Didn't run into any problems in testing.
closes #1372
4. [X] Have you loaded the mission on a dedicated server with HCs?
1. [X] No
2. [ ] Yes (Please …
=> Fix initClient unintentionally running everything on headless clients

A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [X] Bug
2. [ ] Change
Because the community version changed map marker names from "puesto" to "outpost" and "puerto" to "seaport", saved games from Barbolani versions were not loaded correctly. This PR translates the marker names for the important cases (ownership, garrisons). Unimportant params like killzones and idlebases are left alone.
Also fixed some dangerous non-private vars while I was there.
closes #1367
1. [X] No
Make a new vars file, create a save game with a non-community version, capture some outposts and seaports, add some garrisons and load it.
=> Fix loading of outpost & seaport markers from original save games

A3-Antistasi/functions/Garage/fn_garageVehicle.sqf
1. [x] Bug
* Change
* Enhancement
Changed `engageing` to `engaging`
> "You can't garage vehicles while enemies are engaging you"
closes [#1346](https://github.com/official-antistasi-community/A3-Antistasi/issues/1346)
1. [x] No
Steps: 
player AllowDamage false;
spawn vehicle near HQ.
spawn many enemies near HQ so Petros cannot kill them all.
Try garage vehicle and check the spelling of engaging.
Notes:
I doubt this needs a QA review.
=> garageVehicle spelling fix "engaging".

A3-Antistasi/functions/Revive/fn_actionRevive.sqf
1. [ ] Bug
2. [x] Change
Revives and heals can now occur in water.
closes [#1366](https://github.com/official-antistasi-community/A3-Antistasi/issues/1366)
Ln 55 deleted
1. [ ] No
* Yes (Needs testing.)
Steps: 
Load A3A without Ace.
Disable TK Punish in Params.
Find at least one friend.
Brink a FAK.
Shoot him dead in water.
Revive him with FAK.
He should be alive without warnings. (NOTE: There is a delay until movement is allowed.)
Notes:
Only removed water surface check, and converted tabs to spaces.
**Reviewer please first check functionality in first commit. Second commit is Tabs=>tabs.**
=> CS-1366-Vanilla-Ice-Revive

A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
1. [x] Bug
* Change
* Enhancement
Information:
Side checks now use getVariable "pvp" to determine whether rebel or not.
closes #[1407](https://github.com/official-antistasi-community/A3-Antistasi/issues/1407)
1. [ ] No
* Yes (Test)
Steps: 
Rebel damage PvP => Log
Rebel damage rebel => Punish
PvP damage PvP => nothing
PvP damage rebel => Log
=> _FF checks victim side and logs accordingly.

A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf, A3-Antistasi/orgPlayers/nonMemberDistance.sqf
1. [x] Bug
2. [x] Change
Information:
**City supplies**
Made the crate slingloadable, plus needed to not be slingloaded to start countdown. Changed the supplies to be more fitting than a crate with IDAP boxes.
**Non-members fleeing, basically.**
Fixed the countdown number, so it actually updates instead of just saying "%1".
closes #1391 
closes #1422 
1. [x] No
Steps: 
#1391 : Get yourself a city supplies mission, spawn in a heli and slingload it to the city.
#1422 : Get a server running, get someone on who doesn't have membership, and throw them off into the abyss. …
=> Slingloadable supplies & working non-member countdown

A3-Antistasi/functions/CREATE/fn_WPCreate.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
2. [ ] Change
- Fixed a bug added in #417 that caused WPCreate (the old pathfinding function) to crash out on Tanoa.
- Fixed major attacks not checking whether land bases were on the same island.
Second bug will also apply to other multi-island maps.
closes #1401
closes #1405
3. [X] Have you loaded the mission on a dedicated server?
1. [X] No
Start a new reb vs gov vs inv game on Tanoa, then run as server:
`["resource_6", "airport_1", 3] spawn A3A_fnc_wavedCA`
Should neither crash out or spawn any ground vehicles.
=> Fix Tanoa attack bugs

A3-Antistasi/Templates/3CB_Reb_CNM_Temp.sqf, A3-Antistasi/Templates/3CB_Reb_CNM_Trop.sqf, A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf, A3-Antistasi/Templates/3CB_Reb_TTF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_HIDF_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_HIDF_Temp.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/RHS_Reb_NAPA_Temp.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Altis.sqf, A3-Antistasi/Templates/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
1. [X] Bug
2. [X] Change
Information:
**Rebell Template**
Renamed RHS_Reb_CDF to HIDF. #1356 
Changed all Possible Units with HIDF and FIA Units.
A few things as Static weapons are still "CDF" but they dont spawn with Default Crew so there is no Issue.
vehSDKAT and the vehSDKLightArmed are FIA variants cause i didnt want to give a Hmmve or an SPG9 UAZ due to Default CDF Crew for the UAZ.
vehSDKPlane is changed to a Reskined variant of the Apex DLC Cesna.
**Uniform stuff**
Changed Equipmentsort to give a few HIDF Rebell Uniforms for the HIDF Template.
Added an Array to each Greenfor Rebell Templates with all FIA_I Uniforms for #1191, i did it this way so possible other Rebell Templates dont have to fight it getting added.
Added a If Teamplayer Side checks to the other …
=> Replace CDF Rebells / Add Rebell Uniforms / Correct Typos

A3-Antistasi/Templates/Vanilla_Inv_CSAT_Altis.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Enoch.sqf, A3-Antistasi/Templates/Vanilla_Inv_CSAT_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_AAF_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Altis.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Tanoa.sqf, A3-Antistasi/Templates/Vanilla_Occ_NATO_Temp.sqf
1. [x] Bug
2. [ ] Change
Information: 
**Nato Tropical, CSAT Tropical and AAF Template**
Removed Lowtier Factions and replaced Units with Regular Units from that Faction -----> Synd with AAF, Fia with CSAT, FIA with Nato.
**All Vanilla Templates**
Removed Mortar and MG Carriers from 8 Man Groups and Replaced these with LAT Squads as #1364 requested. (Basicly the only stuff i need to be Reviewed by John)
-------> Added 2 LAT2 (Maaws) and 2 LAT (PCML) to Combined Arrays, CSAT got 4 times LAT (RPG32) in 8 man arrays to replace Mortar and MG Carriers.
**Nato Tropical**
Brought 8 Man Squads of Tanoa Nato up to the State of Nato_Altis.
**Nato Altis**
Changed Nato Bodyguard to a Medic, he has the same Equipment exept he doesent get the Forbidden Backpack and his weapon has no …
=> Vanilla Cleanup

A3-Antistasi/MissionDescription/params.hpp
1. [ ] Bug
2. [x] Change
Information:
to prevent the the borken reb vs inv gamemode form being played
closes #1352
1. [x] No
Steps: 
check the parameters on start
Notes: custom params in say server cfg would still be able to overwrite this, possibly a hard block would be needed
=> removed the param for gamemode "Reb vs Inv"

A3-Antistasi/functions/Base/fn_findNearestGoodRoad.sqf, A3-Antistasi/functions/Utility/fn_getRoadDirection.sqf, A3-Antistasi/functions/init/fn_initZones.sqf
1. [X] Bug
2. [ ] Change
Fixed some some road-searching issues:
- Prevented getRoadDirection from crashing out when passed an unconnected road.
- Prevented findNearestGoodRoad from returning unconnected roads.
- Made initZones road-attack blacklist more generous, so it doesn't contain outposts right next to roads.
The latter two should be replaced with navgrid-based logic at some point, but that's more of a project.
closes #1373 
1. [X] No
=> Fix some road search bugs

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/CREATE/fn_createQRF.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/Convoy/fn_spawnConvoy.sqf, A3-Antistasi/functions/Garrison/fn_shouldReinforce.sqf
1. [X] Bug
2. [X] Change
Intro: Killzones are Antistasi's method of preventing the AI from repeatedly suiciding units into the same position. The implementation had a number of problems but wasn't totally retarded in concept, so I fixed it up.
The changes:
- Reinforcements tick now gradually removes killzones, aggro dependent. Previously killzones were near-permanent, so an outpost could easily get stuck in a state where no reinforcements or QRFs were sent, so you could farm it forever for crates.
- New reinf convoys now obey killzones and generate them. Previous behaviour was to ignore killzones, causing infinite pileups when players camped on a road.
- Position QRFs now only generate killzone on nearest marker. Previous behaviour was to generate killzones for all …
=> Get killzones into working condition

A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/Garage/fn_placeEmptyVehicle.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds the JNL load action to any vehicle matching the quadbike entry in the template when spawned through placeEmptyVehicle.
closes none
1. [x] No
Steps: 
Spawn one of each quad, garage and ungarage them, check the scroll menu for "load cargo"
Notes:
Disabled for IFA as that "quadbike" is a Willys Jeep.
=> Adds JNL load action to quads spawned through placeEmptyVeh

A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf, A3-Antistasi/functions/Ammunition/fn_loot.sqf, A3-Antistasi/functions/Templates/fn_aceModCompat.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
1. [ ] Bug
2. [ ] Change
Created a category for ACE electronic gadgets (none of the previous categories fitted) and added the Kestrel, AtragMX and HuntIR to it. The HuntIR was already force-added to lootItem in the ACE compat template, so that was removed to avoid double entries.
closes #1392 
1. [X] No
May want to increase the number of different items dropped in crates for a better chance of finding this stuff. There are around 40 different classes in lootItem in ACE/RHS, and a maximum of four different items by default.
Check what's in the following vars:
```
allGadgets
unlockedGadgets
allItems
unlockedItems
lootItem
```
=> Classify ace gadgets and add them to loot crates

A3-Antistasi/JeroenArsenal/JNL/fn_logistics_init.sqf
1. [x] Bug
2. [ ] Change
What:
I forgot to change the model path for the new city supply object in JNL.
Why:
It doesn't want to be a good pallet and jump into the back of the car if this doesn't get added. Pallet wants treat.
closes #1451 
1. [x] No
Steps: 
Get a city supply mission and a vehicle that can load crates onto the flatbed of it.
=> Jeroen compatibility for supply crate

A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf
1. [ ] Bug
2. [X] Change
Scale the number of killzones removed by the active killzone count. This prevents potential issues where the AI has no QRF/reinf options under high rebel activity.
It doesn't. Should have been in #1450 but that got speed-merged.
1. [X] No
=> Scale killzone removal by active killzones

A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
1. [X] Bug
2. [ ] Change
Information:
Removed "UK3CB_B_B_Radio_Backpack" and replaced it with "tf_rt1523g_big_rhs".
The 3CB Faction Radio doesent work with TFAR at the moment and its unknown when its fixed so its removed for the time being.
Additional: There is "UK3CB_B_O_Radio_Backpack" in TKM_Teamleader but its PVP and i dont realy care, not as important.
closes #1448 
1. [X] No
Steps: 
Notes:
=> BUG-FIX 3CB Factions Radio

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
1. [X] Bug
2. [ ] Change
The arsenal allowed items to be equipped when their count was zero, which could be exploited in some cases (ACE/RHS item translation, stealing items from players in the arsenal, two players taking the same items). This patch prevents that.
closes #1421
1. [X] No
Run with ACE. Put some BIS NLAWs in the arsenal. Click on them in the arsenal, and watch what happens.
=> Prevent equipping zero-count items from the arsenal

A3-Antistasi/functions/Missions/fn_LOG_Supplies.sqf
1. [x] Bug
2. [ ] Change
Information:
fixed the countdown hint not having a hint header and therefor adding another hint to the hint stack of "Countdown 1" instead of being replaced by the supplies delivered, also improved the text thats displayed to be more informative
closes #1471
1. [x] No
Steps: 
do a city supplies mission, does the count down hint get replaced by the deliverd hint? if so then it works
Notes:
=> fixed bad hint with supplies mission

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
1. [X] Bug
2. [ ] Change
Added an exception for the empty item row in the arsenal, because it has count 0 and so the previous patch prevents it from being selected.
closes #1460
1. [X] No
Well, it's possible I missed something else. I did click on a lot of stuff this time though.
Open arsenal, select empty slot, select something else. Check left side items and weapon accessories.
=> Fix arsenal empty-slot selection

A3-Antistasi/functions/Undercover/fn_goUndercover.sqf, A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
1. [X] Bug
2. [ ] Change
- Fixed an exploit where undercover civ helis could sling-load outpost crates. This is also addressed in a much larger patch (#1075) that needs a rebase, but it's a trivial hotfix to the current code and will be necessary with #1484.
- Fixed a client script error in some broken undercover debug output. Easiest way to demonstrate this is to get in and out of a civilian vehicle quickly. Not sure if it had any side effects, but they're fixed now.
- Fixed a display inconsistency with undercover and ACE unconsciousness. It was possible for the HUD bar to report "undercover off" while the player was conscious and undercover. There were various ways of handling this but given a lack of interest I've made it work like the vanilla revive, so you lose …
=> Fix some minor undercover bugs

A3-Antistasi/functions/Undercover/fn_goUndercover.sqf
1. [X] Bug
2. [X] Change
Put seaports in the same category as outposts for undercover: They have a chance of spotting undercover land units, and automatically detect civ helis within 100m.
Also fixed some misnamed variables that were really bugging me.
closes #1491
1. [X] No
=> Add seaports to secure bases for undercover

A3-Antistasi/functions/AI/fn_artillery.sqf
1. [x] Bug
2. [ ] Change
Information: if the arty piece of fn_artillery is destroyed on spawn it freaks out when trying to get the artillery ammo and breaks, now it exits out with a proper error log when this happens
closes #1510
1. [x] No
Steps:  comment out ln 14, add this after ln 21 : `_veh setDamage 1;` and spawn in an arty mission, it should blow up on spawn and this line should be logged instead of an error: ``` [Antistasi] | ERROR | fn_artillery | Arty piece destroyed on spawn, fire mission canceled"``` …
=> added an exit case if arty piece spawned badly and was destroyed

A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
1. [x] Bug
2. [ ] Change
Information:
if findEmptyPosition fails it returns an empty array, now it will retry with a massive area that should not fail.
closes #1511
1. [x] No
Steps: RNG, mass of mission spawns are required
Notes:
=> failed findEmptyPosition attempts retry with massively expanded area

A3-Antistasi/functions/UI/fn_customHint.sqf, A3-Antistasi/functions/UI/fn_customHintInit.sqf, A3-Antistasi/functions/UI/fn_customHintRender.sqf
1. [x] Bug
* Change
* Enhancement
* A3A_fnc_customHintRender will be called every 15 frames regardless of whether the queue is empty.
* This removes the rare chance that a dismiss call and new hint happen at the same time -> queue is not empty, but render does not run.
* BIS_fnc_loop has being replaced by OnEachFrame and a 15 frame counter (for calling A3A_fnc_customHintRender ).
* It is a large function that has more functionality than needed for this task.
* It isn't efficient. 
* BIS_fnc_loop is not to be trusted, sometimes it does not to run the code added to it.
closes [#1504](https://github.com/official-antistasi-community/A3-Antistasi/issues/1504)
1. [x] No
* Yes (Please …
=> CS-1504-PurgeBSLoop

A3-Antistasi/functions/UI/fn_customHint.sqf, A3-Antistasi/functions/UI/fn_customHintDismiss.sqf, A3-Antistasi/functions/UI/fn_customHintInit.sqf, A3-Antistasi/functions/UI/fn_customHintRender.sqf
* Bug
* A3A_customHint_Queue refactored to A3A_customHint_MSGs
* This will differentiate it from other notification systems in the future.
* A3A_customHint_MSGs is treated as an upside-down stack.
* Newest messages are pushed to the back. The last message is rendered.
* **INCLUDES CHANGES IN [#1505](https://github.com/official-antistasi-community/A3-Antistasi/pull/1505)**
closes [#1516](https://github.com/official-antistasi-community/A3-Antistasi/issues/1516)
1. [ ] No
* Yes
* Make sure this change works nicely with the counters/timers in FF_punishment or supply missions.
* Make sure it feels good when interacting with items at HQ like "Map Info". …
=> CS-1516-HintQueueToStack

A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
* Change
* Enhancement
* Inside Punishment_FF: Pvp was previously checked by the "Pvp" variable. However, this variable is not implemented to be JIP compatible.
* Solution: Pvp is now checked by side group of the _instegator/_victim.
*PS: The brackets will be lined up later for those OCD among us.*
closes [#1520](https://github.com/official-antistasi-community/A3-Antistasi/issues/1520)
1. [ ] No
* Yes
1. Rebel Shoot Rebel -> Warning & FF Log
2. Rebel Shoot Pvp -> No Notification & PVPHURT log
3. Pvp Shoot Rebel -> No Notification & PVPATTACK log
*With Updated/Current Mission SQM*
[Antistasi-TEST-CS-1520-FFChecksLocalPvp-2-3-1.Altis.pbo.zip](https://github.com/official-antistasi-communi …
=> CS-1520-FFChecksLocalPvp

A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [x] Bug
* Change
* Enhancement
* SaveLoop announces when it begins to save.
* SaveLoop Completed Hint is remoteExec on all clients
closes [#1530](https://github.com/official-antistasi-community/A3-Antistasi/issues/1530)
1. [x] No (Tested & Can be rubber ducked easily)
* Yes
* Be on DS
* Save -> All players are told that saving is starting
* Wait for it to finish-> All players are told that saving is completed
[Antistasi-TEST-CS-1530-SaveLoopBroadcastHint-2-3-1.Altis.pbo.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/5348195/Antistasi-TEST-CS-1530-SaveLoopBroadcastHint-2-3-1.Altis.pbo.zip)
=> CS-1530 Persistent Save message is broadcast to clients.

A3-Antistasi/functions/Dialogs/fn_createDialog_setParams.sqf, A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf
* Change
* Enhancement
Information:
* A local _autoSaveInterval extracted from params on each client.
* This is used in the hint message.
closes [#1534](https://github.com/official-antistasi-community/A3-Antistasi/issues/1534)
1. [x] No (Can be rubber ducked)
* Yes
Join DS game as a client.
See the current autosave time appear in the `W A R N I N G` message.
[Antistasi-TEST-CS-1534-JoinHint-AutoSaveTime-2-3-1.Altis.pbo.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/5356970/Antistasi-TEST-CS-1534-JoinHint-AutoSaveTime-2-3-1.Altis.pbo.zip)
=> CS-1534-JoinHint-AutoSaveTime

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf
1. [x] Bug
2. [ ] Change
Information: made it so that the keydown eh also requires the player to not be in a vehicle. this will restore what i believe the intent was whit this in the vehicle arsenal.
closes #1543
1. [x] No
Steps: get a vehicle and try to use the keybind (ctrl + o) to load any loadout, and to be sure it still works on foot, exit the vehicle then open the arsenal and try there, again with the keybind
Notes: same condition was added to the save keydown eh
=> blocked players in vehicles to load loadouts in the vehicle arsenal

A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [ ] Bug
2. [ ] Change
Loot crates no longer respawn every time an outpost/seaport/airport garrison is spawned. Instead, stealing or destroying a crate adds a cooldown variable to that garrison, which is decreased on ticks only if the garrison is full. Hence a garrison that isn't being reinforced will not respawn loot crates. Locations with larger garrisons have shorter cooldowns, typically an hour for a large outpost, two hours for a small one or half an hour for an airfield.
This prevents farming a near-empty outpost that's reinforcement-blocked by killzones, and reduces (but doesn't prevent) exploiting outposts that are relatively easy to steal crates from for geographical reasons. It's also logical, because outposts don't send out patrols (to confiscate loot, or …
=> Restrict loot crate respawns

A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf, A3-Antistasi/functions/Base/fn_sellVehicle.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [X] Change
Expanded the vehicle selling capability to include anything reasonable, so that commanders can do something with surplus MRAPs littering the HQ.
Because this would significantly expand the previous exploit of unlocking static weapon parts and then selling the (unlimited) assembled weapons, I've fixed that at the same time, so static weapon parts and backpacks are now prevented from unlocking.
closes #1488
1. [X] No
Testing unlocking:
`cursorObject addItemCargoGlobal ["ace_cws_staticATCarry", 40]`
`cursorObject addBackpackCargoGlobal ["B_Mortar_01_weapon_F", 40]`
Testing vehicle selling:
`vehPoliceCar createVehicle (position player)`
=> Expand vehicle selling and fix related static weapon unlock exploit

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_addItem.sqf, A3-Antistasi/functions/Ammunition/fn_unlockEquipment.sqf
1. [ ] Bug
2. [x] Change
Information:
all unlocks after server init is now logged
Bob request no issue made for it
1. [x] No
Steps: 
start a new campaign and unlock a few items, check the logs, then load a previous save and do the same. it should only log when you unlock stuff and not when initializing the arsenal
Notes:
=> Added logging for unlocks

A3-Antistasi/Scripts/fn_advancedTowingInit.sqf
1. [x] Bug
2. [ ] Change
Information:
squared the speed and max speed to ensure positive number for the comparison conditional
closes #1501
1. [x] No
Steps: get a quad and a tank, start towing the tank with the quad, then turn the quad around and start reversing, you should have the same speed limit
Notes:
=> fixed fast reverse towing exploit

A3-Antistasi/JeroenArsenal/JNL/Actions/fn_logistics_addActionLoad.sqf
1. [x] Bug
2. [ ] Change
Information: Stopped pvp players from getting the load action added
closes #1512
1. [x] No
Steps: Try to load a crate as pvp, you wont have the action, rebels will still have it
Notes:
=> block adding of action to pvp

A3-Antistasi/functions/Save/fn_savePlayer.sqf
1. [X] Bug
2. [ ] Change
In savePlayer, moved the catch-all sanity check for the moneyX variable after the known do-not-save cases, notably for PvP players, so that error messages are reserved for actual errors.
Not too happy about the side check for PvP here, but it'll do until #1520 is resolved.
Not critical for 2.3.1 as it only affects logging, although it's also trivial.
closes #1522
1. [X] No
=> Prevent saveplayer reporting an error for PvP players

A3-Antistasi/functions/CREATE/fn_patrolCA.sqf
1. [ ] Bug
2. [X] Change
In rare cases (no civs or friendly patrols anywhere near), occupants will launch airstrikes on cities, notably during city supply missions. This seems a little unreasonable.
This PR prevents patrolCA calls being resolved as airstrikes when given a position target within half a town's marker radius, regardless of current friendly/civilian presence. Some other sort of QRF will be sent instead.
closes #1508
1. [X] No
You'd need to set up a situation where you're in a town with no occupant troops or civilians within 200m, which is normally not easy without Zeus abuse. Then order a patrolCA on your position like this:
`[position player, Occupants, "", false] remoteExec ["A3A_fnc_patrolCA", 2];`
An …
=> Prevent occupants launching airstrikes instead of QRFs on cities

A3-Antistasi/Templates/RHS_Occ_CDF_Arid.sqf, A3-Antistasi/Templates/RHS_Occ_CDF_Temp.sqf
1. [ ] Bug
2. [x] Change
Information: The BRDMs given to PVP for CDF are way to heavily armored and come with an AA Launcher in its inventory.
They should be removed.
closes #1537 
1. [x] No
Steps: 
Notes:
=> Remove CDF-PVP-Brdms

A3-Antistasi/functions/init/fn_initZones.sqf
1. [ ] Bug
2. [x] Change
Information:
Disabled 2 Towns (Kuusela Niemela) Informations are in #1528 
closes #1528 
1. [X] No
Steps: Load Map, Kuusela Niemela shouldnt be Towns anymore
Notes:
=> Virolahti Remove 2 Towns Markers

A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [x] Bug
2. [ ] Change
Information:
I swapped the old classnames for the new objects we have gotten in fn_LOG_Supplies.sqf. Reason being #1556 
closes #1556 
1. [x] No
Steps: 
Get city supply mission.
Do persistent save.
Restart server and load save.
Notes:
=> City supplies - Blacklist update

A3-Antistasi/functions/Missions/fn_DES_Heli.sqf
1. [x] Bug
2. [ ] Change
Information: on maps not surrounded with water, Des_Heli could spawn outside the map, as players are no longer able to leave the map this blocked completion (for the most part) of this mission, to resolve this the mission will now always spawn within the map boundaries, spawning in the worst case at the border
closes #1558
1. [x] No
Steps: [["airport"],"A3A_fnc_DES_Heli"] remoteExec ["A3A_fnc_scheduler",2]
on kunduz as it had a high tendency to spawn out of bounds.
dismiss the mission with ''[0,"DES"] spawn A3A_fnc_deleteTask;'' and repeat. …
=> made crash pos origin respect map boundaries

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Collections/doc_benchmarksGetSetRem.sqf, A3-Antistasi/functions/Collections/fn_getNestedObject.sqf, A3-Antistasi/functions/Collections/fn_remNestedObject.sqf, A3-Antistasi/functions/Collections/fn_setNestedObject.sqf
* Bug
* Change
* Ability to create nested data object trees. 
*(Locations that reference other locations with values) 
*(Is basically encapsulation of namespaces.)
* Nested Data object trees are speedier to access and update than using arrays.
* Support for self-referencing trees (Shouldn't be a usual use case, but it works with them fine.)
* Allow dropping slow punishData functions.
* Can be used to optimise/pre-cache commonly accessed data.
* Converting to and from arrays for long-term storage.
* Efficient way to transfer/fetch data across the network.
* Punishment_data get&set ran at O(n^n)
* This runs less than O(n) (Due to hashmap implementation of get&set variable)
* Can create 1_000_000 entries in 2861.33ms;
* See benchmarks file for info.
Closes …
=> CS-Collections: NestedObject: Wrapping for createNamespace

A3-Antistasi/functions/SalvageRope/fn_salvageRope.sqf
1. [x] Bug
2. [ ] Change
Information: last fix for the salvage rope damage problem introduced a disconnect between the player and the vehicle, this made it impossible to recover the cargo in the salvage mission, the other actions was also partially broken as well. i fixed this and improved a oversight of the original design that prevents you from re recovering cargo if say the boat is sunk before you reach shore
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fixed broken salvage rope, improved functionality

A3-Antistasi/Templates/3CB_Reb_TPGM_Arid.sqf
1. [X] Bug
2. [ ] Change
Information: Having the same Classname in SDKMil and staticCrewTeamPlayer leads to multiple Issues:
You can't add Squads "Rifleman" that are Rifleman and Crewman to Garisons (Normal Units that are Part of your Squad and High Command Squads).
If you add Rifleman via Manage Garisons you will get a Free Mortar per Rifleman.
closes #1547 
1. [X] No
3CB BAF Modset on Altis Bluefor
Steps: Recruit Rifleman and try to add them to a Garison, there should not be a Hint telling you that you can't add Crewman.
Adding Rifleman via Manage Garisons …
=> 3CB TPGM fix staticCrewTeamPlayer. 👀

A3-Antistasi/functions/Garage/fn_vehPlacementCallbacks.sqf, A3-Antistasi/functions/REINF/fn_addFIAveh.sqf
1. [ ] Bug
2. [X] Change
Adjusts the vehicle purchase code so that commanders purchase any vehicle with faction resources, not just static weapons. This fixes various early-game learning curve problems where people have to steal resources or share between players to put together enough cash for an undercover vehicle.
Might make it a bit too easy to acquire vehicles, but we'll see. Making them more expensive is an option. The civilian heli becomes much easier to acquire, so we should probably hotfix the undercover sling-load exploit at the same time.
closes #1473
1. [ ] No
Not 100% sure how this is going to change player behaviour.
=> Commanders purchase all vehicles with faction resources

A3-Antistasi/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug
2. [ ] Change
- Avoided roadblocks being placed on junctions, where possible.
- Handle case with unconnected roads without crashing out.
closes #1509
1. [X] No
The previous fail case was probably either roadblock 4 or 42 on Virolahti. These are the roadblocks closest to Klamila, in the southwest of the map. One's in the town itself, the other is 300m down the road to the west.
=> Handle a couple of roadblock direction problems

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [X] Bug
2. [ ] Change
- Workaround BIS bug with setUnitLoadout that caused mags to be incorrectly refilled on entering arsenal
- Prevent adding empty magazines when loading loadout with unavailable items
- Fix non-member magazine limits for vehicle arsenal
- Sanitize other non-member limit routines for coherency
closes #1563
1. [X] No
=> Fix some arsenal magazine bugs

A3-Antistasi/functions/init/fn_initACEUnconsciousHandler.sqf
1. [X] Bug
2. [ ] Change
Fixed case where handcuffed units would lose their captive state on waking from unconscious, causing them to be shot by enemy AIs.
This is only one of many compatibility problems that ACE handcuffs has with Antistasi's undercover system, but it probably accounts for 90%+ of the issues in practice, so it's worth quickfixing.
Partial fix for #1540
1. [X] No
=> Fix captive state being stripped from handcuffed units waking from unconscious

A3-Antistasi/functions/Dialogs/fn_clearForest.sqf
1. [x] Bug
2. [ ] Change
Information:
Added Small Tree to Clear Forest and made it shorter cause aparently the rest was not needed.
closes #1586
1. [x] No
Steps: 
Try to clear Forests, on Cherno Winter infront of Default HQ,
The Small Tree at [6745.78,5688.3,0] was never Cleared.
Notes:
=> Add Small Tree to ClearForest

A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf
removes the prop "UK3CB_BAF_MAN_HX60_Container_Servicing_Air" from three vehicle template arrays
1. [x] Bug
2. [ ] Change
Information: because prop != vehicle
closes #1590
=> issue 1590 fix - delete prop from vehicle arrays

A3-Antistasi/NavGridTools/createNavGrid.sqf, A3-Antistasi/NavGridTools/extractRoadTypeData.sqf, A3-Antistasi/NavGridTools/findOffset.sqf, A3-Antistasi/functions/Base/fn_createOutpostsFIA.sqf, A3-Antistasi/functions/Garage/fn_attemptPlaceVehicle.sqf
1. [ ] Bug
2. [ ] Change
3. [x] Enhancement/Refactor
Information:
* All empty silentHints remain as they cover up closing hintC (hint context).
* All hints have been made into customHint (outside UPSMON, commsMP is fine.)
* A3A_fnc_customHint is defined if not defined in 3 navGrid files.
closes #1608 https://github.com/official-antistasi-community/A3-Antistasi/issues/1608
1. [ ] No
2. [x] Needs quick test
Steps: Copy past hints into the console, to try to trigger them naturally.
=> All hints are customHint, navGrid can run without customHint.

A3-Antistasi/JeroenArsenal/JNL/Functions/fn_logistics_classHasCargo.sqf, A3-Antistasi/JeroenArsenal/functions.hpp, A3-Antistasi/Templates/3CB_Inv_Sov_Temp.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Arctic.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Temp.sqf, A3-Antistasi/Templates/3CB_Occ_BAF_Trop.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/CREATE/fn_createAIResources.sqf, A3-Antistasi/functions/init/fn_initServer.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
1. vehFIATruck is required to be a passenger-capable truck by the QRF vehicle selection. Cases where it was not a passenger truck have been changed. Note that before 2.3, vehFIATruck was only used for outpost trucks, so this wasn't a bug until 2.3.
2. 3CB BAF MAN transport trucks are not cargo-capable, unlike every other passenger truck used in Antistasi. Outposts, resources and factories ideally have a truck capable of carrying the loot crate, so I added a filter to make sure that they do. This required adding functionality to JNL and precaching in initVarServer (because it's a very slow check), which led to changing the server init order so that JNL inits before initVar. This is actually the same order as initClient. It's probably fine.
closes …
=> Fix cargo/passenger truck problems

A3-Antistasi/functions/LTC/fn_carryCrate.sqf, A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf, A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
1. [x] Bug
2. [ ] Change
Information: single mags looted from containers (not bodie) could duplicate mags due to addMagazineAmmoCargo now adding a magazine regardless if ammo count are 0. (this does not happen when magazine count is 0)
it now exits out if theres no remainder to be added (only full magazines)
closes #1582
1. [x] No
Steps: drop a backpack with a single count magazine (example: m112 explosive charge), then use a LTC crate to loot the backpack from the ground. you should have exactly what you dropped and no duplicated items …
=> Fixed duplication of single mags

A3-Antistasi/functions/AI/fn_mineSweep.sqf, A3-Antistasi/functions/REINF/fn_equipRebel.sqf
1. [ ] Bug
2. [ ] Change
Information:
Removed not working lines in Fn_Minesweep,
Added Minedetectors to SDKexp, 
-------> It would cost a lot to try to farm Minedetectors by Ordering Minefield Placement and Removal.
Also they don't drop of their Equipment when disbanding, only way to farm is to kill them/let them die.
(500€ for one)
enabled Minedetection on SDKexp to try to prevent them from stepping on Mines.
It does improve their Performance at trying to clear Minefields and makes them sort of Usable again.
Changed Detected Mines to allMines, so they will always look for Mines when within the Radius.
Updated Group Format to fit like all other HC Squads.
Lowered Timeout time.
closes parts of #1593 not everything
2. …
=> Improve "Explosive Experts"/ Improve Minesweep

A3-Antistasi/functions/UI/fn_customHint.sqf, A3-Antistasi/functions/UI/fn_customHintDismiss.sqf, A3-Antistasi/functions/UI/fn_customHintInit.sqf, A3-Antistasi/functions/UI/fn_customHintRender.sqf
* Bug
* Change
The icon space of hints is used to display the headings of previous hints.
See picture at the footer for a visual comparison.
closes 1611 https://github.com/official-antistasi-community/A3-Antistasi/issues/1611
1. [ ] No
* Yes (Needs independent testing.)
Also, please voice any opinions or suggestions about colour size etc.
Steps: 
Create many hints, see if it is visually acceptable.
See documentation in fn_customHint to create from debug console.
***
=> Use Icon space to display previous hint titles.

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/Base/fn_sellVehicle.sqf
1. [x] Bug
* Change
* Enhancement
* Vehicle Sales are not processed on the server.
* "A3A_sellVehicle_inProgress" is made true on vehicles being sold. (This is only checked on the server)
* This change fixes the sell-vehicle exploit abused to gain infinite money.
Please check [2e2d20e](https://github.com/official-antistasi-community/A3-Antistasi/pull/1615/commits/2e2d20ecbf427190c788298eb6689503bc0d5454) for functional changes.
closes #1613 https://github.com/official-antistasi-community/A3-Antistasi/issues/1613
1. [ ] No
* Yes (Give it to an expert exploiter)
On dedicated server: look at a sellable vehicle and run the code below
```sqf
for "_i" from 1 to 1000 do { …
```
=> Fix spam sell vehicle exploit

A3-Antistasi/MissionDescription/CfgDebriefingContents.hpp, A3-Antistasi/MissionDescription/CfgFunctionsContents.hpp, A3-Antistasi/MissionDescription/CfgSoundsContents.hpp, A3-Antistasi/MissionDescription/master.hpp, Map-Templates/Antistasi-Altis-BLUFOR.Altis/description.ext, Map-Templates/Antistasi-Altis.Altis/description.ext, Map-Templates/Antistasi-Anizay.tem_anizay/description.ext, Map-Templates/Antistasi-Chernarus.chernarus_summer/description.ext, Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext, Map-Templates/Antistasi-Kunduz.Kunduz/description.ext, Map-Templates/Antistasi-Livonia.Enoch/description.ext, Map-Templates/Antistasi-Malden.Malden/description.ext, Map-Templates/Antistasi-Stratis.Stratis/description.ext, Map-Templates/Antistasi-Takistan.takistan/description.ext, Map-Templates/Antistasi-Tembelan-Island.Tembelan/description.ext, Map-Templates/Antistasi-Virolahti.vt7/description.ext, Map-Templates/Antistasi-WotP.Tanoa/description.ext
* Bug
* Change
* Common Description.ext contents moved files to MissionDescription.
* Due to instances where a map template has some custom scripts, CfgXX class is still defined there and includess contents from MissionDescription\CfgXXXContents.
* Idea: 0060 Move the All the non specific information from description.ext into the MissionDescription Folder, would make adding sub functions and defines easier.
* 0060 - Yes will be done. Everything besides the strings, as well as the picture references and class CfgDebriefing will be put in one file so we only have one include in the description.ext
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1619
3. [ ] Have you loaded the mission on a dedicated …
=> Common Description.ext contents moved to MissionDescription

A3-Antistasi/functions/CREATE/fn_createCIV.sqf
that pops up almost every time when civs are create in some maps
1. [x] Bug
2. [ ] Change
Information:
when I debugging mission the error in this file pops up on the server almost every time
``` 5:38:21 "Triada/log: ERROR: [BIS_fnc_dirTo] Error: type ARRAY, expected OBJECT, on index 0, in [[10589,4694,0],array]"
5:38:21 Error in expression <Pos (_roadcon select 0);
_dirveh = [_p1,_p2] call BIS_fnc_DirTo;
_pos = [_p1, 3,>
5:38:21   Error position: <_p2] call BIS_fnc_DirTo;
_pos = [_p1, 3,>
5:38:21   Error Undefined variable in expression: _p2
5:38:21 File functions\CREATE\fn_createCIV.sqf [A3A_fnc_createCIV]..., line 62
5:38:21 "5521.52: [Antistasi] | INFO | fn_scheduler | Scheduled function: A3A_fnc_createAIcontrols, Function params: [""control_85""]"
5:38:21 …
```
=> Bug-fix #1648 Script error in the function A3A_fnc_createCIV

A3-Antistasi/MissionDescription/master.hpp
* Bug
2. [x] Change
* Enhancement
* Lists only 1unobtainable key.
* Requires 2 unobtainable keys to be played.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1667
* Have you loaded the mission in singleplayer?  // You'll get a prize for this one
1. [x] No
Steps: 
1. Try load from Scenario menu -> Greyed out and no play button
2. Try localhost or dedicated server -> Works
=> Disable ability to select and play from SP scenario menu

A3-Antistasi/dialogs.hpp, A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3-Antistasi/functions/UI/fn_customHintRender.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
* Bug
2. [x] Change
* Mod load info reduced and is hint message.
* Removed intro shot orbit camera.
* Removed load previous session dialogue, always true.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1670
1. [x] No
Speedrun Load mission, see if you beat the world champ.
Last personal save should be loaded (gear, cash, garage)
=> Removed Start-up Shenanigans

A3-Antistasi/functions.hpp, A3-Antistasi/functions/AI/fn_guardDog.sqf, A3-Antistasi/functions/init/fn_initGetMissionPath.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
* Bug
* Change
3. [x] Performance
* Mission path parsing is now done correctly and does not log non-sense.
* Renamed `ladridos` to `A3A_sounds_dogBark`
* A3A_sounds_dogBark now has full path baked in.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1672
1. [x] No
exec this from debug console. You should hear a dog bark and nothing should appear in the RPT.
```sqf
playSound3D [selectRandom A3A_sounds_dogBark,player, false, getPosASL player, 1, 1, 100];
```
=> Optimised mission root path parsing 

A3-Antistasi/functions/Base/fn_sellVehicle.sqf, A3-Antistasi/functions/Garage/fn_garageVehicle.sqf, A3-Antistasi/functions/REINF/fn_addBombRun.sqf
1. [ ] Bug
2. [X] Change
Information: 
Changed Cannot to Can't, both were used in Hints but for the sake of Consistency i changed it to "can't".
Updated "You can't Garage Plane" Hint in fn_garageVehicle.sqf,
Applied the !Alive check from Garage to fn_addBombRun.sqf,
Applied the "Enemies Near" check from fn_garageVehicle.sqf to fn_addBombRun.sqf,
Added the "In Area" check from fn_garageVehicle.sqf to fn_addBombRun.sqf,
For only HQ and AirportsX, i keept HQ in there for the Poor people that Land a Plane near HQ and Helicopters are fine to Garage at HQ, you can't Pull them out so Airstrike conversion seems alright.
If you have ideas to improve wording, just tell me.
closes #1289 
2. [X] Have you loaded the mission in LAN …
=> Enable Airstrike conversion for Airfields / Update a few Hints

A3-Antistasi/functions/LTC/fn_lootFromContainer.sqf
1. [x] Bug
2. [ ] Change
Information: blocks LTC crates from transfering to destroyed vehicle, causing the loss of the loot
closes #1675 
1. [x] No
Steps: try loading loot into a destroyed vehicle
Notes:
=> block attempt to transfer to loot to destroyed vehicle

A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/onPlayerRespawn.sqf, A3-Antistasi/orgPlayers/unitTraits.sqf
1. [ ] Bug
2. [ ] Change
Information:
The default commander is now given the medic and engineering trait for people who play solo on local host. Default commander is identified by being the only class to have a role description, so thats a new requirement for porting.
Added the new standard header to the file
Cleaned the calls to the file by removing unnecessary parameters
None opened for it
1. [ ] Have you loaded the mission in singleplayer? -> Functionality is MP only
1. [X] No
Steps: 
Select Default Commander on role selection screen and join in, after 5 seconds you should see the text saying you choose commander …
=> Gave default commander medic and engi, updated calls, added header

Map-Templates/Antistasi-Malden.Malden/mission.sqm
1. [x] Bug
2. [x] Change
Updated the location of outpost_12, Outpost now supports ammo missions.
closes #1636 
1. [x] No
Steps: Start the mission and run the following as local:
```[["outpost_12"],"A3A_fnc_LOG_Ammo"] remoteExec ["A3A_fnc_scheduler",2]```
Notes:
Need to verify the quality of outpost. @Bob-Murphy 
Check that the props used do not require DLC ownership ("A3_Props_F_Exp")
=> Fixed Malden outpost_12 (Bad mission spawner)

A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf
1. [x] Bug
2. [ ] Change
Information:
fix a bug preventing getting in mounted statics if there was a dead unit in it.
closes #1708
1. [x] No
Steps: try to get in it using the action on the vehicle, in the 3 different states: none in it, someone in it, someone dead in it.
this should result in: gets in, is blocked, gets in.
Notes:
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Fix logi Mount Block

A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_toggleLock.sqf
1. [x] Bug
2. [ ] Change
Information:
towing cargo loaded would result in funny behavior, i stow towropes off from and to the cargo as its loaded, attaching new towropes while cargo is prevented as cargo is locked when loaded. also added a small qol of turning off the engine of the cargo
closes #1459
1. [x] No
Steps: 
Notes:
=> Hr fix block towing off logistics cargo

A3-Antistasi/Templates/detector.sqf
Included 3CB Factions to ensure Petros gone issue being gone.
1. [x] Bug
2. [ ] Change
Information: Added 3CB Factions to 3CB Detection, due to it missing People would still face Petros gone issues and Issue of Missing a lot of Vehicles + Weapons.
Removed a False check for a Class that never existed, 3CB Detection never worked.
closes #1709 
1. [x] No
Steps: Load with all Requiered mods,
Try to load 3CB without 3CB Factions.
Notes:
=> Add 3CB Factions to 3CB Detection to Prevent Petros gone.

Tools/sqf_validate.py
* Bug
2. [x] Change
* Enhancement
Information:
SQFValidate.py has been throwing far too many false positives. Some of them are unacceptable. Until the validation is updated, it should be disabled. Because I do not have access to Travis, this change forces it to return 0.
1. [ ] No
Steps: 
This SQFValidate.py should always pass.
=> Disabled SQF Validate, always returns valid.

A3-Antistasi/functions/AI/fn_napalm.sqf, A3-Antistasi/functions/AI/fn_napalmDamage.sqf
* Change
* Enhancement
* #️⃣ Napalm checks that a player has a UID before trying to save it and render the fire particles.
* Without this, a player that joined before it's UID propergated to the server: will make getPlayerUID return "" which will not save and cause the player to atleast double render.
* ♨Damage will fall back to global damage if hitPoints can not be retreived. 
* ⚡ Hidden objects (commonly Zeus) will no longer burn and take damage.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1724
1. [ ] No
1.  Spawn napalm `[screenToWorld [0.5,0.5]] remoteExec  ["A3A_fnc_napalm",2];`
2.  Have other …
=> 🔥 Napalm Checks that Player has UID

A3-Antistasi/functions/Dialogs/fn_buyVehicleCiv.sqf
1. [x] Bug
2. [ ] Change
Information:
Corrected the wrong type given in Dialogs for Civboat.
closes #1752
1. [ ] No
Steps: The Civ buy menu should display the correct name of the Boat now.
Notes:
=> Changed SDKBoat to CivBoat in fn_buyVehicleCiv.sqf

A3-Antistasi/functions/LTC/fn_carryCrate.sqf
1. [x] Bug
2. [ ] Change
Information:
moved the force walk set into the waitUntil loop, this will reapply it even if ace resets it, kind of heavy handed but didnt have a noticeable performance impact and command is local only so no network trafic
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fix ace stamina disabling force walk while carrying LTC crate

A3-Antistasi/functions/Dialogs/fn_createDialog_shouldLoadPersonalSave.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf, A3-Antistasi/functions/init/fn_initParams.sqf
1. [X] Bug
2. [ ] Change
When the variable name for the parameter table was changed from paramTable to A3A_paramTable during the review process, I missed one case in the save code, so it wasn't saving the parameters.
Also fixed an incorrect autoSave default in the parameter table, and a minor issue where the autoSave interval was mis-reported in a startup hint.
closes #1761
1. [X] No
=> Fix parameters not saving

A3-Antistasi/MissionDescription/params.hpp
* Bug
* Enhancement
Added 1e6 (1 000 000) to the arsenal unlock amount list. 
One Million Guns (Doctor Evil voice https://youtu.be/cKKHSAE1gIs?t=14).
It will serve as a stop gap until a better solution replaces what we have now.
These people will need to accept that they must manually arm their AI if they want to give them better weapons (I believe the AI take unlocked guns?).
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1774
1. [x] No
Steps: 
Select 1 000 000 as unlock limit, spawn in many guns.
=> CS-1774-OneMillionGuns

A3-Antistasi/functions/Utility/fn_log.sqf
* Bug
* Change
log info is converted to structured text before being fed into diag_log
Allows log colour filtering without having to remove quotations manually. Quotations do not need to be there. Requires addition of text between diag_logand an input string.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1773
Steps: 
Load antistasi, examine log output.
=> CS-1773-NoEscapedLogStrings

A3-Antistasi/functions/AI/fn_airdrop.sqf, A3-Antistasi/functions/CREATE/fn_createAttackVehicle.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf
1. [X] Bug
2. [ ] Change
Information:
The new support QRFs tried to paradrop entire squads near the AI limit, which then resulted into paradropping one guy.
Readded the block, the ensures that this isnt happening. Also decreased the radius in which they can drop, so it doesnt take forever for them to arrive.
None opened for that
1. [X] No
Steps: Was on the test server during the large test, no further testing required
Notes:
=> Fixed paradrops, distances and unit counts

A3-Antistasi/functions/Punishment/fn_punishment_FF.sqf
* Bug
2. [x] Change
Checks for obj null.
Checks for is player.
The extra info is not needed.
1. [x] No
Steps: 
Crash into tree -> no log.
Get shot by AI -> no log.
=> Damage does not log AI or Null

A3-Antistasi/functions/CREATE/fn_spawnVehiclePrecise.sqf
1. [x] Bug
* Change
* Enhancement
Fixed creating a new nested private field rather than setting the parent scope's variable.
1. [x] No
Spawn rebel crewed LSV in proximity to the player.
Spawn rebel LSV nearby
```sqf
private _vehicle = ["B_T_LSV_01_armed_F",getPos player, 0, 20] call A3A_fnc_spawnVehiclePrecise;
_unitType = [_side, _vehicle] call A3A_fnc_crewTypeForVehicle;
[resistance, _vehicle, _unitType] call A3A_fnc_createVehicleCrew;
```
Spawn empty LSV on roof above you
```sqf
private _myPos = getPosWorld player;
_myPos = [_myPos#0,_myPos#1,0,"AGLS"];  // Spawn 0m above highest roof above the player.
["B_T_LSV_01_armed_F",_myPos] call …
```
=> CS-spawnVehiclePresice-FixedAircraftDetection

A3-Antistasi/functions/init/fn_initVarServer.sqf
This was forgotten by accident
1. [x] Bug
2. [ ] Change
Information:
Added the Small UAV Drones to _VehUAVs in InitVarserver which is used
this should allow fn_initVehClassToCrew to select Ai for the Small UAVs and not default to Rifleman D:
closes none
1. [x] No
Steps: I dont have good way of testing besides:
```sqf
A3A_vehClassToCrew getOrDefault 
[vehNATOUAVSmall,[NATOGrunt, CSATGrunt, staticCrewTeamPlayer, "C_Man_1"]] select 0;
```
This should return one of these, depending on Side: ["B_UAV_AI", "O_UAV_AI", "I_UAV_AI", "C_UAV_AI"]],
Notes:
=> Fix Crew Selection for UAVsmall

A3-Antistasi/functions/Ammunition/fn_arsenalManage.sqf
1. [X] Bug
2. [ ] Change
Fixed RPT errors when the arsenal unlock routine runs with zero-cap or broken magazine configs in the arsenal. The code now assumes the magazine capacity is 1 if zero or missing.
Shouldn't have any side effects, although it's possible that other code will behave oddly with zero-cap or broken magazine configs.
closes #1799 
closes #1658
1. [X] No
=> Prevent arsenalManage errors on zero-cap or broken magazine configs

A3-Antistasi/functions/AI/fn_AIreactOnKill.sqf
1. [X] Bug
2. [ ] Change
Fixed error introduced in refactor which could cause divide-by-zero RPT errors.
Because AIReactOnKill has significant execution time, `count units _group` is not necessarily non-zero by the end, even if it is at the start.
closes #1733
1. [X] No
=> Fix occasional divide-by-zero in AIReactOnKill

A3-Antistasi/functions/LTC/fn_lootToCrate.sqf
1. [x] Bug
2. [ ] Change
Information:
non local bodies looted with ltc would not remove the original hmd and (reportedly sidearm)
moved to setUindLoadout to ensure bodies are stripped
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fix-LTC-nonLocalBodiesDupe

A3-Antistasi/REINF/addToGarrison.sqf
1. [x] Bug
2. [ ] Change
Information:
Added TypePetros to the check to prevent units from being added to a Garrison.
Updated the Hint, in case someone wonders why they can't add Units to a Garrison.
closes #1808 
1. [x] No
Steps: 
Move HQ, Select Petros, try adding Petros to a Garrison, this should throw the Unable to Garrison hint.
Notes:
=> Prevent Petros from being added to Garrisons

A3-Antistasi/functions/init/fn_initZones.sqf
1. [X] Bug
2. [ ] Change
During the new pathfinding merge, the code that places town markers on the nearest road rather than the location marker was accidentally disabled, making some city supply missions on Tanoa impossible and probably breaking other functionality. This PR restores that functionality by using nearestTerrainObjects to find a suitable road, as that function is surprisingly fast.
Note that placements are sometimes far from the real centre of the town, but better placement can wait.
closes #1817
1. [X] No
I've only checked Tanoa so far but I'm fairly confident in the method.
Load up mission on various maps, check that city markers are placed on a semi-reasonable road.
=> Fix town markers not being placed on roads

A3-Antistasi/functions/Missions/fn_missionRequest.sqf
1. [X] Bug
2. [X] Change
Minor tweaks to mission request:
- Prevent ammo truck missions at spawned outposts. They'd often spawn under your nose when you were attacking an outpost, making a right mess.
- Allow mission creation at suspended (`spawner getVariable _marker == 1`) markers. This is harmless and makes mission selection broader and more consistent over time.
- Increase chance of DES_Heli mission. It's a fun mission and people haven't seen it enough. DES_Vehicle is not very interesting.
Hakon has a project to purge the entire missions system, but this is a short-term tweak.
closes #1546
1. [X] No
Feel free to request some missions.
=> Minor improvements to mission request

A3-Antistasi/REINF/addToGarrison.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug where troops added to unspawned garrisons were deleted before their types were determined, causing empty strings or nulls to be added to the garrison, depending on whether it was 2.4 or earlier. The bug is old but it was previously disguised by the empty strings being counted in the garrison.
Also fixed spawner status being retained on troops added to spawned garrisons, which will have prevented enemies from despawning in some common cases.
closes #1829
closes #1814
1. [X] No
Tested all four standard cases: Squad AIs to unspawned & spawned, HC squads to unspawned and spawned. I didn't test the case that returns troops to HC squad status if their target (spawned) garrison is captured, …
=> Fix adding rebel units to unspawned garrisons

A3-Antistasi/functions/Base/fn_distance.sqf
1. [X] Bug
2. [ ] Change
A bug added in the fn_distance refactor prevented the rebel city garrison spawning code from executing. This PR restores the call.
closes #1836
1. [X] No
There's a general (old) problem with the civ and military spawning functions not being fully synchronized though, which may cause civilian vehicles to be inappropriately spawned or not spawned. Could maybe fix with separate spawner tags but that's a much tougher problem.
=> Fix rebel city garrisons not spawning

A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf, A3-Antistasi/functions/Supports/fn_SUP_mortar.sqf, A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [x] Bug
2. [ ] Change
Information:
Added Mortar HE Ammo for CSAT/Nato Faction.
Removed 2 missed Cargotrucks with Loaded box from BAF Factions.
closes #1842 
1. [x] No
Steps: 
Probably miss used the Command but it works:
```sqf
tierWar = 6; 
[Occupants, 0, "MORTAR", getpos (player), 1, 4] spawn A3A_fnc_createSupport;
```
Notes:
=> Add Factions Mortar HE ammo / BAF Template remove Cargo Trucks

A3-Antistasi/functions/Utility/fn_log.sqf
1. [x] Bug
* Change
* 🔠 log uses localLog for remote logging.
* ↔ log function output format unified with maco. 
1. [x] No
Steps: 
1. Use the Arma 3 Launcher to start a dedicated server.
2. use `[1, "or thank vacation", "very filed"] call A3A_fnc_log;`
3. Check that log goes to the server
4. Check that there is no serialisation warning
5. Check that the error format matches the multitude of errors thrown when Antistasi starts up.
This will conflict for into master branch merge, it should completely replace the old file.
=> Logging serialisation warning hotfix. Format unified with macro.

A3-Antistasi/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [X] Bug
2. [ ] Change
The disabled code was never correct: It sets too many values (ctrlSetTextColor is sufficient) which causes icon blanking, and appears to be setting the wrong indices anyway. I suspect that until Arma 2.02 the bugs cancelled each other out and the function had no effect at all, but now it causes the icons to be blanked.
This PR restores the previous behaviour by disabling the icon-colouring code. Substantially more effort would be required to make it work as originally intended (colouring category tabs already present in the vehicle inventory), and the functionality isn't important.
closes #1803
1. [X] No
=> Disable incorrect icon-colouring code in vehicle arsenal

A3-Antistasi/Templates/NewTemplates/#Examples/FactionExample.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arctic.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_BAF_Tropical.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_US.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_West.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_USAF_Marines_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf, A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [x] Bug
2. [ ] Change
Information:
Added Nato Unarmed in each Template including the Example,
Added the added Prefix to Natounarmed in fn_compatabilityLoadFaction
Added CSAT Unarmed in Compatfile
Not linked on purpose:
Solution 1 of #1834 
1. [x] No
Steps: 
Execute this on an Occupant Town, it should spawn Civies.
```sqf
//Target, Origin
//Targets are Cities in CitiesX
["Georgetown01", "airport_1"] spawn A3A_fnc_invaderPunish;
```
Creates Civs the same way as the Traitor Mission does right now, just in your Group
```sqf
_civ = [group player, NATOUnarmed,player, [],0,"NONE"] call A3A_fnc_createUnit; 
_civ …
```
=> Fix NatoUnarmed Loadout

A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
1. [ ] Bug
2. [x] Change
Information:
Removed Civ uniforms being given as its given by A3A_fnc_civInit,
Removed random 10% chance of Civ not getting any weapon,
Changed Weapon Selection to use Unlocked Equipment to ensure Template based equipment.
```sqf
_rnd = random 100; 
if (_rnd < 75) then { 
[_civ, selectRandom (unlockedsniperrifles + unlockedshotguns + Unlockedrifles + unlockedsmgs), 5, 0] call BIS_fnc_addWeapon;  
} else {  
[_civ, selectRandom (unlockedmachineguns + unlockedshotguns + Unlockedrifles + unlockedsmgs), 5, 0] call BIS_fnc_addWeapon;
```
Sniperrifles as the Kar98 and other Bolt Action Weapons count towards that Category,
SMG as thats the Vanilla Starting Equipment on most Terrains,
Shotgun as thats used in RHS, 3CB Factions and possibly even future …
=> Remove Vanilla Weapons from Punishment/Change weapon selection on INV Punishment

A3-Antistasi/functions/Supports/fn_SUP_gunshipAvailable.sqf
1. [x] Bug
2. [ ] Change
Information:
Added a HasRHS to the Gunship Availible Check, as all Modsets exept Vanilla are build on RHS, the Gunship will be disabled in every other Modset than Vanilla.
There are better solutions but this will do for now.
closes #1855
1. [x] No
Steps: 
Notes:
=> Disable Gunship on everything exept vanilla

A3-Antistasi/functions/Save/fn_loadServer.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf, A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [X] Bug
2. [X] Change
Turns out setPosATL/getPosATL is absolute trash on Sahrani, spawning vehicles halfway through the ground and either hurling them into the air or dropping to -200. It wasn't amazing on other maps, causing minor position shifts and the occasional vehicle explosion. setPosWorld/getPosWorld seems to give near-perfect results.
- Switched new saves to getPosWorld/setPosWorld.
- Stick to setPosATL for old saves, because the Z coord will be incompatible.
- Changed statics to use up/dir vectors as they were overlooked before.
- Added a basic version number system to the load/save code to handle backwards compatibility.
closes #1816
1. [X] No
Default Sahrani start. Spam a few vehicles and statics around …
=> Switch to using setPosWorld/getPosWorld for saved vehicle positions

A3-Antistasi/functions/CREATE/fn_createVehicleCrew.sqf
1. [X] Bug
2. [ ] Change
Antistasi's createVehicleCrew (added in 2.4) sets the group leader to the commander. Some vehicles (such as the AT cars) don't have a commander slot (`commander _veh` returns null), but the driver isn't the effective commander. This causes the group to act very oddly when given waypoints. I don't know if this was also a problem for enemy vehicles.
This PR sets the group leader to `effectiveCommander` instead, which will hopefully work correctly in all cases. Another option would be to set the effective commander to the leader if there's no commander, but that seems riskier.
closes #1861
1. [X] No
Recruit rebel AT cars, give them high command orders.
=> Fix createVehicleCrew leader selection

A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf
1. [X] Bug
2. [X] Change
The airstrike code was adding the initial speed from createVehicle with FLY (152m/s for an A-10) to a fixed 150m/s, giving an excessive starting speed that may have been causing apparent late spawns.
This PR simplifies the spawning code a bit and sets the initial speed to 100m/s regardless of aircraft. I considered using the stalling speed with a minimum of ~100m/s (starting too slow would delay the airstrike), but as no plausible aircraft have a stalling speed below 100m/s anyway, the complexity would have had no effect.
closes #1864
1. [X] No
Enable at least one airstrike for occupants:
`occupantsAirstrikeTimer set [0, -1]` run as server
Clear the last support type, in case it was airstrike: …
=> Set initial airstrike aircraft velocity to reasonable value

A3-Antistasi/functions/AI/fn_combatLanding.sqf, A3-Antistasi/functions/AI/fn_fastrope.sqf, A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf, A3-Antistasi/functions/Supports/fn_SUP_ASFRoutine.sqf, A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf, A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineCSAT.sqf, A3-Antistasi/functions/Supports/fn_SUP_gunshipRoutineNATO.sqf
1. [X] Bug
2. [ ] Change
The new support system added a lot of incorrect setWaypointStatements calls. Two common problems:
1. Empty-string conditions. These were probably never called, hence the backup aircraft-deletion routines.
2. Global execution. Very bad for attackDrillAI. Probably caused the A-10 ejection seat spam too.
closes #1869
1. [X] No
Could probably improve the aircraft despawn code based on the airstrike code from 2.3.1, but that's a lot more work.
=> Fix setWaypointStatements calls from support system

Map-Templates/Antistasi-ChernarusWinter.chernarus_winter/description.ext, Map-Templates/Antistasi-Sahrani.sara/description.ext, Map-Templates/Antistasi-Takistan.takistan/description.ext
1. [X] Bug
2. [ ] Change
- Takistan and Sahrani were missing CfgNotifications, causing blank support notifications on those maps.
- Chernarus Winter was missing CfgSounds, potentially causing missing sounds.
closes #1877
1. [X] No
=> Fix description.ext for Sahrani, Takistan and Chernarus Winter

A3-Antistasi/functions/Templates/Itemsets/fn_itemset_medicalSupplies.sqf
1. [x] Bug
2. [ ] Change
Information:
Changed A3A_hasACE to A3A_hasACEMedical in fn_itemset_medicalSupplies.sqf
The same mistake is still in GetLoadout, but that is unimportant.
closes #1879 
1. [x] No
Steps:
Load an Up to Date Ace without Medical,
Find Occupant/Invader Ai and check their Inventory they should have Vanilla Medical Equipment.
Or use this:
```sqf
[group player, "loadouts_occ_military_Rifleman", getpos (player)] call A3A_fnc_createUnit; 
[group player, "loadouts_occ_military_Medic", getpos (player)] call A3A_fnc_createUnit;
```
Spawn Units, Check their Inventory they should have Vanilla Medical …
=> Fix Ace without Medical for Ai (Equipment)

A3-Antistasi/functions/AI/fn_liberatePOW.sqf, A3-Antistasi/functions/AI/fn_liberaterefugee.sqf, A3-Antistasi/functions/Missions/fn_RES_Prisoners.sqf, A3-Antistasi/functions/Missions/fn_RES_Refugees.sqf
1. [X] Bug
2. [ ] Change
Fixed a lot of locality and JIP bugs with the prisoner and refugee missions. Should be about as solid as it's going to get.
Released prisoners will still struggle to leave some buildings, but that's just Arma pathing. Zeus-spawned troops have the same problem. Remote control is the workaround.
closes #1574
Tested with HC, as that's the primary fail case.
1. [X] No
These missions can be pretty tough because occupants will happily drop airstrikes and mortar supports on the prisoners. Should do something about that.
=> Fix various locality and JIP problems with prisoner and refugee missions

A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_CW_SOV.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_East.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_AI_TKA_Mix.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_AFRF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_AI_CDF_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
1. [x] Bug
2. [ ] Change
Information:
Removed bad Weapon - Attachment combinations that caused RPT Entries
Like:
```
2021/03/20, 04:43:40 [weapon rhs_weap_akmn]: item[rhs_acc_perst1ik] does not match to this weapon!
2021/03/20, 21:39:23 [weapon SMG_01_F]: item[acc_flashlight] does not match to this weapon!
2021/03/25, 10:22:00 [weapon SMG_03C_black]: item[acc_flashlight] does not match to this weapon!
2021/03/26, 22:41:24 [weapon rhs_weap_akms]: item[rhs_acc_dtk] does not match to this weapon!
2021/04/09, 15:50:52 [weapon rhs_weap_akmn]: item[rhs_acc_dtk] does not match to this weapon!
2021/03/26, 22:42:11 [weapon rhs_weap_akmn_gp25]: item[rhs_acc_dtk] does not match to this weapon!
2021/03/27, 07:33:42 [weapon rhs_weap_akms_gp25]: item[rhs_acc_dtk] does not match to …
```
=> Fix not Matching Attachment

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/Utility/fn_vehicleTextureSync.sqf
1. [X] Bug
2. [ ] Change
Added a function to network-synchronize vehicle textures if necessary. This is a bit cheaper than using BIS_fnc_initVehicle, which also searches for and applies a new random texture. There's also an optimization to avoid the sync if the vehicle lacks texture variants.
Called from AIVEHinit, as that's conveniently called shortly after vehicle creation.
closes #1885
1. [X] No
1. On a DS, go to a city and admire the pretty vehicle colours.
2. On a DS, get some vehicles out of your personal garage. Log off and on again. Check that the vehicles are the same colour.
=> Synchronize vehicle textures so that everyone sees the same colour

A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [x] Bug
2. [ ] Change
Information:
Updated Sanity check with 2 new Magazine Vars,
Silenced it about Loadouts and "Not_supported" as it wont find these in CFG Vehicles
closes nothing
1. [x] No
Steps: Start the Mission,
Check the RPT: Entries like:
```
| Antistasi | Error | File: fn_initVarServer.sqf | Missing classnames: ["loadouts_rebel_militia_Petros","loadouts_rebel_militia_staticCrew","loadouts_rebel_militia_Unarmed","loadouts_rebel_militia_sniper","loadouts_rebel_militia_lat","loadouts_rebel_militia_medic","loadouts_rebel_militia_MachineGunner","loadouts_rebel_militia_ExplosivesExpert","loadouts_rebel_militia_G …
```
=> Silence Sanity checks RPT spam

A3-Antistasi/functions/CREATE/fn_safeVehicleSpawn.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug where safeVehicleSpawn was spawning air vehicles on the ground (with FLY velocity and suicidal consequences) due to unexpected behaviour of findEmptyPosition. 
Also fixed an old bug where the placement randomization was only using one quadrant of the available space.
closes #1891
1. [X] No
There's probably a lot of other broken behaviour but there shouldn't be anything *new*.
`["B_T_VTOL_01_infantry_F", getpos player, 100, 5, true] call A3A_fnc_safeVehicleSpawn`
=> Fix safeVehicleSpawn to spawn air vehicles in the air

A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
1. [X] Bug
2. [ ] Change
The switch in createQRFVehicleBehaviour was not picking the right code for some vehicle types. Tracked APCs used the tank code (with no troop unload) and wheeled APCs and MRAPs used the truck code (all crew disembarked). Transport aircraft used the attack aircraft code (no paradrop), although these suicided on spawn anyway (see #1892).
This PR fixes the incorrect cases. The behaviour is not great due to dodgy old waypoint code and excessive pathfinding waypoints, but it does basically work.
Also fixed some ancient broken setWaypoint radius parameters (probably didn't matter, but it was wrong and confusing), and pulled the vehicle marker name fixes from 2.3.2.
Note that the code for the cases is largely unchanged but github doesn't know that. …
=> Fix QRF APCs and transport aircraft using the wrong behaviour

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_canMoveHQ.sqf, A3-Antistasi/functions/Base/fn_moveHQ.sqf
1. [ ] Bug
2. [ ] Change
Information:
Split the moveHQ function into two functions (moveHQ and canMoveHQ), where canMoveHQ contains all checks and returns the reasons if that is not possible. MoveHQ contains the steps to actually start the HQ moving process.
moveHQ has been updated with the new headers, replaced all tabs with spaces and restructured to code to a readable form.
There are no gameplay or mechanic changes. This is done for Dooms UI rework to work.
closes #1794
1. [X] No
Steps: 
Notes: There are still tabs in functions.hpp which should be removed, …
=> Doom move hq split

A3-Antistasi/cba_settings.sqf
Unfortunately we missed settings this for 2.4.1.
This settings are kinda needed to not interfere with the stuff we give AI and such.
=> TFAR BETA settings update

A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf, A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf, A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
1. [x] Bug
2. [ ] Change
Information:
Due to VN Counting towards Vanilla, the Vanilla filtering removed almost all VN Items
Improved fn_equipmentIsValidForCurrentModset a bit,
Changed FirstAidKit removal to avoid removal of VN FirstAidKits,
Changed DLC Filtering, added a Category for CDLCs and BIDLCs
Added a few Possible TFAR/Ace Names to ensure Item filtering to work.
closes #1908 
closes #1905 
1. [x] No
Steps: 
Type
```sqf
Allweapons
```
Into the Debug console on a Server.
It should return only VN Weapon/Weapons at all, as everything was removed earlier
Type
```Sqf
AllRadios
```
Into the Debug console, it should …
=> VN, Fix Missing Item / Expand Item Filtering

A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf, A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf, A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf
1. [x] Bug
2. [ ] Change
Information: the old ``_remove`` var was left over in the IFA check, still dont know why the last line will remove everything if commented back in, if @jaj22, @Spoffy , or @CalebSerafin  can take a look and figure it out i would appreciate it, note it only breaks on DS, works perfectly on LH.
closes #XXXX
1. [x] No
Steps: load in check the variable ``allWeapons`` it should only have appropriate items, not when running VN with GM on you will have GM items too unless you blacklist GM
Notes:
=> fix error from equipmentIsValidForCurrentmodset

A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_PAVN.sqf
1. [x] Bug
2. [ ] Change
Information:
Due to VN DLC having (Almost) Infinite Load Capacity on their Boxes, loot boxes are currently broken and will be able to take way to many Items giving Players a massive advantage.
VN Boxes maximumLoad = 1e+010; while our Surrenderboxes have maximumLoad = 2000;
For now i changed the LTC/Surrender boxes to the Previous variant as that one has a Limit.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> VN Change Loot boxes due to Infinite Load

A3-Antistasi/functions/Revive/fn_actionRevive.sqf
1. [ ] Bug
2. [ ] Change
Cleaned up fn_actionRevive and rewrote the second half to be more stable and allow faster revive cancellations. The AI function that calls this (fn_help) is an abomination but this seems to be compatible with it.
Based on vn-development to avoid later merge conflicts.
Note that `switchMove ""` is a faster cancel but ultra-janky. This seems to be a good compromise.
closes #1930
1. [X] No
1. Revive some AIs, cancel halfway.
2. Let AIs revive each other, try shooting the reviver halfway to make them cancel.
=> Enable faster vanilla revive cancels

A3-Antistasi/JeroenArsenal/JNA/fn_arsenal.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_addItem.sqf, A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf, A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
1. [x] Bug
2. [ ] Change
Information:
Applied the TFAR Fix for ACRE with slight changes to work with ACRE.
Added ACRE Items to Gadgets so they could apear in Loot.
Using the Category Radios might cause Errors in the Future as ACRE does not use the Radioslot, so linkitem will not work with it.
closes #1949
1. [x] No
Steps: 
Equip ACRE Radios in the Arsenal,
Open and close the Arsenal, they should not stack differently.
Notes:
=> Add ACRE Items to Loot, Fix ACRE items unlocking/Stacking

A3-Antistasi/functions/CREATE/fn_createUnit.sqf, A3-Antistasi/functions/CREATE/fn_registerUnitType.sqf, A3-Antistasi/functions/Templates/fn_compatabilityLoadFaction.sqf
1. [ ] Bug
2. [ ] Change
Implemented type-dependent classes for rebel AIs. This makes the unit type icons in the command bar work correctly (medics and engineers now have the appropriate symbol), plus the overlay names no longer all say "riflemen". Petros is now "officer", for example.
Each element of customUnitTypes now has an additional parameter for the unit class to be used for that unit type. These are varied for rebel units only, as we don't much care about the UI for enemy troops. 
Also fixed some misnamed loadout -> definition variables, and fixed the incorrect loadout count debug text. Definitions already had an extra parameter of unit traits, so the format apparently changed at some point.
Based on vn-development so that we can get the merge conflicts in …
=> Implement type-dependent classes for rebel AIs

A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf
1. [ ] Bug
2. [x] Change
set max amount to 40 as some cities like Hue have up to 2,000 inhabitants which leads to 200 units spawning
closes #1919 
1. [x] No
=> set max civ amount for punishment-mission

A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Arid.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Civ_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_CNM_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/3CB/3CB_Reb_TKM_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Civ.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Arid.sqf, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Reb_NAPA_Temperate.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_CIV.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Civ.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_FIA_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_Reb_SDK_Tanoa.sqf, A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentIsValidForCurrentModset.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf, A3-Antistasi/functions/Ammunition/fn_loot.sqf, A3-Antistasi/functions/REINF/fn_equipRebel.sqf, A3-Antistasi/functions/init/fn_initVarCommon.sqf
1.  Bug
2. [x] Change
Information:
Added more Uniforms/Headgear to the new Arrays in Reb/Civ Templates,
Changed EquipRebell to use the RebellHeadgear array instead of UnlockedHeadGear,
------> This is to avoid Possible PID issues and to give Rebell AI a Faction fitting look.
Renamed 2 Arrays:
AllCivilianGlasses and AllCivilianHeadgear are now called AllCosmeticHeadgear and AllCosmeticGlasses.
These are the Autodetection Arrays given to the Arsenal, the list will be excessive as before, but this is so player can do their normal Barbie Dressup.
-----> Basicly returning it to how it was before GeneralHasVN
Added 2 False NVGs to the Unknown Category to avoid them spawning.
Split 3CB CIV into Arid and Temperate:
Arid will be Takistani Civs, with their Vehicles, Uniforms and …
=> Dressup simulator

A3-Antistasi/functions/CREATE/fn_cleanserVeh.sqf
1. [ ] Bug
2. [x] Change
Information:
Added getpos to the Cleanup of CleanseVeh, so we could log where something spawned bad.
Basicly changing this:
```
12:24:42 2021-05-30 10:24:42:303 | Antistasi | Debug | File: A3A_fnc_cleanserVeh | UK3CB_BAF_Merlin_HC3_CSAR_DDPM_RM destroyed on spawn
```
to
```
12:24:42 2021-05-30 10:24:42:303 | Antistasi | Debug | File: A3A_fnc_cleanserVeh | UK3CB_BAF_Merlin_HC3_CSAR_DDPM_RM destroyed on spawn at [4555.01,15409.3,0.406067]
```
closes #1967 
1. [x] No
Steps: 
Have something spawn bad,
putting a Vehicle on a Helipad and spawning the Outpost in does cause bad spawns. …
=> Improve logging on Bad spawns.

A3-Antistasi/functions/AI/fn_occupantInvaderUnitKilledEH.sqf
1. [X] Bug
2. [ ] Change
The aggression cost for killing surrendered enemies got lost in #1788. This PR restores it.    
closes #1974
1. [X] No
=> Restore missing aggro penalty for killing surrendered enemies

A3-Antistasi/functions/Base/fn_distanceUnits.sqf
1. [ ] Bug
2. [ ] Change
distanceUnits is heavily used in waitUntil loops, and extremely suboptimal. This PR improves the performance with no functionality changes.
In a test with three rebel HC squads, a handful of blufor spawners and ~145 total units, the speedup was typically 5-10x depending on the location used.
closes #1970
1. [X] No
=> Improve performance of distanceUnits

A3-Antistasi/functions/AI/fn_chooseSupport.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrike.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrikeAvailable.sqf, A3-Antistasi/functions/Supports/fn_SUP_airstrikeRoutine.sqf, A3-Antistasi/functions/Supports/fn_showInterceptedSetupCall.sqf, A3-Antistasi/functions/Supports/fn_showInterceptedSupportCall.sqf
1. [X] Bug
2. [X] Change
- Switch HE/cluster/napalm to an aggro/wartier-based probability.
- Prevent wide-area attacks being routinely used near friendly troops.
- Randomly vary bomb count, halve count for cluster & napalm.
- Use separate larger coverage markers to prevent airstrike spam within small area.
- Preserve the coverage marker for a bit after the airstrike completes.
- Reduce maximum airstrike rate a bit.
- Fix some potential holes in cleanup code.
- Remove unnecessary global variable/marker spam.
- Fix some typos that prevented invader radio keys from working.
I'm not doing much with the support selection in this PR, except for (usually) blocking the area supports from use against friendlies, and changing the code that removes QRFs from the long-range options …
=> Mitigate some issues with the airstrike supports

A3-Antistasi/functions/Base/fn_distance.sqf, A3-Antistasi/functions/CREATE/fn_createAICities.sqf, A3-Antistasi/functions/CREATE/fn_createCIV.sqf, A3-Antistasi/functions/Revive/fn_actionRevive.sqf
1. [X] Bug
2. [X] Change
- Converted fn_distance from findIf to inAreaArray to improve performance.
- Split cities into separate civ & garrison spawns to resolve several issues.
- Fixed a bug where invaders could spawn their own garrisons.
- Fixed a bug where destroyed roadblocks prevented nearby city patrols from spawning.
- Fixed a bug where deleting an AI while reviving caused error spam.
Other than the new civ city spawning, the spawning logic is largely unchanged. It's just faster. Tempted to switch the other spawns over to a time-threshold system instead of the simulation-disabled region, but I'd need to do more practical performance testing to see the pros and cons.
closes #1972
2. [ ] Have you …
=> Spawn-related optimization and bugfixes

A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [X] Bug
2. [ ] Change
controlsX was being expanded by initGarrisons but not publicVariable'd afterwards, which meant that HCs and clients couldn't see the whole list. This caused problems including broken text on the conquer roadblock mission.
The init order is an abomination but this is an easy quick-fix.
closes #1961
1. [X] No
Start game on Altis with DS. Check that `count controlsX` has the same value with both local and server execution.
=> Fix partial distribution of controlsX

A3-Antistasi/Garage/Core/fn_confirm.sqf, A3-Antistasi/Garage/Core/fn_getCatIndex.sqf, A3-Antistasi/Garage/Core/fn_onLoad.sqf, A3-Antistasi/Garage/Core/fn_onUnload.sqf, A3-Antistasi/Garage/Core/fn_reciveBroadcast.sqf, A3-Antistasi/Garage/Core/fn_releaseAllVehicles.sqf, A3-Antistasi/Garage/Core/fn_reloadCategory.sqf, A3-Antistasi/Garage/Core/fn_reloadPreview.sqf, A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf, A3-Antistasi/Garage/Core/fn_toggleLock.sqf, A3-Antistasi/Garage/Core/fn_validateGarage.sqf, A3-Antistasi/Garage/Extras/fn_findMount.sqf, A3-Antistasi/Garage/Extras/fn_isAmmoSource.sqf, A3-Antistasi/Garage/Extras/fn_isFuelSource.sqf, A3-Antistasi/Garage/Extras/fn_isRepairSource.sqf, A3-Antistasi/Garage/Extras/fn_reloadExtras.sqf, A3-Antistasi/Garage/StatePreservation/fn_setAmmoData.sqf, A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf, A3-Antistasi/Garage/StatePreservation/fn_setFuel.sqf, A3-Antistasi/Garage/config.inc, A3-Antistasi/Garage/fn_addVehicle.sqf, A3-Antistasi/Garage/fn_addVehiclesByClass.sqf, A3-Antistasi/Garage/fn_getSaveData.sqf, A3-Antistasi/Garage/fn_initServer.sqf, A3-Antistasi/Stringtable.xml, A3-Antistasi/Templates/NewTemplates/RHS/RHS_Logistics_Nodes.sqf, A3-Antistasi/functions/AI/fn_chooseSupport.sqf
Fixed `hasAce` missing the new prefix in new garage
1. [x] Bug
2. [ ] Change
Information: Current bugs fixed:
- Wrong variable used in chooseSuport breaking support selection #1986 
- missing A3A_ prefix for hasAce var in new garage, breaking source detection and ace cargo info entry
- Added 2 Trucks to CoveredVehicles blacklist to prevent loading static weapons into them.
closes #1986 
1. [x] No
Steps: 
Notes: Should not be merged before end of Testing Tuesday, and a chance to fix remaining bugs found before it is over.
=> Patch for bugs  in unstable found during Testing Tuesday 29.jun

A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf
1. [ ] Bug
2. [x] Change
Information:
While checking Configs for IFA stuff i noticed there is a Handful of False "NVGs", basicly Gloves, Scarfs etc. using the NVG Slot but not providing any other Vision Modes.
And as it seems all of those "NVGs" have this in Common:
```sqf
visionMode[] = {"Normal","Normal"};
```
This also seems to Apply to RHS NVG Configs, so assuming it should not cause future Problems.
closes nothing, but it might be nice to have
1. [x] No
Steps: Check the Array **AllNVGs** on RHS, there should be no "rhs_6m2_1_nvg", "rhs_6m2_nvg", "rhsusf_Rhino". …
=> NVG Cleanup

A3-Antistasi/Garage/config.inc
1. [x] Bug
2. [ ] Change
Information:
This is missing from the Garage currently.
This is already in #1998 but that will be Merged later, so to make sure Statics will still work this is for Unstable.
closes #XXXX
1. [x] No
Steps: 
Buy/Place a Static weapon, Check StaticsToSave in the console, it should return the Statics.
Notes:
=> [Garage] Add Static Weapons to staticsToSave

A3-Antistasi/Garage/StatePreservation/fn_getDamage.sqf, A3-Antistasi/Garage/StatePreservation/fn_setDamage.sqf, A3-Antistasi/Garage/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
Information:
Fixed two bugs in new garage
1) vehicle preservation was slightly inaccurate due to lacking of selectionNames for each hit point.
- Fixed by changing from setHit to setHitIndex.
2) LTC refund would not give player back their money.
- Fixed by correcting resourcePlayer exec from  server to client.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Fix damage preservation and ltc refund

A3-Antistasi/functions/Supports/fn_SUP_CASRoutine.sqf
when setting plane dir
1. [x] Bug
2. [ ] Change
Information:
Fixed wrong var name used as target when setting cas plane direction
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fixed wrong var name being used as target

A3-Antistasi/functions/Base/fn_AILoadInfo.sqf
1. [x] Bug
2. [ ] Change
Information:
Fixed AI load info always remoteExec the stats to the commander, when its available to more than just commander (commander & logged in admin)
closes #1990 
1. [ ] No
Steps: 
Notes:
=> fix incorrect remoteExec target in AILoadInfo

A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions.hpp, A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf, A3-Antistasi/functions/OrgPlayers/fn_playerLeash.sqf, A3-Antistasi/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf, A3-Antistasi/functions/OrgPlayers/fn_playerLeashRefresh.sqf, A3-Antistasi/functions/init/fn_initClient.sqf
* Change
* Prevents players from getting too far away from leash before noticing. Reduces desk bangs and rage quites by 200%.
* Player leash provides immersive info. No more teleport magic and non member distance! Now comrade has to within contact range or else he will be "re-inserted" to HQ.
* Player leash no longer uses a 60 second refresh period. Rather it estimates how long the player could get out of the leash and bases the refresh time off that. This saves performace when near members and HQ; And provides fine accuracy when near the leash border.
* Player leash provides more info. Such as distance to HQ or member leash and what direction to retreat to. 
* Moved, renamed, and headered fn_playerLeash.
* Member leash exemption for FF Punishment.
* Player leash fast travel …
=> Member leash FF exemption and many improvements!

A3-Antistasi/functions/REINF/fn_equipRebel.sqf
Added UnlockedToolkits and MineDetectors to Engineers and Explosive Experts.
1. [x] Bug
2. [ ] Change
Information:
Due to my changes in https://github.com/official-antistasi-community/A3-Antistasi/commit/dd00cc782b804492b89388917e48e9a02e563401 Rebell Ai lost Toolkits and Medical Equipment.
This PR returns to Previous behaivior of EquipRebell with the difference that it uses UnlockedToolKits and UnlockedMineDetectors instead of the direct classes now.
closes #1929 
1. [x] No
Steps: 
Buy Engineers and Explosive Specialists,
They should now get their Equipment if its unlocked (ToolKits are always unlocked).
``` …
```
=> 🔧🛠 equipRebell give back their Tools 🛠🔧

A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions/ModsAndDLC/fn_initDisabledMods.sqf, A3-Antistasi/functions/ModsAndDLC/fn_isModNameVanilla.sqf, A3-Antistasi/functions/init/fn_initParams.sqf
1. [X] Bug
2. [ ] Change
Information:
As it seems getLoadedModsInfo doesent find "officialmod" so the Weapons it adds can apear in non vanilla games if the DLC is enabled.
As the "DLC" is free Content. there is no reason to have a Parameter for it.
-----> Removed the Parameter and made sure that it will count as part of _itemIsVanilla
closes #XXXX
1. [ ] No
Steps: 
Load the Mission with RHS,
```sqf
"SMG_03C_hex" in allweapons
```
This should be false, and True in Vanilla.
Notes:
=> 🔫 ADR DLC Funnies 🔫

A3-Antistasi/functions/Base/fn_garbageCleaner.sqf, A3-Antistasi/functions/init/fn_initClient.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
* Bug
* Change
* Now, using the power of timeSpan, a one-line addition can format the time since last GC.
* This time is visible in `Game Options` (for Commanders and Admins) and `Garbage Cleaner`(For all players when in progress or finished.)
* Commanders want to know the time of the last GC to determine whether they should perform one or restart the server. There was no in-game Info/Feedback about when the last GC happened.
closes https://github.com/official-antistasi-community/A3-Antistasi/issues/1991
1. [x] No
1. Start Game
2. Check time since the last GC in `Game Options`.
3. Check again in `Game Options` to confirm …
=> Added Time Span Since Last GC

A3-Antistasi/functions/Dialogs/fn_fastTravelRadio.sqf
1. [x] Bug
* Change
* Enhancement
Information:
* Fast Travel checks membership. If the player is a member, it skips the leash check.
* If this did not occur, members would be unable to fast travel to airports and HQ.
1. [x] No
1. Without debug mode, you can FT to an airport as an alone player.
2. With debug  mode
```sqf
// Following snippet is used to debug as non-member after the game has initialised:
memberDistance = 1000;
membershipEnabled = true;
membersX deleteAt (membersX find getPlayerUID player);
A3A_DEV_playerLeash_debug = true;
[] spawn A3A_fnc_playerLeash;
```
3. You cannot FT to the airport. The hintis sent to you that "There …
=> Fast Travel checks membership before leashCheck.

A3-Antistasi/Garage/config.inc
1. [] Bug
2. [x] Change
3. [] Enhancement
Information:
Removed ADE Camos from Garage due to having a "jihadist flag" on their Camos, which could encourage stuff we don't want,
closes nothing, can be seen as Additions to Garage
1. [x] No
Steps: 
Start the Mission with 3CB Factions,
Spawn and Garage Vehicles,
Open the Garage and check if you can apply Camos that could be problematic.
```sqf
//Garages Vehicles so you don't have to place them.
_vehicle1 = "UK3CB_I_G_Hilux_Spg9" createVehicle getpos (Player);
_vehicle2 = "UK3CB_TKM_I_LR_M2" createVehicle getpos (Player);
_vehicle3 = "UK3CB_CCM_I_Datsun_Open" createVehicle getpos (Player); …
```
=> [Garage] Blacklist ADE Camos

A3-Antistasi/Garage/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
Information: removed the middleman on ltc refunds, this makes it more reliable to transfer and then delete the crates. the transfer is now also synchronous so it should be act faster.
the middleman `A3A_fnc_empty` required the container to be not empty to transfer. hopefully by having a synchronous call to transfere and not have to worry about another function to not bail, the crates will be more leliabilly emptied and deleted.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> removed the middle man, made the refund synchronous

A3-Antistasi/Garage/Core/fn_confirm.sqf, A3-Antistasi/Garage/Extras/fn_findMount.sqf, A3-Antistasi/Garage/Extras/fn_requestMount.sqf, A3-Antistasi/Garage/config.inc, A3-Antistasi/Garage/fn_addVehicle.sqf
1. [ ] Bug
2. [ ] Change
Information: The proxy hint function for the garage now handles localisation, as this function is run on client we now have truly localised hints in the garage.
the garage hint function now takes a stringtable key and optional arguments for string formatting, when no arguments are supplied simply localises and then hints with A3A_fnc_customHint.
this can be used as a inspiration for the A3A localised hint
closes none
1. [ ] No
Steps: 
Notes: garage stringtable entries are only in english for the moment, we should add in some …
=> true localised garage hints

A3-Antistasi/cba_settings.sqf
1. [ ] Bug
2. [ ] Change
Information:
ACE CSW has 2 settings that can cause problems with the Mission, to avoid this they should be forced off.
**ace_csw_defaultAssemblyMode** "Store extra Magazines next to Static Weapon"
-----> This will spawn Ammo next to any Static Weapon that spawns within the Mission, which can be bad for performance.
**ace_csw_defaultAssemblyMode** "Use ace for Assemble/Disassemble of supported static weapons. Loaded ammo is reduced to a Single Magazine".
-----> All Static Weapons will only have one Magazine, Ai can't deal with that, so Ai Mortars and MGs and AA Weapons will run out very quickly.
**ace_ui_groupBar** this is turned of by default and causes people to be incapable of using AI, this might help new people since they might have default …
=> Disable Problematic Ace Settings

A3-Antistasi/functions/Ammunition/fn_categoryOverrides.sqf
1. [x] Bug
2. [ ] Change
Information:
Ace Grenades allows cojnversion of Explosives to Grenades,
These Grenades can be unlocked and be converted back.
Currently only 2 charges use this function, hopefully it stays that way.
I added them to Unknown which will prevent them from Unlocking.
closes #1466 
1. [x] No
Steps: 
Try unlocking the converted Explosives
```sqf
boxx addItemCargoGlobal ["ACE_SatchelCharge_Remote_Mag_Throwable", 500];
boxx addItemCargoGlobal ["ACE_DemoCharge_Remote_Mag_Throwable", 500];
```
Notes:
=> Prevent converted Explosives from Unlocking

A3-Antistasi/functions/Templates/Loadouts/fn_loadout_builder.sqf, A3-Antistasi/functions/Templates/Loadouts/fn_loadout_defaultWeaponMag.sqf
1. [x] Bug
2. [ ] Change
Information: the loadout builder function `A3A_fnc_loadout_defaultWeaponMag` did not have an exception for cba fake magazines and would therefore add it to the loadouts in both weapon mag slot and as spare ammo.
i made it return an empty array if it found the fake mag, and fixed a bug where empty array return from that function would give null magtype used in spare ammo giving.
closes #XXXX
1. [x] No
Steps: 
Notes: this was a quick fix so there may be better ways to do it, but this will do for now
=> patched fake lanucher magazines being added to loadouts

A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_AAF_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_LDF_Enoch.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3-Antistasi/Templates/NewTemplates/Vanilla/Vanilla_AI_NATO_Temperate.sqf
1. [ ] Bug
2. [x] Change
Information:
Due to Vanilla Arma's lack of Vehicle variants HMG MRAPs were assigned as Militias Armed Vehicle, these are used for the Vehicle Roadblocks.
Player feedback is that they are to Strong for a "Low Tier Roadblock".
This PR will replace the HMG MRAPs with HMG Offroads.
closes #XXXX
1. [] Have you loaded the mission in LAN host?
1. [x] No
Steps: 
Notes:
=> Replace Militia Mraps

A3-Antistasi/functions/Missions/fn_taskDelete.sqf
1. [X] Bug
2. [ ] Change
One of the remoteExecs in the task system was missing a target where it should have been server-only, causing some log error spam.    
1. [X] No
=> Fix missing remoteExec target causing RPT spam in task delete

A3-Antistasi/Garage/Extras/fn_isAmmoSource.sqf, A3-Antistasi/Garage/Extras/fn_isFuelSource.sqf, A3-Antistasi/Garage/Extras/fn_isRepairSource.sqf, A3-Antistasi/Garage/fn_addVehicle.sqf, A3-Antistasi/Garage/fn_addVehiclesByClass.sqf
added it to addVehicleByClass
1. [x] Bug
2. [ ] Change
Information:
old saves loaded into the new version would not have source vehicles detected and registered to the garage, resulting in sources having to be re-garaged to be able to use the vehicle services
closes #2051 
1. [x] No
Steps: 
Notes:
=> fix addVehicleByClass lacking source detection

A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [X] Bug
2. [ ] Change
Translated saved garrison data from loadouts_rebel to loadouts_reb so that 2.4(.1) saved games work correctly.
Also fixed some dangerous shallow copies on load from the profileNamespace.
closes #2058
1. [X] No
=> Fix 2.4 -> 2.5 rebel garrison compatibility

A3-Antistasi/functions/Base/fn_flagaction.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [ ] Bug
2. [X] Change
1. Cap the second and third params of fogParams to min zero on Antistasi load. Arma itself doesn't use negative values here, and they're usually set accidentally with Zeus, with serious consequences including random whiteouts, launchers failing to lock and AIs not spotting correctly.
2. Set all three fog params to 0 with the "I hate the fog" option, so that players aren't tempted to use Zeus to clear the last bit.
closes #2060
1. [X] No
=> Protect players from themselves with fog params sanitization

A3-Antistasi/functions/CREATE/fn_spawnVehicle.sqf, A3-Antistasi/functions/Missions/fn_attackHQ.sqf
1. [X] Bug
2. [ ] Change
A couple of fixes related to the use of IFA transport planes:
1. Fixed a bad parameter to paradrop in attackHQ.
2. Added an aircraft config simulation used by IFA to spawnVehicle.
closes #2054
1. [X] No
=> Fix attackHQ transport planes

A3-Antistasi/REINF/addToGarrison.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf
1. [X] Bug
2. [ ] Change
- Fix case where players could be added to a garrison (probably as nils).
- Fix case where units without a unitType (eg. Zeus'd units) could be added to a garrison as nils.
- Remove non-string types (including nils) from garrisons on load.
- Remove empty strings from garrisons on load (bug from <2.4).
closes #1927
1. [X] No
You can test the load checks without saving anything by abusing loadStat with arbitrary data, like this:
```
_garrisonData = [["Zaros", ["", "loadouts_rebel_militia_rifleman", nil, "loadouts_reb_militia_rifleman"]]]; 
["garrison", _garrisonData] call A3A_loadStat;
garrison getVariable "Zaros";
```
=> Prevent bad unit types being added to garrisons, repair saves

A3-Antistasi/functions/Logistics/fn_logistics_addLoadAction.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_addAction.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_addWeaponAction.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_load.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_removeWeaponAction.sqf, A3-Antistasi/functions/Logistics/functions/fn_logistics_unload.sqf
1. [x] Bug
2. [ ] Change
Information: due to object based jip keys overwriting each other some actions on statics were being blocked from being added for jip clients,
this fix adds a custom jip key and null object handling to the logistics system as a band aid as currently the only actions that ***we know*** are conflicting are the logistics and garrison static manning actions.
in the future we might want to consider other possibilities to prevent this from happening again.
closes #2072 
1. [ ] No
Steps: 
Notes:
=> made custom JIP keys for Logistics system

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/Base/fn_mrkWIN.sqf, A3-Antistasi/functions/Base/fn_zoneCheck.sqf
1. [X] Bug
2. [X] Change
1. Changed zoneCheck to use an average marker radius with some mild proximity falloff, as opposed to the previous flat 300m count. What would often happen otherwise is that markers occupied by small teams could potentially be flipped very easily by singleAttacks, especially for small markers with a lot of surrounding tree cover.
2. Changed the mrkWIN calc similarly to the zoneCheck calc. This one was already marker-size based so previously you could often flip the flag back immediately after a zoneCheck recapture (without killing any enemies), causing stacked singleAttacks. Also cleared up a lot of weird shit in mrkWIN while I was there.
3. Fixed some old broken code in markerChange that was used to allow enemies to re-flip rebel-captured …
=> Change zoneCheck to use marker-size based capture radius

A3-Antistasi/functions/CREATE/fn_createAttackVehicle.sqf, A3-Antistasi/functions/CREATE/fn_patrolReinf.sqf, A3-Antistasi/functions/CREATE/fn_singleAttack.sqf
1. [X] Bug
2. [ ] Change
As they typically run on HCs, singleAttack and patrolReinf lost their log-to-server behaviour in the define switchover. This is bad because it means most vehicle spawns are no longer logged. This PR restores the log-to-server behaviour.    
closes #2101
1. [ ] No
Hold this PR until 2.5.3 in case I remember any other functions that needed server logging.
=> Make singleAttack and patrolReinf log to server

A3-Antistasi/functions/AI/fn_fastrope.sqf
1. [X] Bug
2. [ ] Change
Once units have started fastroping from a heli, the whole cargo will continue spawning in the fastrope position (below the heli) regardless of whether it's above the ground. This causes it to spawn corpses underground, wasting performance and annoying players when they can't find the bodies to loot.
This PR fixes the problem by not performing the fastrope process if the heli is destroyed or close to the ground.
This doesn't fix the heli/pilots despawning issue (#1487) which often coincides. That one's much harder.
closes #2093
1. [X] No
Easiest in vanilla with a MAAWS because the patrol helis …
=> Fix fastrope spawning corpses underground after heli crash

A3-Antistasi/functions/Missions/fn_convoy.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf, A3-Antistasi/functions/init/fn_initVehClassToCrew.sqf
1. [X] Bug
2. [ ] Change
allowCrewInImmobile (command that prevents crew from bailing out of an immobilized vehicle) was being applied to the convoy objective vehicle rather than the armoured vehicles due to a copypaste error. This PR fixes it so armoured vehicles are set correctly to allowCrewInImmobile.
closes #2104
1. [X] No
Easiest at high war level but quite difficult. Spawn a convoy with an armoured vehicle in it (tank, APC, AA, not MRAP) that's not the objective vehicle. Delete the other vehicles with zeus or whatever and then cripple the armoured vehicle. The crew should remain in the vehicle.
Probably not worth the testing effort.
=> Fix allowCrewInImmobile not being applied correctly to convoy vehicles

A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [X] Bug
2. [ ] Change
The counts for some limited enemy vehicle types weren't being saved. Static AA & AT, artillery, AA tanks and boats, specifically. This PR fixes this for new saves.
closes #2097
1. [X] No
Some logging code to show the vehicle counts for occupant vehicles:
```
_occTypes = [ 
["StaticAT", [staticATOccupants]],
["StaticAA", [staticAAOccupants]],
["AAPlane", [vehNATOPlaneAA]], 
["AttackPlane", [vehNATOPlane]], 
["AttackHelis", vehNATOAttackHelis], 
["TransportPlanes", vehNATOTransportPlanes], 
["TransportHelis", vehNATOTransportHelis], 
["APCs", vehNATOAPC], 
["Tanks", [vehNATOTank]], 
["AATanks", …
```
=> Save all vehicle pool entries that are incremented by economicsAI

A3-Antistasi/functions/UtilityItems/fn_carryItem.sqf, A3-Antistasi/functions/UtilityItems/fn_initMovableObject.sqf, A3-Antistasi/functions/UtilityItems/fn_rotateItem.sqf
1. [x] Bug
2. [ ] Change
Information: fn_initMovableObject uses cursorObject for addAction. With small objects it is possible for cursorObject to retrieve a different object. If netId is used this shouldn't be possible.
was not posted, here is a video of the issue: https://youtu.be/-N96s0wBq5M
1. [ ] No
Steps: 
Buy a light from vehicle box.
Hit carry object while looking at another object.
(I already did some tests myself but i checked yes just to make sure someone else tests it too)
Notes:
=> Fixed carry object carrying an object that is not the object you want to carry.

A3-Antistasi/functions.hpp, A3-Antistasi/functions/CREATE/fn_AIVEHinit.sqf, A3-Antistasi/functions/CREATE/fn_createSDKgarrisons.sqf, A3-Antistasi/functions/EventHandler/fn_addArtilleryDetectionEH.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Various fixes related to mortar type checking and locality issues:
- Fixed exploit where the mortar detection routine wasn't used on captured mortars.
- Fixed locality bug where the mortar detection routine wouldn't fire on captured mortars.
- Fixed locality bug where the reveal wasn't necessarily applied.
- Moved artillery detection EH out into separate file.
- Fixed issue where captured mortars used by rebel garrisons didn't fire.
addArtilleryDetectionEH is mostly ripped from AIVEHinit so it's not fantastic quality.
closes #2096
1. [X] No
It's not thoroughly tested but it won't be any …
=> Minor mortar fixes

A3-Antistasi/functions/Save/fn_saveLoop.sqf
1. [X] Bug
2. [ ] Change
Fixed the case where the game is saved with zero mines causing a zero divisor error on the save-chance calculation.
closes #XXXX
1. [X] No
Start new game, ensuring that the HQ isn't placed within spawn distance of a specops control point. Check allMines to make sure. Then save.
=> Fix zero-divisor bug in minefield saving

A3-Antistasi/functions/Base/fn_economicsAI.sqf, A3-Antistasi/functions/CREATE/fn_vehKilledOrCaptured.sqf
1. [X] Bug
2. [X] Change
- Fixed the increment function so that it caps correctly for array inputs.
- Used linear player scaling that's basically identical to #2079 but less opaque. Fixed for HCs.
- Increased tier scaling because we don't use many fancy vehicles at low tiers.
- Added a bit of constant to the caps so that carrier-only attacks aren't full of junk.
- Balance scale the caps as well as the increment. Otherwise enemies can pile up vehicles with some playstyles.
- Tweaked the important unit type coefficients based on some community server data.
- Added the logging from #2079, reduced code.
It's normalized such that 9 players at 7 wartier gives one vehicle per hour at typeCoeff 1, or two vehicles per hour for 26 players. Compared to the previous code, the rates …
=> Improve scaling, fix bugs and add logging in economicsAI

A3-Antistasi/functions/AI/fn_chooseSupport.sqf
1. [ ] Bug
2. [X] Change
The civ proximity check used for occupant support selection was overly sensitive due to civs spawning near any building with players nearby, and Arma/UPSMON civs being too dumb to run away from a firefight.
This PR switches it to a city marker radius + nearby house check. Results seem reasonably sensible if the expectation is that occupants don't bomb cities.
closes #2099 
1. [X] No
Bit tricky due to the caller + target requirements. There's a debug log line added for the denial case though, so you can just drive around shooting policemen.
=> Change civ detection to city+house detection

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/Base/fn_rebelAttack.sqf
1. [ ] Bug
2. [X] Change
The simulated attack routine in rebelAttack randomly fills the target garrison after a capture. This fill wasn't based on the garrison size at all, instead adding up to 56 troops, potentially within a very small area.
This PR bases the fill based on garrison size, with a minimum of 12 units. It also disables adding non-rebel targets as easy targets based on garrison size, because there were some weird early-game cases with mass flips.
closes #2115
1. [X] No
Found some fairly weird stuff with squad sizes along the way, but it doesn't really matter for this PR.
In a fresh game, set occupant …
=> Prevent simulated attacks from massively overfilling garrisons

A3-Antistasi/functions.hpp, A3-Antistasi/functions/Base/fn_economicsAI.sqf, A3-Antistasi/functions/Base/fn_getPlayerScale.sqf, A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf, A3-Antistasi/functions/CREATE/fn_singleAttack.sqf, A3-Antistasi/functions/CREATE/fn_wavedCA.sqf, A3-Antistasi/functions/Supports/fn_SUP_QRF.sqf
1. [ ] Bug
2. [X] Change
Softer version of #2079 based on the principle that aggro is already somewhat player-count dependent, so it should be used additively rather than multiplicatively with direct player count balancing. Uses a bit of randomness to smooth out the boundaries. Typical vehicle counts:
QRF:
1 player, 25 aggro: 1.5 vehicles.
9 players, 50 aggro: 2.5 vehicles.
26 players, 100 aggro: 3.5 vehicles.
singleAttack (typically higher aggro because a marker was just captured):
1 player, 50 aggro: 3 vehicles.
9 players, 75 aggro: 4.8 vehicles.
26 players, 100 aggro: 7.5 vehicles.
wavedCA (+2 vehicles for first wave)
1 player: 5.5 vehicles first wave, 3.5 subsequent
9 players: 7 vehicles first wave, 5 subsequent
26 players: 10 vehicles first wave, 8 subsequent …
=> Quick player-count balance for QRF/singleAttack/wavedCA

A3-Antistasi/functions/Base/fn_markerChange.sqf, A3-Antistasi/functions/CREATE/fn_garrisonSize.sqf, A3-Antistasi/functions/CREATE/fn_reinforcementsAI.sqf, A3-Antistasi/functions/Templates/fn_compatibilityLoadFaction.sqf, A3-Antistasi/functions/init/fn_initGarrisons.sqf
1. [X] Bug
2. [X] Change
- Balance reinforcement system for player count.
- Enable reinforcing from "carriers".
- Separate road patrol generation from reinforcements and rebalance.
- Sanitize garrison sizes (fewer giant and tiny garrisons, units of 4 rather than 8).
- Use more 4-man teams in garrisons for both init and reinf.
- Prevent new reinf convoys spamming after a recapture.
- Fill out the AA & AT squads with a fourth soldier, cap militia squads to 8.
The rebalanced reinforcements generate an average of around 16 troops per 10 minute tick for nine players at war level 3, or about half that for a single player. For comparison, the previous version generated 8 troops per airport (not carrier) in range. The new version is not particularly dependent on airfield count …
=> Rebalance reinforcements, plus related tweaks

A3-Antistasi/functions/CREATE/fn_NATOinit.sqf
1. [ ] Bug
2. [X] Change
Currently both the war tier and player-count (difficultyCoef) factors in enemy skill are multiplied by the difficulty parameter, which leads to unreasonably high mission skill values in some cases, or permanent potato mode for easy. This PR levels things out a bit, preserving the gap between enemy and friendly AIs.
closes #XXXX
1. [X] No
=> Make hard/easy difficulty changes less extreme for some cases

A3-Antistasi/functions/init/fn_resourcecheck.sqf
1. [X] Bug
2. [ ] Change
Bad exitWith caused the city-processing loop in resourceCheck to early-out incorrectly on destroyed cities, potentially causing cities not to update and miscalculation of the loss condition.
closes #2140
1. [X] No
Add the first city in the list to destroyed sites (won't black it, but whatever):
`destroyedSites pushBack (citiesX#0); publicVariable "destroyedSites"`
Then to force a tick: `nextTick = time`, run as server
=> Fix bad exitWith in resourceCheck causing incorrect losses

A3-Antistasi/functions/CREATE/fn_singleAttack.sqf
1. [X] Bug
2. [ ] Change
SingleAttack ended with a couple of key log lines not logging to server. This PR fixes the problem.
1. [X] No
=> Fix singleAttack early-exit logging

A3-Antistasi/functions/Base/fn_rebelAttack.sqf
1. [ ] Bug
2. [X] Change
The four small attacks against easy targets option and wave count calculation were not working as intended. I've removed the former and simplified the latter to temporarily fix the behaviour. Example cases that now work reasonably:
- Small attacks not spawning due to HC maxUnits limits so the attack does nothing.
- Only one small attack spawning and being less effective than a wavedCA for a higher timer cost.
- Depending on the size and grouping of the singleAttack, captured target will often have a very small garrison afterwards and so be very easy to recapture.
- With 1-3 easy targets, the code would always prefer a non-easy target, often leading to useless attacks on cities.
- Long distance targets having very large wave counts, even if very …
=> Quick fixes for degenerate behaviour in rebelAttack

A3-Antistasi/functions/Base/fn_markerChange.sqf
1. [ ] Bug
2. [X] Change
Approximately halved the maximum capture response delay. See #2146.
Also removed the case where if you captured a marker outside mission radius, the response would be delayed until the marker despawned. Not sure what the purpose of this was, but it feels weird and exploitable.
Not happy with the response + delay mechanic in general as it feels very artificial with the intentional flag flips, but it'll have to do for the moment.
closes #2146
1. [X] No
=> Reduce capture response delay time

A3-Antistasi/functions/Base/fn_zoneCheck.sqf
1. [X] Bug
2. [ ] Change
Airborne troops, for example overflying in transport helis, counted towards flag recapture checks. This caused some very weird marker flips. This PR prevents airborne troops from counting towards the capture check.
wavedCA probably has a similar issue but it's harder to fix.
closes #2145
1. [X] No
=> Prevent airborne troops from counting towards zoneCheck captures

A3-Antistasi/REINF/controlHCsquad.sqf, A3-Antistasi/REINF/controlunit.sqf
1. [X] Bug
2. [ ] Change
#1818 introduced a bug (_player -> player switch) where the commander could become permanently undercover by remote controlling a high command squad.
I've just blocked it for the moment by preventing use of remote control while undercover, as that seemed to fit better with other design decisions. If we want to bring back undercover RC then goUndercover will need changes to support that.
closes #2133
1. [X] No
=> Block exploit where commander could become permanently undercover

A3-Antistasi/REINF/dismissSquad.sqf, A3-Antistasi/functions/REINF/fn_addFIAsquadHC.sqf, A3-Antistasi/functions/REINF/fn_spawnHCGroup.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Both constructed and single-vehicle AA trucks were being underpriced on purchase due to not calculating truck + static AA costs as the other code did. This PR fixes this for both cases with a horrible hack.    
**Edit:** Additional vehicle price bugs fixed:
- Fixed doubled check price for AA and AT vehicles (missing isInfantry check).
- Fixed AT car check price adding SDKTruck price.
- Fixed ancient bug where zu-23 rebel AA trucks were not refunded on dismissal.
- Fixed bug where vanilla AA trucks were double-refunded.
- Fixed misleading error message when you didn't have enough money to purchase a transport vehicle.
- Fixed wrong price shown for transport vehicle.
- Fixed squad mortars and MGs not being charged for.
closes #2150
closes #2152
1. …
=> Fix multiple rebel squad/vehicle price bugs

A3-Antistasi/Garage/fn_addVehicle.sqf
1. [x] Bug
2. [ ] Change
Information: added the client id to the remoteExec to stop incorrectly issuing feedback to the wrong players.
closes #2155
1. [x] No
Notes:
=> added clientid to remoteExec

A3-Antistasi/functions/Base/fn_flagaction.sqf, A3-Antistasi/onPlayerRespawn.sqf
1. [X] Bug
2. [X] Change
- Fix bug where drop object action (for dropping lamps) wasn't added to player after respawn.
- Fix bug where actions were left on a dead player object.
- Fix bug where LTC actions could be added when disabled by params.
Also accidentally added the setOvercast functionality that solidifies the rain-removal tent option. Can't be bothered to unfuck git and separate it. Note that the overcast state changes very slowly, but it should prevent the rain from coming back.
closes #2154
closes #1992
1. [X] No
=> Fix lamp drop action after respawn and some related things

A3-Antistasi/Templates/NewTemplates/FactionDefaults/RebelDefaults.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_CIV.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_Logistics_Nodes.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_MACV.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_PAVN.sqf, A3-Antistasi/Templates/NewTemplates/VN/VN_Reb_POF.sqf, A3-Antistasi/functions/Ammunition/fn_equipmentSort.sqf, A3-Antistasi/functions/Ammunition/fn_itemSort.sqf, A3-Antistasi/functions/CREATE/fn_createAIAirplane.sqf, A3-Antistasi/functions/CREATE/fn_createAIOutposts.sqf, A3-Antistasi/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [x] Change
Information:
Don't Merge before the VN Update.
Changed Rebell Defaults for DiveGear and FlyGear to use arrays instead of being a True/False,
Added DiveBP due to VN using a Backpack as Rebreather,
changed CreateAiAirplane and CreateAiOutpost to use whats set in the Templates/Rebell Defaults.
Remove the IFA check for Seaports as that can be solved within the Templates.
Removed DiveGear and FlyGear in ItemSort.
Removed the Vars for them in InitVarServer,
Added Back the VN Surrender boxes as the Maximumload issue has been resolved,
Added the new Civ Vehicles added by the Update,
Added the New MGs for MACV,
Added TOW M151A1 for MACV,
changed the Static AT for Rebell and PAVN to an Unguided AT Launcher,
Added Logistic nodes for new Weapons and Civ …
=> VN Template Update

A3-Antistasi/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [X] Change
Added client event handler to remove undercover status when an ACE explosive is set up (note that this is on trigger setup, not placement).
Bob didn't want to publicize the issue.
1. [X] No
=> Remove undercover on setup of ACE explosives

A3-Antistasi/MissionDescription/params.hpp, A3-Antistasi/functions/Templates/fn_aceModCompat.sqf, A3-Antistasi/functions/init/fn_initParams.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds Ace Drink Items by Default, as they can be used to Cool your Barrel.
Food Items are given at the start if the Parameter is enabled, food is only useful if Ace Field Rations is enabled.
closes nothing
1. [x] No
Steps: 
Start the Mission with and without the Parameter on, Water should always be given, Food only with the Parameter on.
Notes:
=> Add Ace Food and Drink Items + Parameter

A3-Antistasi/Templates/selector.sqf, A3-Antistasi/functions/AI/fn_combatLanding.sqf, A3-Antistasi/functions/CREATE/fn_createVehicleQRFBehaviour.sqf, A3-Antistasi/functions/CREATE/fn_invaderPunish.sqf, A3-Antistasi/functions/init/fn_initGarrisons.sqf, A3-Antistasi/functions/init/fn_initZones.sqf, Map-Templates/Antistasi-Altis.Altis/Map/altisInfo.sqf, Map-Templates/Antistasi-Anizay.tem_anizay/Map/tem_anizayInfo.sqf, Map-Templates/Antistasi-CamLaoNam.cam_lao_nam/Map/cam_lao_namInfo.sqf, Map-Templates/Antistasi-Chernarus.chernarus_summer/Map/chernarus_summerInfo.sqf, Map-Templates/Antistasi-ChernarusWinter.Chernarus_Winter/Map/chernarus_winterInfo.sqf, Map-Templates/Antistasi-Kunduz.Kunduz/Map/kunduzInfo.sqf, Map-Templates/Antistasi-Livonia.Enoch/Map/enochInfo.sqf, Map-Templates/Antistasi-Malden.Malden/Map/maldenInfo.sqf, Map-Templates/Antistasi-Sahrani.sara/Map/saraInfo.sqf, Map-Templates/Antistasi-Stratis.Stratis/Map/stratisInfo.sqf, Map-Templates/Antistasi-Takistan.takistan/Map/takistanInfo.sqf, Map-Templates/Antistasi-Tembelan-Island.Tembelan/Map/tembelanInfo.sqf, Map-Templates/Antistasi-Virolahti.vt7/Map/vt7Info.sqf, Map-Templates/Antistasi-WotP.Tanoa/Map/tanoaInfo.sqf
1. [ ] Bug
2. [x] Change
Information:
Removed all relevant hardcoded map info, like antenna and population values. Placed them in there own file that is call from the old file. Removed hardcoded outpost garrisons locations, placed them in the same file. And removed search in arrays for arid, temperate, tropic, and etc.... maps. Made them a string that is compared.
closes #1555
1. [ ] No
There are probably edges cases that I missed. 
Notes:
=> initZones Refactor

A3-Antistasi/Garage/Core/fn_requestSelectionChange.sqf, A3-Antistasi/Garage/Core/fn_toggleLock.sqf, A3-Antistasi/Garage/Pylons/fn_pylonsTurretToggle.sqf, A3-Antistasi/functions/AI/fn_artySupport.sqf, A3-Antistasi/functions/Base/fn_mrkWIN.sqf, A3-Antistasi/functions/Garrison/fn_updatePreference.sqf, A3-Antistasi/functions/Missions/fn_AS_Traitor.sqf, A3-Antistasi/functions/Missions/fn_convoy.sqf, A3-Antistasi/functions/Punishment/fn_punishment_oceanGulag.sqf, A3-Antistasi/functions/Punishment/fn_punishment_release.sqf, A3-Antistasi/functions/REINF/fn_garrisonDialog.sqf, A3-Antistasi/functions/Save/fn_loadStat.sqf, A3-Antistasi/functions/Supports/fn_SUP_QRFAvailable.sqf, A3-Antistasi/functions/Supports/fn_SUP_QRFRoutine.sqf, A3-Antistasi/functions/init/fn_initServer.sqf
For example, in fn_initServer.sqf Info_2 is defined with 3 parameters, but in this case it is passed (unintentially) 4 arguments, this means that the macro will instead be expanded to nothing.
Related documentation can be found on the [wiki](https://community.bistudio.com/wiki/PreProcessor_Commands), relevant part is under __Arguments__.
1. [x] Bug
2. [ ] Change
1. [x] No
Steps: 
Notes:
=> Fixed various incorrect usages of defined macros

A3A/addons/core/defines.hpp, A3A/addons/core/dialogs.hpp
* Change
* Enhancement
Refactored the classes defined inside `defines.hpp` to have the A3A_core prefix.
This prevents it from overriding base game UIs and base game UIs overriding it.
closes [#2237](https://github.com/official-antistasi-community/A3-Antistasi/issues/2237)
* Have you loaded the mission on a dedicated server?
Steps: 
1. Start Game.
2. Mouse over base game buttons and UI in server lobby. They should not turn red.
3. Open the battle menu (Y), and see that the font is Roboto, they are big red buttons. 
All changes can be reproduced with the following:
```
File Match:
A3A\addons\core\d*
Find & Replace:
Match Case & Whole Word & Regex
RscText(?!\\)
A3A_core_BattleMenuText
RscPicture(?!\\)
A3A_core_BattleMenuPicture
RscButton(?!\\) …
```
=> ⚒ Refactored BattleMenu to Fully Qualified Classes

A3A/addons/Garage/config.cpp, A3A/addons/JeroenArsenal/config.cpp, A3A/addons/core/Includes/LogMacros.inc, A3A/addons/core/config.cpp, A3A/addons/maps/config.cpp, Tools/Builder/buildAddons.ps1
1. [ ] Bug
2. [ ] Change
Information:
changed from armake build to armake pack to prevent binarisation by HEMTT so we can use PreProcessor commands added with Arma 2.02 and newer
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> switched to armake pack from build

A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
1. [ ] Bug
2. [x] Change
Information:
The Jam script only included Outposts, this could cause confusion to Players as they expected Airbases to also Own Radiotowers but they don't.
Seaports are basicly Outposts just with Water so it makes sense to include them.
closes #2248 
1. [x] No
Steps: 
Capture Seaports/Airports with Radiotowers nearby,
The Jam script should lower its values/set them to 1 when there is no other Tower Nearby.
Removed the Line for PVP
Possible Maps to check with that:
CLN,
Sahrani
As it Tested with Sahrani:
```sqf
tierwar = 10;
//Occupants
[Teamplayer, "airport_2"] remoteExec …
```
=> Add Seaports and Airbases to Jam Script

A3A/addons/core/functions/UI/fn_customHintInit.sqf, A3A/addons/core/functions/UI/fn_customHintRender.sqf, A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp, A3A/addons/core/keybinds/CfgUserActions.hpp, A3A/addons/core/keybinds/UserActionGroups.hpp, A3A/addons/core/keybinds/UserActionsConflictGroups.hpp, A3A/addons/core/keybinds/fn_keyActions.sqf
* Bug
* Change
* Dismiss Previous Hint key is now set by Arma 3 Modded Keybinds.
* CustomHint will explain how to set a keybinding if unbound.
* There is no backwards compatibility with the past system. This is because the keybindings cannot be programmatically set.
* Have you loaded the mission on a dedicated server?
Steps: 
1. Load antistasi.
2. The bottom of the hint should look like Addendum 1
3. Following the instructions to set the keybinding should make the hint look normal.
Addendum 1:
=> 🔕 Dismiss hint migrated to modded keybinds.

A3A/addons/Garage/Public/fn_addVehicle.sqf, A3A/addons/Garage/Stringtable.xml, A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf, A3A/addons/core/functions/Base/fn_sellVehicle.sqf, A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initZones.sqf, A3A/addons/maps/Antistasi_cam_lao_nam.cam_lao_nam/mapInfo.hpp
1. [ ] Bug
2. [ ] Change
* Made fuel only buyable with the commander.
* Fixed fuel station capitalization.
* Changed starting fuel amount for ace in stations
* Added Land_vn_usaf_fueltank_75_01 to cam.
* No more garaging fuel, now only selling. 
* Also changed fuel station marker colour and alpha.
replaces #2216 
closes #2213
1. [ ] No
Steps: 
Notes:
=> ⛽ Fuel Support Rework

A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createAICities.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf, A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug
2. [ ] Change
Fixed an old bug where dogs spawned in garrison patrols weren't despawned, potentially blocking singleAttacks and causing unnecessary performance loss.
The traitor mission also spawns a dog, but that's cleaned up with groupDespawner, which appears to work correctly with dogs (by luck rather than judgement).
closes #2211
It'll work. All this stuff runs locally to the garrison.
1. [X] No
Drive around for a while with zeus, check that the dogs are despawning behind you.
=> Fix patrol dogs not despawning with locations

A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf, A3A/addons/JeroenArsenal/JNA/fn_vehicleArsenal.sqf
1. [ ] Bug
2. [ ] Change
Used Hakon's allMagazines function to generate compatible magazine lists for the top-right arsenal tab button. This is much better at finding the full list of compatible magazines. IIRC some AKs were pretty bad for this before.
Also used the same function to add vehicle mags in the vehicle arsenal. This makes 3CB BAF much easier to work with. You can now easily top up vehicle weapon mags without having to search through several pages of magazines.
There was an issue for the personal-weapon side but it was prematurely closed. Not sure if there's an issue for the 3CB vehicle ammunition annoyance.
1. [ ] No
2. [X] Yes (Please provide further …
=> Improve arsenal and vehicle arsenal compatible-magazine lists

A3A/addons/Garage/Core/fn_confirmPlacement.sqf, A3A/addons/Garage/Public/config.inc
1. [ ] Bug
2. [ ] Change
Information:
When we added the keybinds sript_component.hpp was included into confirmPlacement, this had the negative effect of also including the log macros, which in turn had `Debug` defined.
In confirmPlacement this define was used durring development to toggle on the debug rendering for ensuring good collision detection and spotting gaps.
Now this pre proccessor command checks `__A3_DEBUG__` instead.
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Fixed always on debug render for garage

A3A/addons/core/Templates/fn_selector.sqf
was problem for baf but is also a needed functionality
1. [x] Bug
2. [ ] Change
Information:
When a the highest priority faction was loaded and it didnt have a world default for every side it would sett the faction to be empty, this would break mod sets like BAF
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> added a check to block setting prioritsed faction if it has no entry

A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
1. [ ] Bug
2. [X] Change
Changed the rebel squad recruiting to move units directly into their purchased vehicles, an in pre-2.5 versions. Prevents issues with AI pathing at busy HQs and generally speeds up recruit->use for the commander.
Technical note: moveInXXX functions appear to assign the specified role too, so assign+moveIn is unnecessary. 
closes #2203
1. [X] No
Recruit various vehicle-based or vehicle-added high command squads. Check that they're moved into the vehicle correctly. Make sure they move afterwards.
=> Switch back to moving recruited rebel squads into their vehicles

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
1. [ ] Bug
2. [x] Change
Information:
This change removes the Raven Drone Backpack from Loot and prevents Unlocking if people spawn them in using Zeus.
closes #2274
1. [x] No
Steps: 
Check 
```sqf
"B_rhsusf_B_BACKPACK" in allbackpacks //Should be false
"B_rhsusf_B_BACKPACK" in lootbackpack //Should be false
"B_rhsusf_B_BACKPACK" in allunknown //Should be true
```
Notes:
=> Remove Ravenbackpack from Loot

A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ADA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ANA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_US.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_East.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_Mix.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_West.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf, A3A/addons/core/Templates/Templates/VN/VN_AI_MACV.sqf, A3A/addons/core/Templates/Templates/VN/VN_AI_PAVN.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
1. [ ] Bug
2. [x] Change
Information:
This adds a Check for Ace so Ace items are only given if Ace is Active, without the check there might be a bit of RPT spam as these items don't exist without Ace and the Template Validation screams at you too.
Also fixed the Casing Error in SquadLeader extra items. (did the same on the BAF PR, we will see if they conflict)
closes nothing
1. [x] No
Steps: 
Start with and without Ace,
There should be no RPT Errors about Missing Items from the Template Validation.
Notes:
=> Templates - Added check for Ace Extra Gear

A3A/addons/core/functions/init/fn_initGarrisons.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [x] Bug
2. [ ] Change
Information:
This moved the problematic solution in InitGarrisons to InitServers, right next to where we set the Carriermarkers Names.
closes #2282 
1. [x] No
Steps: 
Load a Save, the Carriers should get their Factions Markertypes applied.
Notes:
=> Fix Carrier Markertype after loading a Save

How to build.md
1. [X ] Bug
2. [ ] Change
The link to vs code market was misspelled for `markedplace`, I edited and added the t instead of the d
=> Fix typo in how to build.md guide

A3A/addons/core/functions/Base/fn_sellVehicle.sqf
1. [X] Bug
2. [ ] Change
vehiclesCargoTrucks wasn't included in the sell checks, so flatbed trucks couldn't be sold.    
closes #2291
1. [X] No
=> Fix cargo trucks not being sellable

A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf, A3A/addons/core/functions/UtilityItems/fn_remainingFuel.sqf
1. [ ] Bug
2. [x] Change
Information:
Added an event handler to the play when holding an movable item. Once trigger the item is moved away from the vehicle to stop damage. Also removed forced walk as the intent is use this around base.
1. [x] No
Steps: 
Notes:
=> UtilityItems - Prevent players from carrying objects into vehicles and fix order precedence

A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug
2. [ ] Change
An accidentally preserved code section (merge fail?) could deleting vehicles from roadblocks after being stolen by players. This PR removes it, fixing the problem.
closes #2289
1. [X] No
=> Fix roadblock vehicles being despawned after stealing

A3A/addons/core/functions/Base/fn_logPerformance.sqf, A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf
1. [x] Bug
2. [ ] Change
Information:
Arma's default string conversion limits numbers to 6 significant figures. We use toFixed to convert numbers to strings longer than 6 digits.
closes #2319
1. [x] No
Steps: 
See #2319
Notes:
=> Added toFixed to visual money displays

A3A/addons/Garage/Extras/fn_reloadExtras.sqf, A3A/addons/Garage/StatePreservation/fn_getAmmoData.sqf, A3A/addons/Garage/StatePreservation/fn_prepPylons.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug where the garage's pylon-removal code could remove weapons that were not pylons due to them sharing magazines with pylon weapons. The new code should work correctly with everything but I haven't tested it with much.
Also fixed a zero-divisor bug in the ammo percentage calculation that I ran into with the FA-181.
closes #2246
1. [ ] No
Should ideally be tested with a decent selection of vehicles. I've only tried a few vanilla air vehicles so far.
Enable debug mode to get TRACE working. Take vehicles out of garage and check the output of `HR_GRG_fnc_prepPylons | Removing pylon …
=> Fix non-pylons being removed by prepPylons

A3A/addons/core/functions/CREATE/fn_createVehicleCrew.sqf
1. [X] Bug
2. [ ] Change
createVehicleCrew was pre-filtering the turret classes using configClasses, which doesn't work because it breaks the turret path if earlier items are removed. In the case of the UAZ, the commander FFV turret is before the proper turret.
This PR moves the turret filtering until after the turret path has been established. Also moved the nested turret code, because I'm pretty sure that was also wrong in the case where the first-level turret doesn't have weapons.
closes #2308
1. [ ] No
Don't know a vehicle to test the nested turrets logic. Feel free to suggest one.
Start game with CUP mods and …
=> Fix createVehicleCrew placing turret crew in wrong seats

A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
1. [x] Bug
2. [x] Change
Information:
So apparently this has been in InitClient and OnPlayerRespawn for 3 Years,
As everyone got 0,8 Audio and Camo applied this just meant that TL was the worst Class to use as you only had negative Perks, and everyone else had the Good perks only you should have got.
Cleaned up unused/Dead Case for UnitTraits
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Remove left over setUnitTrait

A3A/addons/JeroenArsenal/JNA/fn_arsenal_addItem.sqf, A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf, A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3A/addons/core/functions/Ammunition/fn_fetchRebelGear.sqf, A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf, A3A/addons/core/functions/Ammunition/fn_itemSort.sqf, A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf, A3A/addons/core/functions/Base/fn_initPetros.sqf, A3A/addons/core/functions/REINF/fn_dismissPlayerGroup.sqf, A3A/addons/core/functions/REINF/fn_dismissSquad.sqf, A3A/addons/core/functions/REINF/fn_equipRebel.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/init/fn_initServer.sqf, A3A/addons/core/functions/init/fn_initVarCommon.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf, A3A/addons/maps/MissionDescription/params.hpp
1. [ ] Bug
2. [ ] Change
We need a new method of picking rebel AI equipment after removing unlocks. I've decided that the best method is to base AI equipment on the arsenal contents but generate new items. This is relatively simple (actually taking items from the arsenal is complex and expensive, especially with garrisons) and should have low exploit potential and no significant player count balance problems.
Processing the arsenal for each unit recruited is still too expensive, so this PR rewrites the rebel AI equipping code to use server-generated weighted lists. Some details:
- Generates weighted arrays on server every 10mins, transmits to clients as required.
- Weight based on arsenal contents. Typically 10 items min chance, 50 max.
- Item usage is also capped by …
=> No-unlocks support for rebel AI equipping

A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ACR_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_CDF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_SLA_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [ ] Bug
2. [ ] Change
Information:
Cleanup the Mess in SetPlaneLoadout,
Add Drones to Templates, they were left out without any Reason stated.
Lower the Amount of GMG/GLs/MK19s, only BAF, rest is mostly 4 to 1ish
Removed AttackHelicopters in Transport,
Removed Vanilla Trucks in CargoTrucks, if there is no Truck for the Faction then there should be no Truck.
Removed Vanilla AA in BAF Template, replaced with US AA.
Added More Variants to US Army AA
Texture Path consistency, all to lower.
Removed leftover Comments.
supressed the Format rebellion, If we want to change the Format we should do it in all Not start it randomly in one Modset.
closes eh
1. [x] No
2. [ ] …
=> Cup Cleanup

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/functions/Templates/Verification/fn_TV_verifyAssets.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/proxy/fn_onPlayerRespawn.sqf
1. [x] Bug
2. [x] Change
Information:
Added a Check for not having Ace, so Players with Ace won't get a Speaker set and it should stay with "Ace_novoice".
Removed the Speaker Lines in OnPlayerRespawn.
Added a missed Semicolon.
1. [x] No
Steps: 
Notes:
=> Silence Players with Ace / Missed Semicolon

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3A/addons/core/functions/init/fn_initVarCommon.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [X] Bug fix
2. [ ] Change
Forgot to test #2305 on DS+client. Apparently the only broken bit was that categoryOverrides is only created on the server, but now needs to be created everywhere because equipmentClassToCategories is used for general equipment identification.
Also tagged it with A3A_.
closes #2327
1. [X] No
=> Fix categoryOverrides not being created on clients, and tag with A3A

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Punishment/fn_punishment.sqf, A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf, A3A/addons/core/functions/Punishment/fn_punishment_FF_checkNearHQ.sqf, A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
* Bug
* Change
* Refactored `A3A_fnc_punishment_FF` to `A3A_fnc_punishment_evaluateEvent`
* Added additional Punishment logging for cheking player's UAV body.
Steps: 
```sqf
[player, 0, 0, objNull] remoteExec ["A3A_fnc_punishment_evaluateEvent",2];          // Test self with no victim
[player, 0, 0, cursorObject] remoteExec ["A3A_fnc_punishment_evaluateEvent",2];     // Test self with victim
[getPlayerUID player,"forgive"] remoteExec ["A3A_fnc_punishment_release",2];  // Self forgive all sins
```
=> Added additional Punishment logging for cheking player's UAV body

A3A/addons/core/functions/CREATE/fn_createAICities.sqf, A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf, A3A/addons/core/functions/Missions/fn_attackHQ.sqf, A3A/addons/core/functions/Templates/fn_compileGroups.sqf
1. [ ] Bug
2. [x] Change
Information:
added groupSpecOpsRandom, and groupSpecOpsSniper.
groupSpecOpsRandom is used for random selection of 6 man group of sf units. 
groupSpecOpsSniper will be used for sniper patrols, right now It is not used, just defines it.
groupSpecOps still exist, was kept for no school specOps if needed somewhere later.
all references of groupSpecOps are replaced with groupSpecOpsRandom. (hq_attack, dead towns, and controls)
N/A
1. [x] No
Steps: 
Notes:
=> Adding more Special Forces Groups

A3A/addons/core/functions/REINF/fn_NATObomb.sqf
1. [x] Bug
2. [ ] Change
Information:
Corrected a likely copy past error that prevented proper flight height restriction for rebel airstrikes when target is on terrain with steep elevation differenc
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fixed incorrect variable used for flight height restrictions

A3A/addons/Garage/StatePreservation/fn_prepPylons.sqf
1. [X] Bug
2. [ ] Change
Turns out weapon classes found in vehicle turret config are not guaranteed to have the same case as weapon classes found using `weaponsTurret`. Which is fun. So the comparison here needs to be case-sensitive.
The RHS zu-23s tripped up on this, which is very bad.
closes #XXXX
1. [X] No
=> Fix garage pylon removal case sensitivity (kills zu-23)

A3A/addons/core/Templates/fn_selector.sqf, A3A/addons/core/functions/init/fn_initVarCommon.sqf
1. [X] Bug
2. [ ] Change
A3A_climate was declared in selector.sqf (which only runs on the server) and not published, but used in combatLanding which runs on HCs. This probably caused singleAttack combat landings to follow the wrong path with HCs present.
selector.sqf seemed like a terrible place for it anyway, so I moved A3A_climate to initVarCommon which runs early and everywhere.
closes #XXXX
1. [X] No
=> Move A3A_climate init to initVarCommon for sanity and HC-functionality

A3A/addons/core/functions/Dialogs/fn_moveHQObject.sqf, A3A/addons/core/functions/Missions/fn_LOG_Supplies.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initZones.sqf
1. [x] Bug
2. [ ] Change
Information:
Added an attachedTo check on the pallet to see if it was attached to anything before deletion.
Changed color of the fuel marker and made the small fuel containers purchasable for non-commanders.
Added a check for moving objects out of bounds, allows for objects that are out of bounds to be moved.
closes #2193 
closes #2164 
1. [x] No
Steps: 
Notes:
=> Bug Fixes for city supplies 🛢️, QOL for fuel ⛽, and Out of Bounds Check for Moving assets. 

A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BAF_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
1. [ ] Bug
2. [x] Change
Information:
#2312 added extra items for marksman and sniper loadouts. This PR adds consistency to rest of the blufor cup templates.
Adds ir, nightvision scopes to the loadouts. Changes the binocular to the SOFLAM. These changes try to award the players with better and higher quality items from sf units. 
N/A
1. [ ] No
Steps: 
Notes:
=> Templates - CUP Blufor updates for consistency with ACR changes

A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [X] Change
Added an EH to disable rating changes for players. It's common for players to end up in negative rating for bad reasons and then get attacked by their own AIs. Some reasons for losing rating:
- Crashing their own vehicles.
- Blowing up unoccupied vehicles with mortars.
- Shooting down enemy vehicles that have an inherent side as greenfor (eg. some AAF stuff).
AIs don't seem to take rating penalties (although oddly enough they do get the bonuses), so I don't think we need to do anything complicated here. Only remaining problem case is if a player remote-controls AI and blows up something, but that's not a major or common issue.
closes #2386 …
=> Disable Arma rating changes for players

A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_RACS_Tropical.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [x] Bug
2. [ ] Change
Information:
Change the A10 for cup in setPlaneLoadout to the right a10 that takes pylon cmds. Fixes CRV7s to work.
1. [x] No
Steps: 
Notes:
=> Change CUP A10 to A10 with real pylons

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/Templates/Templates/#Examples/FactionExample.sqf, A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/functions/REINF/fn_equipRebel.sqf, A3A/addons/core/functions/Templates/Loadouts/fn_loadout_builder.sqf, A3A/addons/core/functions/Templates/Loadouts/fn_loadout_setFacewear.sqf, A3A/addons/core/functions/Templates/Verification/fn_TV_verifyLoadout.sqf
1. [ ] Bug
2. [ ] Change
This pull request adds the ability for AI to randomly select from facewear items to wear specified in their template (e.g. goggles, glasses, bandanas, custom mod items like beards, etc.).
This has been something requested occasionally by other community members on the Discord server, and I personally wanted to add this functionality myself as well after I started playing around with faction templates. Essentially, its overall purpose is adding more variety with AI appearance.
closes #XXXX
1. [X] No
The AAF and FIA factions are setup with facewear. By spawning any FIA units (except for …
=> Facewear support for AI loadouts

A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
1. [x] Bug
2. [ ] Change
Information:
changed argument for carry function to use originalTarget from addAction instead of cursorObject, this should prevent picking up the incorrect action
closes #2425 
1. [x] No
Steps: 
Notes:
=> Stop god carry

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/LTC/fn_carryCrate.sqf, A3A/addons/core/functions/Logistics/functions/fn_logistics_load.sqf, A3A/addons/core/functions/Logistics/functions/fn_logistics_unload.sqf
1. [ ] Bug
2. [X] Change
Test PR for looting/logistics tweaks, intended to make the looting process less annoying without removing the time cost entirely.
- Switch loot crate carrying from forceWalk true to allowSprint false (about 2x faster movement).
- Enabled buying loot crates from any rebel flag.
- Fixed incorrect bounding box calc for load/unload.
- Changed load/unload speed to be independent of script load.
The bounding box calc change will have little effect for some vehicles (eg. vanilla offroad) but a huge effect for others (eg. vanilla HEMTT). Unloading a box from an HEMTT will no longer place it >5m behind the vehicle.
closes #XXXX
1. [ ] No
2. [X] Yes …
=> Quality-of-life looting/logistics tweaks

A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
1. [X] Bug
2. [ ] Change
The code that makes rebels mount statics in live garrisons (either when static weapons are placed or when units are added) didn't work well on a dedicated server because joining them to an empty group didn't change their locality. This code works around the problem by forcing locality immediately with changeOwner. This seems to work - I wasn't sure if it'd need a delay.
closes #2409 
1. [X] No
=> Fix rebel static mounting on DS

A3A/addons/JeroenArsenal/JNA/fn_arsenal.sqf, A3A/addons/JeroenArsenal/JNA/fn_arsenal_addItem.sqf
1. [X] Bug
2. [ ] Change
A3 patch 2.07 changed the behaviour of magazinesAmmoFull by adding unique IDs to each magazine. This broke some janky arsenal code that subtracted the new magazinesAmmoFull array from the old one after a weapon switch, causing it to duplicate all player magazines into the arsenal contents.
This patch fixes the problem by cutting the offending elements out of the arrays. Also threw in a fix for the update code causing bogus RPT complaints about remoteExecCalls to 0 targets (0 is apparently greater than 1000).
closes #XXXX
1. [X] No
Easiest to see the effects if you run a  script first to hack …
=> Fix arsenal weapon switch duping magazines

A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf
1. [X] Bug
2. [ ] Change
Fixed hanging setStartTime from #2439 that was probably used for pre-PR profiling.
closes #XXXX
1. [X] No
=> Fix leftover setStartTime from #2439

A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf, A3A/addons/core/functions/REINF/fn_addToGarrison.sqf
1. [X] Bug
2. [ ] Change
Changed HC fast travel and HC garrison to directly turn off the commanding menu and override the map click. The fast travel was using a command bar on/off method before which caused the BIS HC functions to throw script errors, while the garrison function wasn't turning off the commanding menu at all, so you needed an additional map click.
Also fixed a couple of things from #2165:
- Prevented closing the map after high command fast travel completion.
- Prevented tow ropes on personal vehicle from blocking squad fast travel.
partially fixes #2165 plus some other stuff that may not have an issue.
1. [X] No
2. [ ] Yes (Please provide further …
=> Fix high command FT and garrison annoyances

A3A/addons/Garage/Public/fn_addVehicle.sqf, A3A/addons/core/functions/Save/fn_loadStat.sqf, A3A/addons/core/functions/UtilityItems/fn_buyItem.sqf
1. [x] Bug
2. [ ] Change
Information:
- added unload for ace cargo on unload, also refunds ltc crates (emptying its contents to arsenal first)
- fixed fuel containers interaction and important variables not being restored on load
closes #2447 
1. [x] No
Steps: 
- load items into ace cargo
- garage vehicle
- buy fuel container
- save and load game
- garage fuel container
Notes: as purchased light sources cost money we should consider refunding or restoring them on load
=> Ace unload on garage

A3A/addons/Garage/Core/fn_confirmPlacement.sqf, A3A/addons/core/functions/REINF/fn_addFIAveh.sqf
1. [ ] Bug
2. [ ] Change
Information:
Old, pre-2.5.0-garage had the ability to show some extra messages during vehicle placement process. This PR implements same thing for Hakon's Garage too.
This might be useful in some non-general use cases: some additional hints, guidances or simply vehicle price can be shown to player.
-
-
1. [x] No
For example, fn_addFIAVeh.sqf:
```sqf
private _extraMessage = format ["Buying vehicle for $%1.", vehiclePurchase_cost];
[_typeVehX, "BUYFIA", [], nil, nil, nil, false, _extraMessage] call HR_GRG_fnc_confirmPlacement;
```
=> Extra message for New Garage

A3A/addons/Garage/Core/fn_requestSelectionChange.sqf, A3A/addons/Garage/Core/fn_toggleLock.sqf, A3A/addons/Garage/Extras/fn_findMount.sqf, A3A/addons/Garage/Public/config.inc
1. [x] Bug
2. [ ] Change
Information:
on lh it always returned true for cmdClient calls on the server( where its mostly used as most checks that need it are server side) this made everyone able to act as admin/commander on a lh session
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> fixed issue with everyone being considered admin on lh (garage)

A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf
1. [X] Bug
2. [ ] Change
IFV array was missing in RHS AFRF Temperate, causing getVehiclesGroundTransport to throw RPT errors. Didn't seem to have any knock-on effects, as ground vehicles were still spawning after the error.
closes #XXXX
1. [X] No
=> Fix missing IFV array in RHS AFRF

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf
1. [x] Bug
2. [ ] Change
Information:
This fixes the weird issue of vanilla "not knowing what vanilla has". There where weapon attachments in the wrong slot. That was fixed. Snipers now should get the optics for the lynx.
1. [x] No
Steps: 
Notes:
=> Vanilla template fixes

A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf, A3A/addons/core/functions/OrgPlayers/fn_makePlayerBossIfEligible.sqf, A3A/addons/core/functions/OrgPlayers/fn_memberAdd.sqf, A3A/addons/core/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf, A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf, A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf, A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf, A3A/addons/core/functions/init/fn_clientIdleChecker.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [X] Bug
2. [X] Change
1. AFK timeout increased to five minutes. Two minutes was a bit short in practice: Didn't give players enough time for bio breaks and ACE unconsciousness was a bit harsh. Will see how this goes.
2. Fixed missing eligibility-toggle cursorTarget transfer code.
3. Fixed wrong info bar string being shown to guest-commanders. There was some weird old code that only applied to guest-commanders.
4. Guests are now initialized to ineligible. Mostly an issue when the server's guest-only and someone who has no idea what they doing and/or poor comms gets commander.
5. Fixed a couple of debug logs not showing player names.
6. Added a warning for commanders who go AFK.
7. Increased HC squad remote control limit to three minutes. Should be fine.
Added in …
=> Fixes and tweaks related to guest commander functionality

Tools/Builder/buildAddons.ps1
1. [ ] Bug
2. [x] Change
Information:
I use Hakon's powershell builder all the time, I like it. I was however fed up with not knowing when I last built was or if I even built. This pr adds support for displaying what time you last ran the builder.
N/A, its a tool
N/A, its a tool
Steps: 
Notes:
=> Builder displays when you built 

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Dialogs/fn_moveHQObject.sqf
1. [ ] Bug
2. [X] Change
- Locked static for the player carrying it, preventing horrible Arma physics glitches. This removes the "get in as ..." actions. Other players mounting the static is less bad physics-wise and is already handled.
- Fixed the static actions not closing the menu on selection, which was causing Arma's wackass UI to default to the wrong action after pickup. Now everything gets "Drop object" in the screen centre while carrying.
Was tempted to fix some other shit but that's more involved and overdue a general rewrite.
closes #XXXX
No locality-related changes.
1. [X] No
=> Block players from mounting a static they're carrying and improve menu behaviour

A3A/addons/core/functions/CREATE/fn_attackHQ.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf, A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
1. [ ] Bug
2. [X] Change
- HQ attacks and punishments now add the location to forced spawns. This is to prevent various direct actions (eg. fast travel, recruiting) during the warning time, but also adds the locations to leash centres (see #2462) to make it easier for guests to respond to attacks.
- Fast travel (including high command) no longer possible to markers in the forced spawn list.
- Player scale effect on min travel time removed for punishments and waved attacks. While larger servers have more capability to respond to attacks, they're also less organized and generally slower to react. Base time is now a flat five minutes.
- Added 1min per 2km increase in min travel time for punishments. Enough for reasonably fast driving, and you can often shortcut with …
=> Tweak ability of rebels to respond to punishments and major attacks

A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
1. [x] Bug
2. [ ] Change
Information:
Made Carry Item use bounding box dimensions for attaching to. Prevents players from getting stuck in a large object that they are carrying.
1. [x] No
Steps: 
Notes:
=> attachTo use bounding box dimensions

A3A/addons/core/functions/Base/fn_sellVehicle.sqf
1. [X] Bug
2. [X] Change
This PR fixes a bug where enemy militia trucks weren't sellable unless their classname was also in the regular truck list. Also added a $200 category for light APCs, enemy boats and utility trucks.
closes #2463
1. [X] No
=> Fix enemy militia trucks not being sellable

A3A/addons/core/functions/Ammunition/fn_fillLootCrate.sqf, A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf, A3A/addons/core/functions/Ammunition/fn_loot.sqf, A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf, A3A/addons/core/functions/REINF/fn_equipRebel.sqf
1. [X] Bug
2. [X] Change
Fixes and balance adjustments for various issues discovered during public testing:
- Remove magazine limitations on rebel equipping for the moment. This was too complicated to do correctly with the combination of black-box template data and broken mods, and not important enough to worry about.
- Use compatibleMagazines instead of config magazines#0 generally. Fewer reliability issues with broken/weird mods.
- Always use no-unlocks selection rules for missile launchers & explosives. Because they're never unlocked by default, and if those flags are enabled then the no-unlocks rules still work.
- Fill out mid-range optics with close range when it's thin. There was an exploit/weirdness where your riflemen would always get the first mid-range optic …
=> Fix/tweak various rebel gear & loot issues found in public testing

A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf, A3A/addons/core/Templates/Templates/GM/GM_Civ.sqf, A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
1. [X] Bug
2. [X] Change
Fixes and tweaks for GM template issues discovered in playtesting:
- Add IEDs and 20 M72A3s to starting GM rebel gear.
- Remove helis from civ medical vehicle arrays.
- Remove vanilla repair offroad (too good).
- Fill out the civ car array with cherno CUP.
- Replace militia C7A1 with M16A1 (C7A1 has mid-range optic).
- Fill out the GL ammo a bit.
closes #XXXX
1. [X] No
=> Tweaks and fixes to GM templates

A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf
1. [ ] Bug
2. [x] Change
Information:
Remove bridge laying tank from BW engineering vehicles, since it is kind of strange to send this vehicle to a downed heli or an tower rebuild.
none
1. [ ] No
check if it loads correctly
Steps: 
load the game with mods for GM template
Notes:
=> removed biber from list of engineering vehicles

A3A/addons/core/functions/Base/fn_sellVehicle.sqf
1. [x] Bug
2. [ ] Change
Information:
- added array with assets blacklisted from being sold    
- price for items in said array is set to 0 which triggers the "you can't sell this" response
closes #2371
1. [x] No
Steps: 
- get one of the items and try to sell it
Notes:
- I know that this is not the optimal fix but I rather have a working non-optimal one than no fix at all.
=> rough fix for infinite money exploit

A3A/addons/core/Params.hpp, A3A/addons/core/functions/Base/fn_chooseAttack.sqf
1. [ ] Bug
2. [X] Change
Made some changes to rebel target attack selection because it had artifacts (enemies tended to prefer targets 10km from HQ over targets 4.1km from HQ due to distance from airbase) and generally wasn't strong enough:
- Removed dependence on mission distance, because the attack logic is more bound by airbase separation.
- Increased default maximum multiplier but smoothed it out, so there's no sudden jump at a specific radius.
closes #XXXX
1. [X] No
=> Improve attack selection dependency on rebel HQ position

A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
There was no sanitization of saved params for autoloaded games, which meant that if a parameter name changed between versions, the new parameter would not be initialized when autoloading.
This PR fixes the problem by using the saved params as an override for the true default list.
closes #XXXX
1. [X] No
=> Fix case where autoload game had different params list

A3A/addons/core/Params.hpp, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
Information:
PR gives ability to tune starting money for individual players and overall rebel at startup params menu. 
1. [x] No
Steps: 
1. Choose any starting money dropdown value.
2. Start new game.
3. Check if custom starting money parameter have applied.
Notes:
=> Player and Rebel Faction starting money parameters

A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/UNS/UNS_AI_PAVN.sqf, A3A/addons/core/Templates/Templates/UNS/UNS_AI_US.sqf
1. [ ] Bug
2. [ ] Change
Information:
Changed NVA to PAVN so i can see what people use when they post Screenshots.
Also Removes the chances to mix up GM NVA with Unsungs NVA as its PAVN now.
Removed EX41 (Chinalake) from PAVN Loadouts.
This should reduce Ai throwing Nades directly at People as its not their Mainweapon anymore.
Removed 1 Pouchless Vest from the US Faction.
There was a chance that US Military Rifleman/Other Classes spawned with no Mags due overfilling.
closes #2506,
My own Sanity a little. (🥳 if someone reads this)
1. [x] No
Steps: 
Notes:
=> Rename Unsung NVA to PAVN / Loadout Adjustments

A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_setupMonitor.sqf
1. [x] Bug
2. [ ] Change
Information:
CDLCs have no positive flag on `#3` index
```json
[
"Arma 3 Creator DLC: Western Sahara",
"ws",
false,
false,
"GAME DIR",
"2179d4a085ac65e7da04b2685410844e10141ac0",
"6ba95015",
"1681170"
]
```
, thus making it undetectable, so any `"ws" in A3A_enabledDLC` checks will return false when WS CDLC is actually turned on.
This PR fixes this issue.
1. [x] No
Steps: 
1. Enable WS CDLC.
2. Start Antistasi mission.
3. Select WS CDLC in DLC section in mission setup menu.
4. Type `"ws" in A3A_enabledDLC`, the result should be `true`. …
=> Western Sahara CDLC detection fix

A3A/addons/core/Templates/Templates/GM/GM_AI_BW.sqf, A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf, A3A/addons/core/Templates/Templates/GM/GM_Vehicle_Attributes.sqf
1. [ ] Bug
2. [X] Change
Changes that I forgot earlier to bring the GM in line with the other factions and ensure attack/support is using the vehicles somewhat correctly:
- Vehicles that don't seat troops moved out of lightAPC/APC/IFV.
- Some scout-ish cannon-armed vehicles moved to light armed with increased cost.
- Reduced cost of vehicles that are fragile for their class.
closes #XXXX
1. [X] No
=> Fix up GM vehicle categories to work better with attack/support

A3A/addons/core/functions/Base/fn_commsMP.sqf, A3A/addons/core/functions/Base/fn_markerChange.sqf, A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
Minor bug fixes:
- Switch back to createPetros on init so he gets the right uniform.
- Prevent commsMP trying to run before client init.
- Fix non-local surrenderAction call.
closes #2516
1. [X] No
=> Minor fixes for 3.0

A3A/addons/core/Params.hpp, A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/OrgPlayers/fn_assignBossIfNone.sqf, A3A/addons/core/functions/OrgPlayers/fn_theBossTransfer.sqf, A3A/addons/core/functions/init/fn_clientIdleChecker.sqf
1. [ ] Bug
2. [ ] Change
- Made the AFK checker timeout a parameter. 15 minutes probably makes more sense for community servers, but short values are best for SP alt-tabbing.
- Added a red AFK indicator at the end of the status bar.
- Fixed cases where commander switch logging was using the unit rather than the unit name.
closes #XXXX
1. [X] No
=> AFK timeout parameter + status bar indicator and logging tweaks

A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf, A3A/addons/core/Templates/Templates/UNS/UNS_Reb_VC.sqf, A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
1. [X] Bug
2. [X] Change
Overlooked/forgotten stuff in GM & Unsung launchers and rebel gear:
- Add M72 ammo to GM initial equipment. The launchers don't work otherwise.
- Add some RPG2s plus ammo to Unsung initial equipment.
- Add IEDs to Unsung initial equipment.
- Fix classification of GM & Unsung disposable launchers and their used tubes.
closes #XXXX
1. [X] No
=> Fix GM & Unsung rebel launchers

A3A/addons/core/CfgFunctions.hpp
1. [x] Bug
2. [ ] Change
Information:
The support left out some semicolons in cfg functions. Which might explain something, somewhere.
1. [ ] No
Steps: 
Notes:
=> Fix missing semicolon in cfgfunctions

A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf, A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf, A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf, A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
1. [X] Bug
2. [ ] Change
- Fixed an issue where rebel troops were exiting their vehicle after spawning, and possibly other issues. AIVEHinit is called twice on rebel high command spawned vehicles, and the second one was causing it to be reported as destroyed due to an incorrect parameter.
- Fixed an issue where vanilla AA vehicles spawned without their missile launcher when remote-spawned. From #2047.
- Fixed an issue where the antenna repair mission could throw an error when exiting without having spawned the group or vehicle.
- Probably fixed an issue where mortarRoutine could throw errors due to the main loop timing out and cleaning up the mortar while it was still firing.
- Disabled mine detection AI on convoy vehicles. Already done for most combat vehicles, as …
=> Various one-liner fixes

A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
1. [ ] Bug
2. [X] Change
One of the main complaints about the Unsung modset was that it was much harder to acquire fuel and repair trucks due to the lack of civilian vehicles. This PR attempts to balance that out by adding a chance of picking military fuel and repair vehicles instead of the static cargo trucks at bases. It's exploitable by spawn/despawn but no more so than the civ spawns in other modsets.
Also clears up some old/broken occupant/invader asymmetry on usage of cargo trucks.
Note that createAIOutposts is also used for seaports, and createAIResources is also used for factories. Airports already have a chance of spawning utility trucks so I didn't touch those.
closes #XXXX
2. [ ] Have you loaded the mission on a …
=> Balance utility trucks in cases where the civ factions lacks them

A3A/addons/Garage/Public/config.inc
1. [ ] Bug
2. [X] Change
As agreed in dev meeting on 27 August, increased the default garage cap to 20 base + 4 per tier.    
closes #XXXX
1. [X] No
=> Increase default garage cap to 20 base + 4 per tier

A3A/addons/core/functions/Base/fn_commsMP.sqf, A3A/addons/core/functions/Intel/fn_showIntel.sqf, A3A/addons/core/functions/Revive/fn_respawn.sqf, A3A/addons/core/functions/Revive/fn_unconscious.sqf, A3A/addons/core/functions/Undercover/fn_goUndercover.sqf, A3A/addons/core/functions/init/fn_credits.sqf, A3A/addons/core/functions/init/fn_tags.sqf
1. [X] Bug
2. [ ] Change
See #2431. Antistasi was using fixed low numbers for UI layers, which is very bad practice as those numbers are also distributed by BIS_fnc_rscLayer, and caused it to damage the UI of other mods. This PR switches all cases I found to using BIS_fnc_rscLayer so that there will be no unexpected collisions.
Tested all of them, I think: Respawn, undercover, unconscious, showIntel, resource income, aggro change, credits, tags.
closes #2431
1. [X] No
=> Fix Antistasi UI layer numbers fighting with other mods

A3A/addons/maps/Antistasi_vn_khe_sanh.vn_khe_sanh/mapInfo.hpp, A3A/addons/maps/Antistasi_vn_khe_sanh.vn_khe_sanh/onPlayerRespawn.sqf
1. [x] Bug
2. [ ] Change
Information:
adds lost `onPlayerRespawn.sqf` and adds city data    
closes #2552 
1. [x] No
=> vn_khe_sanh pop update

A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf
1. [X] Bug
2. [ ] Change
Some pieces of the airfield mortar spawning code went missing, probably in #2047, which made airfields rather too easy. This PR restores them.
Also added a workaround to avoid spawning airfield mortars on top of support mortars. Seems to work.
closes #2317
1. [X] No
Tests run:
- Move near airbase, check the mortars spawn (Therisa airbase on Altis has two).
- Move away from airbase until it despawns. Fire up a mortar support on the airbase:
`["MORTAR", Occupants, "defence", 500, objNull, markerPos "Therisa", 0.8, 0] call A3A_fnc_createSupport;`
(needs a bit of luck or retrying, as it picks …
=> Fix airport mortars

A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [X] Bug
2. [ ] Change
Classname typo, prevents CAS jet using guns and throws RPT errors.    
closes #XXXX
1. [X] No
=> Fix bad cannon classname for ACR CAS plane

A3A/addons/core/Templates/Templates/CUP/CUP_Reb.sqf
1. [ ] Bug
2. [X] Change
Switched out the Zu23 Hilux for the Zu23 Ural in the CUP rebel template, because apparently the AIs cannot drive the Hilux without rolling it. The Hilux can come back later as a player vehicle once we have the buy menu.
closes #XXXX
1. [X] No
=> Switch CUP rebel AA vehicle to Ural zu23 because the AIs cannot drive

A3A/addons/GUI/dialogues/controls.hpp, A3A/addons/GUI/dialogues/setupDialog.hpp
1. [ ] Bug
2. [x] Change
Information:
Move the controls that John defined into control.hpp so that if we need a combobox or one of the other defines we don't have to double define stuff. 
1. [x] No
Steps: 
Notes:
=> Move the controls defined in setupDialog.hpp to control.hpp

A3A/addons/core/functions/Convoy/fn_createAIAction.sqf
1. [x] Bug
2. [ ] Change
Information:
fn_createAIAction uses wrong rebel faction hashmap key.
1. [x] No
=> Unarmed key fix in fn_createAction

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/core/functions/Intel/fn_searchIntelOnLeader.sqf
1. [x] Bug
2. [ ] Change
For some reason players have a "Search for Intel" action on very alive and conscious enemy leaders which does not makes sense at all. Also, there are some exploits that allows to  search intel multiple times (I don't remember exact steps to reproduce as it was fixed in Antistasi Plus for about an year, but it seems it was tied to changing conscious/unconscious state of leader by wounding and reviving him).
This PR fixes both issues.
1. [x] No
Steps: 
1. Stay close to enemy SL with intel while being, for example, undercovered. "Search for Intel" action prompt will not appear.
2. Wound him …
=> 🗎 Leader Intel Search Fixes

A3A/addons/core/functions/ModsAndDLC/fn_darkMapFix.sqf
1. [X] Bug
2. [ ] Change
Apparently getLighting returns 0 brightness when Arma is tabbed out, at least in fullscreen. This causes darkMapFix to overbrighten the screen for 15 seconds after tabbing back in. Seemed minor to me, but multiple people did complain, so may as well fix it.
closes #XXXX
1. [X] No
Run game on CamLaoNam. Alt tab for >15 seconds. Tab back in.
=> Fix darkMapFix whiteout after alt-tab

Tools/Builder/buildAddons.ps1
1. [x] Bug
2. [ ] Change
Information:
not having unique names for our key gen caused signed mods to have the same detection in the launcher, this adds the version number to the key gen when building with the buildAddon.ps1 script that out ci/cd tools use (can be used by local users too)
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> Added version number to the bikey generation

A3A/addons/core/functions/Intel/fn_searchIntelOnLaptop.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [x] Bug
2. [ ] Change
Old texture paths does not work in mod environment. This PR fixes laptop and mapX texture paths.
closes #XXXX
1. [x] No
=> Texture path fix for setObjectTextureGlobal

A3A/addons/Garage/Public/fn_addVehicle.sqf
1. [X] Bug
2. [ ] Change
Utility items (lights, fuel tanks) were being refunded to player money rather than faction money, which I'm assuming was unintentional.
closes #XXXX
1. [X] No
=> Make garaged utility items refund to faction money

A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf
1. [x] Bug
2. [ ] Change
REP_Antenna mission is broken as it can't spawn repair truck due to missing pick from repair vehicles pool for `createVehicle`.    
closes #XXXX
1. [x] No
=> createVehicle fix for REP_Antenna

A3A/addons/JeroenArsenal/JNA/fn_arsenal_loadInventory.sqf
1. [X] Bug
2. [ ] Change
The loadout loading code wasn't updated along with other guest-limit changes. It was using a now-undefined variable (memberOnlyMagLimit), so I'm not sure why it wasn't throwing client RPT errors. Whatever. Result seems to be that it was possible to take member-only mags from the arsenal by loading a loadout. This PR fixes it, along with an old issue where the displayed missing item count could be too high.
closes #XXXX
1. [ ] No
I've tested what I could think of, but players get twitchy as hell when it comes to the arsenal, so this might not be a candidate for a speed merge.
=> Fix bug where guests could take limited magazines by loading a loadout

A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf, A3A/addons/core/functions/OrgPlayers/fn_playerLeash.sqf, A3A/addons/core/functions/OrgPlayers/fn_playerLeashCheckPosition.sqf
1. [X] Bug
2. [ ] Change
I didn't read the leash/FT code sufficiently and missed a couple of things:
- Guest commander was unintentionally still blocked from fast travelling to far locations.
- Previous behaviour removed all leash restrictions when there were no members online. This is no longer desired behaviour now that we have guest commanders with leash privileges.
closes #XXXX
1. [X] No
You can become a guest as localhost by running this:
```
membershipEnabled = true;
membersX = [];
[] spawn A3A_fnc_playerLeash;
```
The playerLeash call is necessary because the leash loop currently exits as soon as the player …
=> Fix guest commander leash issues

A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
1. [ ] Bug
2. [X] Change
Rebel UAVs were being deleted by the garbage cleaner when more than 500m away from players, even though this is reasonable behaviour for UAVs. They're already special-cased for marker spawning (they're not general spawners) so it makes sense to special-case them here.    
closes #XXXX
1. [X] No
=> Remove UAVs from garbage collection

A3A/addons/maps/Antistasi_vt7.vt7/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
multiple ammo trucks from ammo truck missions got reported as exploding. Hence all assets got moved a bit away from roads to give more space for spawning
=> moves assets further from road on vt7_outpost_10

A3A/addons/core/Templates/Templates/CUP/CUP_AI_TKA_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
1. [x] Bug
2. [ ] Change
Information:
Apparently there was a little Line Skipper and we had Faces assigned as Voices and the other way Around.
closes #XXXX
1. [ ] No
Steps: 
Any Unit from the Factions should have the Right Faces and Voices.
A Wrong Entry will just use "Default Face" and English as Voice.
Notes:
=> Fix Face-Voice Typo in CUP Templates

A3A/addons/core/Includes/cba_settings.sqf
1. [ ] Bug
2. [x] Change
Information:
Due to how Ace Captives is set up by Default it would allow Players to cheese-Exploit a few things.
**ace_captives_allowHandcuffOwnSide**
This Allows to Handcuff your Own Factions Units, Player can cheese stuff from Stealing Friendly AI Gear up to keeping Petros Handcuffed so Ai cant Attack his as he is SetCaptive.
**ace_captives_allowSurrender**
This Setting is Only for Players, it Allows Players to Put their Hands up and Surrender.
They can't Move and get SetCaptive so Ai won't Attack them (Sometimes you dont get SetCaptive which makes it funny too).
This can be Exploited by Surrendering Mid Combat, waiting for Ai to Leave the Area and then contiue whatever you wanted todo
**ace_captives_requireSurrender**
These are just Settings …
=> Force Ace Captives settings to prevent silly Exploits

A3A/addons/core/functions/Intel/fn_placeIntel.sqf
1. [x] Bug
2. [ ] Change
Information:
Desk object simulation could be enabled if it's corresponding building has been previously destroyed thus eliminating objects forever frozen in air (usually it's a problem for multistory buildings and tower-like constructions). This PR does this thing, also it removes intel if intel building destruction occured.
closes #XXXX
1. [x] No
Steps: 
1. Destroy building with spawned desk with intel.
2. The table should fall to the ground, it's intel should dissappear.
=> Fix intel desks hanging in air after building destruction

A3A/addons/core/functions/init/fn_playerMarkers.sqf
1. [X] Bug
2. [ ] Change
The player markers logic was very bad and didn't correctly handle players respawning or changing group. I rewrote it. Features are mostly the same, although it now contracts players in a vehicle to the format "player1/player2+N". Perf should be somewhat better.
Method uses `getPlayerID` as a persistent tracking value. I originally used `getPlayerUID` which probably worked but was impossible to test due to loopback players having the same UID.
closes #2590
1. [ ] No
Couldn't test with more than two players. Not enough RAM.
You're gonna need some players.
=> Rewrite playerMarkers so that it works

A3A/addons/core/functions/Save/fn_loadServer.sqf
1. [X] Bug
2. [ ] Change
Because the loading code only replaces invader and rebel marker sides, markers that had been changed from invader to occupant either by reb vs gov or capture were being reset to invaders on loading. This PR fixes the problem by resetting every main marker to occupants before the load.
Also fixed a perf bug in the roadblock side selection.
closes #2596
1. [X] No
Create new reb vs gov game. Save. Load.
=> Fix marker side loading

A3A/addons/core/Templates/Templates.hpp
1. [x] Bug
2. [ ] Change
Information:
The 3CB BAF Templates are written with the RHS Vehicles Dependency in Mind, not loading RHSUSAF will result in Instant Wins for Ammo Truck Missions, and Lack of other Vehicles etc.
closes #XXXX
1. [x] No
Steps: 
Load 3CB BAF without RHS and with, it should only be selectable with RHS.
Notes:
=> Childproof 3CBBAF

A3A/addons/core/functions/Save/fn_collectSaveData.sqf
1. [X] Bug
2. [ ] Change
The original & old community save detection code had a few bugs:
- Error-throwing use of undefined campaignID var in cases with no previous save.
- Wrong variable name in the conditional bypassed the whole section.
- Misread of original code: CampaignID is the new one, ServerID is original.
Fixed, everything probably works now. Original saves even appear to load correctly.
closes #2602
1. [X] No
=> Fix original save detection

A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
1. [x] Bug
2. [ ] Change
Information:
HC mortar squads are not working due to faction hashmap key typo. This PR fixes that.     
closes #XXXX
1. [x] No
Steps:
=> HC Mortar faction key fix

A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/keybinds/fn_keyActions.sqf
1. [X] Bug
2. [ ] Change
With the setup UI, I overlooked the ability to use various Antistasi hotkeys before associated systems were initialized, causing errors with uninitialized data. This PR disables those hotkeys until client init is complete.
closes #XXXX
1. [X] No
=> Fix early battle menu key use

A3A/addons/core/functions/Intel/fn_placeIntel.sqf
1. [x] Bug
2. [ ] Change
Information:
Seems that `enabledSimulation` is not enough to unfreeze tables on network-complicated environments. The fix includes `enableSimulationGlobal` execution on server which will do the rest (the same way as it used in the same circumstances in the codebase)
closes #XXXX
1. [x] No
Steps: 
-
=> Dedicated Server/Headless client air tables fix

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Base/fn_initPetros.sqf, A3A/addons/core/functions/CREATE/fn_CIVinit.sqf, A3A/addons/core/functions/CREATE/fn_NATOinit.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/Missions/fn_RES_Prisoners.sqf, A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf, A3A/addons/core/functions/REINF/fn_FIAinit.sqf, A3A/addons/core/functions/Utility/fn_setIdentity.sqf, A3A/addons/core/functions/Utility/fn_setIdentityLocal.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [X] Bug
2. [ ] Change
We used BIS_fnc_setIdentity to set voices and faces globally, but it didn't work correctly because it assumes that the initial call returns false for `isRemoteExecuted`. Because the remote execution flag is passed through spawns (wtf BIS), most Antistasi code actually returns true.
Rewrote with an explicit global/local split. Also skips the reflection-to-server, as that wasn't necessary. You can run JIP remoteExecs from anywhere.
Also changed the name code to use the proper function rather than the one that only sets first/last names, so we no longer need the hack for Petros and future unit naming code will be easier.
One somewhat unwanted effect inherited from the original code is that it continually grows the JIP queue until someone new …
=> Fix setIdentity

A3A/addons/core/functions/CREATE/fn_createAttackVehicle.sqf, A3A/addons/core/functions/CREATE/fn_createVehicleCrew.sqf
1. [X] Bug
2. [ ] Change
In 3.0, createVehicleCrew is prevented from filling "showAsCargo" turrets with crew units. This is because BIS_fnc_crewCount counts these turrets as cargo, and hence the cargo capacity calculations would return incorrect results if they were filled with crew. However, in some cases (eg. various RHS Mi-8 doorguns) these turrets weren't filled with cargo either, unintentionally nerfing the vehicles.
This PR forces the cargo turrets to be filled: With cargo units in the case of transport vehicles, and with crew in the case of attack helicopters. For some transport helis this is questionable, as they have plenty of other cargo seats and dismounting the door gunners may not be ideal. However it is what the mod specifies, and in some cases we'd need …
=> Ensure cargo turrets (eg. door guns) are crewed

A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf, A3A/addons/core/functions/CREATE/fn_milBuildings.sqf
1. [X] Bug
2. [ ] Change
Static crew could be created with simulation disabled due to their creation code running NATOinit before moving them into the static weapon. Because static crew are assumed to have simulation enabled, they'd remain disabled, making them invulnerable to damage.
This PR fixes the issues by moving the NATOinit calls after moveInGunner. Structure is generally bad but I'll probably be reworking garrisons soon-ish so it'll do for now.
closes #2666
1. [X] No
In theory you can trigger the original issue by moving within spawn distance of a marker and then immediately moving out again, so that at …
=> Fix static crew simulation bug

A3A/addons/core/functions/Dialogs/fn_moveHQObject.sqf
1. [x] Bug
2. [ ] Change
Information:
sets the mass of the object to be close to zero, to prevent damage. Same method as the other carry code. Maybe on day we will merge all the carry code.
closes #2593
1. [ ] No
Steps: 
Notes:
=> making moveHQObjects non-lethal

A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
1. [ ] Bug
2. [x] Change
Information:
Uses code from moving hqObjects to place the objects of the surface of other objects. Allows players to place the object on top of a surface.
1. [x] No
Steps: 
Notes:
=> Add the ability for carrable objects to be placed on surfaces

A3A/addons/core/Templates/Templates/GM/GM_AI_NVA.sqf
1. [X] Bug
2. [ ] Change
GM BW template had an artillery classname with no matching magazine spec, breaking the artillery support. Apparently it wasn't supposed to be there, so I removed it.
closes #2654
1. [X] No
=> Fix GM artillery error

.github/workflows/publishBranchToSteam.yml, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [ ] Change
Information:
This enhancement will disable lambs danger when it is loaded despite warnings to NOT load it.
It needs CBA, but that should be a requirement anyways already.
Notes:
I have gotten multiple people asking me about lambs and antistasi compat. Since lambs tries to integrate like vanilla AI, just with another FSM it is often seen that a mission should have an implementation to deal with it.
The Antistasi docs make it clear that lambs is not to be loaded and is not supported. As far as I could tell, it keeps happening that people do it anyways. So here ya go, it just disables all danger AI features from lambs without additional network cost. Problem solved.
=> Disable lambs danger when it is loaded

A3A/addons/core/functions/OrgPlayers/fn_radioJam.sqf
1. [X] Bug
2. [ ] Change
Fixed a bug in radioJam where jamming could persist after the last radio tower was destroyed or captured, as jamming was only changed if there were enemy towers present.
The code also did a full N(radio towers) * M(outposts+airports+seaports) distance scan on every check so I rewrote it. 
closes #2630
1. [X] No
Can be tested without TFAR running. After setup, load the jam script with:
`[] spawn A3A_fnc_radioJam`
Then do something like this to observe the effects:
```
onEachFrame {
hint str (player getVariable "tf_receivingDistanceMultiplicator");
};
```
=> Rewrite radioJam, improve perf and fix last-tower bug

A3A/addons/core/functions/Base/fn_buildHQ.sqf, A3A/addons/core/functions/Base/fn_placementselection.sqf, A3A/addons/core/functions/Base/fn_relocateHQObjects.sqf, A3A/addons/core/functions/Save/fn_loadServer.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
Fixed bug where the two HQ markers (respawnTeamPlayer and "Synd_HQ") could become desynced because placementSelection was setting one of them on the client side for some goddamned reason.
Also stripped out the new-game code from placementSelection (and associated placementDone flag stuff) that was obsoleted by the setup UI HQ placement interface.
The case where the commander disconnects while placing still hasn't been addressed. Quite a lot more work.
closes #2675
1. [ ] No
Should do a DS run really as the code has a client/server split, although it should be solid.
Load or start game, wait …
=> Fix HQ position desync

A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
1. [x] Bug
2. [ ] Change
Information:
- Added logic to remove undercover status when players come within 150 units of crashed heli (based on similar functionality of salvage mission)
- Updated file with standardized header
closes #2311 
1. [ ] No
Steps: 
- Spawn mission
- `["airport_1"] spawn A3A_fnc_DES_Heli`
- Be undercover
- Approach crash site on foot
- ~Get shot at~ lose undercover status
[helidown.webm](https://user-images.githubusercontent.com/733514/205788388-971825c2-9392-4847-8511-b58d6f8354eb.webm)
Notes:
=> implement undercover removal when approaching downed heli

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Base/fn_distance.sqf, A3A/addons/core/functions/CREATE/fn_availableBasesLand.sqf, A3A/addons/core/functions/CREATE/fn_countFreeSpawnPositions.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirplane.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf, A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf, A3A/addons/core/functions/CREATE/fn_createAttackForceMixed.sqf, A3A/addons/core/functions/CREATE/fn_findSpawnPosition.sqf, A3A/addons/core/functions/CREATE/fn_freeSpawnPositions.sqf, A3A/addons/core/functions/CREATE/fn_milBuildings.sqf, A3A/addons/core/functions/CREATE/fn_patrolReinf.sqf, A3A/addons/core/functions/CREATE/fn_spawnVehicleAtMarker.sqf, A3A/addons/core/functions/EventHandler/fn_vehicleDeletedEH.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf, A3A/addons/core/functions/Supports/fn_SUP_QRFAir.sqf, A3A/addons/core/functions/Supports/fn_SUP_QRFLand.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf, A3A/addons/core/functions/init/fn_initSpawnPlaces.sqf, A3A/addons/core/functions/init/fn_prepareMarkerArrays.sqf
1. [X] Bug
2. [ ] Change
Previously ground QRFs could not spawn at any spawned marker. This was a rather severe and exploitable restriction, as once a marker spawns in, it remains spawned as long as any spawning unit is within 1.3km (assuming 1km spawn distance). On some map regions this made land QRFs excessively rare, causing the AI to use more air QRFs and artillery instead.
I rewrote the spawn places system in the process, as the old one required publishing the entire spawn places array for a marker every time a spawn place was allocated or freed. The new one splits the place data and used-place flags and stores a separate array per place type. This doesn't use many extra variables because most locations only have vehicle places anyway. addTimeForIdle is now almost …
=> Rewrite spawn positions so QRFs and garrisons coexist

A3A/addons/core/functions/Base/fn_vehicleBoxRestore.sqf
1. [ ] Bug
2. [ ] Change
Added the ability for the Vehicle Box to restore hearing while running ACE with the Hearing module enabled.
closes #2688 and removes the need for #2313 (abandoned)
1. [ ] No
Steps: 
Run the changes on a server with more than one player and see if it works for multiple players
=> Add ACE Hearing reset to Vehicle Box

A3A/addons/core/functions/Base/fn_updateRebelStatics.sqf
1. [X] Bug
2. [ ] Change
The function that automatically moves rebel garrison riflemen into static weapons (updateRebelStatics) made the false assumption that staticsToSave only contains static weapons. As small and large bunkers are both added to staticsToSave, riflemen would be incorrectly allocated to them and act oddly.
This PR filters staticsToSave down to actual static weapons before selecting them for crewing.
closes #2642
1. [X] No
Build a sandbag bunker, buy a static, add a rifleman to the garrison.
=> Fix bunkers being counted as static weapons for rebel AI manning

A3A/addons/core/dialogs.hpp
1. [X] Bug
2. [ ] Change
Members (including guest members) had the ability to change spawn distance and civ limit values in the game settings UI. This was unintentional. Especially the guest access.
closes #XXXX
1. [X] No
=> Limit spawn distance and civ limit settings to admins

A3A/addons/garage/Extras/fn_reloadMounts.sqf
1. [X] Bug
2. [ ] Change
As described in #2620, there's an exploit where if you use the garage to mount a static weapon in a vehicle and then swap the vehicle to one that cannot load it, placing the vehicle will then spawn a free copy of the weapon.
As far as I can tell, reloadMounts is just overcomplex: On a refresh operation, it starts with the old list of statics, removes those that are unticked (but not those that are no longer in the UI list, hence the bug), and then adds those that are newly ticked. However, as there's no attempt to preserve the objects themselves, this is all unnecessary and the list can simply be rebuilt from the ticked boxes.
I left the original code intact in case I missed something, although I don't think I did. Everything seems to work …
=> Fix garage static weapon vehicle swap exploit

A3A/addons/core/functions/REINF/fn_spawnHCGroup.sqf
1. [X] Bug
2. [ ] Change
spawnHCGroup used moveInAny to board every unit except the driver for rebel infantry trucks. Unfortunately this is bugged, and moveInAny somehow breaks driving AI when used to move an AI into a gunner seat, such that they'll refuse to drive anywhere, or occasionally act like they have a brick wall in front. setEffectiveCommander to the driver will allow them to drive again, but setting it back to gunner (which is default) will block them again. You can do moveInDriver + moveInGunner and it's fine, while moveInDriver + moveInAny will break. Tested with Hunter HMG, Marshall and a couple of GM armed trucks.
Currently this is only an identified problem with GM rebel trucks, so that's what I've fixed. Other usage of moveInAny should be checked, …
=> Workaround Arma bug with moveInAny

A3A/addons/core/functions/AI/fn_inmuneConvoy.sqf
1. [X] Bug
2. [ ] Change
The ancient inmuneConvoy function has an anti-bridge hack that continues running after the vehicle reaches its final waypoint. If it stops near a bridge and not within 500m of players, this causes it to throw a divide-by-zero error because it's trying to teleport to the next waypoint position. Rare but degenerate. Definitely don't want this running after the vehicle runs out of waypoints anyway.
closes #XXXX
1. [ ] No
Still waiting for the test convoy.
=> Fix inmuneConvoy running its bridge hack after reaching its objective

A3A/addons/core/functions/Ammunition/fn_hasARadio.sqf
1. [X] Bug
2. [ ] Change
Unsung handheld radios weren't being detected by hasARadio because the Unsung radios are named xxx_TFAR which fails the check.
Did a dumb fix for it, because getSlotItemName is apparently being added in Arma 2.14 and we can improve the function then.
closes #2655
1. [X] No
=> Fix Unsung radio detection

A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf
1. [X] Bug
2. [ ] Change
The ASF (CAP) supports didn't set the altitude for the loiter waypoint, and the default behaviour is... very weird. L-39s fly around at 100m. F-22s will go into orbit, and then spin down to their deaths once given an attack order.
This PR sets the loiter altitude to 700m. Also fixes an old bug with the maximum targets count which probably never triggers anyway.
closes #XXXX
1. [X] No
=> Fix ASF loiter altitude

A3A/addons/core/functions/Base/fn_distance.sqf
1. [X] Bug
2. [ ] Change
Had an addTimeForIdle in the wrong place. Trouble is that the function breaks if called on cities, because they store different information in the same location. Didn't trigger until invaders owned a city, because I also missed the call for occupants.
closes #XXXX
1. [ ] No
=> Fix incorrect addTimeForIdle

A3A/addons/core/functions/UtilityItems/fn_rotateItem.sqf
1. [x] Bug
2. [ ] Change
Information:
The object database made references to _object in the destructor. This is impossible because _object is out of its scope. This fixes it the make a reference to the database object itself.
1. [x] No
Steps: 
Notes:
=> Fixing rotations again

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf
1. [X] Bug
2. [ ] Change
- compatibleMagazines [weapon, muzzle] is case-sensitive on the muzzle. This is a bug. "UK3CB_G3KA4_GL" has bad casing on the grenade launcher muzzle. This is a bug. We have to deal with it because it's our shit that it breaks.
- Some RHS M70 rifles have a rifle grenade muzzle which has no compatible magazines. categoryOverrides it is.
closes #XXXX
1. [X] No
=> Workaround some bad GL configs

A3A/addons/core/Templates/Templates/#Examples/RebelExample.sqf, A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf, A3A/addons/core/functions/Convoy/fn_createAIAction.sqf, A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf, A3A/addons/core/functions/Missions/fn_LOG_Supplies.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
Original PR By: @igorkis-scrts; `Igorkis-scrts-feature/box-vehicle-template-var`
1. [ ] Bug
2. [ ] Change
Information:
Direct usage of `C_Van_01_box_F` classname has been replaced with template variable which will allow to redefine Bank/Convoy missions vehicle for specific modsets.
continues #2562
1. [ ] No
Steps: 
- Spawn the supply mission.
- Confirm that the supply vehicle is created.
- Confirm that the supply vehicle is not persisted after a save/load (As per [(not (_typeVehX in (A3A_faction_reb get "vehiclesCivSupply")))](https://github.com/official-antistasi-community/A3-Antistasi/blob/63537e45ac03f0f4f70b2fbd1f …
=> 🚚(cont.)Bank/Convoy truck convertation to template variable

A3A/addons/core/functions/Base/fn_mrkWIN.sqf
1. [X] Bug
2. [ ] Change
There may be literally one case on the entire map set where this is possible (outpost_14 on Chernarus summer), but it's possible to have a hill marker and outpost marker close together, which can cause the wrong marker to flip when the flag action is used.
This PR removes roadblocks, hill markers and cities from the mrkWIN lookup as they're not supposed to be flipped with a flag action. Fixes the issue and maybe some other rare cases.
Immediate fix for #2732 but the other half of it needs maps checking.
1. [X] No
=> Fix freak case where mrkWIN can flip the wrong marker

A3A/addons/core/functions/Base/fn_markerChange.sqf, A3A/addons/core/functions/Supports/fn_SUP_CASApproach.sqf, A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf, A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [X] Change
Minor balance tweaks and fixes to support responses:
- Reduce threat value of rebel AA trucks. They were never supposed to get the same threat as AA tanks. Should cut down on CAS requests a bit.
- Reduce maximum air defence spend to 30%. Cuts down on useless jetspam. Not like AIs can shoot competent players down anyway.
- Block outposts from sending QRFs for 30min after recapture. Bug, assumed these had the same rules as airports.
- Cap maximum CAS attack runs to three. On high-activity servers, CAS could be a little too effective due to constant availability of new targets.
closes #XXXX
1. [X] No
2. [ ] Yes (Please provide further detail …
=> Support response tweaks

A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
1. [X] Bug
2. [ ] Change
Turns out that you could freely walk onto enemy airbases when on foot, making it trivial to steal armoured vehicles. Fixed some other shit while I was in there:
- Fix a corner case where you could enter an airfield undercover through another marker.
- Fix civilian planes doing the road proximity check.
- Clean up unnecessary setCaptive remoteExecs and JIP spam.
- Improve text hints for detection by enemy bases.
closes #2729
1. [ ] No
Probably needs some live-server testing just in case there's some reason to spam remoteExecs on setCaptive that I missed.
=> Undercover fixes

A3A/addons/core/functions/AI/fn_attackDrillAI.sqf, A3A/addons/core/functions/REINF/fn_vehStats.sqf
1. [?] Bug
2. [X] Change
After giving a high command squad a Y-menu dismount order, they'd still board a vehicle if ordered to travel more than 200m with no enemies visible. This was generally not how commanders wanted the order to work.
This PR changes the logic so that HC squads won't reboard after a Y-menu dismount order unless given a mount order. They can still reboard if they decided to get out on their own, for example due to enemy contact.
closes #XXXX
1. [X] No
=> Prevent HC squads reboarding to travel after an explicit dismount order

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/Base/fn_createPetros.sqf, A3A/addons/core/functions/Base/fn_initPetros.sqf, A3A/addons/core/functions/Base/fn_petrosDeathMonitor.sqf, A3A/addons/core/functions/Base/fn_placementselection.sqf
1. [X] Bug
2. [ ] Change
Petros post-death placement handling wasn't reliable. If a player managed to exit the placement interface (eg. by dying or disconnecting) then no-one would have access to the placement control.
With this PR, a petros death instead triggers a monitor loop that triggers the placement UI on suitable commanders. It survives both commander deaths and disconnections, and any other map close actions.
closes #2701
1. [ ] No
- Consider disabling the debug petros respawn. That might cause more issues than it fixes now.
=> Rework Petros death handling

A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf
1. [X] Bug
2. [ ] Change
When crate or vehicle contents were transferred to the arsenal, it would run an unlock check (arsenalManage) but before adding the new items due to timing issues. This PR fixes the problem by removing the last server->server remoteExec in the way.
Would have been a lot harder to fix before, but another blocking issue with arsenal_addItem timing was fixed relatively recently.   
Items may or may not unlock immediately for players who are already viewing the arsenal. Shouldn't be an issue.
closes #885
1. [X] No
=> Fix crate transfer not updating arsenal unlocks with new items

A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf
1. [ ] Bug
2. [ ] Change
The punishment system didn't detect ACE grenade throwing (shift-G default). Now it does.
closes #1690
1. [X] No
=> Prevent use of ACE grenade throwing near HQ

A3A/addons/core/functions/Base/fn_createOutpostsFIA.sqf
1. [X] Bug
2. [ ] Change
There have been several cases of players breaking badly by completing a roadblock using remote control, including Arma crashes and broken player objects. Couldn't replicate, maybe because a dedicated server with significant latency is required.
The roadblock code has specific logic for this, which is bad but shouldn't cause this sort of problem. My best guess is that the problem is that the roadblock code deletes the units immediately after, and this can outpace some selectPlayer functionality. Added a short delay and removed some redundant operations that wouldn't have worked correctly anyway due to remoteExec order.
maybe closes #1964
1. [ …
=> Test-fix for establishing a roadblock using remote control

A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf
1. [x] Bug
2. [ ] Change
Due to FAKs and Medkits not set, they are not recognised for Antistasi revive system.
This fixes it and also adds toolkits and pilot clothing.
1. [ ] No
=> additional GM template stuff

A3A/addons/core/functions/CREATE/fn_FIAinitBASES.sqf, A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
1. [X] Bug
2. [ ] Change
Some classic-Antistasi code that revealed air units to garrison gunners & missile launcher troops was accidentally revealing *everything* to those units due to a precedence error. This was easy to demonstrate by moving within spawn distance of an early-game (vehicle) garrison while not undercover, because those garrisons don't use UPSMON (or patcom now), so they'd use the vanilla behaviour of sending units to investigate the contact. This bug may well have had significant performance penalties in addition to some weird cheating behaviour.
Fixed it to only reveal air vehicles. Also cleaned up and improved performance of the reveal code.
closes #XXXX
2. [X] Have you loaded the mission on a dedicated …
=> Fix units being inappropriately revealed to garrisons

A3A/addons/core/Stringtable.xml, A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/Base/fn_garrisonInfo.sqf, A3A/addons/core/functions/Dialogs/fn_unit_recruit.sqf, A3A/addons/core/functions/REINF/fn_equipRebel.sqf, A3A/addons/core/functions/REINF/fn_garrisonAdd.sqf, A3A/addons/core/functions/REINF/fn_garrisonDialog.sqf, A3A/addons/core/functions/REINF/fn_reinfPlayer.sqf, A3A/addons/core/functions/Templates/fn_compileGroups.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
There was an old feature where if you had missile launchers set to unlockable, recruiting engineers to your squad or riflemen to garrisons would equip them with a missile launcher. This was removed with the rebelGear/no-unlocks update, but the intention was that it'd be replaced by directly purchasable (but expensive) missile launcher troops in the new UI. As this still isn't finished and people are complaining about it, I've jammed new buttons into the unit recruit and garrison recruit UIs.
It's a bit questionable whether we should be allowing direct purchase of missile launcher AIs, but:
1. They're expensive at 500+ per unit.
2. AIs are idiots and usually stand in the wrong place to use the things.
3. Zu23s are relatively overpowered against …
=> Allow rebels to purchase AT and AA missile launcher troops

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
1. [X] Bug
2. [ ] Change
The syntax for adding the WS ZU23 static AA was incorrect in the vanilla rebel templates, causing them to be unpurchasable. This PR probably fixes it.
New bug in 3.2.
closes #XXXX
1. [ ] No
Need someone else to test this as I don't have WS.
Start campaigns with vanilla FIA and SDK rebels with WS DLC enabled in the factions page. Check that the static zu23 is available to purchase in the vehicle buy menu.
=> Fix syntax for adding WS CDLC static AA to rebel templates

A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [X] Bug
2. [ ] Change
Fixed some bugs in the ION Temperate template:
- Trailing comma in vehiclesAPCs.
- No L39s in KDF as far as I can tell. Put a MiG 29 in there instead.
There are cluster MLRS launchers in these templates. Not sure if there are supposed to be anymore as they were too strong?
closes #XXXX
1. [ ] No
Maybe make a note to test this template for 3.3.
=> Fix trailing comma and missing AA plane in ION Temperate

A3A/addons/core/functions/CREATE/fn_NATOinit.sqf
1. [X] Bug
2. [ ] Change
The enemy skill calculation had an unintentional dependence on the resource balance setting, so setting resource balance to Hard would increase enemy skill substantially for high player counts. This PR fixes this by calculating directly from active player count instead.
The calculation works out pretty close to previous values (at Normal) for most of the player count range, with a small reduction at very high player counts.
closes #XXXX
1. [X] No
=> Remove unintentional enemy skill dependence on resource balance setting

A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf
1. [x] Bug
2. [x] Change
Information:
Replaced duplicate entries of vehicles in the vanilla SDK template (`I_G_Offroad_01_AT_F `listed twice)
Removed the duplicate civilian offroad from the FIA & SDK template (`C_Offroad_01_F`), replaced by the jeep
Replaced the unarmed Tigr (`rhs_tigr_m_vv`) used for militia light armed with an armed Tigr (`rhs_tigr_sts_vv`)
closes #2779, #2765
1. [x] No
Steps: 
Notes:
The armed Tigr (`rhs_tigr_sts_vv`) has both a PK and an AGS, if that is too powerful either for the enemy or too powerful for the ease of access for the rebels …
=> Bugfix (Duplicate rebel vehicles/unarmed AFRF tigr) #2779 #2765

A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/UNS/UNS_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf
1. [ ] Bug
2. [x] Change
Information:
Across all rebel templates:
Discounted vehicles with 7.62 MG's by 100$
Discounted static 7.62 MG's by 100$
Discounted vehicles with 5.56 MG's by 200$ (SDK)
closes #2803
1. [x] No
Steps: 
Notes:
There were a lot fewer vehicles that this was applicable for than expected, perhaps the rebels could get some additional vehicles in the future.
For VN and UNS their discounts may not make sense due to their earlier technology setting where 7.62 MGs might be a lot better compared to the equipment it is up against
=> Discounted rebel 7.62 and 5.56 vics & statics

A3A/addons/core/functions/CREATE/fn_milBuildings.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
1. [X] Bug
2. [ ] Change
The Patcom garrison AI code wasn't checking whether buildings were destroyed before placing units on them, which could cause units to fall to their deaths on spawn, or possibly spawn underground in some cases.
Also fixed an oversight in the enemy garrison static placement code where statics could be placed underground on a building destroyed in the current session. Apparently buildings are not set hidden when they're destroyed.
closes #XXXX
1. [X] No
=> Don't place units or statics on destroyed buildings

A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [X] Change
Players with narrow screens (mostly laptops) have had trouble seeing the setup UI behind the "Admin is setting up the game" hint. This PR stops it being refreshed while a dialog is opened. Still hangs around for 15 seconds after the dialog opens, but better than nothing.
closes #XXXX
1. [X] No
=> Don't spam hints on top of setup UI

A3A/addons/core/functions/AI/fn_undercoverAI.sqf
1. [X] Bug
2. [ ] Change
Because undercover AIs retain their backpacks but have them replaced when they lose undercover, it was possible to duplicate statics and other devices by ordering assembly while undercover. This PR fixes the problem by not restoring the unit's backpack    if it no longer matches.
Also added random civ hats to undercover AIs, as we have an array for that now.
closes #XXXX
1. [X] No
=> Fix undercover backpack exploit

A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf, A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf
1. [X] Bug
2. [ ] Change
Light APCs were missing from the vehiclesArmor list and IFVs were blocked by a rogue semicolon, with the following effects:
- Not breachable.
- Labelled as MRAP on map.
- Crew bailing out inappropriately.
- CAS not using missiles against them.
Also fixed a related typo in currently-unused vehicle selection code.
closes #2824
1. [X] No
=> Fix typos in lightAPC & IFV categorization

A3A/addons/core/Params.hpp, A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
1. [ ] Bug
2. [X] Change
Minor resource/support tweaks for 3.3:
- Add more levels to resource difficulty params for finer tweaking. The previous 1 -> 1.4 was too large a jump for community at least.
- Take ASF out of combat mode when it returns to loiter (experimental). Thought it was in there before. Might clear up some engage-while-loitering issues. Might not.
- Reduce maximum number of volleys for mortar & artillery supports. Because the effectiveness jump from small -> large servers is too strong. The other multi-target supports (CAS, ASF) already got reduced.
closes #XXXX
1. [X] No
=> Support/resource balance tweaks:

A3A/addons/core/functions/Base/fn_timingCA.sqf, A3A/addons/core/functions/Missions/fn_AS_Official.sqf, A3A/addons/core/functions/Missions/fn_AS_specOP.sqf, A3A/addons/core/functions/Missions/fn_CON_Outpost.sqf, A3A/addons/core/functions/Missions/fn_DES_Antenna.sqf, A3A/addons/core/functions/Missions/fn_DES_Heli.sqf, A3A/addons/core/functions/Missions/fn_DES_Vehicle.sqf, A3A/addons/core/functions/Missions/fn_LOG_Ammo.sqf, A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf, A3A/addons/core/functions/Missions/fn_REP_Antenna.sqf, A3A/addons/core/functions/Missions/fn_convoy.sqf
1. [ ] Bug
2. [X] Change
I realized that the mission rewards that reduced enemy resources were unbalanced enough to be throwing the whole resource system, so this could do with a relatively fast fix.
Principles:
- Most missions have direct effects on enemy resources (especially convoys when destroyed), so they shouldn't have large additional effects. The main exception is AS_official.
- Failure results generally shouldn't be dependent on mission difficulty.
- Increased commander score reward for completed missions, as they were lagging hard in most cases.
- Stripped out some weird/unnecessary city support change rewards.
- Removed aggro reductions for failing missions.
If this is too much for 3.3 I'll have to make another PR to disable timingCA until the next version. …
=> Rebalance mission effects on enemy resources

A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [X] Bug
2. [ ] Change
New chdkz template is using plane versions that don't have a loadout definition. This PR fixes them.
closes #XXXX
1. [ ] No
=> Add CAS planes used by chdkz to setPlaneLoadout

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [ ] Change
Checks server against client versions on client init, throws an error and quits if they're different. Also works correctly with older versions that don't publish a version number.
Wrote a lot of trash to check whether multiple Antistasi mods were loaded as well, but this doesn't seem to be necessary or useful unless the server & client versions are different, so I stripped it out.
Didn't update the version number yet so the display will be kinda weird with 3.2 server versus unstable client.
closes #2784
1. [X] No
=> Check client vs server version on init

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf, A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf
1. [X] Bug
2. [X] Change
- Changed SPE-IFA Wehrmacht militia cars to IFA Kubelwagens (was M3 Halftrack, very obviously US).
- Fixed issue with unarmed cars that could cause them not to drive.
closes #XXXX
1. [X] No
=> Change SPE-IFA militia cars to kubelwagens, fix unarmed car navigation bug

A3A/addons/jeroen_arsenal/JNA/fn_arsenal_itemType.sqf
1. [X] Bug
2. [ ] Change
The arsenal itemType check for fake SPE mags broke on an old bug where the loadout code sends empty strings to ItemType which caused _itemCategory to have the wrong type. This broke loadout loading. 
closes #XXXX
1. [X] No
=> Fix arsenal loadout loading broken by SPE fakemag check  

A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug
2. [ ] Change
Code accidentally introduced with the SPE roadblock changes switched the militia roadblock vehicles from vehiclesMilitiaLightArmed to VehiclesMilitiaCars, causing unarmed vehicles to show up in roadblocks for all modsets. This PR fixes it.
closes #XXXX
1. [X] No
=> Fix unarmed militia vehicles being used in roadblocks

A3A/addons/core/functions/init/fn_initVarCommon.sqf
1. [ ] Bug
2. [X] Change
Found a couple of additional bocage mounds with building positions that aren't in the blacklist. Added them.    
closes #2869
1. [X] No
=> Block units from spawning in additional SPE bocage mounds

A3A/addons/core/functions/REINF/fn_addFIAveh.sqf, A3A/addons/core/functions/Save/fn_loadStat.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf
1. [X] Bug
2. [ ] Change
Forgot to do full save/load testing for the buyable items refactor. Lots of bugs:
- Fixed bought statics not being added to staticsToSave.
- Fixed incorrect logic for adding statics/bunkers to staticsToSave on load.
- Fixed copypaste errors in 50m HQ vehicle save checks.
- Fixed attached statics being inappropriately saved (partially old).
closes #2867
1. [X] No
=> Various vehicle/static save fixes

A3A/addons/core/functions/AI/fn_autoRearm.sqf
1. [X] Bug
2. [ ] Change
The autoRearm function had an ancient bug that caused it to jam permanently if it wasn't possible to fit 10 first aid kits into a medic's equipment. Quick-fixed by bailing when the source container runs out of FAKs. Should work. Also fixed the waitUntil spam on the doMove monitors.
Not tested because I know I'm going to find ten other horrific bugs if I test this monstrosity. It hasn't kept up with rest of the codebase. At least there shouldn't be anything else in there that jams, as the waitUntils have timeouts and the only while is bugfixed.
closes #XXXX
1. [X] No
=> Fix autoRearm first aid kits jam bug and reduce waitUntil spam

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
1. [X] Bug
2. [ ] Change
Misspelt entry in categoryOverrides, caused some RPT errors when AIs attempted to use a tripod as an anti-tank weapon.
closes #XXXX
1. [X] No
=> Fix Lafette tripod category override typo

A3A/addons/patcom/functions/Patcom/fn_patrolArmStatics.sqf
1. [x] Bug
2. [ ] Change
Information:
Undefined Variable in PatrolArmStatics on line 59 due to unitArray being exhausted.
closes #2895 
1. [x] No
Steps: 
Notes:
`<12799> 2023/07/16, 16:21:49 Error in expression <e _unit = selectRandom _unitArray;
<12800> 
<12801> if (_unit distance2D _x < 100) then {
<12802> _assig>
<12803> 2023/07/16, 16:21:49   Error position: <_unit distance2D _x < 100) then {
<12804> _assig>
...
<12806> 2023/07/16, 16:21:49   Error Undefined variable in expression: _unit
<12807> 2023/07/16, 16:21:49 File …
=> Fix for undefined variable in ArmStatics

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf
1. [ ] Bug
2. [ ] Change
Rebel AI can't use the SPE grenade launcher rifles because they're broken down into base weapons when adding them to the arsenal. This PR searches categoryOverrides for suitable weapons and adds them in generateRebelGear when you have sufficient rifles and muzzles.
Probably a bit too dangerous for 3.3.3 because it has a small risk of causing issues in other modsets.
closes #2897
1. [ ] No
Check if it does anything weird in other modsets.
After startup you can check the value of `A3A_specialGrenadeLaunchers` for weird shit. It's a hashmap with GL rifle classes as keys and [baseweapon, muzzle] …
=> Enable rebel AI to use rifle+muzzle combo grenade launchers

A3A/addons/core/functions/CREATE/fn_createAttackForceAir.sqf
1. [x] Bug
2. [x] Change
Information:
Fix to allow AI use light helis in QRF    
1. [ ] No
2. [x] Yes (Probably.)
Steps: 
Just spam this command in console ["QRFVAIR", Occupants, attack, 10000, player, getPosATL player, 1, 0] spawn A3A_fnc_createSupport; 
=> Fix to allow AI use light helis in QRF

A3A/addons/core/functions/init/fn_initVarCommon.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf, A3A/addons/patcom/functions/Patcom/fn_patrolInit.sqf
1. [ ] Bug
2. [x] Change
Information:
Changed how garrison units are distributed to buildings. Instead of filling up all building positions and then moving to the next building in the list, the script now takes the amount of garrison-able buildings and units and distributes them evenly with a defined minimum allowed in each building.
Changes how finding garrison-able buildings functions. Instead of it being a one or the other choice,  it now just uses the A3A building blacklist and checks for pre-defined building positions in the whitelist. If pre-defined positions are not found, we use the default ones and randomize.
1. [x] No
2. [ ] Yes (Please provide further …
=> PATCOM Garrisons minor fixes and adjustments

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf
1. [ ] Bug
2. [x] Change
Information:
Added csat transport planes so every template has them    
1. [x] No
Steps: 
Notes:
Can check existence of hex camo variant here https://community.bistudio.com/wiki/Arma_3:_CfgVehicles_EAST#:~:text=O_T_VTOL_02_infantry_hex_F
Enoch variant same as tropical and temperate since every other vehicle in this template uses Ghex camo
=> CSAT enoch and arid transport planes

A3A/addons/core/functions/AI/fn_mortarDrill.sqf
1. [x] Bug
2. [ ] Change
Because otherwise the call `Faction(side _groupX)` is not meaningful. `faction` in A3A is both a [unary](https://community.bistudio.com/wiki/faction) and a macro defined in `common.inc`. Without the include, it behaves as the unary function, that expects a unit. My understanding is that here we expect the macro call, that requires the include.
Identified by [sqf-analyzer](https://marketplace.visualstudio.com/items?itemName=SQF-analyzer.sqf-analyzer).
1. [x] No
=> Fixed missing include

A3A/addons/core/functions/init/fn_initZones.sqf
1. [ ] Bug
2. [x] Change
Adds GM assets for compatibility.
Fuel stations are defined in mapInfo.hpps, no need for anything
There are no useful buildings to use with static placements, nothing to add here either.
=> Add GM Assets

A3A/addons/config_fixes/RHS/chdkz_rhs.hpp, A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf
1. [ ] Bug
2. [x] Change
Information:
Added retextured classes of the RHS armed Mi8's to provide correct camouflage for the faction template.
1. [x] No
Steps: 
Loading into the editor and placing these down should be sufficient.
Notes:
=> Retextured RHS Mi8's to chdkz camo

A3A/addons/garage/CfgFunctions.hpp, A3A/addons/garage/Core/fn_getLockCount.sqf, A3A/addons/garage/Core/fn_toggleLock.sqf, A3A/addons/garage/Public/config.inc, A3A/addons/garage/Public/fn_addVehicle.sqf, A3A/addons/garage/Stringtable.xml
1. [ ] Bug
2. [ ] Change
Heavily-requested community feature. Adds CBA-configurable member and guest limits to garage vehicle locks. It ignores source vehicles, as they are effectively public resources that should be managed by the commander.
Issue that needs resolving: Garage is currently rendered on top of customHint. Not sure why yet.
closes #2823
1. [ ] No
Need to fix the UI rendering order issue.
=> Add member & guest lock limits to garage

A3A/addons/core/functions/AI/fn_combatLanding.sqf
1. [X] Bug
2. [ ] Change
The combat landing routine didn't trigger landing gear use because it never told Arma that it was landing. This PR fixes it. Seems to work and shouldn't have any negative effects on other helis. Might be more reliable in other ways.
Not sure if any helis weren't currently using have landing gear aside from the vanilla Huron.
closes #2929
1. [X] No
See #2929
=> Fix Huron (vanilla Chinook-like) not using gear on combat landing

A3A/addons/core/functions/Base/fn_relocateHQObjects.sqf, A3A/addons/core/functions/Save/fn_loadServer.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [X] Change
Moved HC logic objects along with HQ. This needed three hooks for different HC join times, because the logic objects don't exist until an HC connects:
1. relocateHQObjects: The obvious one, triggered on new games and when the HQ is moved.
2. loadServer: Loading a game doesn't call any HQ relocation functions.
3. initClient: Required for headless clients joining in progress.
In theory this should improve AI responses, because firedNear event handlers are based on the headless client logic position. Difficult to test but it's easy enough to move the logic objects so may as well.
closes #2875
1. [X] No
2. [ ] Yes (Please provide further detail …
=> Move headless clients with HQ to theoretically improve AI responses

A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
Turns out that OnUserAdminStateChanged fires when the current admin disconnects, but after the user info is cleared out, so getUserInfo doesn't work on the ID, Probably an Arma bug but whatever. We only care about players gaining admin status rather than losing it, so preventing the RPT error is enough.
closes #2896
1. [X] No
=> Fix RPT error when admin disconnects

A3A/addons/core/Templates/AddonVics/cup_veh_Civ.sqf
1. [X] Bug
2. [ ] Change
The CUP civ vehicles addon (#2919) had a missing comma. Tested working now.
closes #XXXX
1. [X] No
=> Fix missing comma in CUP civ vehicles addon

A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [X] Change
Prevent high command squad icons from being visible in 3d display, because it's a massive cheat. The icons make it very easy to spot enemy units when you're commander.
closes #2971
1. [X] No
=> Prevent high command squad icons from being visible in 3d display

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/LTC/fn_initLootToCrate.sqf
1. [X] Bug
2. [ ] Change
Found some stringtable key mismatches:
1. Carry and rotate had wrong key. That's mine from #2384, broke it late in the merge.
2. Loot-to-crate action was missing the c off the end. From Bob's big PR.
Wasn't even trying to test this, so maybe a bit worrying that I found #2.
closes #XXXX
1. [X] No
=> Carry, rotate and loot to crate stringtable fixes

A3A/addons/core/Templates/Templates/SPE/SPE_REB_FFF.sqf
1. [X] Bug
2. [ ] Change
SPE FFF rebel template has a non-basic backpack in initial rebel items, which causes the contents to be switched for explosives when you load it from a loadout. Changed it for the basic variant.
closes #XXXX
1. [X] No
=> Fix non-basic backpack in SPE FFF rebel template

A3A/addons/core/functions/init/fn_initACE.sqf
1. [X] Bug
2. [ ] Change
Fixed a missing semicolon in the ACE rope PR.
Also tested it, works fine except ACE bugged out on connecting the tow rope. Not our problem.
closes #XXXX
1. [X] No
=> Fix missing semicolon in initACE ropeDeployed handler

A3A/addons/core/Templates/Templates/3CB/3CB_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf
1. [ ] Bug
2. [x] Change
Information:
Changes 3CB's FIA to use 7.62 NATO Enfields.
Adds two random rolls for additional Enfield rifles for the TKM and FIA.
This will also make it so that both factions start with at least one beech and one walnut stocked enfield, while making some of the other enfield version appear on occasion.
1. [x] No
Steps: 
Notes:
=> 3CB FIA & TKM Starting enfields

A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
`theBoss` wasn't being published in the case where the server was autostarted, causing RPT errors of unknown seriousness on the first clients. This PR fixes it.
closes #2847
1. [X] No
=> Fix theBoss var not being published in autostart case

A3A/addons/core/functions/Builder/fn_buildingPlacerStart.sqf
1. [X] Bug
2. [ ] Change
- Fixed team leader not being able to use the building placer.
- Fixed error in client-side locking logic that allowed multiple players to use the same builder box. Probably.
closes #XXXX
1. [ ] No
Locking logic is gonna need further MP testing.
=> Fix build placer permissions

A3A/addons/core/functions/Builder/fn_buildingPlacer.sqf, A3A/addons/core/functions/Builder/fn_lockBuilderBox.sqf
1. [X] Bug
2. [ ] Change
Fixed building repair not working on MP clients. The ruin/building link vars were never published, so here we publish the required one to the builder client for nearby destroyed buildings.
Also fixed the code theoretically allowing radio towers to be rebuilt. They were probably too large but whatever.
closes #XXXX
1. [X] No
=> Fix building repair not working on MP clients

A3A/addons/core/Templates/Templates/SPE/SPE_REB_FFF.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf, A3A/addons/core/functions/AI/fn_mortyAI.sqf, A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
1. [X] Bug
2. [ ] Change
Some SPE-specific fixes:
- Give panzerfausts the correct types so that AIs equip them.
- Add panzerfaust ammo to starting gear.
- Prevent RPT error in mortyAI when mortar doesn't disassemble.
closes #XXXX
1. [X] No
=> SPE panzerfaust and mortyAI fixes

A3A/addons/core/functions/init/fn_initClient.sqf
1. [X] Bug
2. [ ] Change
Fixed high command icons being visible after leaving HC mode. Checked this but apparently I got distracted by the white borders, which are added elsewhere.
closes #XXXX
1. [X] No
=> Fix HC icons being visible after leaving HC mode

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/functions/REINF/fn_addFIAsquadHC.sqf, A3A/addons/core/functions/REINF/fn_spawnHCVeh.sqf, A3A/addons/core/functions/Utility/fn_boxCollisionCheck.sqf
1. [x] Bug
2. [ ] Change
With the introduction of the building placer, remotely recruiting vehicles for high command became even less reliable. This is a new routine that attempts to find empty spots facing onto roads, which does a much better job of picking a place where vehicles can actually drive out of HQ in various directions. Deals ok with various obstacle types and terrain gradients.
Fallback uses the old random placement but with a larger radius.
closes #2999
1. [X] No
=> Add routine for better spawning of high command vehicles

A3A/addons/config_fixes/WS/CfgWeapons.hpp, A3A/addons/config_fixes/WS/config.cpp
1. [x] Bug
2. [ ] Change
Information:
arifle_VelkoR5_lxWS had the wrong baseWeapon entry, making it, this corrects that making the gun compatible with the antistasi loot and arsenal system.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> fixed base weapon Vektor R5 GL

A3A/addons/core/functions/Utility/fn_setIdentityLocal.sqf
1. [X] Bug
2. [ ] Change
setIdentityLocal was calling `ace_common_fnc_setName` on every machine, which is a performance problem because that function does two global setVariables. Hence with 30 players you have 60 excess global setVariables per unit created. Fixed by only running on the server, which is simple enough that it can get into 3.4.
Also changed the condition so that it doesn't break in JIP.
closes #2995
1. [X] No
=> Fix ACE setName spam and JIP error

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [ ] Change
Added ACE_suture to initial rebel equipment, because apparently it's required for some medical settings.     
closes #2980
1. [X] No
=> Add ACE_suture to initial rebel equipment

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf, A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf, A3A/addons/core/functions/Ammunition/fn_generateRebelGear.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [X] Bug
2. [ ] Change
Misc essentials and basic medical gear weren't being added to FFF rebels. Troops having no FAKs is pretty bad in vanilla at least, as it prevents them from reviving and may cause them to over-loot later.
I suspect this was a workaround for an issue where the rebel AI equipping code ignores small backpacks even if there aren't any larger ones, as FFF doesn't have any large backpacks at the start. Rewrote that code so that it'll now use the largest available if all of them are small.
Ended up a bit large for a late 3.4 patch but I think I've tested all the cases.
closes #2909
1. [X] No
=> Fix basic/medical gear missing in SPE/IFA FFF rebel faction

A3A/addons/garage/defines.hpp, A3A/addons/gui/config.cpp, A3A/addons/gui/dialogues/arsenalLimitsDialog.hpp
1. [X] Bug
2. [ ] Change
Apparently the arsenal limits dialog only worked by a weird chain of luck. Unlike everything else in the mission, it used the import keyword with vanilla UI classes, which is very wrong syntax outside mission config. Not entirely sure how it did work, but it's written with the correct dependencies now. Can remove the A3 loadorder if I ever convert the arsenal limits dialog to Antistasi UI classes, but it doesn't hurt anyway.
Also found an unused garage UI define that was accidentally overwriting a vanilla class. Fixed.
closes #3014
closes #2958
1. [X] No
=> Fix some weird/broken UI config dependencies

A3A/addons/core/functions/Base/fn_setPlaneLoadout.sqf
1. [X] Bug
2. [ ] Change
Added missing CAS and AA planes used in the WS factions to setPlaneLoadout.
closes #XXXX
1. [X] No
=> Update setPlaneLoadout with missing WS faction aircraft

A3A/addons/gui/dialogues/placerHintsRsc.hpp, A3A/addons/gui/dialogues/teamLeaderBuilder.hpp, A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf
1. [X] Bug
2. [ ] Change
The building placer UI didn't work correctly in any resolution except 1080p, as the placer hints were placed at fixed coords relative to the screen center, and 1080p is the odd one out. Even 4K was busted, because Arma. Non-widescreen resolutions didn't have any room for the hints anyway, as the building selection dialog took up too much space.
Reworked the alignment:
- Hints now based on screen bottom-right, no longer drifts off screen.
- Selector now runs from screen bottom-left to hints UI instead of fixed-width centered.
- Icons a bit smaller so that they fit vertically and you get 3 wide on 4:3.
Icon aspect ratio is varied a bit to avoid giant spaces, because because different resolutions have wildly different pixelgrid counts. The icons …
=> Rework builder UI alignment to work with non 1080p resolutions:

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_Vehicle_Attributes.sqf
1. [ ] Bug
2. [x] Change
Information:
both ION and AAF was way overpaying for their AA vehicle.
Vehicle attributes for the variants of Zu-23 trucks added.
Zu-23 truck added to light armed of ION and CSAT north africa.
1. [x] No
Steps: 
Notes:
=> Added WS AA/Zu truck vehicle attributes 

A3A/addons/core/functions/Base/fn_flagaction.sqf, A3A/addons/logistics/Public/fn_addLoadAction.sqf
1. [X] Bug
2. [ ] Change
Fixed the static weapon move asset and AI permissions actions not showing for JIP clients, caused by the logistics load action JIP blatting them. This was a regression added in #2511 shortly before the 3.0 release.
Also fixed an issue where the non-ACE action for loading an unconscious unit into a vehicle was being global-JIP spammed in a function that was already global JIP.
closes #XXXX
1. [X] No
=> Fix logistics JIP bugs

A3A/addons/core/Includes/script_mod.hpp, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [X] Change
Add checking of Arma version, as requiredVersion is apparently ignored.
Can test by setting REQUIRED_VERSION to a value higher than 2.14 or higher. Effect is a pop-up on starting the mission. Not super-clear what it means, but better than having pirates complain about the AIs not moving and having to dig out their RPTs to find out they're running an ancient Arma version.
I don't think we're currently using anything from 2.14 so I set it at 2.12.
closes #XXXX
1. [X] No
=> Add Arma version checking

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf, A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds the Kozlice 12G and the sawed off variant to the rebel arsenal when the contact DLC is enabled.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Adds Kozlice 12G to rebels

A3A/addons/core/functions/init/fn_initServer.sqf, A3A/addons/gui/functions/SetupGUI/fn_setupParamsTab.sqf
1. [X] Bug
2. [ ] Change
Moved the number param -> boolean variable conversion to initServer to fix cases where autoloading an old save or starting a game with a mismatched client could break.
partial fix for #3041
1. [X] No
=> Move bool param conversion to initServer to fix autoload

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Revive/fn_actionRevive.sqf
1. [X] Bug
2. [ ] Change
If a unit was revived (either by another unit or self-revive) while a second unit is attempting to revive them, that unit will continue the revive animation, and will reset the target unit's health state on completion. 
This PR cancels the second revive attempt once a unit is no longer incapacitated. Throws a message for players.
Tested interrupting both players and AIs, works fine.
closes #3038
1. [X] No
=> Improve double-revive case

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Punishment/fn_punishment_FF_AddEH.sqf, A3A/addons/core/functions/Punishment/fn_punishment_checkStatus.sqf, A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
1. [ ] Bug
2. [X] Change
Added a log & notify only option to the punishment system. Implemented before the actual punishment function because life is too short to read that again.
Needs #3042 to autoload older saves correctly due to bool -> number conversion.
Probably works but not fully tested due to lack of RAM.
closes #3060
1. [ ] No
=> Add log/notify only option to punishment system

A3A/addons/core/Scripts/fn_advancedTowingInit.sqf, A3A/addons/core/functions/Base/fn_mrkWIN.sqf, A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf, A3A/addons/core/functions/REINF/fn_controlunit.sqf
1. [X] Bug
2. [ ] Change
the variable for the title was a private variable, so the hint actually calls the stringtable
decreased the time to wait to match a bit closer with when the animation is finished
closes #3050 
1. [x] No
Steps: 
Notes:
=> Fix for minor header bug

A3A/addons/core/Params.hpp
1. [ ] Bug
2. [x] Change
Updates parameters as readable in #3057
closes #3057
=> params update

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Missions/fn_AS_Official.sqf, A3A/addons/core/functions/Missions/fn_AS_Traitor.sqf, A3A/addons/core/functions/Missions/fn_AS_specOP.sqf
1. [X] Bug
2. [ ] Change
Stringtable: Changed SpecOps to Special Forces. Personal preference, I've heard this and "SF" a lot more than SpecOps, and it's a bit less confusing
Officer mission should render time and faction correctly, and removed a few useless lines
Traitor mission, removed a few useless lines and the old pvp mission
SpecOps: The faction should be displayed correctly, SEE BELOW    
closes https://discord.com/channels/449481990513754112/647694189236322305/1139340437132419212 
1. [ ] No
Steps: 
Officer: Move to the middle of the peninsula south of the southwest airbase, and call an assassinate mission, or …
=> Assassinate mission misc fixes

A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
1. [X] Bug
2. [ ] Change
The early-out cases in patrolGroupGarrison had incorrect return values, which bugged out garrison spawning in cases where there were no buildings to garrison.
Test case: Tanoa outpost_5, just west of the middle airfield.
closes #3039
1. [X] No
=> Fix errors when there are no suitable buildings to garrison

A3A/addons/core/functions/Revive/fn_handleDamage.sqf, A3A/addons/core/functions/Revive/fn_handleDamageAAF.sqf, A3A/addons/core/functions/Revive/fn_unconscious.sqf, A3A/addons/core/functions/Revive/fn_unconsciousAAF.sqf
1. [X] Bug
2. [X] Change
- Fixed a bug where players could have revive permanently disabled if they were killed by damage while downed.
- Changed downed damage lockout to 0.2 seconds rather than one frame. This is to handle a theoretical case where the server might split HandleDamage calls across multiple packets. Not if it happens, but it won't hurt anyway.
- Remove persistence of the downed damage accumulator. The "starting point" for downed damage used to vary by the revive method, but it incorrectly persisted over respawns, and didn't make a whole lot of sense anyway.
closes #XXXX
1. [X] No
=> Fix some real and theoretical revive issues

A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_AFRF_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_CDF.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_SAF.sqf
1. [x] Bug
2. [ ] Change
Information:
the magazine hash for the 2s1 was set to the same magazine as the D-30 rhs_mag_3of56_10 instead of rhs_mag_3of56_35, preventing the gun for functioning.
closes #XXXX
1. [ ] No
Steps: 
Changes aren't necessarily need in this PR but the RHS 2S1 could potentially be not the only one with this issue.
I have not checked 3CB, CUP, and i cannot check CDLC artillery. 
3CB can potentially have inherited this issue, probably what happened with the RHS templates. 
PR itself has been loaded and the gun now functions.
Notes:
before / …
=> Corrected magazine for RHS 2S1 Artillery 

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
Updated version numbers and changelog for 3.4.1 release
=> 3-4-1 changelog and version

A3A/addons/core/functions/Punishment/fn_punishment.sqf, A3A/addons/core/functions/Punishment/fn_punishment_evaluateEvent.sqf
1. [X] Bug
2. [ ] Change
Refactored FF notifications from the punishment system so that they're all called from evaluateEvent. Custom hints like "Watch your fire" and "XXX shot you!" should now show up in notify-only mode. Makes it a bit more readable too.
closes #XXXX
1. [ ] No
Should probably get a non-loopback DS test.
=> Move FF damage notifications into evaluateEvent (master)

A3A/addons/logistics/Private/fn_packObject.sqf
1. [x] Bug
2. [ ] Change
Information:
Item prices were placed on the package, causing refunds to be zero. Extended the price to reflect the packed object.
Ace cargo wasn't defaulted to a size of 4. That was fixed. All packed objects are size 4 for ace cargo.
closes #3084 
closes #3085 
1. [x] No
Steps: 
N/A
Notes:
N/A
=> Fixed: itemprice of packed object not extended to package.

A3A/addons/garage/Public/fn_addVehicle.sqf, A3A/addons/garage/Public/fn_addVehiclesByClass.sqf
1. [X] Bug
2. [ ] Change
Information:
Changed the line to update the garage interface to only work when there's someone in the garage interface, removing 2 startup errors and 1 error every time someone garaged a vehicle. All errors purely present in the logs with no gameplay impact
closes [this discord comment from John](https://discord.com/channels/449481990513754112/637869964107186199/1183578742598148187)
1. [X] No
=> Miscellaneous logs fix for garage

A3A/addons/patcom/functions/Patcom/fn_patrolGroupGarrison.sqf
1. [X] Bug
2. [ ] Change
The building count check in patrolGroupGarrison was put in the wrong place, so garrison spawning may error out when all valid garrison buildings have been destroyed.
closes #XXXX
1. [X] No
=> Fix garrison spawning case where all buildings are destroyed

A3A/addons/garage/StatePreservation/fn_setFuel.sqf
1. [X] Bug
2. [ ] Change
The ACE fuel cargo state wasn't being correctly set when ungaraging vehicles, because ACE uses the ace_refuel_capacity variable to indicate whether the fuel cargo vars have been initialized, and doesn't set it itself until a player interacts with the vehicle. Hence fuel vehicles were being topped up to capacity when players interacted with them.
Not absolutely sure that this is a good thing to merge, because I don't think there's currently any way to top up fuel cargo other than this bug. Community might not deal well with the fix.
closes #XXXX
1. [X] No
=> Fix ACE fuel state not being correctly set on ungaraging

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/UtilityItems/fn_initObjectRemote.sqf, A3A/addons/core/functions/init/fn_initUtilityItems.sqf, A3A/addons/logistics/Cargo/Vanilla.hpp
1. [ ] Bug
2. [x] Change
Information:
Adds more builder boxes with increasing prices. More variety.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Added: More builder boxes

A3A/addons/config_fixes/3CB/CfgWeapons.hpp, A3A/addons/config_fixes/3CB/config.cpp, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_LSM.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_Vehicle_Attributes.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds template for 3CB's  Livonian Separatist Militia.
Adds name to the LDF template.
Adds the 8mm CZ550 "Lux", derived from the 3CB CZ550 but in a caliber that does not 1-shot through every body armor.
1. [x] No
Steps: 
Notes:
=> 3CB LSM rebel template.

A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
1. [X] Bug
2. [ ] Change
The code for spawning trucks at outposts/seaports/resources/factories was supposed to fallback to spawning a truck from vehiclesCargoTrucks if the list would otherwise lack cargo trucks, but the code was incorrect and did nothing. This PR fixes it.
The main difference is that factions are no longer requires to have cargo-capable trucks in the militia list.
closes #3097
1. [ ] No
Please test with a faction that doesn't have cargo vehicles in the militia list. Early game factory or resource should work.
=> Fix fallback code for militia lacking cargo trucks

A3A/addons/core/functions/Base/fn_distance.sqf
1. [X] Bug
2. [ ] Change
Players remote-controlling AIs didn't count for the spawning routine, which could cause nearby markers to despawn unintentionally. This PR fixes it by adding the original player to the array.
closes #3113
1. [X] No
Fast-travel to a rebel garrison or city with no other players nearby. Check that it spawns in (civ cars in the city case, flag and garrison units for the rebel garrison case). Then remote-control a distant high-command squad, wait several seconds and then return control. Check that the state of the nearby marker is unchanged.
=> Fix remote-controlling players despawning rebel garrisons & civs

A3A/addons/core/functions/Base/fn_placementselection.sqf
1. [X] Bug
2. [ ] Change
#3089 added a syntax bug in the Petros placement function that crashed it out, preventing anyone from placing Petros after death. This PR fixes it.
Probably no similar cases because hintC is barely used in the current codebase.
closes #3089
closes #3122 
1. [X] No
=> Fix petros placement stringtable conversion bug

A3A/addons/core/functions/Base/fn_airspaceControl.sqf, A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [X] Bug
2. [ ] Change
The airspaceControl routine was launched by a GetIn EH on the vehicle installed locally by AIVEHInit. Because the vehicle is created locally to the client that bought or ungaraged a vehicle, this means the event handler would be lost if the player who placed the vehicle disconnected. Players who boarded that vehicle subsequently would not be checked for airspace control, and could for example steal outpost crates with an undercover civilian heli.
There was additionally a timing condition where if players boarded or left a vehicle close together, airspaceControl might be incorrectly left running or incorrectly removed.
In this PR I've changed the code to launch with a GetInMan EH on the player(s). Multiple airspaceControl routines could run …
=> Fix cases where airspaceControl wouldn't execute

A3A/addons/core/Stringtable.xml, A3A/addons/core/dialogs.hpp
1. [ ] Bug
2. [X] Change
Added a tooltip to the blank button in the Y menu so that players from older version can find the new construction system more easily.
closes #3132
1. [X] No
=> Add hint to help older players find the new construction system

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/init/fn_initUtilityItems.sqf
1. [ ] Bug
2. [X] Change
The very large builder boxes don't fit in either width or weight for a lot of vehicles that they'll load into. Can be fixed later, but not in 3.5. Also the gameplay need for them is questionable: We probably don't want people building or repairing that much.
Buffed the "large" box to 1500 as a placeholder.
closes #XXXX
1. [X] No
=> Cull large builder boxes because they don't work yet

A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
I had been sitting on this change for a bit now, and wanted to make sure it got in before release.
1. [ ] Bug
2. [X] Change
Information: Previously, maps without seaports would not allow players any discounts for buying vehicles. Now, if a map has less than 4 seaports (it's a reasonable cutoff, most maps have either 5-6 or 0), the vehicle discount will be scaled on war level instead.
1. [X] No
Steps: 
Notes:
=> Vehicle discounts with no seaports

A3A/addons/config_fixes/Vanilla/ifv.hpp, A3A/addons/config_fixes/WS/ws_ifv.hpp
1. [X] Bug
2. [ ] Change
As described in #3127. This PR rewrites the SLAT IFV config entries to inherit their EventHandler classes rather than overwriting.
Some of these vehicles also had non-standard Fired event handlers, so the SLAT versions would have had something missing.
**Todo:** Some of the classes (IIRC the invader ones at least) already have a postInit function that does the texture/animation init, so we should delete one of them. Not sure whether this is better to run as init or postInit. Hopefully doesn't matter.
closes #3127
1. [ ] No
See above, need to cull one of init or postInit for some classes.
=> Make SLAT IFVs CBA-compatible

A3A/addons/core/functions/Supports/fn_SUP_orbitalStrikeRoutine.sqf
1. [X] Bug
2. [ ] Change
A destroyCity call was added to the orbital strike routine. This is incorrect: The orbital strike routine already causes massive destruction on its own and doesn't need any extra. The punishment attack uses destroyCity because it doesn't cause enough destruction naturally.
closes #XXXX
1. [X] No
=> Orbital strike already destroys the city naturally, don't do it twice

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/CREATE/fn_attackHQ.sqf, A3A/addons/core/functions/Undercover/fn_goUndercover.sqf
1. [X] Bug
2. [ ] Change
Information:
Hotfixes for 3.5.1 based on community feedback.
Fixed a rogue quote in a stringtable entry
Removed the option to toggle undercover (removed code and associated stringtable entries)
Added a lost pair of brackets in fn_attackHQ
closes #3146 
1. [x] No
Steps: 
Notes:
=> 3.5.1 Undercover and Defend fixes

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf
1. [X] Bug
2. [ ] Change
Vanilla LDF template broke on a ref to a non-existent variable. This PR fixes it.
closes #XXXX
1. [X] No
Load the vanilla LDF template.
=> Fix rogue var breaking vanilla LDF template

A3A/addons/core/functions/AI/fn_artySupport.sqf
1. [ ] Bug
2. [X] Change
The rebel high command artillery function currently force-spawned markers near the start point. This kinda makes sense, but we don't do it for anything else except major attacks, every other usage assumes it indicates a major attack. It's dangerous because it modifies and pushes the forcedSpawn array from the commander's client, which can lead to desyncs where a marker remains in the array permanently or is incorrectly removed.
This PR disables the forced spawn.
closes #XXXX
1. [X] No
=> Disable forced marker spawn in artySupport

A3A/addons/core/functions/Ammunition/fn_arsenalManage.sqf, A3A/addons/core/functions/Ammunition/fn_unlockEquipment.sqf, A3A/addons/core/functions/Save/fn_loadServer.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [X] Change
In cases where multiple items were unlocked at once (new campaign, loading, arsenal update), the unlockedXXX arrays were re-published with publicVariable per item, causing massive network load and "message pending" spam in some cases. This PR collates the variable names to publish in these cases, so that each array is not published more than once.
All five code paths tested on both localhost and DS+client.   
closes #3080
1. [X] No
=> Avoid spamming unlockedXXX publicVariables

A3A/addons/core/functions/Templates/Loadouts/fn_loadout_addItems.sqf
1. [X] Bug
2. [ ] Change
loadout_addItems assumed that units have a backpack, and could dump large item batches into the void under certain conditions, for example if a batch fitted within uniform+vest but not in either individually. Could happen with marksman rifles, as 5x20rnd 7.62 mags is often too much for a vest, and marksmen don't use backpacks.
This PR fixes the problem by using the vest as the fallback container in the case where backpack max load is zero. This may mean that the vest is sometimes overfilled, but that's working as intended. It does the same with backpacks.
closes #3153
1. [ ] No
Probably needs …
=> Fix case where loadout_addItems loses magazines

A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf, A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/init/fn_initClient.sqf
1. [x] Bug
2. [x] Change
Information:
Fixed a broken WS template missing a few brackets.
The troop training GUI will no longer close after an upgrade is purchased, making it easier if you want to buy more than 1 level at a time.
Players will be kicked out of any animations before teleport, fixing a bug with the setup stage.
Added a space in the "loaded mods" hint.
Localized a No/Yes in the Map Info hint.
1. [x] No
Steps: 
Notes:
=> Minor fixes 20240302

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf
Removed pre-dynamic loadout helicopters
1. [x] "Bug"
2. [ ] Change
Information:
Removed the classnames which predate the Helicopter/Dynamic Loadouts update.
No change in functionality or template vehicle probabilities expected.
The classnames removed predate Dynamic Loadouts so they do not conform with standard expected Arma behaviour anymore.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Removed old Kajman & Orca version from CSAT

A3A/addons/core/Templates/Templates/3CB/3CB_AI_AAF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ADA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ANA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arctic.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Arid.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Temperate.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_BAF_Tropical.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_US.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_HIDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_ION_Temperate.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_KRG.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_MDF.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_East.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_AI_TKA_Mix.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Civ_CHC.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Civ_TKC.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_CNM.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_ION.sqf, A3A/addons/core/Templates/Templates/3CB/3CB_Reb_TKM.sqf, A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf, A3A/addons/logistics/Cargo/3CBFactions.hpp, A3A/addons/logistics/Nodes/3CBFactions.hpp
1. [x] Bug
2. [x] Change
Information:
Adds name identity to a number of template that were opened in the process.
Adds Forklift as rare civilian vehicle.
Adds the MAT49 submachinegun to template MDF and HIDF were appropriate.
Adds the Port Said (M/45) Submachinegun to ADA, TKA East, and TKA Mix were appropriate.
Adds the RPD lightmachinegun to ADA, CW_SOV, LDF, TKA East, and TKA Mix were appropriate.
Adds the CZ550 sniper rifle to the LDF Militia.
Adds scoped Enfield rifles to the HIDF Militia, replacing some rifles.
Fixes the HIDF Militia having the wrong classname for the Bren gun, due to the latest 3CB update (Update 8.0.0 2024-03-12)
closes /*Next report of the HIDF militia not having machineguns*/
closes #3180 
2. [ ] …
=> 3CB Weapons & New Stuff Patch

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf, A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added a param to disable the "restore nearby units" option on the garage box.
Added an option to the fast travel param to completely block fast traveling.
Fixed a typo in a string I found on accident.
closes #XXXX
1. [X] No
Steps: 
Everything should be visible and work from the setup GUI.
Notes:
This is all Bob's fault.
=> Params for no fast travel and no box restore

A3A/addons/config_fixes/RHS/chdkz_rhs.hpp
1. [x] Bug
2. [ ] Change
Information:
Corrects how the eventhandlers for the fixed chdkz tanks from RHS, the ones that had to lose their flags.
In principle the same changes as #3128, and the issue is as described by #3127
closes #3173
1. [x] No
Steps: 
Notes:
This should be the final nail in the coffin for these flags, i hope
=> RHS ChDKZ T-72 Event Handler Inheritance

A3A/addons/core/functions/init/fn_initZones.sqf
1. [ ] Bug
2. [x] Change
Information:
~~adds "nameVillage" to fn_initZones.sqf as that is how some terrains are.~~
~~We could really do with a case insensitive or otherwise more clever solution to this.~~
Kills the case sensitivity of the check at line 76.
No need to add special cases for the various miss-casings of the town types anymore.
1. [x] No
Steps: 
example map https://steamcommunity.com/sharedfiles/filedetails/?id=1757672655
Notes:
=> Updates fn_initZones.sqf to remove the case sensitivity of the town-type check

A3A/addons/core/functions/init/fn_initServer.sqf
1. [ ] Bug
2. [ ] Change
The initial arsenal unlocks code used jn_fnc_arsenal_addItem to add each item individually to the arsenal. This blows up when the list is large, because addItem checks each current entry to see if there's a classname match, causing 20min+ startups when mods add a large number of cosmetic headgear or glasses (eg. USP).
This PR fixes the problem by ensuring that the initial gear has no dupes and then adding it directly to jna_datalist. This is a bit of a hack, but then the whole arsenal is a hack at this point. 
This even improves 3CB Factions startup time by several seconds.
closes #3194
1. [X] No
2. [ ] Yes (Please provide …
=> Prevent O(N^2) startup hang with excessive hats/glasses

A3A/addons/core/functions/Dialogs/fn_fastTravelRadio.sqf
1. [X] Bug
2. [ ] Change
Two bug fixes in fast travel:
1. Parameter inversion introduced in 3.5.2. Any location and HQ/airfield only options were swapped.    
2. Ancient exploit where changing group shortly after fast travelling would make you immortal.
closes #3193
closes #3164
1. [X] No
=> Fix fast travel parameter inversion and allowDamage exploit

A3A/addons/jeroen_arsenal/JNA/fn_arsenal_handleAction.sqf
1. [X] Bug
2. [ ] Change
The arsenal code that preserves attachments on weapons inside containers (uniform, vest, backpack) uses the index for the secondary magazine instead of the bipod, causing it to lose bipods and throw an SQF error. This PR fixes it.
closes #XXXX
1. [X] No
=> Fix arsenal backpack weapon attachments code adding the wrong element

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [X] Change
Added ACE painkillers to initial rebel equipment when KAT isn't loaded. They're slightly weird with the Antistasi arsenal because they count as magazines rather than items, but whatever.
Disabled the publicVariables because the data isn't currently used anywhere else and probably shouldn't be.
closes #XXXX
1. [X] No
=> Add ACE painkillers to initial rebel equipment

A3A/addons/core/functions/Ammunition/fn_randomRifle.sqf, A3A/addons/core/functions/CREATE/fn_NATOinit.sqf, A3A/addons/core/functions/REINF/fn_equipRebel.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal.sqf
1. [x] Bug
2. [x] Change
Information:
Replaces calls to BIS_fnc_compatibleItems to the script command. No need to call the function, and it prevents cba errors when they override the function.
1. [x] No
=> Changed: BIS_fnc_compatibleItems to script command

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf
1. [X] Bug
2. [ ] Change
Pylon-armed and unarmed versions of an RF heli were placed in the wrong categories. This PR fixes it.
closes #XXXX
=> Fix swapped RF armed and unarmed helis

A3A/addons/garage/Core/fn_confirmPlacement.sqf
1. [X] Bug
2. [ ] Change
If you enable the placement rays rendering in the garage options, you get a script error for a missing variable. Didn't hurt much, but we fix these things.
Wasn't entirely sure about the intention here but it looks fine, so whatever.
closes #3199
1. [X] No
Load CBA. Enable placement rays rendering. Attempt to place a vehicle from the garage.
=> Fix script error for missing variable in placement rays rendering code

A3A/addons/maps/MissionDescription/gameSettings.hpp
1. [ ] Bug
2. [X] Change
Short-term fix for player corpses getting deleted too early under high user count conditions. Didn't realise Arma had a system for this that's enabled by default. Could disable it entirely, but I've compromised on giving players at least 15 mins to get their gear back.
closes #3213
1. [X] No
Respawn 16 times. Check that the first corpse is still present for 15 minutes afterwards.
=> Prevent Arma from deleting player corpses for 15 mins

A3A/addons/core/Templates/Templates.hpp
1. [ ] Bug
2. [x] Change
Information:
reduces the priority of the vanilla NATO/UK and vanilla ION factions to 5 such that they won't be the default faction for every damn map and campaign.
1. [x] No
Steps: 
Notes:
=> Reduced priority of highly DLC dependent factions

A3A/addons/core/functions/REINF/fn_spawnHCVeh.sqf
1. [X] Bug
2. [ ] Change
If high command squads containing vehicles are purchased when the commander is away from HQ, and the HQ has no roads within 100m, the placement code breaks. This PR fixes it to place the vehicle randomly as intended.
closes #XXXX
1. [X] No
=> Fix case where HC vehicles are remote-spawned with no roads near HQ

A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
Fixed two issues in the initial unlocks code introduced in 3.5.3:
1. Items now retain their original order in the arsenal, so you can find ACE items again.
2. unlockedXXX arrays are filled out correctly on new campaign start, so outpost crates and looting crates filter items correctly without needing a load/save cycle.
closes #3225
1. [X] No
Start a new campaign with ACE:
1. Check that the ACE items are in the usual order in the arsenal.
2. Check that vars like unlockedMagazines have everything in them.
=> Fix reordering and unlockedXXX arrays in initial unlocks

A3A/addons/core/functions/REINF/fn_postmortem.sqf
1. [X] Bug
2. [ ] Change
Fixed the remaining case where vehicle seats might be permanently blocked with ACE after the crew is cleaned up.
Example test case: Set the `cleantime` global var to 10 seconds. Put some AIs in a vehicle. Kill them.
closes #3145
1. [X] No
=> Fix case where seats may not be unlocked when dead crew are deleted

A3A/addons/core/Templates/Templates/FactionDefaults/EnemyDefaults.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_ChDKZ.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arctic.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Army_Temperate.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Arid.sqf, A3A/addons/core/Templates/Templates/RHS/RHS_AI_USAF_Marines_Temperate.sqf, A3A/addons/core/functions/CREATE/fn_AAFroadPatrol.sqf, A3A/addons/core/functions/Templates/fn_compileMissionAssets.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [x] Change
Information:
add a vanity/atmosphere vehicle category which dictates what vehicles the enemy send on air patrols.
This category can include: scout planes, scout helicopters, and light helicopters with door gunners.
closes #XXXX
1. [x] No
Steps: 
run
`tierWar = 10; [] spawn A3A_fnc_AAFroadPatrol;`
in the vicinity (2km) from enemy airbase.
Notes:
=> Adds Air Patrol Vehicle category 

A3A/addons/core/functions/REINF/fn_vehiclePrice.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds a check to fn_vehiclePrice that ensure the function doesn't error when _typeX is nil.
This would be the first step in the direction of letting some rebel templates have less stuff.
Reformatted file.
Cleaned up the non-seaport based discount 
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Update fn_vehiclePrice to not fail on absent vehicles.

A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf
1. [X] Bug
2. [X] Change
Some artillery vehicles have a limited firing arc and the artillery support code didn't take account of that. This PR fixes the issue by making artillery vehicles rotate towards the target before firing. Method should be solid. Adjusted the firing rate to 1/sec max as previously it varied based on rotation distance.
Not tested with anything except vanilla mortars, but should work fine.
closes #2775
1. [X] No
Adjust as required:
`["MORTAR", Occupants, "defence", 500, objNull, markerPos "Therisa", 0.8, 20] call A3A_fnc_createSupport;`
=> Make artillery rotate to target before firing

A3A/addons/config_fixes/RF/CfgVehicles.hpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_FIA.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_LFF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_SDK.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Reb_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_Vehicle_Attributes.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf, A3A/addons/core/Templates/Templates/WS/WS_Reb_TURA.sqf, A3A/addons/logistics/Nodes/RF.hpp
1. [ ] Bug
2. [ ] Change
Information:
Added RF compatibility to the WS templates, as well as adding pickups to the militia vehicle pool for most factions.
Switched the SF marksmen to using the big suppressor for their 12.7mm rifle.
Several known bugs right now, but since the RPT has no errors I'm throwing this up now for a preliminary review.
1. [ ] No
Known bugs:
Military vehicles will take on civilian colors sometimes when bought.
Notes:
=> RF Compatibility - WS Templates

A3A/addons/core/functions/Base/fn_citySupportChange.sqf
1. [X] Bug
2. [ ] Change
The safety checks added to citySupportChange for command line usage currently break when a position is used as input to citySupportChange. This PR fixes it.
closes #XXXX
1. [X] No
Go into a town and steal a car.
=> Fix breaking error in citySupportChange type-safety checks

A3A/addons/logistics/Nodes/3CBFactions.hpp
1. [X] Bug
2. [ ] Change
Information: Added cargo nodes to the 3CB covered hiluxes.
Since they have no base class, the initial nodes are defined and then applied to all of the different variants we use in our templates. These are using the same cargo nodes as the other 3CB Hiluxes, since the model is identical except for a canopy.
Note that this means two bugs carry over: the first crate clips into the front of the truck a bit, which will be easier to fix if every value is consistent, and that the large ammo crates clip through the top. Unfortunately I believe there is no fix for this until #3103 is merged
closes #3045
1. [X] No
2. [ ] Yes (Please provide further …
=> Cargo nodes for 3CB Hilux (Covered)

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Missions/fn_RES_Refugees.sqf
1. [X] Bug
2. [ ] Change
Information:
Added a missing timer element to the description of the Refugees Evac description.
1. [X] No
`[["Molos"],"A3A_fnc_RES_Refugees"] remoteExec ["A3A_fnc_scheduler",2]` on Altis
=> Refugee mission timer fix

A3A/addons/core/Templates/Templates/3CB/3CB_AI_CW_SOV.sqf
updates weapons of ADA SOV HIDF LDF TAK EAST MIX
1. [ ] Bug
2. [x] Change
Information:
this PR adds the RPD to the 3CB Soviet Faction, as was intended with #3170
closes #XXXX
1. [x] No
Steps: 
Notes:
=> "Re-adds" the RPD to the 3CB SOV template

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Revive/fn_respawn.sqf, A3A/addons/core/functions/Revive/fn_selfRevive.sqf, A3A/addons/core/functions/Revive/fn_unconscious.sqf, A3A/addons/core/keybinds/CfgDefaultKeysPresets.hpp, A3A/addons/core/keybinds/CfgUserActions.hpp, A3A/addons/core/keybinds/UserActionGroups.hpp, A3A/addons/core/keybinds/UserActionsConflictGroups.hpp
1. [ ] Bug
2. [ ] Change
Antistasi medical respawn (R) and self-revive (H) keys were hard-coded. Now they're not. Also cleaned up some questionable logic that might have caused weird effects if people hit these keys too early.
closes #3232
1. [X] No
Start Antistasi without ACE medical and self-revive enabled in parameters. Get yourself killed, for example by using this:
`player setPosATL (getPosATL player vectorAdd [0,0,50]);`
Try changing the keybinds in the controls menu.
=> Switch respawn & self-revive keys to custom keybinds

A3A/addons/core/Templates/Templates/FactionDefaults/RebelDefaults.sqf, A3A/addons/core/Templates/Templates/GM/GM_Reb.sqf, A3A/addons/core/Templates/Templates/VN/VN_Reb_POF.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
1. [ ] Bug
2. [ ] Change
Information:
Faction dependent parachutes will now spawn in airbase crates to make them more reliable to unlock. Added appropriate parachutes to every appropriate template with `flyGear`.
closes [this suggestion on Discord](https://discord.com/channels/449481990513754112/566329285024022567/1240311553685721210)
1. [X] No
Steps: Spawn any airbase crate with an appropriate faction, so not WW2 factions mostly
=> Parachutes in airbase crates

A3A/addons/core/functions/Base/fn_garbageCleaner.sqf
1. [X] Bug
2. [ ] Change
Information:
Adds the Ka-52 ejection rocket and rotor blade vehicles to the GC function.
1. [X] No
=> Adding a few RHS items to GC

A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
1. [X] Bug
2. [ ] Change
Fixed a couple of issues with lootToCrate and IFA gear:
1. MP38s would disappear when looted. lootToCrate only considered handguns as possible weapons on corpses.
2. BIS_fnc_basicBackpack breaks on at least one radio backpack. The workaround in A3A_fnc_basicBackpack seems fine.
closes #3262
1. [X] No
Load IFA AIO. Zeus in a radioman and a sapper from the Fallschirmjager faction (can use vanilla factions). Kill them, loot them with a crate.
=> Fix lootToCrate issues with IFA gear

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/AI/fn_AIreactOnKill.sqf, A3A/addons/core/functions/Base/fn_addRecentDamage.sqf, A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf, A3A/addons/core/functions/Base/fn_airspaceControl.sqf, A3A/addons/core/functions/Base/fn_distance.sqf, A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf, A3A/addons/core/functions/CREATE/fn_availableBasesAir.sqf, A3A/addons/core/functions/CREATE/fn_vehKilledOrCaptured.sqf, A3A/addons/core/functions/OrgPlayers/fn_playerLeash.sqf, A3A/addons/core/functions/Supports/fn_SUP_ASF.sqf, A3A/addons/core/functions/Supports/fn_SUP_CAS.sqf, A3A/addons/core/functions/Supports/fn_SUP_SAM.sqf, A3A/addons/core/functions/Supports/fn_SUP_SAMAvailable.sqf, A3A/addons/core/functions/Supports/fn_initSupports.sqf, A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf, A3A/addons/core/functions/init/fn_initServer.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [X] Change
Wrote a semi-proper system for support system responses against air vehicles. Previously, any airspace violation or damage-related support call against an air vehicle would automatically draw responses, until a cap was reached. The new system also takes account of base vehicle threat, vehicle activity (both damage and airspace, cumulative), supports already called against that vehicle and available resources. Starved factions need serious provocation to send a response to air threats, although it should always happen eventually.
Other changes:
- War tier scaling removed for CAS/ASF/SAM response times. Should lead to longer response times overall. Feels maybe too long to me, but we'll see.
- Adjusted airfield choice to prefer airfields ~5km away …
=> Rework anti-air support response balance

A3A/addons/core/functions/Supports/fn_getArtilleryRanges.sqf
1. [ ] Bug
2. [ ] Change
- Improve artillery turret detection. I think they worked anyway with the fallback method, but this should throw fewer errors.
- Search fire modes properly in case the maximum charge size isn't 1. Apparently this was an issue with the IFA mortars.
- Remove incorrect attempt at determining minimum range. maxElev and minElev aren't easily usable because they seem to be relative to the default position in the model, which can't be obtained easily through code. Not worth the trouble so I set fixed minimums instead. Arty one might need a bump.
closes #3263
1. [ ] No
Should probably recheck some …
=> Improve getArtilleryRanges, fix IFA mortar case

A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
1. [X] Bug
2. [ ] Change
Information:
Added an ammobox to Destroy Heli missions where the heli isn't an attack heli and the crate can be slingloaded. Same functions as the ammoboxes from outposts
Refined the placement of the task marker; it will now check that it's inside bounds and not in water to make it less confusing for newer players who think it's on the task itself
1. [ ] No
Steps: 
To force-spawn a mission: `[["airport_1"],"A3A_fnc_DES_Heli"] remoteExec ["A3A_fnc_scheduler",2];`
Can use being tested to make sure the ammo crate despawns properly and that we don't get any more out-of-bounds spawns, not a good …
=> Destroy Heli mission fixes

A3A/addons/core/functions/Base/fn_aggressionUpdateLoop.sqf, A3A/addons/core/functions/Base/fn_chooseAttack.sqf, A3A/addons/core/functions/CREATE/fn_attackHQ.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/CREATE/fn_wavedAttack.sqf
1. [X] Bug
2. [ ] Change
4. [X] Balance
Because the bigAttackInProgress flag was set in the individual major attack functions (which are spawned), it wasn't necessarily set before the invader flag check happened in aggressionUpdateLoop, so concurrent major attacks were possible, and the flag could then be cleared while a major attack was still running. This PR fixes it by moving the flag set to chooseAttack.
Also added a "planning cost" to attacks to reduce the spamming of cheap attacks, especially punishments (because the helis tend to escape intact, so the failure cost is basically a few squads of infantry) and early-game supply convoys. Attack resource income has been adjusted to compensate.
Not all code paths have been tested yet, because it's difficult to arrange …
=> Prevent concurrent major attacks, and add a planning cost

A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp
1. [X] Bug
2. [ ] Change
The loadouts -> config PR used an incorrect array specifier for diveParams entries, causing dive bombing runs to fail. This PR fixes it.
closes #XXXX
1. [X] No
=> Fix incorrect config array specifier for diveParams

A3A/addons/core/functions/CREATE/fn_createAttackForceLand.sqf, A3A/addons/core/functions/Supports/fn_SUP_tankRoutine.sqf
1. [X] Bug
2. [ ] Change
createAttackForceLand was supposed to have a troopType parameter back in 3.0 but it wasn't implemented. Used the same slot for tanksOnly, which broke some other uses. This PR fixes both the old bug (never using specops in ground vehicles) and the new one.
Tested all three calls of createAttackForceLand (QRF, attack, tanks) and they now work correctly.
closes #XXXX
=> Fix inconsistent parameter bug with createAttackForceLand

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf, A3A/addons/core/functions/Supports/fn_initSupports.sqf
1. [X] Bug
2. [ ] Change
Since SAMs are no longer unfair supports, they'll also be used by all factions. Although the SAM launcher used isn't strictly appropriate for most factions, it's probably a bit much for WW2. This PR adds a faction attribute to disable SAMs.
Attribute will also need adding to the new IFA factions in #3166
closes #XXXX
1. [X] No
=> Prevent SAM supports being used by WW2 factions

A3A/addons/gui/dialogues/buyVehicleDialog.hpp, A3A/addons/gui/functions/GUI/fn_buyVehicleDialog.sqf, A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf
1. [X] Bug
2. [ ] Change
The buy vehicle menu somehow got skipped in the GUI function tagging update, so it just came up blank. This PR fixes it.
Also checked build placer and arsenal limits, but those are fine.
closes #XXXX
1. [X] No
=> Fix buy vehicle menu function tagging

A3A/addons/core/CfgFunctions.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/REINF/fn_convertToSquad.sqf, A3A/addons/core/functions/REINF/fn_reinfPlayer.sqf
1. [ ] Bug
2. [ ] Change
Added a commander dialog button to convert currently selected personal-squad members to a high command squad. This is mostly to make it easier to use vehicles with AI. Previously for a 2-man vehicle you needed a sniper team, while for a three-man vehicle you have to buy a team and murder one of them.
To make it less annoying to use, I also changed personal-squad recruiting to use faction rather than personal money for commanders, as with vehicle purchasing.  Maybe slightly controversial but it's probably fine.
While I was in there, I also fixed a bug where RPT errors could be thrown the first time a player attempted to purchase a unit. Consequence is that it might be delayed for a second or two. Not really noticeable.
I think I covered all the …
=> Allow commanders to make custom HC squads

A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf, A3A/addons/core/functions/UtilityItems/fn_dropItem.sqf
1. [X] Bug
2. [ ] Change
It was apparently possible to fire off the drop item action twice under some real circumstances, which causes script errors. There may also have been ways to dodge some of the carry checks under similar load. This PR hardens the carry & drop actions so that they're hopefully proofed against script load issues.
Note that the github diff is a mess because the indentation changed. Actual changes are just adding sanity checks at the front of each function and wrapping the rest in isNil { code } to make sure it's not interrupted.
**Edit:** I suspect the reported issue was actually caused by dropItem taking a scheduler break between the detach and the A3A_carryingItem reset, which then causes the spawn in carryItem to trigger a second dropItem. The …
=> Fix potential double-carry or double-drop errors under heavy script load

A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
1. [X] Bug
2. [ ] Change
The arsenal limits dialog never fetched the arsenal data (jna_datalist) itself, so on clients it could show out-of-date information, or error out if the arsenal hadn't been accessed locally. This PR fixes it by fetching the arsenal data on dialog init.
closes #XXXX
1. [X] No
=> Fetch current arsenal data before displaying the arsenal limits dialog

A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug?
2. [ ] Change
Apparently initClientDone can be true before A3A_utilityItemHM exists on the client, causing errors in the initRemoteObject JIP function. This was expected to be impossible due to publicVariable order guarantees. I have a dumb theory that subsequent publicVariable calls on the same variable don't update the order, which means that A3A_startupState is not a valid fence variable.
This PR switches the fence variable to serverInitDone. If the ordering problem doesn't show up again then we learnt something weird about Arma.
closes #XXXX
1. [ ] No
It's probably not possible to generate the issue …
=> Speculative init order fix

A3A/addons/core/functions/OrgPlayers/fn_unitTraits.sqf
1. [ ] Bug
2. [X] Change
Just adds the explosiveSpecialist and UAVHacker traits to the default commander slot so that solo players can disarm mines and convert UAVs. Shouldn't be controversial.    
closes #3253
1. [X] No
=> Add explosiveSpecialist and UAVHacker traits to default commander slot

A3A/addons/core/functions/UtilityItems/fn_carryItem.sqf
1. [X] Bug
2. [ ] Change
Turns out `count crew petros` is 1, not 0. Arma never fails to surprise me.
closes #XXXX
1. [X] No
=> Fix move asset not working on Petros

A3A/addons/config_fixes/IFA/CfgAmmo.hpp, A3A/addons/config_fixes/IFA/CfgVehicles.hpp, A3A/addons/config_fixes/IFA/CfgWeapons.hpp, A3A/addons/config_fixes/IFA/config.cpp, A3A/addons/core/Templates/Templates/IFA/IFA_AI_ALLIES.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_UK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_Reb_Vehicle_Attributes.sqf
1. [ ] Bug
2. [X] Change
IFA mortars were extremely weak so I've buffed them a bit closer to the vanilla ones. Changes:
- Flattened out the wild inaccuracy at higher charge sizes. Still worse than vanilla but not so far off.
- Made effective radius against unarmoured units somewhere near vanilla effective radius against armoured units.
The 60mm mortar was left a bit weaker. Should probably adjust the templates so that enemies all use the larger mortars, because the range and effectiveness of the 60mm isn't really sufficient for use as a support.
Also fixed a couple of config bugs while I was in there:
- IFA config fixes were using the vanilla patch name.
- IFA had a bugged target dummy that broke CBA XEH.
closes #3313
2. [ …
=> Buff IFA mortars closer to mk6

A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp, A3A/addons/core/Templates/Templates/IFA/IFA_AI_WEH.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_Vehicle_Attributes.sqf
1. [ ] Bug
2. [x] Change
Information:
1. Sets the cost of all IFA aircraft down to a reasonable for their capabilities, 75
2. tweaked the P39, Pe2, and Ju87 loadout configuration to put them better in line with the other airplanes.
3. Removed excessive number of variants of the fw190 from the weh template
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Ifa aircraft price update & loadout tweak

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_Vehicle_Attributes.sqf, A3A/addons/core/functions/Supports/fn_SUP_ASF.sqf, A3A/addons/core/functions/Supports/fn_SUP_SAM.sqf, A3A/addons/core/functions/Supports/fn_initSupports.sqf, A3A/addons/core/functions/Supports/fn_maxDefenceSpend.sqf
1. [ ] Bug
2. [X] Change
WW2 planes are not very effective but they were treated as such by the air support response. This PR adjusts air support responses based on the cost of ASF planes, making it more likely that multiple enemy aircraft are sent against one plane.
Also removed the lowAir adjustment for CAS vs tank platoon, as it doesn't make sense to reduce CAS for most lowAir factions. They're more low-heli than low-air.
Needs #3317 for the IFA planes.
closes #XXXX
1. [X] No
=> Adjust air support response for cheap planes

A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf
1. [x] Bug
2. [ ] Change
Information:
closes [#XXXX](https://github.com/official-antistasi-community/A3-Antistasi/issues/3324)
1. [x] No
Steps: 
Notes:
=> Fixed script error in new BattleMenu.

A3A/addons/core/Templates/Templates/IFA/IFA_REB_AK.sqf, A3A/addons/core/Templates/Templates/IFA/IFA_REB_FFI.sqf
1. [x] Bug
2. [ ] Change
Information:
Adds the detonators needed for IFA explosives 
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Added IFA-ACE-Compat detonators

A3A/addons/core/Templates/AircraftLoadouts/3CB/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/CUP/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/RHS/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/SFP/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/Tornado_AWS/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/UNS/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/VN/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/WS/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/config.cpp, A3A/addons/core/script_component.hpp
1. [X] Bug
2. [ ] Change
The aircraft loadout configs all had the same CfgPatches name as core (A3A_core), which caused RPT errors. Not sure it did anything else important, but it should be cleaned up.   
closes #3314
1. [X] No
=> Fix conflicting addon messages from aircraft loadout configs

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
preliminary changelog and version update for 3.6.0
=> version and preliminary changelog

A3A/addons/gui/functions/GUI/fn_adminTab.sqf, A3A/addons/gui/functions/GUI/fn_aiManagementTab.sqf, A3A/addons/gui/functions/GUI/fn_airSupportTab.sqf, A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf, A3A/addons/gui/functions/GUI/fn_buyVehicleDialog.sqf, A3A/addons/gui/functions/GUI/fn_buyVehicleTabs.sqf, A3A/addons/gui/functions/GUI/fn_commanderTab.sqf, A3A/addons/gui/functions/GUI/fn_configColorToArray.sqf, A3A/addons/gui/functions/GUI/fn_constructTab.sqf, A3A/addons/gui/functions/GUI/fn_donateTab.sqf, A3A/addons/gui/functions/GUI/fn_fastTravelTab.sqf, A3A/addons/gui/functions/GUI/fn_fireMissionEH.sqf, A3A/addons/gui/functions/GUI/fn_getGroupInfo.sqf, A3A/addons/gui/functions/GUI/fn_getGroupVehicle.sqf, A3A/addons/gui/functions/GUI/fn_getVehicleCrewCount.sqf, A3A/addons/gui/functions/GUI/fn_hqDialog.sqf, A3A/addons/gui/functions/GUI/fn_mainDialog.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawHcGroupsEH.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawSelectEH.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawUserMarkersEH.sqf, A3A/addons/gui/functions/GUI/fn_playerManagementTab.sqf, A3A/addons/gui/functions/GUI/fn_playerTab.sqf, A3A/addons/gui/functions/GUI/fn_recruitDialog.sqf, A3A/addons/gui/functions/GUI/fn_recruitSquadDialog.sqf, A3A/addons/gui/functions/GUI/fn_requestMissionDialog.sqf, A3A/addons/gui/functions/GUI/fn_setUpPlacerHints.sqf, A3A/addons/gui/functions/GUI/fn_teamLeaderRTSPlacerDialog.sqf, LICENSE
1. [ ] Bug
2. [x] Change
closes #XXXX
1. [ ] No
Steps: 
Notes:
=> DoomMetal GUI Header and license adjustments

A3A/addons/core/functions/Supports/fn_SUP_artilleryAvailable.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortarAvailable.sqf
1. [ ] Bug
2. [X] Change
The ratio of artillery to mortar supports was apparently a bit excessive at high war tiers. This PR reduces it:
Tier 8: Was 50% artillery, now 33% artillery.
Tier 10: Was 75% artillery, now 50% artillery.
closes #XXXX
1. [X] No
=> Reduce artillery/mortar ratio at high war tiers

A3A/addons/config_fixes/CUP/CfgVehicles.hpp, A3A/addons/config_fixes/IFA/CfgVehicles.hpp
1. [ ] Bug
2. [X] Change
Most planes with "airplane" simulation have absolutely horrible turn rates when flown by AIs. A major reason for this seems to be that the planes gain too much altitude while banked, causing the AI to back off the elevators until it levels out.
We can't improve this behaviour directly, but it turns out that increasing the value that causes the nose of the plane to dip when banked helps a lot. This is the time in seconds for a 180 degree waypoint turn at normal speed before and after the changes:
```
before    after
CUP A-10     48       16
CUP AV-8B    37       17
CUP F-35B    33       17
CUP LZ-39    40        9
CUP SU-25    50       16
CUP SU-34    54       19
IFA FW-190   26       13
IFA P39      18       13
IFA Pe2      31       15
```
As a …
=> Improve CUP and IFA plane turn rates when flown by AI

A3A/addons/gui/dialogues/arsenalLimitsDialog.hpp, A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf
1. [X] Bug
2. [ ] Change
On slow dedicated servers, it was possible to select a category in the arsenal limits dialog before the arsenal data had been received. This could cause double-overlaid controls because the control creation routines would overlap. This PR fixes the problem by disabling the category controls until the initial setup and category rendering are complete.
The arsenal limits code also recently acquired incorrect attribution and licensing. This has been fixed.
closes #XXXX
1. [ ] No
Should test on a server that's slow enough to generate the problem, although I'm pretty sure this will work.
=> Fix slow-server UI issue and incorrect licensing in arsenal limits

A3A/addons/core/functions/Revive/fn_unconscious.sqf
1. [ ] Bug
2. [X] Change
4. [X] Exploit
Because the self-revive timeout and unconscious bleeding timeout were both five minutes, it was possible to self-revive indefinitely. Mostly not an issue (laying on the floor for five minutes is not productive), but it enables some degenerate behaviour with missions and vehicle stealing.
The fix adds half a second to the self-revive timeout for each second a player was downed. This means that you'd need to stay alive for ~150 seconds to self-revive successfully before bleeding to death.
closes #3342
1. [X] No
=> Slow down self-revive timeout when downed

A3A/addons/gui/functions/GUI/fn_arsenalLimitsDialog.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_init.sqf
1. [ ] Bug
2. [x] Change
Information:
Sets magazine limits to equal unlock limit rather than 3 times guest limit - adjusting the limit of magazines from either direction proved to be an absolute chore and a nuisance.
Still uses the 3 * guest limit in cases of games ran with no unlocks, as i find that a reasonable case. 
Changed arsenalLimitsDialog to reduce duplicate code, RFC.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Default Arsenal Magazine Limits

A3A/addons/core/functions/Base/fn_destroyCity.sqf
1. [X] Bug
2. [ ] Change
When loading the Interiors for CUP mod, destroyCity (used when a punishment fails) would crash on some cities. Apparently this is because the mod incorrectly removes the models for some sign objects, causing setHit to crash Arma. This PR works around the problem by not calling setHit on selections that don't exist, which was rather dangerous behaviour anyway.
Shouldn't have any functional changes in other cases. Note that CUP buildings are mostly lacking in building damage modelling compared to vanilla A3 buildings, so destroyed cities don't look much different.
closes #3357
1. [X] No
Load …
=> Fix issue where running destroyCity with CUP interiors could crash

A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_initServer.sqf
1. [X] Bug
2. [ ] Change
Information: HQ objects can no longer be slingloaded.
closes #3346
1. [X] No
=> Disallow sling-loading HQ objects

A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_BW_Temperate.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_HIL.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arctic.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_ION_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Arid.sqf, A3A/addons/core/Templates/Templates/CUP/CUP_AI_US_Marine_Temperate.sqf
1. [X] Bug
2. [X] Change
Information: Removed CUP Cluster MLRS from a few templates, specifically the M270 DPICM, as the cluster munitions it uses are absolutely devastating against infantry and are unfun to play against.
1. [X] No
Steps: `["ARTILLERY", Occupants, "defence", 10000, player, getPosATL player, 1, 1] spawn A3A_fnc_createSupport;`
=> Remove CUP Cluster MLRS

A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_setupMonitor.sqf
1. [X] Bug
2. [ ] Change
If you use the "Arma 3 Unix Launcher" to start Arma with CDLC, they are not reported as official in the mod table. Can be replicated by seelecting mods to load from within Arma. This breaks Antistasi's CDLC detection logic. 
https://feedback.bistudio.com/T182946
This PR replaces the detection logic with a whitelist, which should at least work on all platforms. If further CDLC need to be supported then we'll need to add them to the list.
closes #3360
1. [X] No
=> Workaround Arma bug with CDLC detection and arma3.cfg mod loading method

A3A/addons/core/functions/Supports/fn_SUP_ASFRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_CASRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf
1. [X] Bug
2. [ ] Change
Vehicle crew for most supports weren't being paid for up-front, but were being "refunded" on support completion, which meant that enemy factions had an unintended income stream. The effect is small for most factions but relatively large for WW2 due to the cheap planes with multiple crew.
Tested all six affected supports, works correctly. For the late-spawning supports (ASF, CAS, airstrike) the crew cost isn't applied to supportSpends, but that value only needs to be approximate.
closes #3340
1. [X] No
=> Fix support crew being provided for free and then refunded

A3A/addons/core/functions/CREATE/fn_AIVEHinit.sqf, A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf, A3A/addons/core/functions/CREATE/fn_createAIOutposts.sqf, A3A/addons/logistics/Private/fn_addAction.sqf, A3A/addons/logistics/Public/fn_addLoadAction.sqf
1. [X] Bug
2. [ ] Change
Information: Ammoboxes now have rudimentary protection to prevent unintended yoinking.
Attempting to load an outpost/seaport ammobox into a vehicle will break undercover.
Slingloading an ammbox will break undercover when the ropes are attached. Players can still potentially get away, so it's a bit exploity still, but it's a fair risk/reward payoff
closes #3347 
1. [ ] No
Steps:  Logic can probably be checked and should be double-checked if the change to `isKindOf "Air"` will break anything, but it all works in testing.
=> Seaport Ammobox Protection

A3A/addons/core/functions/Base/fn_getVehicleSellPrice.sqf
1. [X] Bug
2. [X] Change
Information: Most buyable/civilian vehicles will now be sold for half of their buy price. This fixes an exploit where a Poseidon could be bought for 20 and sold for 25
closes #3350 
1. [X] No
=> Very small sell price rework

A3A/addons/core/CfgVehicles.hpp, A3A/addons/core/config.cpp, A3A/addons/core/functions/Templates/fn_compatibilityLoadFaction.sqf, A3A/addons/core/functions/init/fn_initACE.sqf
1. [X] Bug
2. [ ] Change
Created new classes for Antistasi AI units, giving us better control over ACE actions and slightly better server & client performance. Removes ACE group join & handcuff actions from those classes.
Mostly works. Doesn't touch headgear/glasses/identity stuff but stripping more of that would have further performance benefits if I can be bothered to do the research. `headgearProbability = 0` doesn't seem to do anything.
closes #3348
1. [ ] No
Probably needs a test server run in case I overlooked something.
=> Create new classes for Antistasi AI units, block those from group join

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Base/fn_rebuildAssets.sqf
1. [X] Bug
2. [ ] Change
Some maps have radio towers on non-outpost markers, but it was impossible to rebuild these. This has been fixed.
Refactored the code because it was too spaghetti to fix sensibly. Also improved the text feedback.
Tested every code path.
closes #3339
1. [X] No
=> Fix inability to rebuild non-outpost radio towers

A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
1. [ ] Bug
2. [X] Change
Dive bombers needed to be extremely accurate to have a chance of killing tanks, but this behaviour made them overly oppressive against infantry targets. This PR reduces the problem by adding a random offset to infantry targets.
Also fixed a bug that caused dive bombers to be inaccurate and frequently kill themselves against targets on steep hills.
Tested and working. It's still pretty dangerous tbh but you have a chance now.
closes #3345
1. [X] No
=> Make dive bomb runs less accurate against infantry targets

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/Dialogs/fn_skiptime.sqf
1. [X] Bug
2. [ ] Change
Information:
Skip time will now check for undercover players as well when looking for absent players.
Depending on how many players are missing, the action will display a hint. 0, 1, 2-9, and 10+ will display different messages.
1. [X] No
Steps: Push players away from HQ, try the tent action.
=> Skip time improvements

A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
1. [ ] Bug
2. [X] Change
Added some extra options to getVehiclesGroundTransport to better handle some WW2 and Vietnam-era modsets:
- Faction attributeMoreTrucks will bias the table heavily towards trucks, for when APCs should have limited use even at high war tiers.
- Having no APC or LAPC entries is now allowed.
closes #XXXX
1. [X] No
=> Add attributeMoreTrucks and IFV-only option to ground transport selection

A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_REB_FFF.sqf
1. [ ] Bug
2. [x] Change
Information:
Adds "attributeMoreTrucks" to the US and WEH template.
WEH template loses the "APC" stugs, only "IFV" stugs remain.
Drops the rebel starting rifle - shotguns and pistols should be good enough in the WW2 setting.
Replaced the rebel's starting Panzerfaust 30 with the Faustpatrone.
Adds an additional nr4 buckshot ammo type for the shotgun.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> SPE Rebel template tuned, enemy template adapted for #3370

A3A/addons/core/functions/CREATE/fn_createVehicleQRFBehaviour.sqf, A3A/addons/core/functions/CREATE/fn_patrolReinf.sqf, A3A/addons/core/functions/Missions/fn_DES_Heli.sqf
1. [X] Arma bug workaround
2. [ ] Change
The GETOUT waypoint is very broken and can cause squads to leave their transport vehicle for no good reason. Fortunately it is relatively straightforward to replace, so this PR does so.
Tested all uses except the destroy heli mission. It's probably fine.  
closes #3374
1. [X] No
Create land QRFs like this:
```
_destPos = markerPos "Outpost_13";
["QRFLAND", Occupants, "defence", 500, objNull, _destPos, 0.8, -1] call A3A_fnc_createSupport;
```
Or more specific vehicle types and source/dest:
```
_sourceMrk = "Airport_3";
_destPos = markerPos "Outpost_18";
["LIB_US_M3_Halftrack", …
```
=> Replace all uses of GETOUT waypoints

A3A/addons/core/CfgVehicles.hpp, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_US.sqf, A3A/addons/core/Templates/Templates/SPE_IFA/SPE_IFA_AI_WEH.sqf
1. [x] Bug
2. [ ] Change
Information:
Adds flashlights to the unit definitions
Fixes eventhandler inheritance by making I_G_Soldier_base_F inherit the EHs from SoldierGB correctly - this permits units derived from the vanilla FIA classes to use SPE flashlights, hipfire, some flamethrower hose stuff, SPE static weapons, fixes for the SPE alt reloads.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> SPE flashlight fix

A3A/addons/core/CfgVehicles.hpp
1. [X] Bug
2. [ ] Change
#3377 broke the CBA XEH event handlers for SoldierGB onwards, I guess because CBA works around the broken inheritance by selectively spamming the event handlers into various places, and our new inheritance chain didn't touch any of those. Fixing the link from SoldierGB -> CAManBase seems to work, although I'm not 100% sure that I've tested both load orders. Because our config doesn't have a dependency on CBA, it's possible for CBA to be loaded either before or after. Either way it's better than it was, but we might need to handle the inheritance patch differently.
closes #XXXX
1. [ ] No
I …
=> Fix SoldierGB inheritance chain for CBA XEH. Probably.

A3A/addons/core/Includes/script_version.hpp, README.md, changelog.rst
updates changelog and version for 3.7 udpate
=> 3.7 changelog and version

A3A/addons/core/functions/Base/fn_getVehiclesGroundSupport.sqf, A3A/addons/core/functions/Base/fn_getVehiclesGroundTransport.sqf
1. [ ] Bug
2. [x] Change
Information:
Shuffled around the weigh distributions of militia vs military vehicles to increase the probability of encountering militia troops in the early game - something i did not deem common enough.
weighed against all other transports the total should be the same unless i've made a lapse in my maths.
Adjusted the way the weights of light tanks are distributed if they are absent - there's probably a reason why MBTs and equivalent can be dispatched at war level 2 but i don't feel that's particularly fitting.
closes #XXXX
1. [ ] No
Steps: …
=> More frequent militia vehicles/transports early game

A3A/addons/core/functions/Supports/fn_SUP_artillery.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortar.sqf, A3A/addons/core/functions/Supports/fn_SUP_mortarRoutine.sqf, A3A/addons/core/functions/Supports/fn_requestSupport.sqf
1. [ ] Bug
2. [ ] Change
Changing artillery shot positioning & timing to make artillery deaths feel a bit less random:
- Added a "ranging shot" with forced 100m offset and flight-time delay afterwards.
- Changed all volleys to 8 rounds which now draw a +/-50m line through the target position.
- Offsets specified are for mortars. Doubled for heavy artillery.
- Force the reload time per shot to avoid mortars wobbling around.
Possible changes:
- Could add an additional ranging shot, say 150m -> 75m.
- Could switch back to random radius offsets for the fire-for-effect stage.
- Might add a general aggro factor for determining whether area supports are used.
closes #XXXX …
=> Implement mortar/artillery support ranging shot and walking barrage

A3A/addons/core/functions/REINF/fn_FIAskillAdd.sqf
1. [x] Bug
2. [ ] Change
Information:
- Button tooltip did not update after upgrading ai skill.
- Copied update functionality from dialogHQ
closes #3351
1. [x] No
=> Fix skill upgrade tooltip not updating

A3A/addons/core/functions/init/fn_tags.sqf
1. [x] Bug
2. [ ] Change
Information:
Looking at friendly units no longer causes script errors
Now tags are displayed for downed/killed units as well
closes #3394
1. [x] No
Steps: 
see issue.
Notes:
=> Fix errors caused by tags function

A3A/addons/core/functions/init/fn_initServer.sqf
1. [x] Bug
2. [ ] Change
Information:
-     Owner ID now gets removed from playersInArsenal when player disconnects while in arsenal
closes #3344 
1. [x] No
Steps: 
1. Open the arsenal on a dedicated server and disconnect while in it
2. Log back in and check jna_playersInArsenal, (if you were the only player) the array should be empty
Notes:
=> Fix arsenal not clearing client IDs on disconnect

A3A/addons/core/functions/Ammunition/fn_categoryOverrides.sqf
1. [X] Bug
2. [ ] Change
VN melee weapons were being autoclassified as handguns, which caused the rebel AI equipping code to use them in the early game. Fixed by overriding to "Unknown", which is basically where we put stuff that AI doesn't know how to use.
closes #XXXX
1. [X] No
=> Prevent rebels AIs being equipped with VN melee weapons

A3A/addons/config_fixes/WS/CfgWeapons.hpp
1. [x] Bug
2. [ ] Change
Information:
Fixes base weapon classname of the GM6 Snake - making it not convert into a blank element in the arsenal
closes #XXXX
1. [ ] No
Steps: 
loot srifle_GM6_snake_lxWS before and after this change.
Notes:
=> Fix base class for srifle_GM6_snake_lxWS 

A3A/addons/core/functions/init/fn_initACE.sqf
1. [ ] Bug
2. [X] Change
Information: ACE Injector use is now logged on success, not on beginning the action. This helps server admins identify medical malpractice.
Injector use now has UIDs attached.
Fixed mis-named case for using adenosine injectors. Added painkillers.
1. [X] No
=> Injector success and UID logging

A3A/addons/core/functions/Ammunition/fn_equipmentClassToCategories.sqf
1. [ ] Bug
2. [ ] Change
4. [X] Fuck CBA
A variable used for detecting disposable missile launcher types was changed in CBA 3.18, breaking Antistasi init when CUP weapons is loaded. This PR works around it. Also doesn't break in older CBA, although it won't detect the missiles correctly.
closes #XXXX
1. [ ] No
=> Fix CUP disposable missile launchers breaking init after CBA 3.18 update

A3A/addons/logistics/CfgFunctions.hpp, A3A/addons/logistics/Dev/fn_drawSeats.sqf
1. [ ] Bug
2. [ ] Change
Information:
Added a new function in `logistics/Dev` called `fn_drawSeats`. Similar to the hardpoints function, it draws cargo/gunner seat proxy locations on a vehicle along with each seat index.
May be useful for getting a nice visualization of what seats should be locked when loading cargo.
---
> You can figure out which seats were locked quite easily.
---
N/A
1. [x] No
Steps: 
Look at a vehicle and run the following locally
```sqf
[cursorObject] call A3A_logistics_fnc_drawSeats;
```
Notes:
=> Seat drawing dev function

A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
1. [ ] Bug
2. [x] Change
Information:
Added officer loadouts to the vanilla factions - these are used for the Officer assassination targets.
Added RF pickups and helicopters to the vanilla ION and UK/NATO factions.
Switched the NLAW and MAAWS around in the vanilla factions : NLAW is now used as light AT launchers and MAAWS as regular AT launchers.
Tweak the weapons of several loadouts to be better in line with expectations.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Vanilla/WS Factions update, fine tuning, officer loadouts, further RF integration on missed factions

A3A/addons/core/functions/Supports/fn_SUP_airstrikeRoutine.sqf, A3A/addons/core/functions/Supports/fn_SUP_carpetBombs.sqf, A3A/addons/core/functions/Supports/fn_initSupports.sqf
1. [ ] Bug
2. [x] Change
Information:
Replaces previous functionality with three parallel airstrikes dropping a minimum of 5 bombs each, up to 8 bombs depending on aggression.
Notable improvement is that the support is now tied to some actual aircrafts instead of being bombes just thrown at you.
a "CARPET" behaviour has been added to the airstrike routine setting the speed and minimum bomb count to a higher minimum.
closes #3426 
1. [ ] No
Steps: 
Notes:
=> Carpet bombing turned into triple airstrike

A3A/addons/config_fixes/RF/CfgVehicles.hpp, A3A/addons/core/Templates/AircraftLoadouts/EF/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/RF/config.cpp, A3A/addons/core/Templates/Templates.hpp, A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Arid.sqf, A3A/addons/core/Templates/Templates/EF/EF_AI_MJTF_Temperate.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
1. [ ] Bug
2. [ ] Change
Information:
Adds arid and temperate version of the Marine Joint Task Force from the Expeditionary Forces DLC
Adds config entries for alternative textured RF helicopters (Navy for MJTF, SFIA for SFIA)
Adds helicopter loadouts specific to the EF and MJTF RF helicopters
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Expeditionary Forces MJTF factions

A3A/addons/core/Templates/AircraftLoadouts/Vanilla/config.cpp, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_AAF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Enoch.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_CSAT_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_LDF.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Apex.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Temperate.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Arid.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_NATO_UK_Tropical.sqf, A3A/addons/core/Templates/Templates/Vanilla/Vanilla_AI_PMC.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ADF.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_CSAT_NAfrica.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_ION.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_NATO_Desert.sqf, A3A/addons/core/Templates/Templates/WS/WS_AI_SFIA.sqf
1. [ ] Bug
2. [x] Change
Information:
Updates vanilla and WS templates with the new EF assets where applicable.
Adds helicopter loadouts for vanilla helicopter.
Rebalances availability of interchangeable 100 rounds magazines.
Adds the RHIB boat to all templates, for its generic nature and capacity.
Fixes more case validation errors.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Expeditionary Forces Vanilla and Western Sahara compatibility 

A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_setupMonitor.sqf
1. [x] Bug
2. [ ] Change
Information:
adds "ef" to two arrays
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Ef detect as additional DLC

A3A/addons/core/functions/REINF/fn_addBombRun.sqf
1. [x] Bug
2. [ ] Change
Information:
Unowned aircraft and aircrafts owned by the commander are now correctly able to be converted into airstrike points.
Wrong owner variable now blocks the commander from converting aircrafts that aren't theirs
closes #3341
1. [x] No
Steps: 
Tested by buying two helicopters.
Setting the ownerX variable on one of them prevents that helicopter from being converted, setting the variable to the commander's UID premits you to convert it again.
The other helicopter does not have its ownerX variable set, and it permits you to convert it. …
=> Fixed wrong owner check in fn_addBombRun.sqf

A3A/addons/core/Templates/Templates/3CB/3CB_AI_LDF.sqf
1. [ ] Bug
2. [x] Change
Information:
Remodel the LDF police to replicate the LDF Armed Forest Rangers, they'll be pulling extra duty now.
Set the LDF up with air patrol vehicles, reorganised helicopter lineup
Set the correct magazine type for the rocket artillery 
closes #XXXX
1. [x] No
Steps: 
Notes:
=> 3CB Ranger update, artillery fix

A3A/addons/core/functions/Base/fn_distance.sqf
1. [X] Bug
2. [ ] Change
- Remove effectiveCommander optimization for rebels to prevent locations despawning incorrectly when drivers disconnect. Not ideal but anything else would be messy. It was probably a bit of a best-case optimization anyway.
- Optimize performance for simpleVM (3-4x speedup on enemies).
- Remove some unnecessary conditions for rebels (isKindOf is fast).
closes #3450
1. [X] No
=> Bugfix and optimizations to spawner selection

A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/REINF/fn_equipRebel.sqf, A3A/addons/gui/functions/GUI/fn_customLoadoutsDialog.sqf
1. [X] Bug
2. [ ] Change
- Changed custom loadout UI to work with temporary copy. Safer, and fixes serious bug with Reset All button.
- Added case for static crew (eg mortar team units) and fixed optics typo in fallback case.
- Disabled optics UI control so that players are less likely to expect it to do something.
- Fixed casing on button to open custom loadouts UI.
closes #XXXX
1. [X] No
=> Rebel loadout fixes

A3A/addons/core/Templates/Templates/CWR/CWR_AI_USSR_Temperate.sqf, A3A/addons/core/Templates/Templates/CWR/CWR_AI_US_Army_Temperate.sqf
1. [x] Bug
2. [ ] Change
Information:
Adds NVGs to the CWR3 factions
Reason: Players would unlock NVGs and at night the AI would be completely hopeless
closes #XXXX
1. [x] No
Steps: 
Notes:
=> CWR3 NVG fix

A3A/addons/core/functions/LTC/fn_lootToCrate.sqf
1. [ ] Bug
2. [X] Change
Reworked loot-to-crate to dump all the leftovers to a single weapon holder next to the looting crate. This has some likely client performance & networking advantages, and enabled easier detection of whether the leftover weapon holder could be deleted as a priority (due to only containing unlocked items).
The original code didn't differentiate between the crate-full and already-unlocked cases when looting items from bodies (only when looting other weapon holders), and there was a danger of all the additional weapon holders (typically 2-3 per corpse) filling up the postmortem queue and causing premature deletion of corpses.
As far as I can tell I didn't break anything new in the process. Test cases:
- Full squads of various types, ended with zeus. …
=> Modify loot-to-crate to dump all leftovers to a single weapon holder

A3A/addons/maps/Antistasi_isladuala3.isladuala3/initPlayerLocal.sqf, A3A/addons/maps/Antistasi_isladuala3.isladuala3/initServer.sqf, A3A/addons/maps/Antistasi_isladuala3.isladuala3/mapInfo.hpp, A3A/addons/maps/Antistasi_isladuala3.isladuala3/mission.sqm
1. [ ] Bug
2. [x] Change
Information:
General cleanup and adjustments of assets
Moved or removed a number of control markers.
Testing a change to make the bridges indestructible on more than the host machine.
Moved the support corridors further away from land
closes #XXXX
1. [x] No
Steps: 
Notes:
=> Isla duala playtest adjustment

A3A/addons/core/functions/REINF/fn_NATObomb.sqf, A3A/addons/core/functions/REINF/fn_addBombRun.sqf
1. [X] Bug
2. [ ] Change
Information:
addBombRun actually checks the vehicle type now
NATObomb will now properly clean up vehicles, a sleep for an unknown variable caused stuff to be instantly deleted
Hopefully the entire natoBomb function can be reworked with the GUI update
1. [X] No
Steps: 
addBombRun: attempt to sell a helicopter or plane from the enemy factions for airstrikes, it returns the proper amount
NATObomb: call an airstrike, shoot down the plane on approach. it crashes and despawns an hour later.
=> Rebel airstrike fixes

A3A/addons/core/functions/Base/fn_onPlayerDisconnect.sqf
1. [X] Bug?
2. [ ] Change
There have been occasional reports of an AI with a player's name being generated after they disconnect. This could in theory happen due to a `true` return value in handleDisconnect. There's no obvious way that this can happen in the code, but we don't enforce a return value and the return values of setDamage or deleteVehicle might be unreliable. This PR enforces the return value, so it should at least rule out that problem.
closes #XXXX
1. [X] No
=> Ensure return value of HandleDisconnect is correct

A3A/addons/core/functions/init/fn_initVarServer.sqf
added ACRE_BF888S https://acre2.idi-systems.com/wiki/class-names
1. [ ] Bug
2. [ ] Change
Information: added the missing radio.
This Radiotype is way more fitting to a rebellion then the american ones.
1. [X] No
Steps: Loadup game, check arsenal?
Notes: is there a specific reason why TFAR is in the templates, and acre in initvarserver? would anyone mind (or merge) if I move acre to all the Templates?
=> Add ACRE_BF888S

A3A/addons/core/functions/AI/fn_paradrop.sqf
1. [ ] Bug
2. [X] Change
Some changes to make paradrops a bit more effective:
- Move drop centre another 100m away (now 250-400m from target).
- Check 150m before and after for water, not just drop centre.
- Move leader to middle of group to reduce regroup time after drop.
I should probably make more of an attempt to control the speed of the transport aircraft, but it's the sort of messy and error-prone config abuse that I can't be bothered with at the moment.
closes #XXXX
1. [ ] No
I left some test code in there for drawing a marker around the drop site. Otherwise you can't tell exactly where they were trying to …
=> Improve paradrop placement

A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
At present, laser designator batteries are not loaded into laser designators when a loadout is loaded from JNA. This PR implements loading of desginator batteries by taking a more general approach to load the first binocular magazine that is fully unlocked from the arsenal.
1. [ ] Bug
2. [ ] Change
Information:
[Line 176](https://github.com/official-antistasi-community/A3-Antistasi/blob/3.8.0/A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf#L176) of `fn_arsenal_loadInventory.sqf` as of 3.8.0 indicates that designator battery loading is unimplemented.
We implement the loading of designator batteries by considering all the possible magazines that can be loaded into the equipped binocular and finding the first one that is unlocked/infinite in the arsenal and …
=> Implement loading of binocular magazine from arsenal

A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_initZones.sqf
1. [ ] Bug
2. [ ] Change
Added mapInfo parameters for air & land attack distances, for maps where the default 3km/10km didn't work due to larger spacing between locations. These use default fallbacks, so that older extensions still work.
Changed the mapInfo banks specification to be type-agnostic. If you put a position into the banks array then it will simply look for the nearest house object. Won't change behaviour on any current maps unless the positions were very inaccurate. Altis works fine at least.
closes #3485
1. [X] No
=> Add some mapInfo features (banks, distances)

A3A/addons/config_fixes/IFA/CfgAmmo.hpp, A3A/addons/config_fixes/SPE/CfgAmmo.hpp, A3A/addons/config_fixes/SPE/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/IFA/config.cpp, A3A/addons/core/Templates/AircraftLoadouts/SPE/config.cpp, A3A/addons/core/functions/Supports/fn_SUP_CASDiveBombRun.sqf
1. [ ] Bug
2. [ ] Change
4. [X] Arma bullshit
Long research project into why dive bombing is less accurate than expected (+/-4m or so in the forward direction). Turns out the main reason is that bombs have airSideFriction which causes them to lift fairly drastically in flight. It's the same effect as the PCML's dumbfire flight path, as they have the same simulation type (shotMissile), but with the bombs it doesn't seem to be very deterministic. Setting the airSideFriction to zero makes the bombs much more accurate.
Of course I had to change all the numbers afterwards. The other changes in CASDiveBombRun are all test code and will be removed prior to merging.
closes #XXXX
2. [ ] Have you loaded the mission on a dedicated …
=> Improve dive bombing accuracy

A3A/addons/core/functions/CREATE/fn_attackHQ.sqf, A3A/addons/core/functions/Supports/fn_SUP_UAVRoutine.sqf, A3A/addons/core/functions/Supports/fn_initSupports.sqf, A3A/addons/core/functions/Supports/fn_requestArtillery.sqf, A3A/addons/core/functions/Supports/fn_requestSupport.sqf
1. [X] Bug
2. [X] Change
The UAV support that reveals targets for major attacks and HQ attacks was accidentally disabled at some point in the 3.0+ process. I have simplified, optimized and re-tested it.
The principle was that attacks often stall or take an excessive time because they can't see enemies in buildings. The UAV-reveal gives them an assist, which should give them half a chance of dealing with hidden units.
closes #3466
1. [X] No
=> Fix up and re-enable UAV support for major attacks and HQ attacks

A3A/addons/core/functions/CREATE/fn_createAIAirbase.sqf
1. [ ] Bug
2. [x] Change
Information:
Previous behaviour would spawn all vehicles with equal probability, which would make certain categories of vehicles much much more probable than others. a big issue for factions which had certain categories that were unusually lean or heavily stacked.
New behaviour adds per category weights, that then get divided by the count of the vehicle category to "flatten" out the probabilities and remove effect of having more vehicles in one category than in the others.
This will also let us more closely tune the spawn behaviour to balance it as we'd like to.
closes #XXXX
1. [ ] No
Steps: …
=> Normalised and weighted vehicle spawns for airbases

A3A/addons/garage/Core/fn_onLoad.sqf
1. [X] Bug
2. [ ] Change
Information: Vehicle count of garage is now always updated when new garage data is received, not just on load. This fixes an issue where the garage count would be inaccurate when being loaded again in a session.
closes #3352 
1. [x] No
Steps: Host dedicated and add vehicles to garage
=> Update garage count on load

A3A/addons/gui/Stringtable.xml, A3A/addons/gui/dialogues/setupDialog.hpp
1. [ ] Bug
2. [ ] Change
Added some explanatory tooltips to the weirder setup UI new-campaign options. Hopefully reduces the number of people trying to use missionProfileNamespace on Linux servers.
closes #3500
1. [X] No
=> Add explanatory tooltips to some setup UI new-game options

A3A/addons/core/functions/CREATE/fn_createAIResources.sqf
1. [ ] Bug
2. [x] Change
Information:
Switched an equality check around so that at low war levels there's a high chance for militia to be patrolling around the perimeter instead of military, this probability shifts with war tier.
This was likely a typo or error from way back then.
closes #XXXX
1. [x] No
Steps: 
Notes:
=> [Change] Update fn_createAIResources.sqf to have militia patrols at resources and factories

A3A/addons/core/functions/AI/fn_airbomb.sqf, A3A/addons/core/functions/AI/fn_napalm.sqf, A3A/addons/core/functions/AI/fn_napalmDamage.sqf, A3A/addons/core/functions/Base/fn_initPetros.sqf
1. [X] Bug
2. [ ] Change
Some of this really needs a broader rework due to locality switch issues, but that's not really workable within 3.9.0 so I've just removed the busted vanilla handleDamage and fixed up the MPKilled handler to take up the slack. Don't really want Petros rolling around on the floor for 5min in vanilla anyway.
Also thrown in a slightly hacky fix so that Petros can die to napalm.
closes #3275
1. [X] No
Shoot Petros (should respawn nearby), spawn in enemy to kill petros (should work), call napalm airstrike on petros (should work). Not that after every respawn petros gets allowDamage false for 120 …
=> Fix some Petros death handling

A3A/addons/core/functions/CREATE/fn_createAIcontrols.sqf
1. [X] Bug
2. [ ] Change
Fixed an ancient bug with specops control points not registering their soldiers if there's nothing in the uavsPortable array. This has two effects:
- The specops do not despawn.
- The specops point is immediately marked as captured.
closes #XXXX
1. [X] No
=> Fix ancient specops bug with missing UAVs

A3A/addons/core/functions/Base/fn_postmortemLoop.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [X] Change
Postmortem cleanup rules were overly strict, often causing corpses to be deleted prior to looting. This PR doubles the minimum cleanup time to 1 hour and also increases the radius at which it's extended further if players are nearby.
There's still the rule that corpses are deleted earlier if there are too many of them, so we can probably afford to be lenient here.
closes #3546
1. [X] No
=> Soften postmortem cleanup rules

A3A/addons/core/functions/Templates/fn_aceModCompat.sqf
1. [ ] Bug
2. [X] Change
Information: changes fixed/deprecated 82mm rangetable to universal one that adapts to any nearby pieces
this also works better with modded mortars which may be highly accessible
1. [X] No
Steps: Load the arsenal, has the universal table now
=> Arty rangetable in start gear

A3A/addons/gui/functions/GUI/fn_mapDrawHcGroupsEH.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
1. [ ] Bug
2. [ ] Change
Optimized mapDrawOutpostsEH as it was a pretty big hit when you had a UI map open. Main changes:
- Pre-culling icons in world space.
- No label rendering when faded out.
- Color precaching.
- Icon type precaching.
Bumps from 45 -> 60 vsync cap here unless you zoom out all the way. 
Includes limeified HQ.
closes #XXXX
1. [X] No
=> Optimized mapDrawOutpostsEH

A3A/addons/core/functions/Missions/fn_LOG_Bank.sqf
1. [X] Bug
2. [ ] Change
Fixed bank robbery vehicle placement being overly dependent on a specific building. This check should be reasonable for any building.
Tested by actually playing the bank mission to completion.
closes #3556
1. [X] No
=> Fix bank mission truck proximity checks for arbitrary bank buildings

A3A/addons/core/functions/Missions/fn_missionRequest.sqf
1. [X] Bug
2. [ ] Change
The gun shop mission request code had no check for the case where there are no valid cities available. The mission does not work without a city. Fixed the mission request logic.
closes #3557
1. [X] No
=> Fix case where gun shop mission may be started without a city

A3A/addons/config_fixes/Napf/config.cpp, A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp, A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp
1. [X] Bug
2. [ ] Change
Napf (and Napf Winter, identical config) have very bad config types for their names. There were about half a dozen clear villages marked as "Name" rather than "NameVillage", and a similar number of woods and industrial complexes marked as NameVillage. Cleared up everything I could find.
It still has a lot of tiny villages which are really farms, but that's more arguable and doesn't make a big difference either way, so I left them alone.
Both the roadblock pair and load/save code correctly handled adding and removing towns, although there's probably some data loss on town support.
closes #XXXX
1. [X] No
2. [ ] Yes (Please provide further …
=> Fix towns on Napf and Napf Winter

A3A/addons/gui/functions/SetupGUI/fn_setupHQPosDialog.sqf
1. [X] Bug
2. [ ] Change
Fixed now-incorrect use of controlsX in HQ position setup dialog.
closes #XXXX
1. [X] No
=> Fix controlsX remnant in HQ position setup dialog

A3A/addons/core/keybinds/fn_keyActions.sqf, A3A/addons/gui/dialogues/mainDialog.hpp
1. [ ] Bug
2. [ ] Change
4. [X] Clown fiesta
Rewrote the battle menu open action so that it no longer generates Zeus pings from players who didn't bother to rebind the key. Zeus seems to ignore the keypress if there's a dialog open, but this clashes with our code to delay opening the battle menu until the commanding menu is closed. The solution is to create a dummy dialog immediately and then close it before opening the real one. However, Arma appears to refire key events sometimes on closing a dialog, causing multiple battle menu UIs to open in quick succession. I have worked around this using a dumb global variable block.
Hopefully this works on other PCs as well. I do not have a whole lot of trust in it.
closes #3578
2. …
=> Worst hack ever written

A3A/addons/config_fixes/Vanilla/CfgVehicles.hpp, A3A/addons/core/Scripts/fn_advancedTowingInit.sqf
1. [ ] Bug
2. [X] Change
Added a server-side loop to cleanup orphaned towing helper objects (was Land_Can_V2_F), which should prevent them from occasionally spamming the RPT. The routine's fast (0.07ms here with a lot of units on the server) so I put it on a 10min loop in the towing code rather than relying on the manual GC.
Created a separate object class for the towing helper so that it can be identified quicker and with no risk of mod collisions.
There are more precise ways of managing the helper objects, but they involve multiple killed & deleted object handlers so it's probably not worth the complexity. Maybe when we try rewriting the thing for Arma towing logic.
closes #2543
2. [ ] Have you loaded the mission on a …
=> Clean up orphaned towing helpers to prevent log spam

A3A/addons/core/functions/Base/fn_chooseAttack.sqf, A3A/addons/core/functions/Base/fn_findAttackTargets.sqf, A3A/addons/core/functions/CREATE/fn_invaderPunish.sqf, A3A/addons/core/functions/Save/fn_loadStat.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf
1. [ ] Bug
2. [ ] Change
4. [X] Balance
If rebels don't put garrisons in towns, they can be spammed with punishment attacks even if they're defeating them consistently. This is quite annoying. This PR reduces the chance of punishment attack after a successful defence, gradually increasing again each time invaders decide to do something else.
Tested every code path. Which was a pain.
Could be easily adjusted if the resulting number of punishment attacks is too low.
closes #3578
1. [X] No
=> Reduce punishment chance after successful punishment defence

A3A/addons/core/functions/Base/fn_findBasesForConvoy.sqf, A3A/addons/core/functions/Missions/fn_missionRequest.sqf
1. [ ] Bug
2. [ ] Change
Rewrote findBasesForConvoy to use navgrid-based logic properly. findLandSupportMarkers is essentially perfect for this. Will give more reliable results for cases with short direct distance and long paths, like crossing Regero's bridges. Also faster.
closes #3567
1. [X] No
=> Update findBasesForConvoy to use new navgrid-based logic

A3A/addons/core/functions/MinorSites/fn_generateCamps.sqf, A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm, A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
1. [X] Bug
2. [ ] Change
One specops camp on Napf was placed on the end of a road so it became a roadblock. Fixed. Also fixed one log line that was firing incorrectly.
closes #XXXX
1. [X] No
=> Fix misplaced camp on Napf plus an incorrect log line

A3A/addons/config_fixes/Napf/config.cpp, A3A/addons/maps/Antistasi_Napf.Napf/mapInfo.hpp, A3A/addons/maps/Antistasi_Napf.Napf/mission.sqm, A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mapInfo.hpp, A3A/addons/maps/Antistasi_NapfWinter.NapfWinter/mission.sqm
1. [ ] Bug
2. [x] Change
Changes mentioned from the discord
Information: Alpnach, Giswil and Hagacher blacklisted. 
Worb Horw, Brienz, Sissach, Mutternz, Hungerschwand, Luzern and Liestal moved away from outposts or just more to where the marker would be expected.
Seap_5_Mortar changed to it's accompanied outpost name, was missed during the inital changing of markers.
Changed a military towers rotation.
closes #XXXX
1. [x] No
Steps: Load branch, check town postions. RPT no longer shows error for marker.
Notes:
=> Napf town edits, Seap_5_Mortar fix, capitalisation of Napf winter's climate

A3A/addons/core/functions/AI/fn_combatLanding.sqf
1. [ ] Bug
2. [X] Change
Used limitSpeed to cap transport heli speeds once they're within 1.5km of the objective. Shouldn't do anything noticeable to normal helis but makes Ospreys look a lot more plausible.
closes #XXXX
1. [X] No
`["UK3CB_B_Osprey_USMC_WD", "Normal", "defence", [], Occupants, "airport_3", markerPos "Sachseln"] call A3A_fnc_createAttackVehicle;`
=> Reduce Osprey speed before combat landing

A3A/addons/core/functions/Ammunition/fn_setCargoItems.sqf, A3A/addons/core/functions/Missions/fn_GSMission.sqf, A3A/addons/core/functions/Missions/fn_supplyDrop.sqf
1. [X] Bug
2. [ ] Change
Various edge case fixes:
- Make Solomon despawn as soon as players are 200m away.
- Run supply drop cleanup if items in the box are changed.
- Don't set crate maximum load below default.
closes #3583
1. [X] No
=> Various gunshop/supply drop edge case fixes:

A3A/addons/jeroen_arsenal/JNA/fn_arsenal_addItem.sqf, A3A/addons/jeroen_arsenal/JNA/fn_arsenal_loadInventory.sqf
1. [X] Bug
2. [ ] Change
BIS_fnc_baseWeapon was being called on things that were not necessarily items from CfgWeapons, causing it to spam errors into the log. This PR fixes it.
Tested with various gear including non-base weapons. Seems fine. BIS_fnc_baseWeapon returns the input classname by default so you don't need to test the return.
closes #XXXX
1. [X] No
=> Not the final baseWeapon fix

A3A/addons/gui/functions/GUI/fn_mapDrawHcGroupsEH.sqf, A3A/addons/gui/functions/GUI/fn_mapDrawOutpostsEH.sqf
1. [ ] Bug
2. [X] Change
Simplified some UI icon drawing code by using a 360 degree icon angle to block outlining rather than two draw calls. Should be faster and is a potential (unlikely again) crash fix, as it removes the one-pixel dynamic icons.
closes #XXXX
1. [X] No
=> Remove invisible map icon usage with 360 angle trick

A3A/addons/garage/Core/fn_getCatIndex.sqf
1. [X] Bug
2. [ ] Change
The RHS M252 mortar and possibly some other non-vanilla static weapons were being placed in the armour category rather than the statics category in the garage. Changed the check order to fix it. I don't think it'll break anything else.
closes #XXXX
1. [X] No
=> Fix RHS M252 appearing in armour category in garage

A3A/addons/gui/dialogues/mainDialog.hpp
1. [ ] Bug
2. [ ] Change
4. [X] Fuck Arma
Preload most map icons in a desperate speculative attempt to stop rare Arma crashes on map icon rendering. Don't know whether it's a valid idea or not. Did the rendering in the dummy menu that's used as part of the battle menu opening hack, so it should definitely render before any map icon drawing.
This doesn't preload the high command map icons because they're a lot trickier to look up. They're also routinely shown on the main map to players using high command so hopefully less risk.
closes #XXXX
1. [X] No
=> Preload map icons in attempt to workaround Arma crash bug

A3A/addons/core/Params.hpp, A3A/addons/core/Stringtable.xml, A3A/addons/core/dialogs.hpp, A3A/addons/core/functions/init/fn_initClient.sqf
1. [ ] Bug
2. [ ] Change
Switched the old/new UI switch from a global parameter to a per-user setting, which can be toggled live in the game options menu on the map board. Kinda janky but it'll do what we need. The global parameter was bad if specific players are running into issues with the new UI and want to switch back.
closes #XXXX
1. [X] No
=> Change UI setting to a per-user toggle in game options

A3A/addons/core/functions/Ammunition/fn_configSort.sqf, A3A/addons/core/functions/Templates/fn_loadFaction.sqf
1. [ ] Bug
2. [ ] Change
Ported the unscheduled double-loop optimization to configSort. This effectively increases the per-frame script time allowance from 3ms to 20ms. This reduces startup equipment categorization for a 3CBF (non-ACE) modset from 12 seconds to 2 seconds on my PC.
I don't think this has any additional risks as the code isn't spawned anyway. Gonna think on it a bit though, so maybe not for 3.9.0.
closes #XXXX
1. [ ] No
Start a game with a heavy modset, check the time taken. The log entry for this is:
`A3A_fnc_initVarServer | Scanning config entries for items`
=> Apply unscheduled optimization to configSort

A3A/addons/core/Stringtable.xml, A3A/addons/core/functions/AI/fn_airbomb.sqf, A3A/addons/core/functions/Base/fn_statistics.sqf, A3A/addons/core/functions/REINF/fn_NATObomb.sqf, A3A/addons/core/functions/REINF/fn_addBombRun.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf, A3A/addons/gui/Stringtable.xml, A3A/addons/gui/functions/GUI/fn_airSupportTab.sqf
1. [ ] Bug
2. [X] Change
Calling airstrikes near HQ is blocked with tkPunish on
Airstrike counter removed from top bar, cap added to new battle menu
Airstrike cap imposed as (4 + tierWar*2) which is 10 at WL3 when you unlock airport, which is enough to convert a full jet, and 24 at war level 10. You cannot gain more points or convert more vehicles that would pass this cap.
Rebel napalm strikes are now 2 bombs instead of 4
Napalm now costs 3 airstrike points
closes #3541
1. [ ] No
Steps: 
Notes: Additional points integration still needs to be done for the new UI
=> Airstrike/Napalm Nerfs

A3A/addons/core/functions/REINF/fn_controlHCsquad.sqf, A3A/addons/core/functions/REINF/fn_controlunit.sqf
1. [X] Bug
2. [ ] Change
Your player unit would run off in an arbitrary direction sometimes when you remote controlled a unit. All AI is disabled on your old unit now when you remote control.
closes #3383 
1. [ ] No
Steps: 
Notes:
=> Unit RC AI Disable

A3A/addons/core/functions/Intel/fn_selectIntel.sqf, A3A/addons/core/functions/Save/fn_deleteSave.sqf, A3A/addons/core/functions/Save/fn_loadServer.sqf, A3A/addons/core/functions/Save/fn_loadStat.sqf, A3A/addons/core/functions/Save/fn_saveLoop.sqf, A3A/addons/core/functions/Supports/fn_useRadioKey.sqf, A3A/addons/core/functions/init/fn_initVarServer.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf
1. [ ] Bug
2. [ ] Change
For some reason, enemy radio keys werent saved and were lost on server restart. This PR fixes that, and also renames the vars entirely because "occupants" vs "invader" is dumb    
1. [X] No
Steps: Get in game, give yourself a few keys, go aggro a counterattack / QRF, check keys, save game, restart game, check keys
=> Radio key saving

A3A/addons/core/functions/AI/fn_enemyReturnToBase.sqf, A3A/addons/core/functions/Base/fn_citySupportChange.sqf, A3A/addons/core/functions/Base/fn_moveHQ.sqf, A3A/addons/core/functions/CREATE/fn_patrolReinf.sqf, A3A/addons/core/functions/CREATE/fn_reinforceSide.sqf, A3A/addons/core/functions/GarrisonLocal/fn_spawnGarrisonSquads.sqf, A3A/addons/core/functions/GarrisonServer/fn_showSiteInfo.sqf, A3A/addons/core/functions/Missions/fn_CON_PoliceStation.sqf, A3A/addons/core/functions/Missions/fn_missionRequest.sqf, A3A/addons/core/functions/init/fn_initClient.sqf, A3A/addons/core/functions/init/fn_installClientEH.sqf, A3A/addons/core/functions/init/fn_resourcecheck.sqf, A3A/addons/tasks/Params/fn_city_hostage_p.sqf, A3A/addons/tasks/Tasks/fn_LOG_Supplies.sqf, A3A/addons/tasks/Tasks/fn_cityBattle.sqf, A3A/addons/tasks/Tasks/fn_city_hostage.sqf, A3A/addons/tasks/Tasks/fn_city_killcop.sqf, A3A/addons/tasks/Tasks/fn_city_repair.sqf, A3A/addons/tasks/Tasks/fn_city_taxi.sqf
Balance changes:
- Buffed speed of city support changes, reduced antenna importance a bit.
- Towns with police station destroyed now have *1.5 city support change multiplier.
- Doubled enemy spend on reinforcements.
- Prevented camp squads spawning UAVs unless they're actually specops or near.
- Reduced block time for police station & city supply missions.
- Increased city supply missions relative to police station missions.
- Increased base HR income for large player counts.
- Reduced money income of some missions.
Fixes:
- Fixed bug where HR loss on player death would stack with death count.
- Fixed city supply mission countdown not showing in some cases.
- Fixed air vehicles returning to outposts.
- Attempted fix of hostage/passenger getting back into vehicle.
- Fix bug in kill cop …
=> Balance changes and fixes, mostly for city/HR rework. (#3673)
